{
 "title": "_Home (WIP)",
 "description": "Key Metrics Across All Devices and Services",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,2m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "mountpoint",
    "label": "NAS Mountpoints",
    "query": "SHOW TAG VALUES FROM \"disk\" WITH KEY = \"path\" WHERE host =~ /crush/"
   },
   {
    "name": "intf",
    "label": "NAS Network Interface",
    "query": "SHOW TAG VALUES FROM \"ifTable\" WITH KEY = \"ifName\" WHERE \"agent_host\" =~ /192.168.0.10/"
   },
   {
    "name": "winhost",
    "label": "Windows Hostname",
    "query": "SHOW TAG VALUES FROM \"win_system\" WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<style type=\"text/css\">\r\np.markdown-html.panel-text-content {\r\noverflow: hidden;\r\n}\r\np.markdown-html.panel-text-content iframe {\r\nheight:225px;\r\n}\r\n</style>\r\n<script type=\"text/javascript\">\r\nvar weatherProperties = 'lat=55.889068&lon=-3.634458&color=#FFFFFF&text-color=#FFFFFF&units=uk';\r\n\r\n// initial load\r\ndocument.getElementById('embedweather').src = 'https://forecast.io/embed/?ts=' + (Date.now()) + '#' + weatherProperties;\r\n\r\n// refresh\r\nvar weatherRefresh = setInterval(function() { document.getElementById('embedweather').src = 'https://forecast.io/embed/?ts=' + (Date.now()) + '#' + weatherProperties; }, 1800000);\r\n\r\n</script>\r\n<iframe id=\"embedweather\" height=\"100%\" src=\"#\" style=\"margin: 0; padding: 0; border: none; width:100%; position:relative; top:-50px; overflow:hidden; margin-bottom: -70px;\"></iframe>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_laNames Minute",
     "groupBy": [
      { "params": [ "laNames" ], "type": "tag" }
     ],
     "measurement": "laTable",
     "select": [
      [
       { "params": [ "laLoadInt" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.0.10" }
     ]
    }
   ]
  },
  {
   "title": "NAS Interface Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName:$col",
     "groupBy": [
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "ifXTable",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.0.10" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$intf$/" }
     ]
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{instance!=\"\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "alias": "Containers",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=", "value": "crush" }
     ]
    },
    {
     "alias": "Paused",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_paused" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=", "value": "crush" }
     ]
    },
    {
     "alias": "Stopped",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_stopped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=", "value": "crush" }
     ]
    },
    {
     "alias": "Running",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=", "value": "crush" }
     ]
    }
   ]
  },
  {
   "title": "ERX Interface Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifXTable",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.0.1" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 2, "x": 15, "y": 19 },
   "options": {
    "content": "eth0 = WAN  \neth1 = NAS  \neth2 = [empty]  \neth3 = Switch  \neth4 = Wifi AP"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Alerts",
   "type": "alertlist",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backups",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "node_duplicacy{storage=\"wasabi-home\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"wasabi-backup\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"wasabi-docker\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"wasabi-media\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"wasabi-scratchpad\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-vpstorage-home\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-vpstorage-backup\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-vpstorage-docker\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-vpstorage-media\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-vpstorage-scratchpad\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-mgsquared-home\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-mgsquared-backup\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-mgsquared-docker\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-mgsquared-media\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-mgsquared-scratchpad\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_snapraid{action=\"snapraid\"}",
     "legendFormat": "{{action}}"
    },
    {
     "expr": "node_rsync_marlin{action=\"home\"}",
     "legendFormat": "rsync-{{action}}"
    },
    {
     "expr": "node_rsync_marlin{action=\"Backup\"}",
     "legendFormat": "rsync-{{action}}"
    },
    {
     "expr": "node_rsync_marlin{action=\"Docker\"}",
     "legendFormat": "rsync-{{action}}"
    },
    {
     "expr": "node_rsync_marlin{action=\"Media\"}",
     "legendFormat": "rsync-{{action}}"
    },
    {
     "expr": "node_rsync_marlin{action=\"scratchpad\"}",
     "legendFormat": "rsync-{{action}}"
    }
   ]
  },
  {
   "title": "NAS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "crush" }
     ]
    }
   ]
  },
  {
   "title": "Boot Drive Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "crush" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "crush" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "NAS Drive %",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 32 },
   "targets": [
    {
     "alias": "Boot Drive - $tag_path",
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "crush" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/mnt/data/disk1" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/mnt/data/disk3" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/mnt/data/disk5" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/mnt/parity/1-parity" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/mnt/parity/2-parity" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/mounts/storage" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/mnt/data/disk2" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/mnt/data/disk4" }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "snmp.EdgeOS",
     "select": [
      [
       { "params": [ "hrSystemNumUsers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.0.10" }
     ]
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_laNames Minute",
     "groupBy": [
      { "params": [ "laNames" ], "type": "tag" }
     ],
     "measurement": "laTable",
     "select": [
      [
       { "params": [ "laLoadInt" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.0.10" }
     ]
    }
   ]
  },
  {
   "title": "Interface Traffic (8 Mbps = 1 MBps)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName:$col",
     "groupBy": [
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "ifXTable",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=", "value": "192.168.0.10" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$intf$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "function": "mean",
     "groupBy": [
      { "interval": "auto", "params": [ "auto" ], "type": "time" },
      { "key": "host", "params": [ "tag" ], "type": "tag" }
     ],
     "measurement": "mem_inactive",
     "query": "SELECT mean(total) as total, mean(used) as used, mean(cached) as cached, mean(free) as free, mean(buffered) as buffered  FROM \"mem\" WHERE host =~ /crush/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "disk",
     "query": "SELECT last(\"total\") AS \"total\", last(\"used\") AS \"used\", last(\"free\") AS \"free\", last(\"used_percent\") AS \"used_percent\" FROM \"disk\" WHERE (\"path\" =~ /^$mountpoint$/) AND $timeFilter GROUP BY \"path\"",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "total" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=~", "value": "/^$mountpoint$/" }
     ]
    }
   ]
  },
  {
   "title": "NAS - Folder Sizes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_directory_size_bytes", "legendFormat": "{{directory}}" }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "No Smoothing",
     "measurement": "crush_temp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "crush" }
     ]
    },
    {
     "alias": "30s Average",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" }
     ],
     "measurement": "crush_temp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "crush" }
     ]
    },
    {
     "alias": "1m Average",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "crush_temp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "crush" }
     ]
    },
    {
     "alias": "5m Average",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "crush_temp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "crush" }
     ]
    }
   ]
  },
  {
   "title": "Backups",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "node_duplicacy{storage=\"wasabi-home\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"wasabi-backup\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"wasabi-docker\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"wasabi-media\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"wasabi-scratchpad\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-vpstorage-home\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-vpstorage-backup\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-vpstorage-docker\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-vpstorage-media\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-vpstorage-scratchpad\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-mgsquared-home\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-mgsquared-backup\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-mgsquared-docker\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-mgsquared-media\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_duplicacy{storage=\"gcd-mgsquared-scratchpad\"}",
     "legendFormat": "{{storage}}"
    },
    {
     "expr": "node_snapraid{action=\"snapraid\"}",
     "legendFormat": "{{action}}"
    },
    {
     "expr": "node_rsync_marlin{action=\"home\"}",
     "legendFormat": "rsync-{{action}}"
    },
    {
     "expr": "node_rsync_marlin{action=\"Backup\"}",
     "legendFormat": "rsync-{{action}}"
    },
    {
     "expr": "node_rsync_marlin{action=\"Docker\"}",
     "legendFormat": "rsync-{{action}}"
    },
    {
     "expr": "node_rsync_marlin{action=\"Media\"}",
     "legendFormat": "rsync-{{action}}"
    },
    {
     "expr": "node_rsync_marlin{action=\"scratchpad\"}",
     "legendFormat": "rsync-{{action}}"
    }
   ]
  },
  {
   "title": "Docker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Docker CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[1m])) / count(node_cpu_seconds_total{mode=\"user\"}) * 100"
    }
   ]
  },
  {
   "title": "Docker Memory Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes+node_memory_Buffers_bytes+node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})"
    }
   ]
  },
  {
   "title": "Images count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_images" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=", "value": "crush" }
     ]
    }
   ]
  },
  {
   "title": "Used Storage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(container_fs_usage_bytes)" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 75 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "scalar(count(container_memory_usage_bytes{image!=\"\"}) > 0)",
     "legendFormat": "containers"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 75 },
   "targets": [
    {
     "alias": "Containers",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=", "value": "crush" }
     ]
    },
    {
     "alias": "Paused",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_paused" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=", "value": "crush" }
     ]
    },
    {
     "alias": "Stopped",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_stopped" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=", "value": "crush" }
     ]
    },
    {
     "alias": "Running",
     "measurement": "docker",
     "select": [
      [
       { "params": [ "n_containers_running" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "engine_host", "operator": "=", "value": "crush" }
     ]
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) / scalar(count(node_cpu_seconds_total{mode=\"user\"})) * 100",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name)(container_memory_usage_bytes{image!=\"\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{image!=\"\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\"}[1m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Ephemeral Volume Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_usage_bytes{name!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Docker Containers Down",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 114 },
   "targets": [
    { "expr": "node_docker_container_down{}", "legendFormat": "{{action}}" }
   ]
  },
  {
   "title": "Home Assistant",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Windows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Clients Uptime",
     "type": "graph",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 121 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "alias": "$tag_host",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_system",
       "select": [
        [
         { "params": [ "System_Up_Time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk Space",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 121 },
     "targets": [
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "win_disk",
       "query": "SELECT last(\"Percent_Free_Space\")  *-1 + 100 AS \"Used - %\" FROM \"win_disk\" WHERE (\"host\" =~ /^$winhost$/) AND $timeFilter GROUP BY \"instance\", \"host\"",
       "select": [
        [
         { "params": [ "Percent_Free_Space" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " *-1 + 100" ], "type": "math" },
         { "params": [ "Used - %" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ]
      },
      {
       "alias": "$tag_instance",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "host" ], "type": "tag" }
       ],
       "measurement": "win_disk",
       "select": [
        [
         { "params": [ "Free_Megabytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Free - MB" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    },
    {
     "title": "Last Uptime - $winhost",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 127 },
     "repeat": "winhost",
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_system",
       "select": [
        [
         { "params": [ "System_Up_Time" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$winhost$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory Free - $winhost",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 2, "x": 3, "y": 127 },
     "repeat": "winhost",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "win_mem",
       "select": [
        [
         { "params": [ "Available_Bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$winhost$/" }
       ]
      }
     ]
    },
    {
     "title": "Used Disk % - $winhost",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 5, "y": 127 },
     "repeat": "winhost",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$hostname - $tag_instance",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "instance" ], "type": "tag" },
        { "params": [ "previous" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "select": [
        [
         { "params": [ "Percent_Free_Space" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "*-1+100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$winhost$/" }
       ]
      }
     ]
    },
    {
     "title": "CPU Usage - $winhost",
     "type": "graph",
     "gridPos": { "h": 5, "w": 6, "x": 11, "y": 127 },
     "repeat": "winhost",
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$hostname: $col",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "select": [
        [
         { "params": [ "Percent_Privileged_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Priviledged Time" ], "type": "alias" }
        ],
        [
         { "params": [ "Percent_User_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% User Time" ], "type": "alias" }
        ],
        [
         { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Interrupt Time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$winhost$/" }
       ]
      }
     ]
    },
    {
     "title": "Network Throughput - $winhost",
     "type": "graph",
     "gridPos": { "h": 5, "w": 7, "x": 17, "y": 127 },
     "repeat": "winhost",
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$hostname: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Bytes_Received_persec\") AS \"Bytes Received persec\", mean(\"Bytes_Sent_persec\") AS \"Bytes Sent persec\" FROM \"win_net\" WHERE \"host\" =~ /$winhost$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "RaspPi",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "PiPrint Frequency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 122 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rpi_freq",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "PiPrint Temperature",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 122 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "rpi_temp",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=", "value": "pi_print" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network - Router & Wifi UAP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "ERX Uptime",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "snmp.EdgeOS",
       "select": [
        [
         { "params": [ "sysUpTime" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=", "value": "192.168.0.1" }
       ]
      }
     ]
    },
    {
     "title": "ERX Interface Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 19, "x": 5, "y": 40 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_ifName:$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "ifName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifXTable",
       "select": [
        [
         { "params": [ "ifHCInOctets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "In" ], "type": "alias" }
        ],
        [
         { "params": [ "ifHCOutOctets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "Out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=", "value": "192.168.0.1" }
       ]
      }
     ]
    },
    {
     "title": "ERX Users",
     "type": "stat",
     "gridPos": { "h": 2, "w": 5, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "snmp.EdgeOS",
       "select": [
        [
         { "params": [ "hrSystemNumUsers" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=", "value": "192.168.0.1" }
       ]
      }
     ]
    },
    {
     "title": "ERX CPU Load Average",
     "type": "graph",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_laNames Minute",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "laNames" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "laTable",
       "select": [
        [
         { "params": [ "laLoadInt" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=", "value": "192.168.0.1" }
       ]
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 19, "x": 5, "y": 47 },
     "content": "eth0 = WAN | eth1 = NAS | eth2 = [Empty] | eth3 = Switch | eth4 = Wifi AP"
    },
    {
     "title": "Wifi UAP Uptime",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "snmp.UAP",
       "select": [
        [
         { "params": [ "sysUpTime" ], "type": "field" },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=", "value": "192.168.0.2" }
       ]
      }
     ]
    },
    {
     "title": "Wifi UAP CPU Load Average",
     "type": "graph",
     "gridPos": { "h": 6, "w": 9, "x": 4, "y": 49 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "alias": "$tag_loadDescr",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "loadDescr" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "loadTable",
       "select": [
        [
         { "params": [ "loadValue" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=", "value": "192.168.0.2" }
       ]
      }
     ]
    },
    {
     "title": "Stations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 11, "x": 13, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_unifiVapName",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "unifiVapName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unifiVapTable",
       "select": [
        [
         { "params": [ "unifiVapNumStations" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=", "value": "192.168.0.2" }
       ]
      }
     ]
    },
    {
     "title": "UAP Ethernet Traffic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_unifiIfName:$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "unifiIfName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unifiIfTable",
       "select": [
        [
         { "params": [ "unifiIfRxBytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "In" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiIfTxBytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "Out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=", "value": "192.168.0.2" }
       ]
      }
     ]
    },
    {
     "title": "UAP Wifi Traffic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "alias": "$tag_unifiVapName:$col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "unifiVapName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unifiVapTable",
       "select": [
        [
         { "params": [ "unifiVapRxBytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "In" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiVapTxBytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "Out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=", "value": "192.168.0.2" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network - Pihole & Speedtest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 },
   "targets": [
    {}
   ]
  },
  {
   "title": "pi-hole Ad blocking",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 123 },
   "targets": [
    {
     "measurement": "pihole",
     "query": "SELECT last(\"status\"), \"unique_clients\", \"dns_queries_today\", \"ads_percentage_today\", \"ads_blocked_today\", \"domains_being_blocked\", \"unique_domains\" FROM \"pihole\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "unique_clients" ], "type": "field" }
      ],
      [
       { "params": [ "dns_queries_today" ], "type": "field" }
      ],
      [
       { "params": [ "ads_percentage_today" ], "type": "field" }
      ],
      [
       { "params": [ "ads_blocked_today" ], "type": "field" }
      ],
      [
       { "params": [ "domains_being_blocked" ], "type": "field" }
      ],
      [
       { "params": [ "unique_domains" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Speedtest Ping",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speed_test_results",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ISP Speedtest",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Speedtest",
     "select": [
      [
       { "params": [ "download_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Download" ], "type": "alias" }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Speedtest",
     "select": [
      [
       { "params": [ "upload_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Upload" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network - Traefik",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Average Response Time - Backend (ms)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(traefik_backend_request_duration_seconds_sum) / sum(traefik_backend_requests_total) * 1000"
      }
     ]
    },
    {
     "title": "Average Response Time - Entrypoint (ms)",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 8, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "sum(traefik_entrypoint_request_duration_seconds_sum) / sum(traefik_entrypoint_requests_total) * 1000"
      }
     ]
    },
    {
     "title": "404 Error Count last 5 Minutes",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "expr": "sum(rate(traefik_backend_requests_total{code=\"404\",method=\"GET\",protocol=\"http\"}[5m])) * 1000"
      }
     ]
    },
    {
     "title": "Backend Servers Up",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 127 },
     "yaxes": [
      { "format": "none", "label": "Count" }
     ],
     "targets": [
      { "expr": "traefik_backend_server_up", "legendFormat": "{{backend}}" }
     ]
    },
    {
     "title": "Open Backend Connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 132 },
     "yaxes": [
      { "format": "none", "label": "Count" }
     ],
     "targets": [
      {
       "expr": "traefik_backend_open_connections",
       "legendFormat": "{{protocol}} {{backend}}"
      }
     ]
    },
    {
     "title": "Backend Requests - Success Code (200) - 5m rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 138 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(traefik_backend_requests_total{code=\"200\"}[5m])",
       "legendFormat": "{{backend}} {{protocol}} {{method}} {{code}}"
      }
     ]
    },
    {
     "title": "Backend Requests - Bad Codes - 5m rate",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 138 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(traefik_backend_requests_total{code!=\"200\"}[5m])",
       "legendFormat": "{{backend}} {{method}} {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transmission",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Leechers",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(transmission_torrent_leechers)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Current Speed - Download",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "transmission_session_stats_download_speed_bytes"
      }
     ]
    },
    {
     "title": "Current Speed - Upload",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 16, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "transmission_session_stats_upload_speed_bytes"
      }
     ]
    },
    {
     "title": "Seeders",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(transmission_torrent_seeders)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Number of torrents",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(transmission_torrent_done)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Downloaded - Total",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 5, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "transmission_session_stats_downloaded_bytes{type=\"cumulative\"}"
      }
     ]
    },
    {
     "title": "% Completion",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      { "expr": "transmission_torrent_done", "legendFormat": "{{name}}" }
     ]
    },
    {
     "title": "Download Speed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 93 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "transmission_torrent_download_bytes{}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Uploaded - Total",
     "type": "stat",
     "gridPos": { "h": 2, "w": 7, "x": 9, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "transmission_session_stats_uploaded_bytes{type=\"cumulative\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Media Stack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total BW",
     "type": "stat",
     "description": "Streaming Brain Estimate",
     "gridPos": { "h": 2, "w": 2, "x": 1, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "measurement": "Tautulli",
       "select": [
        [
         { "params": [ "total_bandwidth" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "current_stream_stats" }
       ]
      }
     ]
    },
    {
     "title": "LAN BW",
     "type": "stat",
     "description": "Streaming Brain Estimate",
     "gridPos": { "h": 2, "w": 2, "x": 3, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Tautulli",
       "select": [
        [
         { "params": [ "lan_bandwidth" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "current_stream_stats" }
       ]
      }
     ]
    },
    {
     "title": "WAN BW",
     "type": "stat",
     "description": "Streaming Brain Estimate",
     "gridPos": { "h": 2, "w": 2, "x": 5, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "Kbits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Tautulli",
       "select": [
        [
         { "params": [ "wan_bandwidth" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "current_stream_stats" }
       ]
      }
     ]
    },
    {
     "title": "Device Types (Tautulli)",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 5, "x": 8, "y": 65 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "alias": "$tag_device_type",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "device_type" ], "type": "tag" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "Tautulli",
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "select": [
        [
         { "params": [ "hash" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "type", "operator": "=", "value": "Session" }
       ],
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Stream Types (Tautulli)",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 5, "x": 13, "y": 65 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "alias": "$tag_video_decision",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "video_decision" ], "type": "tag" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "Tautulli",
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "select": [
        [
         { "params": [ "hash" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "type", "operator": "=", "value": "Session" }
       ],
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Stream Count (Tautulli)",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 65 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "alias": "$tag_friendly_name",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "friendly_name" ], "type": "tag" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "Tautulli",
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "select": [
        [
         { "params": [ "hash" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "tags": [
        { "key": "type", "operator": "=", "value": "Session" }
       ],
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Total Streams",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Tautulli",
       "select": [
        [
         { "params": [ "stream_count" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "current_stream_stats" }
       ]
      }
     ]
    },
    {
     "title": "Transocde Streams",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Tautulli",
       "select": [
        [
         { "params": [ "transcode_streams" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "current_stream_stats" }
       ]
      }
     ]
    },
    {
     "title": "Direct Play Streams",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Tautulli",
       "select": [
        [
         { "params": [ "direct_play_streams" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "current_stream_stats" }
       ]
      }
     ]
    },
    {
     "title": "Direct Stream",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Tautulli",
       "select": [
        [
         { "params": [ "direct_streams" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "current_stream_stats" }
       ]
      }
     ]
    },
    {
     "title": "TV Episodes",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Tautulli",
       "select": [
        [
         { "params": [ "episodes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "library_stats" },
        { "condition": "AND", "key": "section_name", "operator": "=", "value": "TV Shows" }
       ]
      }
     ]
    },
    {
     "title": "TV Seasons",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Tautulli",
       "select": [
        [
         { "params": [ "seasons" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "library_stats" },
        { "condition": "AND", "key": "section_name", "operator": "=", "value": "TV Shows" }
       ]
      }
     ]
    },
    {
     "title": "TV Shows",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Tautulli",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "library_stats" },
        { "condition": "AND", "key": "section_name", "operator": "=", "value": "TV Shows" }
       ]
      }
     ]
    },
    {
     "title": "TV - Recent",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "measurement": "Tautulli",
       "select": [
        [
         { "params": [ "episodes" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "library_stats" },
        { "condition": "AND", "key": "section_name", "operator": "=", "value": "TV Shows" }
       ]
      }
     ]
    },
    {
     "title": "Movies",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Tautulli",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "library_stats" },
        { "condition": "AND", "key": "section_name", "operator": "=", "value": "Movies" }
       ]
      }
     ]
    },
    {
     "title": "Movies - 3D",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 2, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Tautulli",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "library_stats" },
        { "condition": "AND", "key": "section_name", "operator": "=", "value": "Movies - 3D" }
       ]
      }
     ]
    },
    {
     "title": "Movies - 4K",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 4, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "Tautulli",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "library_stats" },
        { "condition": "AND", "key": "section_name", "operator": "=", "value": "Movies - 4K" }
       ]
      }
     ]
    },
    {
     "title": "Recently Added Movies",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 6, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "measurement": "Tautulli",
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "library_stats" },
        { "condition": "AND", "key": "section_name", "operator": "=", "value": "Movies" }
       ]
      }
     ]
    },
    {
     "title": "Movies in Queue (Radarr)",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 72 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "protocol_id" ], "type": "tag" },
        { "params": [ "quality" ], "type": "tag" }
       ],
       "measurement": "Radarr",
       "select": [
        [
         { "params": [ "hash" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Queue" }
       ]
      }
     ]
    },
    {
     "title": "TV Shows in Queue (Sonarr)",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 72 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "protocol_id" ], "type": "tag" },
        { "params": [ "sxe" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "Sonarr",
       "select": [
        [
         { "params": [ "hash" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Queue" }
       ]
      }
     ]
    },
    {
     "title": "Server Popularity",
     "type": "heatmap",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 73 },
     "targets": [
      {
       "alias": ".",
       "application": { "filter": "" },
       "group": { "filter": "" },
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "host": { "filter": "" },
       "item": { "filter": "" },
       "measurement": "Tautulli",
       "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
       },
       "select": [
        [
         { "params": [ "hash" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "table": {
        "skipEmptyValues": false
       },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Users Online - 24h (Tautulli)",
     "type": "table-old",
     "gridPos": { "h": 8, "w": 16, "x": 0, "y": 76 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "title" ], "type": "tag" },
        { "params": [ "quality" ], "type": "tag" },
        { "params": [ "video_decision" ], "type": "tag" },
        { "params": [ "quality_profile" ], "type": "tag" },
        { "params": [ "platform" ], "type": "tag" },
        { "params": [ "product_version" ], "type": "tag" },
        { "params": [ "location" ], "type": "tag" }
       ],
       "measurement": "Tautulli",
       "query": "SELECT distinct(\"hash\") FROM \"Tautulli\" WHERE (\"type\" = 'Session') AND $timeFilter GROUP BY \"friendly_name\",  \"title\", \"quality\", \"video_decision\", \"quality_profile\", \"platform\", \"product_version\", \"location\", \"player_state\"",
       "select": [
        [
         { "params": [ "session_key" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Session" }
       ]
      }
     ]
    },
    {
     "title": "Missing Available Movies (Radarr)",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 76 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "titleSlug" ], "type": "tag" }
       ],
       "measurement": "Radarr",
       "select": [
        [
         { "params": [ "hash" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "Missing_Available", "operator": "=", "value": "0" }
       ]
      }
     ]
    },
    {
     "title": "Missing TV Shows [Last 7 Days] (Sonarr)",
     "type": "table-old",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 80 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "sxe" ], "type": "tag" },
        { "params": [ "server" ], "type": "tag" }
       ],
       "measurement": "Sonarr",
       "select": [
        [
         { "params": [ "hash" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Missing" }
       ]
      }
     ]
    }
   ]
  }
 ]
}