{
 "title": "SpeedTest",
 "description": "A dashboard to display speedtest results (Dashboard: 13053)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "SpeedTest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Download Speed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "Speedtest_download_bandwidth", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Upload Speed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "Speedtest_upload_bandwidth", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Response Time",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "Speedtest_ping_latency", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Last Test Duration",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "Speedtest_download_elapsed", "legendFormat": "__auto" },
      { "expr": "Speedtest_upload_elapsed", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Download Test Size Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      { "expr": "Speedtest_download_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Upload Test Size Total",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      { "expr": "Speedtest_upload_bytes", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Speedtest Results",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "expr": "Speedtest_download_bandwidth * 8",
       "legendFormat": "Download"
      },
      { "expr": "Speedtest_upload_bandwidth * 8", "legendFormat": "Upload" }
     ]
    },
    {
     "title": "Results",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "Speedtest_server_id", "legendFormat": "__auto" },
      { "expr": "Speedtest_server_ip", "legendFormat": "__auto" },
      { "expr": "Speedtest_server_host", "legendFormat": "__auto" },
      { "expr": "Speedtest_server_location", "legendFormat": "__auto" },
      { "expr": "Speedtest_result_url", "legendFormat": "__auto" },
      { "expr": "Speedtest_download_bandwidth", "legendFormat": "__auto" },
      { "expr": "Speedtest_upload_bandwidth", "legendFormat": "__auto" },
      { "expr": "Speedtest_download_bytes", "legendFormat": "__auto" },
      { "expr": "Speedtest_upload_bytes", "legendFormat": "__auto" },
      { "expr": "Speedtest_download_elapsed", "legendFormat": "__auto" },
      { "expr": "Speedtest_upload_elapsed", "legendFormat": "__auto" },
      { "expr": "Speedtest_ping_jitter", "legendFormat": "__auto" },
      { "expr": "Speedtest_ping_latency", "legendFormat": "__auto" },
      { "expr": "Speedtest_packetLoss", "legendFormat": "__auto" },
      {}
     ]
    }
   ]
  }
 ]
}