{
 "title": "Windows (WIP)",
 "description": "Metrics for Windows devices reporting to InfluxDB",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": {
     "query": "label_values(win_system_System_Up_Time,host)"
    }
   },
   {
    "name": "network",
    "label": "Network Interface",
    "query": {
     "query": "label_values(win_net_Bytes_Received_persec{host=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "hostname_influx",
    "label": "Hostname",
    "query": "SHOW TAG VALUES FROM \"win_system\" WITH KEY = \"host\""
   },
   {
    "name": "network_influx",
    "label": "Network Interface",
    "query": "SHOW TAG VALUES FROM \"win_net\" WITH KEY = \"instance\" WHERE host =~ /$hostname/"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview - Uptime, Disk Space, Network Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clients Uptime",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    { "expr": "win_system_System_Up_Time", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Space Free",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-win_disk_Percent_Free_Space{instance!~\"HarddiskVolume.+\"}",
     "legendFormat": "{{host}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(win_net_Packets_Received_persec[$__interval])",
     "legendFormat": "Received: {{instance}}"
    },
    {
     "expr": "avg_over_time(win_net_Packets_Sent_persec[$__interval]) * -1",
     "legendFormat": "Sent: {{instance}}"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg_over_time(win_net_Bytes_Received_persec[$__interval])",
     "legendFormat": "Received: {{instance}}"
    },
    {
     "expr": "avg_over_time(win_net_Bytes_Sent_persec{instance=~\"$network\"}[$__interval]) * -1",
     "legendFormat": "Sent: {{instance}}"
    }
   ]
  },
  {
   "title": "Client Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$hostname - Uptime",
   "type": "stat",
   "description": "for $hostname",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 16 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "win_system_System_Up_Time{host=~\"$hostname\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "for $hostname",
   "gridPos": { "h": 5, "w": 2, "x": 3, "y": 16 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "win_cpu_Percent_Processor_Time{instance=~\".*Total\", host=~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "gauge",
   "description": "for $hostname",
   "gridPos": { "h": 5, "w": 2, "x": 5, "y": 16 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "win_mem_Available_Bytes{host=~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 16 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-win_disk_Percent_Free_Space{host=~\"$hostname\",instance!~\"HarddiskVolume.+\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "win_cpu_Percent_User_Time{host=~\"$hostname\", instance=~\".*Total\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "win_cpu_Percent_Privileged_Time{host=~\"$hostname\", instance=~\".*Total\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "win_cpu_Percent_Interrupt_Time{host=~\"$hostname\", instance=~\".*Total\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "win_cpu_Percent_DPC_Time{host=~\"$hostname\", instance=~\".*Total\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "repeat": "hostname",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg_over_time(win_net_Bytes_Received_persec{host=~\"$hostname\", instance=~\"$network\"}[$__interval])",
     "legendFormat": "Received: {{instance}}"
    },
    {
     "expr": "avg_over_time(win_net_Bytes_Sent_persec{host=~\"$hostname\", instance=~\"$network\"}[$__interval]) * -1",
     "legendFormat": "Sent: {{instance}}"
    }
   ]
  },
  {
   "title": "$hostname",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "hostname",
   "targets": [
    {}
   ]
  },
  {
   "title": "Last Uptime - $hostname",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "win_system_System_Up_Time{host=~\"$hostname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used - %",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100- win_disk_Percent_Free_Space{host=~\"$hostname\",instance!~\"HarddiskVolume.+\"}",
     "legendFormat": "[{{host}}] {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Space Free",
   "type": "table",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "win_disk_Free_Megabytes{host=~\"$hostname\",instance!~\"HarddiskVolume.+\"}"
    },
    {
     "expr": "100 - win_disk_Percent_Free_Space{host=~\"$hostname\",instance!~\"HarddiskVolume.+\"}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "win_cpu_Percent_User_Time{host=~\"$hostname\", instance=~\".*Total\"}",
     "legendFormat": "% User [{{host}}]"
    },
    {
     "expr": "win_cpu_Percent_Privileged_Time{host=~\"$hostname\", instance=~\".*Total\"}",
     "legendFormat": "% Privileged [{{host}}]"
    },
    {
     "expr": "win_cpu_Percent_Interrupt_Time{host=~\"$hostname\", instance=~\".*Total\"}",
     "legendFormat": "% Interrupt [{{host}}]"
    },
    {
     "expr": "win_cpu_Percent_DPC_Time{host=~\"$hostname\", instance=~\".*Total\"}",
     "legendFormat": "% DPC [{{host}}]"
    }
   ]
  },
  {
   "title": "GPU - Utilization (Nvidia Only)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvidia_smi_utilization_gpu{host=~\"$hostname\"}",
     "legendFormat": "GPU Utilisation"
    },
    {
     "expr": "nvidia_smi_utilization_memory{host=~\"$hostname\"}",
     "legendFormat": "Memory Utilisation"
    },
    {
     "expr": "nvidia_smi_clocks_current_graphics{host=~\"$hostname\"}",
     "legendFormat": "Video Clock"
    },
    {
     "expr": "nvidia_smi_clocks_current_memory{host=~\"$hostname\"}",
     "legendFormat": "Memory Clock"
    }
   ]
  },
  {
   "title": "GPU - Temp & Power (Nvidia Only)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "nvidia_smi_power_draw{host=~\"$hostname\"}",
     "legendFormat": "GPU Power"
    },
    {
     "expr": "nvidia_smi_temperature_gpu{host=~\"$hostname\"}",
     "legendFormat": "Temperature"
    },
    {
     "expr": "nvidia_smi_fan_speed{host=~\"$hostname\"}",
     "legendFormat": "Fan Speed"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "win_mem_Available_Bytes{host=~\"$hostname\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "win_mem_Pool_Nonpaged_Bytes{host=~\"$hostname\"}",
     "legendFormat": "Pool - Non-Paged"
    },
    {
     "expr": "win_mem_Pool_Paged_Bytes{host=~\"$hostname\"}",
     "legendFormat": "Pool - Paged"
    }
   ]
  },
  {
   "title": "Memory Cache Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "win_mem_Standby_Cache_Core_Bytes{host=~\"$hostname\"}",
     "legendFormat": "Standby Cache Core Bytes"
    },
    {
     "expr": "win_mem_Standby_Cache_Reserve_Bytes{host=~\"$hostname\"}",
     "legendFormat": "Standby Cache Reserve Bytes"
    },
    {
     "expr": "win_mem_Standby_Cache_Normal_Priority_Bytes{host=~\"$hostname\"}",
     "legendFormat": "Standby_Cache Normal Priority Bytes"
    }
   ]
  },
  {
   "title": "Memory Usage Rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "win_mem_Cache_Faults_persec{host=~\"$hostname\"}",
     "legendFormat": "Cache Faults persec"
    },
    {
     "expr": "win_mem_Demand_Zero_Faults_persec{host=~\"$hostname\"}",
     "legendFormat": "Demand Zero Faults persec"
    },
    {
     "expr": "win_mem_Page_Faults_persec{host=~\"$hostname\"}",
     "legendFormat": "Page Faults persec"
    },
    {
     "expr": "win_mem_Pages_persec{host=~\"$hostname\"}",
     "legendFormat": "Pages persec"
    },
    {
     "expr": "win_mem_Transition_Faults_persec{host=~\"$hostname\"}",
     "legendFormat": "Transition Faults persec"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$col: $tag_instance [$tag_host]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "query": "SELECT mean(\"Bytes_Received_persec\") AS \"Bytes Received persec\" FROM \"win_net\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "Bytes_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Bytes Received persec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "$col: $tag_instance [$tag_host]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "query": "SELECT mean(\"Bytes_Sent_persec\") *-1 AS \"Bytes Sent persec\" FROM \"win_net\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "Bytes_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "Bytes Sent persec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col: $tag_instance [$tag_host]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "query": "SELECT mean(\"Packets_Received_persec\") AS \"Packets Received persec\" FROM \"win_net\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "Packets_Received_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Packets Received persec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "$col: $tag_instance [$tag_host]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "query": "SELECT mean(\"Packets_Sent_persec\") *-1 AS \"Packets Sent persec\" FROM \"win_net\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "Packets_Sent_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "Packets Sent persec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Packet Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col: $tag_instance [$tag_host]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "query": "SELECT mean(\"Packets_Received_Discarded\") AS \"Packets Received Disacarded\", mean(\"Packets_Received_Errors\") AS \"Packets Received Errors\" FROM \"win_net\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "Packets_Received_Discarded" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Packets Received Disacarded" ], "type": "alias" }
      ],
      [
       { "params": [ "Packets_Received_Errors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Packets Received Errors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "$col: $tag_instance [$tag_host]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_net",
     "query": "SELECT mean(\"Packets_Outbound_Discarded\") *-1 AS \"Packets Sent Discarded\", mean(\"Packets_Outbound_Errors\") *-1 AS \"Packets Sent Errors\" FROM \"win_net\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "Packets_Outbound_Discarded" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "Packets Sent Discarded" ], "type": "alias" }
      ],
      [
       { "params": [ "Packets_Outbound_Errors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "Packets Sent Errors" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "Read: [$tag_host] $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT last(\"Percent_Disk_Read_Time\") AS \"Read Time percent\" FROM \"win_disk\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"instance\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Percent_Disk_Read_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Read Time percent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    },
    {
     "alias": "Write: [$tag_host] $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT last(\"Percent_Disk_Write_Time\") *-1 AS \"Write Time percent\" FROM \"win_disk\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"instance\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Percent_Disk_Write_Time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*-1" ], "type": "math" },
       { "params": [ "Write Time percent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[$tag_host] $tag_instance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT mean(\"Current_Disk_Queue_Length\") FROM \"win_disk\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"host\", \"instance\" fill(null)",
     "select": [
      [
       { "params": [ "Current_Disk_Queue_Length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_system",
     "query": "SELECT mean(\"Context_Switches_persec\") AS \"Context Switches persec\" FROM \"win_system\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "Context_Switches_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Context Switches persec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "System Calls",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_host: $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_system",
     "query": "SELECT mean(\"System_Calls_persec\") AS \"Context Switches persec\" FROM \"win_system\" WHERE (\"host\" =~ /^$hostname$/) AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "System_Calls_persec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Context Switches persec" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  }
 ]
}