{
 "title": "Cadvisor - Docker Containers",
 "description": "Metrics for Docker containers",
 "tags": [
  "docker",
  "prometheus",
  "cadvisor",
  "nodeexporter",
  "production"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host_system",
    "label": "Host System",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},host_system)"
    }
   },
   {
    "name": "group",
    "label": "Container Group",
    "query": "external,home-auto,minecraft,monitoring,torrent,sablier"
   },
   {
    "name": "containers",
    "label": "Containers",
    "query": {
     "query": "label_values({__name__=~\"container.*\",host_system=~\"$host_system\",container_label_org_label_schema_group=~\".*$group.*\"},name)"
    }
   },
   {
    "name": "interfaces",
    "label": "Interfaces",
    "query": {
     "query": "label_values(container_network_receive_bytes_total{host_system=~\"$host_system\"},interface)"
    }
   },
   {
    "name": "fsdevice",
    "label": "FS Device",
    "query": {
     "query": "label_values({__name__=~\"container_fs_.*\",host_system=~\"$host_system\"},device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cadvisor Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (host_system,cadvisorVersion,dockerVersion,osVersion,kernelVersion) (cadvisor_version_info{host_system=~\"$host_system\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host_system,id,name,pretty_name,version,version_codename,version_id) (node_os_info{host_system=~\"$host_system\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Image Count (FILTERED)",
   "type": "stat",
   "description": "Uses crontab command to push metric to VictoriaMetrics since not available via Cadvisor.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "docker_custom_image_count{host_system=~\"$host_system\"}",
     "legendFormat": "{{host_system}}"
    }
   ]
  },
  {
   "title": "Running Containers (FILTERED)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(host_system) (container_last_seen{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"})",
     "legendFormat": "{{host_system}}"
    }
   ]
  },
  {
   "title": "Running Containers (FILTERED)",
   "type": "table",
   "description": "Excludes containers which have been stopped by Sablier",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "now() - max(container_start_time_seconds{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name,container_label_com_docker_compose_project_config_files,container_label_org_label_schema_group,image)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(container_memory_usage_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(container_memory_rss{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(container_memory_working_set_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(container_memory_swap{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(container_memory_migrate{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(container_memory_mapped_file{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(container_memory_cache{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(container_spec_memory_limit_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HOST CPU Use ",
   "type": "gauge",
   "description": "Busy state of all CPU cores together\n\n[Node Exporter]",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(host_system) (irate(node_cpu_seconds_total{host_system=~\"$host_system\", mode!=\"idle\"}[$__rate_interval])) / on(host_system) group_left sum by (host_system)((irate(node_cpu_seconds_total{host_system=~\"$host_system\"}[$__rate_interval])))) * 100",
     "legendFormat": "{{host_system}}"
    }
   ]
  },
  {
   "title": "Container CPU Use (ALL CONTAINERS)",
   "type": "gauge",
   "description": "[Node Exporter & Cadvisor]\n",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(host_system) (irate(container_cpu_usage_seconds_total{host_system=~\"$host_system\",name=~\".+\"}[$__rate_interval])) / on(host_system) group_left sum by (host_system)((irate(node_cpu_seconds_total{host_system=~\"$host_system\"}[$__rate_interval])))) * 100",
     "legendFormat": "{{host_system}}"
    }
   ]
  },
  {
   "title": "Container CPU Use (FILTERED)",
   "type": "gauge",
   "description": "[Node Exporter & Cadvisor]",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(host_system) (irate(container_cpu_usage_seconds_total{host_system=~\"$host_system\",name=~\"$containers\"}[$__rate_interval])) / on(host_system) group_left sum by (host_system)((irate(node_cpu_seconds_total{host_system=~\"$host_system\"}[$__rate_interval])))) * 100",
     "legendFormat": "{{host_system}}"
    }
   ]
  },
  {
   "title": "HOST RAM Used ",
   "type": "gauge",
   "description": "[Node Exporter]\n\nSee 'Memory Metrics Explained' row below.",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{host_system=~\"$host_system\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{host_system=~\"$host_system\"}[$__rate_interval]))",
     "legendFormat": "{{host_system}}"
    }
   ]
  },
  {
   "title": "Container RAM Use (ALL CONTAINERS)",
   "type": "gauge",
   "description": "[Node Exporter & Cadvisor]\n\nSee 'Memory Metrics Explained' row below.",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{host_system=~\"$host_system\",name=~\".+\",name!~\"\"}) by(host_system)) / (sum(node_memory_MemTotal_bytes{host_system=~\"$host_system\"}) by(host_system)) * 100",
     "legendFormat": "{{host_system}}"
    }
   ]
  },
  {
   "title": "Container RAM Use (FILTERED)",
   "type": "gauge",
   "description": "[Node Exporter & Cadvisor]\n\nSee 'Memory Metrics Explained' row below.",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_working_set_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by(host_system)) / (sum(node_memory_MemTotal_bytes{host_system=~\"$host_system\"}) by(host_system)) * 100",
     "legendFormat": "{{host_system}}"
    }
   ]
  },
  {
   "title": "CPU - Percent (FILTERED)",
   "type": "timeseries",
   "description": "• container_cpu_usage_seconds_total: Measures the amount of CPU time used by the container - sum of container_cpu_user_seconds_total and container_cpu_system_seconds_total. If the CPU is fully utilized and unable to handle additional requests, it can lead to saturation.\n\n• node_cpu_seconds_total: Node Exporter measure of total seconds CPU has spent in each category - summing all categories to get total CPU seconds.\n\n\n[Node Exporter & Cadvisor]",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (host_system,name) (rate(container_cpu_usage_seconds_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}[$__rate_interval])) / scalar(count(node_cpu_seconds_total{host_system=~\"$host_system\",mode=\"user\"})) * 100",
     "legendFormat": "{{host_system}} - {{ name }}"
    },
    {
     "expr": "sum by (host_system) (rate(container_cpu_usage_seconds_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\"}[$__rate_interval])) / scalar(count(node_cpu_seconds_total{host_system=~\"$host_system\",mode=\"user\"})) * 100",
     "legendFormat": "{{host_system}} - ALL CONTAINERS"
    }
   ]
  },
  {
   "title": "Memory - Working Set (FILTERED)",
   "type": "timeseries",
   "description": "See 'Memory Metrics Explained' row.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host_system,name) (container_memory_working_set_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"})",
     "legendFormat": "{{host_system}} - {{ name }}"
    },
    {
     "expr": "sum by (host_system) (container_memory_working_set_bytes{host_system=~\"$host_system\",name=~\".+\",name!~\"\"})",
     "legendFormat": "{{host_system}} - ALL CONTAINERS"
    }
   ]
  },
  {
   "title": "Network Traffic (FILTERED)",
   "type": "timeseries",
   "description": "Received and transmitted bytes rate - per container.\nMeasure the amount of network traffic transmitted and received by the container, respectively. When the network becomes saturated, the container may experience latency or dropped requests.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host_system,name) (rate(container_network_receive_bytes_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
     "legendFormat": "IN: {{host_system}} - {{name}}"
    },
    {
     "expr": "sum by (host_system,name) (rate(container_network_transmit_bytes_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
     "legendFormat": "OUT: {{host_system}} - {{name}}"
    },
    {
     "expr": "sum by (host_system) (rate(container_network_receive_bytes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
     "legendFormat": "IN: {{host_system}} - ALL CONTAINERS"
    },
    {
     "expr": "sum by (host_system) (rate(container_network_transmit_bytes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
     "legendFormat": "OUT: {{host_system}} - ALL CONTAINERS"
    }
   ]
  },
  {
   "title": "IO Bytes Per Container (FILTERED)",
   "type": "timeseries",
   "description": "Bytes per second.\n\nNote that the metrics are produced such that some of them have container names, and some don't. The ones without container names appear to cover the reads/writes as applied to the whole device. \n\nWe have created output to show:\n\n• <container_name> = metrics which include a container name are displayed according to dashboard Container filter.\n\nIt was too complex to show additional breakdown of IOps metrics in the same chart - see other panel for IOps charts showing:\n\n• ALL CONTAINERS = summation per device of all metrics with container names specified. \n\n• NO CONTAINERS = summation per device of all metrics without a container name specified. \n\n• ALL DEVICE = summation per device, regardless of whether it has a container name specified or not.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (host_system,name,device) (rate(container_fs_reads_bytes_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
     "legendFormat": "READ : {{host_system}} - {{name}} ({{ device }})"
    },
    {
     "expr": "sum by (host_system,name,device) (rate(container_fs_writes_bytes_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
     "legendFormat": "WRITE : {{host_system}} - {{name}} ({{ device }})"
    },
    {
     "expr": "sum by (host_system,device) (rate(container_fs_reads_bytes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
     "legendFormat": "READ : {{host_system}} - ALL CONTAINERS ({{ device }})"
    },
    {
     "expr": "sum by (host_system,device) (rate(container_fs_writes_bytes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
     "legendFormat": "WRITE : {{host_system}} - ALL CONTAINERS ({{ device }})"
    }
   ]
  },
  {
   "title": "CPU - $host_system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "host_system",
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - Percent (FILTERED)",
     "type": "timeseries",
     "description": "• container_cpu_usage_seconds_total: Measures the amount of CPU time used by the container - sum of container_cpu_user_seconds_total and container_cpu_system_seconds_total. If the CPU is fully utilized and unable to handle additional requests, it can lead to saturation.\n\n• node_cpu_seconds_total: Node Exporter measure of total seconds CPU has spent in each category - summing all categories to get total CPU seconds.\n\n\n[Node Exporter & Cadvisor]",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (host_system,name) (rate(container_cpu_usage_seconds_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}[$__rate_interval])) / scalar(count(node_cpu_seconds_total{host_system=~\"$host_system\",mode=\"user\"})) * 100",
       "legendFormat": "{{host_system}} - {{ name }}"
      },
      {
       "expr": "sum by (host_system) (rate(container_cpu_usage_seconds_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\"}[$__rate_interval])) / scalar(count(node_cpu_seconds_total{host_system=~\"$host_system\",mode=\"user\"})) * 100",
       "legendFormat": "{{host_system}} - ALL CONTAINERS"
      }
     ]
    },
    {
     "title": "CPU - Host (NodeExporter)",
     "type": "timeseries",
     "description": "[Node Exporter]",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{host_system=~\"$host_system\", mode=\"system\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{host_system=~\"$host_system\"}[$__rate_interval])))",
       "legendFormat": "System - Processes executing in kernel mode"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{host_system=~\"$host_system\", mode=\"user\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{host_system=~\"$host_system\"}[$__rate_interval])))",
       "legendFormat": "User - Normal processes executing in user mode"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{host_system=~\"$host_system\", mode=\"nice\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{host_system=~\"$host_system\"}[$__rate_interval])))",
       "legendFormat": "Nice - Niced processes executing in user mode"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{host_system=~\"$host_system\", mode=\"iowait\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{host_system=~\"$host_system\"}[$__rate_interval])))",
       "legendFormat": "Iowait - Waiting for I/O to complete"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{host_system=~\"$host_system\", mode=\"irq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{host_system=~\"$host_system\"}[$__rate_interval])))",
       "legendFormat": "Irq - Servicing interrupts"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{host_system=~\"$host_system\", mode=\"softirq\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{host_system=~\"$host_system\"}[$__rate_interval])))",
       "legendFormat": "Softirq - Servicing softirqs"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{host_system=~\"$host_system\", mode=\"steal\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{host_system=~\"$host_system\"}[$__rate_interval])))",
       "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{host_system=~\"$host_system\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{host_system=~\"$host_system\"}[$__rate_interval])))",
       "legendFormat": "Idle - Waiting for something to happen"
      }
     ]
    },
    {
     "title": "CPU - Use (FILTERED)",
     "type": "timeseries",
     "description": "• container_cpu_usage_seconds_total: Measures the amount of CPU time used by the container - sum of container_cpu_user_seconds_total and container_cpu_system_seconds_total. If the CPU is fully utilized and unable to handle additional requests, it can lead to saturation.\n",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (host_system,name) (rate(container_cpu_usage_seconds_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}[$__rate_interval]))",
       "legendFormat": "{{host_system}} - {{ name }}"
      },
      {
       "expr": "sum by (host_system) (rate(container_cpu_usage_seconds_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\"}[$__rate_interval]))",
       "legendFormat": "{{host_system}} - ALL CONTAINERS"
      }
     ]
    },
    {
     "title": "CPU Throttled",
     "type": "timeseries",
     "description": "container_cpu_cfs_throttled_seconds_total = This measures the total amount of time a certain container has been throttled due to being over its CFS (Completely Fair Scheduler) quota. Generally, container CPU usage can be throttled to prevent a single busy container from essentially choking other containers by taking away all the available CPU resources.\n\nThrottling is usually a good way to ensure a minimum processing power is available for essential services on all running containers. This metric measures the total time that a container’s CPU usage was throttled, and observing this provides the information one needs to properly reallocate resources to specific containers. This can be done, for example, by adjusting the setting for CPU shares in Docker.‍",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (host_system,name) (rate(container_cpu_cfs_throttled_seconds_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}[$__rate_interval]))",
       "legendFormat": "{{host_system}} - {{name}}"
      },
      {
       "expr": "sum by (host_system) (rate(container_cpu_cfs_throttled_seconds_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\"}[$__rate_interval]))",
       "legendFormat": "{{host_system}} - ALL CONTAINERS"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Metrics Explained",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Metrics Explained",
     "type": "text",
     "gridPos": { "h": 34, "w": 24, "x": 0, "y": 63 },
     "options": {
      "content": "**container_memory_usage_bytes**\n* Size of all memory used regardless of when it was accessed (including both anonymous and page cache memory). Includes memory which can be evicted under memory pressure e.g. cached items.\n* Doesn’t show ‘exact’ value of memory (and swap) usage, it’s a fuzz value for efficient access. If you want to know more exact memory usage, you should use RSS+CACHE(+SWAP) value in memory.stat \n* (The value inside the memory.usage_in_bytes file)\n---\n**container_memory_working_set_bytes**\n* A heuristic for the minimum size of memory required for the app to work. It is an estimate of how much memory cannot be evicted. Equals container_memory_usage_bytes minus inactive memory (inactive_file: number of bytes of file-backed memory on inactive LRU list). \n* This metric is used to trigger Out Of Memory (OOM) actions if limits reached.\n* (Deduct inactive_file inside the memory.stat file from the  value inside the memory.usage_in_bytes file. If result is negative then use 0)\n---\n**container_memory_max_usage_bytes**\n* This metric gives the max memory usage recorded.\n* (The value inside the memory.max_usage_in_bytes file)\n---\n**container_memory_cache**\n* This measures the number of bytes used by a container's page cache. Size of memory used by the cache that’s automatically populated when reading/writing files. \n* (total_cache value in the memory.stat file inside the container’s cgroup directory folder)\n---\n**container_memory_rss**\n* Size of memory not used for mapping files from the disk. Number of bytes of anonymous and swap cache memory (includes transparent hugepages). This should not be confused with the true ‘resident set size’ or the amount of physical memory used by the cgroup. ‘rss + mapped_file’ will give you resident set size of cgroup.\n* (total_rss value in the memory.stat file inside the container’s cgroup directory folder)\n---\n**container_memory_mapped_file**\n* Size of memory that’s used for mapping files. Number of bytes of mapped file (includes tmpfs/shmem).\n* (total_mapped_file value in the memory.stat file inside the container’s cgroup directory folder)\n---\n**container_memory_swap**\n* Number of bytes of swap usage   \n* (total_swap value in the memory.stat file inside the container’s cgroup directory folder)\n---\n**container_spec_memory_limit_bytes**\n* Memory limit for the container. This will be 0 if no limits are set using the docker compose key 'mem_limit'.\n---\n**container_memory_failcnt**\n* Number of times a container’s memory usage hits the maximum limit. It is good practice to set container memory usage limits, to prevent memory-intensive tasks from essentially starving other containers on the same server by using all the available memory.\n* (The value inside the memory.failcnt file)\n---\n**container_memory_failures_total{failure_type=\"pagmajfault\"}**\n* Cumulative count of memory allocation failures. {failure_type=\"pagmajfault\"} filters the metric to only include MAJOR page faults, use ''.\n\n---\n\n###### Useful Sources\n* https://mihai-albert.com/2022/02/13/out-of-memory-oom-in-kubernetes-part-3-memory-metrics-sources-and-tools-to-collect-them/#cadvisor-table\n* https://blog.freshtracks.io/a-deep-dive-into-kubernetes-metrics-part-3-container-resource-metrics-361c5ee46e66\n"
     }
    }
   ]
  },
  { "title": "Memory - $host_system", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }, "repeat": "host_system" },
  {
   "title": "Memory - Working Set (FILTERED)",
   "type": "timeseries",
   "description": "Estimate of how much memory cannot be evicted. Equals container_memory_usage_bytes minus inactive memory (inactive_file: number of bytes of file-backed memory on inactive LRU list). This metric is used to trigger Out Of Memory (OOM) actions if limits reached.\n\nSee 'Memory Metrics Explained' row.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host_system,name) (container_memory_working_set_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"})",
     "legendFormat": "{{host_system}} - {{ name }}"
    },
    {
     "expr": "sum by (host_system) (container_memory_working_set_bytes{host_system=~\"$host_system\",name=~\".+\",name!~\"\"})",
     "legendFormat": "{{host_system}} - ALL CONTAINERS"
    }
   ]
  },
  {
   "title": "Memory - Usage (FILTERED)",
   "type": "timeseries",
   "description": "Size of all memory used regardless of when it was accessed (including both anonymous and page cache memory). Includes memory which can be evicted under memory pressure e.g. cached items.\n\nSee 'Memory Metrics Explained' row.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host_system,name) (container_memory_usage_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"})",
     "legendFormat": "{{host_system}} - {{ name }}"
    },
    {
     "expr": "sum by (host_system) (container_memory_usage_bytes{host_system=~\"$host_system\",name=~\".+\",name!~\"\"})",
     "legendFormat": "{{host_system}} - ALL CONTAINERS"
    }
   ]
  },
  {
   "title": "Memory - Working Set Percent Of Memory Limit Used (FILTERED)",
   "type": "timeseries",
   "description": "Working Set memory size divided by memory limit - Breaching 100% will likely trigger OOO event (although system may first try to evict memory to remain below limits).\n\nSee 'Memory Metrics Explained' row.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name) / sum(container_spec_memory_limit_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name) < 1",
     "legendFormat": "{{host_system}} - {{ name }}"
    }
   ]
  },
  {
   "title": "Memory - Cached Memory Usage (FILTERED)",
   "type": "timeseries",
   "description": "This measures the number of bytes used by a container's page cache. Size of memory used by the cache that’s automatically populated when reading/writing files.\n\nSee 'Memory Metrics Explained' row.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (host_system,name) (container_memory_cache{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"})",
     "legendFormat": "{{host_system}} - {{ name }}"
    },
    {
     "expr": "sum by (host_system) (container_memory_cache{host_system=~\"$host_system\",name=~\".+\",name!~\"\"})",
     "legendFormat": "{{host_system}} - ALL CONTAINERS"
    }
   ]
  },
  {
   "title": "Memory - Failures (FILTERED)",
   "type": "timeseries",
   "description": "Number of times a container’s memory usage hits the maximum limit.\n\nSee 'Memory Metrics Explained' row.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(container_memory_failcnt{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}[$__rate_interval])) by (host_system, name)",
     "legendFormat": "Max Mem Limit - {{host_system}} - {{ name }}"
    },
    {
     "expr": "sum(rate(container_memory_failcnt{host_system=~\"$host_system\",name=~\".+\",name!~\"\"}[$__rate_interval])) by (host_system)",
     "legendFormat": "Max Mem Limit - {{host_system}} - ALL CONTAINERS"
    },
    {
     "expr": "sum(rate(container_memory_failures_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",type=\"pagmajfault\"}[$__rate_interval])) by (host_system, name)",
     "legendFormat": "Major Mem Alloc Errors - {{host_system}} - {{ name }}"
    },
    {
     "expr": "sum(rate(container_memory_failures_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",type=\"pagmajfault\"}[$__rate_interval])) by (host_system)",
     "legendFormat": "Major Mem Alloc Errors - {{host_system}} - ALL CONTAINERS"
    }
   ]
  },
  {
   "title": "Swap - HOST Swap",
   "type": "timeseries",
   "description": "[Node Exporter]",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{host_system=~\"$host_system\"} - node_memory_SwapFree_bytes{host_system=~\"$host_system\"}",
     "legendFormat": "SWAP Used (Bytes)"
    },
    {
     "expr": "((node_memory_SwapTotal_bytes{host_system=~\"$host_system\"} - node_memory_SwapFree_bytes{host_system=~\"$host_system\"}) / (node_memory_SwapTotal_bytes{host_system=~\"$host_system\"} )) * 100",
     "legendFormat": "SWAP Used (%)"
    }
   ]
  },
  {
   "title": "Swap - ALL Containers Swap Usage",
   "type": "timeseries",
   "description": "Number of bytes of swap usage\n\nSee 'Memory Metrics Explained' row.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host_system,name) (container_memory_swap{host_system=~\"$host_system\",name=~\".+\",name!~\"\"})",
     "legendFormat": "{{host_system}} - {{ name }}"
    }
   ]
  },
  {
   "title": "Swap - Container Swap Usage (FILTERED)",
   "type": "timeseries",
   "description": "Number of bytes of swap usage\n\nSee 'Memory Metrics Explained' row.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (host_system,name) (container_memory_swap{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"})",
     "legendFormat": "{{host_system}} - {{ name }}"
    },
    {
     "expr": "sum by (host_system) (container_memory_swap{host_system=~\"$host_system\",name=~\".+\",name!~\"\"})",
     "legendFormat": "{{host_system}} - ALL CONTAINERS"
    }
   ]
  },
  {
   "title": "Swap - Percent Of Swap Limit Used (FILTERED)",
   "type": "timeseries",
   "description": "Container swap usage divided by Swap Memory Limit. (equals ∞ if no swap limit set)\n\nSee 'Memory Metrics Explained' row.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_swap{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name) / sum(container_spec_memory_swap_limit_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name) ",
     "legendFormat": "{{host_system}} - {{ name }}"
    }
   ]
  },
  {
   "title": "Network - $host_system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "repeat": "host_system",
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic (FILTERED)",
     "type": "timeseries",
     "description": "Received and transmitted bytes rate - per container.\nMeasure the amount of network traffic transmitted and received by the container, respectively. When the network becomes saturated, the container may experience latency or dropped requests.\n\nNote that the metrics are produced such that some of them have container names, and some don't. The ones without container names appear to cover the reads/writes as applied to the whole device. \n\nWe have created output to show:\n\n• <container_name> = metrics which include a container name are displayed according to dashboard Container filter.\n\nIt was too complex to show additional breakdown of metrics in the same chart - see other panel for charts showing:\n\n• ALL CONTAINERS = summation per device of all metrics with container names specified. \n\n• NO CONTAINERS = summation per device of all metrics without a container name specified. \n\n• ALL INTERFACE = summation per interface, regardless of whether it has a container name specified or not.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (host_system,name) (rate(container_network_receive_bytes_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
       "legendFormat": "IN: {{host_system}} - {{name}}"
      },
      {
       "expr": "sum by (host_system,name) (rate(container_network_transmit_bytes_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
       "legendFormat": "OUT: {{host_system}} - {{name}}"
      },
      {
       "expr": "sum by (host_system) (rate(container_network_receive_bytes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
       "legendFormat": "IN: {{host_system}} - ALL CONTAINERS"
      },
      {
       "expr": "sum by (host_system) (rate(container_network_transmit_bytes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
       "legendFormat": "OUT: {{host_system}} - ALL CONTAINERS"
      }
     ]
    },
    {
     "title": "Traffic Per Interface",
     "type": "timeseries",
     "description": "Received and transmitted bytes rate - per interface.\nMeasure the amount of network traffic transmitted and received by the container, respectively. When the network becomes saturated, the container may experience latency or dropped requests.\n\nNote that the metrics are produced such that some of them have container names, and some don't. The ones without container names appear to cover the reads/writes as applied to the whole device. \n\nSee other chart for (filtered) view of metrics per specific container. \n\nThis chart shows:\n\n• ALL CONTAINERS = summation per device of all metrics with container names specified. \n\n• NO CONTAINERS = summation per device of all metrics without a container name specified. \n\n• ALL INTERFACE = summation per interface, regardless of whether it has a container name specified or not.",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (host_system,interface) (rate(container_network_receive_bytes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
       "legendFormat": "IN - ALL CONTAINERS : {{host_system}} - {{interface}}"
      },
      {
       "expr": "sum by (host_system,interface) (rate(container_network_transmit_bytes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
       "legendFormat": "OUT - ALL CONTAINERS : {{host_system}} - {{interface}}"
      },
      {
       "expr": "sum by (host_system,interface) (rate(container_network_receive_bytes_total{host_system=~\"$host_system\",name=~\"\",interface=~\"$interfaces\"}[$__rate_interval])) ",
       "legendFormat": "IN - NO CONTAINERS : {{host_system}} - {{interface}}"
      },
      {
       "expr": "sum by (host_system,interface) (rate(container_network_transmit_bytes_total{host_system=~\"$host_system\",name=~\"\",interface=~\"$interfaces\"}[$__rate_interval])) ",
       "legendFormat": "OUT - NO CONTAINERS : {{host_system}} - {{interface}}"
      },
      {
       "expr": "sum by (host_system,interface) (rate(container_network_receive_bytes_total{host_system=~\"$host_system\",interface=~\"$interfaces\"}[$__rate_interval])) ",
       "legendFormat": "IN - ALL INTERFACE : {{host_system}} - {{interface}}"
      },
      {
       "expr": "sum by (host_system,interface) (rate(container_network_transmit_bytes_total{host_system=~\"$host_system\",interface=~\"$interfaces\"}[$__rate_interval])) ",
       "legendFormat": "OUT -  ALL INTERFACE : {{host_system}} - {{interface}}"
      }
     ]
    },
    {
     "title": "Networking Errors (FILTERED)",
     "type": "timeseries",
     "description": "Received and transmitted error rate - per container.\nThis measures the cumulative count of errors encountered while receiving/transmitting bytes over your network. Networking on containers can get tricky sometimes, so it’s essential to keep an eye on failures when they occur. This metric simply lets you know how many failures occurred on inbound traffic, which gives you an idea of where to look for debugging.",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (host_system,name) (rate(container_network_receive_errors_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
       "legendFormat": "IN: {{host_system}} - {{name}}"
      },
      {
       "expr": "sum by (host_system,name) (rate(container_network_transmit_errors_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
       "legendFormat": "OUT: {{host_system}} - {{name}}"
      },
      {
       "expr": "sum by (host_system) (rate(container_network_receive_errors_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
       "legendFormat": "IN: {{host_system}} - ALL CONTAINERS"
      },
      {
       "expr": "sum by (host_system) (rate(container_network_transmit_errors_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
       "legendFormat": "OUT: {{host_system}} - ALL CONTAINERS"
      }
     ]
    },
    {
     "title": "Networking Packet Drops (FILTERED)",
     "type": "timeseries",
     "description": "Rate of packet drops - per container.\nThis measures the cumulative count of errors encountered while receiving/transmitting bytes over your network. Networking on containers can get tricky sometimes, so it’s essential to keep an eye on failures when they occur. This metric simply lets you know how many failures occurred on inbound traffic, which gives you an idea of where to look for debugging.",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (host_system,name) (rate(container_network_receive_packets_dropped_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval])) !=0",
       "legendFormat": "IN: {{host_system}} - {{name}}"
      },
      {
       "expr": "sum by (host_system,name) (rate(container_network_transmit_packets_dropped_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval])) !=0",
       "legendFormat": "OUT: {{host_system}} - {{name}}"
      },
      {
       "expr": "sum by (host_system) (rate(container_network_receive_packets_dropped_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval])) !=0",
       "legendFormat": "IN: {{host_system}} - ALL CONTAINERS"
      },
      {
       "expr": "sum by (host_system) (rate(container_network_transmit_packets_dropped_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval])) !=0",
       "legendFormat": "OUT: {{host_system}} - ALL CONTAINERS"
      },
      {
       "expr": "sum by (host_system,name) (rate(container_network_receive_packets_dropped_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval])) / sum by (host_system,name) (rate(container_network_receive_packets_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval])) !=0",
       "legendFormat": "IN %: {{host_system}} - {{name}}"
      },
      {
       "expr": "sum by (host_system,name) (rate(container_network_transmit_packets_dropped_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval])) / sum by (host_system,name) (rate(container_network_transmit_packets_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval])) !=0",
       "legendFormat": "OUT %: {{host_system}} - {{name}}"
      },
      {
       "expr": "sum by (host_system) (rate(container_network_receive_packets_dropped_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval])) / sum by (host_system) (rate(container_network_receive_packets_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval])) !=0",
       "legendFormat": "IN %: {{host_system}} - ALL CONTAINERS"
      },
      {
       "expr": "sum by (host_system) (rate(container_network_transmit_packets_dropped_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval])) / sum by (host_system) (rate(container_network_transmit_packets_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval])) !=0",
       "legendFormat": "OUT %: {{host_system}} - ALL CONTAINERS"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk - $host_system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 },
   "repeat": "host_system",
   "collapsed": true,
   "panels": [
    {
     "title": "FS Usage Per Container (FILTERED)",
     "type": "timeseries",
     "description": "FS Usage.\n\nNote that the metrics are produced such that some of them have container names, and some don't. The ones without container names appear to cover the reads/writes as applied to the whole device. \n\nWe have created output to show:\n\n• <container_name> = metrics which include a container name are displayed according to dashboard Container filter.\n\nIt was too complex to show additional breakdown of metrics in the same chart - see other panel for charts showing:\n\n• ALL CONTAINERS = summation per device of all metrics with container names specified. \n\n• NO CONTAINERS = summation per device of all metrics without a container name specified. \n\n• ALL DEVICE = summation per device, regardless of whether it has a container name specified or not.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (host_system,name,device) (container_fs_usage_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",device=~\"$fsdevice\"})",
       "legendFormat": "{{host_system}} - {{name}} ({{device}})"
      },
      {
       "expr": "sum by (host_system) (container_fs_usage_bytes{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"})",
       "legendFormat": "{{host_system}} - ALL CONTAINERS"
      }
     ]
    },
    {
     "title": "FS Use Per Device",
     "type": "timeseries",
     "description": "FS Usage\n\nNote that the metrics are produced such that some of them have container names, and some don't. The ones without container names appear to cover the reads/writes as applied to the whole device. \n\nSee other chart for (filtered) view of metrics per specific container. \n\nThis chart shows:\n\n• ALL CONTAINERS = summation per device of all metrics with container names specified. \n\n• NO CONTAINERS = summation per device of all metrics without a container name specified. \n\n• ALL DEVICE = summation per device, regardless of whether it has a container name specified or not.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (host_system,device) (container_fs_usage_bytes{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}) !=0",
       "legendFormat": "ALL CONTAINERS : {{host_system}} - {{device}}"
      },
      {
       "expr": "sum by (host_system,device) (container_fs_usage_bytes{host_system=~\"$host_system\",name=~\"\",device=~\"$fsdevice\"}) !=0",
       "legendFormat": "NO CONTAINERS : {{host_system}} - {{device}}"
      },
      {
       "expr": "sum by (host_system,device) (container_fs_usage_bytes{host_system=~\"$host_system\",device=~\"$fsdevice\"}) !=0",
       "legendFormat": "ALL DEVICE : {{host_system}} - {{device}}"
      }
     ]
    },
    {
     "title": "IOps Per Container (FILTERED)",
     "type": "timeseries",
     "description": "Operations per second.\n\nNote that the metrics are produced such that some of them have container names, and some don't. The ones without container names appear to cover the reads/writes as applied to the whole device. \n\nWe have created output to show:\n\n• <container_name> = metrics which include a container name are displayed according to dashboard Container filter.\n\nIt was too complex to show additional breakdown of IOps metrics in the same chart - see other panel for IOps charts showing:\n\n• ALL CONTAINERS = summation per device of all metrics with container names specified. \n\n• NO CONTAINERS = summation per device of all metrics without a container name specified. \n\n• ALL DEVICE = summation per device, regardless of whether it has a container name specified or not.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (host_system,name,device) (rate(container_fs_reads_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "READ : {{host_system}} - {{name}} ({{ device }})"
      },
      {
       "expr": "sum by (host_system,name,device) (rate(container_fs_writes_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "WRITE : {{host_system}} - {{name}} ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_reads_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "READ : {{host_system}} - ALL CONTAINERS ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_writes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "WRITE : {{host_system}} - ALL CONTAINERS ({{ device }})"
      }
     ]
    },
    {
     "title": "IOps Per Device",
     "type": "timeseries",
     "description": "Operations per second.\n\nNote that the metrics are produced such that some of them have container names, and some don't. The ones without container names appear to cover the reads/writes as applied to the whole device. \n\nSee other chart for (filtered) view of metrics per specific container. \n\nThis chart shows:\n\n• ALL CONTAINERS = summation per device of all metrics with container names specified. \n\n• NO CONTAINERS = summation per device of all metrics without a container name specified. \n\n• ALL DEVICE = summation per device, regardless of whether it has a container name specified or not.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (host_system,device) (rate(container_fs_reads_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "READ : {{host_system}} - ALL CONTAINERS ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_writes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "WRITE : {{host_system}} - ALL CONTAINERS ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_reads_total{host_system=~\"$host_system\",name=~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "READ : {{host_system}} - NO CONTAINERS ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_writes_total{host_system=~\"$host_system\",name=~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "WRITE : {{host_system}} - NO CONTAINERS ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_reads_total{host_system=~\"$host_system\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "READ : {{host_system}} - ALL DEVICE ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_writes_total{host_system=~\"$host_system\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "WRITE : {{host_system}} - ALL DEVICE ({{ device }})"
      }
     ]
    },
    {
     "title": "IO Bytes Per Container (FILTERED)",
     "type": "timeseries",
     "description": "Bytes per second.\n\nNote that the metrics are produced such that some of them have container names, and some don't. The ones without container names appear to cover the reads/writes as applied to the whole device. \n\nWe have created output to show:\n\n• <container_name> = metrics which include a container name are displayed according to dashboard Container filter.\n\nIt was too complex to show additional breakdown of IOps metrics in the same chart - see other panel for IOps charts showing:\n\n• ALL CONTAINERS = summation per device of all metrics with container names specified. \n\n• NO CONTAINERS = summation per device of all metrics without a container name specified. \n\n• ALL DEVICE = summation per device, regardless of whether it has a container name specified or not.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (host_system,name,device) (rate(container_fs_reads_bytes_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "READ : {{host_system}} - {{name}} ({{ device }})"
      },
      {
       "expr": "sum by (host_system,name,device) (rate(container_fs_writes_bytes_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "WRITE : {{host_system}} - {{name}} ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_reads_bytes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "READ : {{host_system}} - ALL CONTAINERS ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_writes_bytes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "WRITE : {{host_system}} - ALL CONTAINERS ({{ device }})"
      }
     ]
    },
    {
     "title": "IO Bytes Per Device",
     "type": "timeseries",
     "description": "Operations per second.\n\nNote that the metrics are produced such that some of them have container names, and some don't. The ones without container names appear to cover the reads/writes as applied to the whole device. \n\nSee other chart for (filtered) view of metrics per specific container. \n\nThis chart shows:\n\n• ALL CONTAINERS = summation per device of all metrics with container names specified. \n\n• NO CONTAINERS = summation per device of all metrics without a container name specified. \n\n• ALL DEVICE = summation per device, regardless of whether it has a container name specified or not.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (host_system,device) (rate(container_fs_reads_bytes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "READ : {{host_system}} - ALL CONTAINERS ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_writes_bytes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "WRITE : {{host_system}} - ALL CONTAINERS ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_reads_bytes_total{host_system=~\"$host_system\",name=~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "READ : {{host_system}} - NO CONTAINERS ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_writes_bytes_total{host_system=~\"$host_system\",name=~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "WRITE : {{host_system}} - NO CONTAINERS ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_reads_bytes_total{host_system=~\"$host_system\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "READ : {{host_system}} - ALL DEVICE ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_writes_bytes_total{host_system=~\"$host_system\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "WRITE : {{host_system}} - ALL DEVICE ({{ device }})"
      }
     ]
    },
    {
     "title": "IO Utilization (FILTERED)",
     "type": "timeseries",
     "description": "This measures the cumulative count of seconds spent doing I/Os. It can be used as a baseline to judge the speed of the processes running on your container and help advise future optimization efforts.‍",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (host_system,name,device) (container_fs_io_time_seconds_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",device=~\"$fsdevice\"})",
       "legendFormat": "{{host_system}} - {{name}} ({{device}})"
      },
      {
       "expr": "sum by (host_system) (container_fs_io_time_seconds_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"})",
       "legendFormat": "{{host_system}} - ALL CONTAINERS"
      }
     ]
    },
    {
     "title": "IO Weighted Utilization (FILTERED)",
     "type": "timeseries",
     "description": "This measures the cumulative WEIGHTED count of seconds spent doing I/Os. It can be used as a baseline to judge the speed of the processes running on your container and help advise future optimization efforts.‍",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (host_system,name,device) (container_fs_io_time_weighted_seconds_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",device=~\"$fsdevice\"})",
       "legendFormat": "{{host_system}} - {{name}} ({{device}})"
      },
      {
       "expr": "sum by (host_system) (container_fs_io_time_weighted_seconds_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"})",
       "legendFormat": "{{host_system}} - ALL CONTAINERS"
      }
     ]
    },
    {
     "title": "Disk Average Wait Time Per Container (FILTERED)",
     "type": "timeseries",
     "description": "Filesystem read/write time divided by number of reads/writes (for that container) to get time taken per read/write. \n\nNote that the metrics are produced such that some of them have container names, and some don't. The ones without container names appear to cover the reads/writes as applied to the whole device. \n\nWe have created output to show:\n\n• <container_name> = metrics which include a container name are displayed according to dashboard Container filter.\n\nIt was too complex to show additional breakdown of IOps metrics in the same chart - see other panel for IOps charts showing:\n\n• ALL CONTAINERS = summation per device of all metrics with container names specified. \n\n• NO CONTAINERS = summation per device of all metrics without a container name specified. \n\n• ALL DEVICE = summation per device, regardless of whether it has a container name specified or not.",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (host_system,name,device) (rate(container_fs_read_seconds_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0 / sum by (host_system,name,device) (rate(container_fs_reads_total[$__rate_interval]))",
       "legendFormat": "READ : {{host_system}} - {{name}} ({{ device }})"
      },
      {
       "expr": "sum by (host_system,name,device) (rate(container_fs_write_seconds_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0 / sum by (host_system,name,device) (rate(container_fs_reads_total[$__rate_interval]))",
       "legendFormat": "WRITE : {{host_system}} - {{name}} ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_read_seconds_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0 / sum by (host_system,device) (rate(container_fs_reads_total[$__rate_interval]))",
       "legendFormat": "READ : {{host_system}} - ALL CONTAINERS ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_write_seconds_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0 / sum by (host_system,device) (rate(container_fs_reads_total[$__rate_interval]))",
       "legendFormat": "WRITE : {{host_system}} - ALL CONTAINERS ({{ device }})"
      }
     ]
    },
    {
     "title": "Disk Average Wait Time Per Device",
     "type": "timeseries",
     "description": "Filesystem read/write time divided by number of reads/writes (for that container) to get time taken per read/write. \n\nNote that the metrics are produced such that some of them have container names, and some don't. The ones without container names appear to cover the reads/writes as applied to the whole device. \n\nSee other chart for (filtered) view of metrics per specific container. \n\nThis chart shows:\n\n• ALL CONTAINERS = summation per device of all metrics with container names specified. \n\n• NO CONTAINERS = summation per device of all metrics without a container name specified. \n\n• ALL DEVICE = summation per device, regardless of whether it has a container name specified or not.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 84 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (host_system,device) (rate(container_fs_read_seconds_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0 / sum by (host_system,device) (rate(container_fs_reads_total[$__rate_interval]))",
       "legendFormat": "READ : {{host_system}} - ALL CONTAINERS ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_write_seconds_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0 / sum by (host_system,device) (rate(container_fs_reads_total[$__rate_interval]))",
       "legendFormat": "WRITE : {{host_system}} - ALL CONTAINERS ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_read_seconds_total{host_system=~\"$host_system\",name=~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0 / sum by (host_system,device) (rate(container_fs_reads_total[$__rate_interval]))",
       "legendFormat": "READ : {{host_system}} - NO CONTAINERS ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_write_seconds_total{host_system=~\"$host_system\",name=~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0 / sum by (host_system,device) (rate(container_fs_reads_total[$__rate_interval]))",
       "legendFormat": "WRITE : {{host_system}} - NO CONTAINERS ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_read_seconds_total{host_system=~\"$host_system\",device=~\"$fsdevice\"}[$__rate_interval])) !=0 / sum by (host_system,device) (rate(container_fs_reads_total[$__rate_interval]))",
       "legendFormat": "READ : {{host_system}} - ALL DEVICE ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_write_seconds_total{host_system=~\"$host_system\",device=~\"$fsdevice\"}[$__rate_interval])) !=0 / sum by (host_system,device) (rate(container_fs_reads_total[$__rate_interval]))",
       "legendFormat": "WRITE : {{host_system}} - ALL DEVICE ({{ device }})"
      }
     ]
    }
   ]
  }
 ]
}