{
 "title": "Crowdsec",
 "description": "Panels from official dashboards merged in one place.",
 "tags": [
  "crowdsec",
  "prometheus",
  "production"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(cs_info,instance)" } },
   {
    "name": "datasource_type",
    "label": "Datasource Type",
    "query": {
     "query": "label_values(cs_parsing_time_seconds_bucket,type)"
    }
   },
   {
    "name": "source",
    "label": "Source",
    "query": {
     "query": "label_values(cs_parsing_time_seconds_bucket{instance=\"$instance\", type=\"$datasource_type\"},source)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-(process_start_time_seconds{instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$instance\"}[$__interval])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Mem Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top scenarios",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_overflowed_total{instance=~\"$instance\"}[$__interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$__interval])*100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Mem Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Max FDs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_max_fds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total raw lines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_filesource_hits_total{instance=~\"$instance\"}[$__interval]) or up * 0) + sum(increase(cs_cloudwatch_stream_hits_total{instance=~\"$instance\"}[$__interval]) or up * 0) + sum(increase(cs_journalctlsource_hits_total{instance=~\"$instance\"}[$__interval]) or up * 0) + sum(increase(cs_syslogsource_hits_total{instance=~\"$instance\"}[$__interval]) or up * 0)"
    }
   ]
  },
  {
   "title": "Total unparsed lines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_parser_hits_ko_total{instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Acquisitions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(cs_filesource_hits_total{instance=\"$instance\"}[$__interval])) by (instance, source)",
     "legendFormat": "{{instance}} - {{source}}"
    },
    {
     "expr": "sum(increase(cs_journalctlsource_hits_total{instance=\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(increase(cs_cloudwatch_stream_hits_total{instance=\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum(increase(cs_syslogsource_hits_total{instance=\"$instance\"}[$__interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Open FDs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total parsed lines",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_parser_hits_ok_total{instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Overflows",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_overflowed_total{instance=~\"$instance\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Parsers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(cs_parser_hits_total{instance=\"$instance\"}[$__interval])) by (instance,source)",
     "legendFormat": "{{instance}} - {{source}}"
    }
   ]
  },
  {
   "title": "Buckets overflow",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(cs_bucket_overflowed_total{instance=~\"$instance\"}[$__interval])) by (instance,name)",
     "legendFormat": "{{instance}} - {{name}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Decisions Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cs_active_decisions{instance=\"$instance\"})"
      }
     ]
    },
    {
     "title": "Decisions By Type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 10, "x": 4, "y": 30 },
     "targets": [
      {
       "expr": "sum(cs_active_decisions{instance=\"$instance\"}) by (action)",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Decisions by scenario",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 10, "x": 14, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(cs_active_decisions{instance=\"$instance\"}) by (reason)",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Alerts Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 35 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(cs_alerts{instance=\"$instance\"})"
      }
     ]
    },
    {
     "title": "Alerts per Scenario",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cs_alerts{instance=\"$instance\"}",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Duration - Decisions GET (live)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cs_lapi_request_duration_seconds_bucket{endpoint= \"/v1/decisions\", instance=\"$instance\", method=~\"(GET)|(HEAD)\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Duration - Decisions GET (stream)",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cs_lapi_request_duration_seconds_bucket{endpoint= \"/v1/decisions/stream\", instance=\"$instance\", method=~\"(GET)|(HEAD)\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Duration - Decisions DELETE",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cs_lapi_request_duration_seconds_bucket{endpoint=~\"/v1/decisions.*\", instance=\"$instance\", method=\"DELETE\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Duration - Alerts POST",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cs_lapi_request_duration_seconds_bucket{endpoint=\"/v1/alerts\",instance=\"$instance\",method=\"POST\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Duration - Alerts GET",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cs_lapi_request_duration_seconds_bucket{endpoint=\"/v1/alerts\",instance=\"$instance\",method=~\"(GET)|(HEAD)\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Parsers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total raw lines",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(cs_filesource_hits_total{instance=~\"$instance\"}[$__interval]) or up * 0) by (source) + sum(increase(cs_cloudwatch_stream_hits_total{instance=~\"$instance\"}[$__interval]) or up * 0) by (source) + sum(increase(cs_journalctlsource_hits_total{instance=~\"$instance\"}[$__interval]) or up * 0) by (source) + sum(increase(cs_syslogsource_hits_total{instance=~\"$instance\"}[$__interval]) or up * 0) by (source)",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Acquisition",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(cs_filesource_hits_total{instance=\"$instance\"}[$__interval])) by (source)",
       "legendFormat": "{{source}}"
      },
      {
       "expr": "sum(increase(cs_journalctlsource_hits_total{instance=\"$instance\"}[$__interval])) by (source)",
       "legendFormat": "{{source}}"
      },
      {
       "expr": "sum(increase(cs_cloudwatch_stream_hits_total{instance=\"$instance\"}[$__interval])) by (group, stream)",
       "legendFormat": "{{group}} - {{stream}}"
      },
      {
       "expr": "sum(increase(cs_syslogsource_hits_total{instance=\"$instance\"}[$__interval])) by (source)"
      }
     ]
    },
    {
     "title": "Parsed lines",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(cs_parser_hits_ok_total{instance=\"$instance\"}[$__interval])) by (source)",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Unparsed lines",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(cs_parser_hits_ko_total{instance=\"$instance\"}[$__interval])) by (source)",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Parsers ok",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(cs_node_hits_ok_total{instance=\"$instance\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Parsers nok",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(cs_node_hits_ko_total{instance=\"$instance\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Parsing time - $source",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cs_parsing_time_seconds_bucket{instance=\"$instance\", type=\"$datasource_type\", source=\"$source\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Duration - Agents Login",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 },
     "repeat": "query0",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cs_lapi_request_duration_seconds_bucket{endpoint=\"/v1/watchers/login\", instance=\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "Duration - Heartbeat",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cs_lapi_request_duration_seconds_bucket{endpoint=\"/v1/watchers/login\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buckets Timeline",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(cs_buckets{instance=~\"$instance\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buckets underflow",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(cs_bucket_underflowed_total{instance=\"$instance\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buckets created",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(cs_bucket_created_total{instance=~\"$instance\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buckets overflow",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(cs_bucket_overflowed_total{instance=~\"$instance\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Bucket pour time - $source",
     "type": "heatmap",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 58 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(cs_bucket_pour_seconds_bucket{instance=\"$instance\", type=\"$datasource_type\", source=\"$source\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}