{
 "title": "Frigate (18226)",
 "tags": [
  "frigate",
  "prometheus",
  "production"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## The values below relate only to what the Frigate docker container can access - refer also to the Node Exporter and Cadvisor dashboards for this system to get full insight into performance."
   }
  },
  {
   "title": "Inference Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frigate_detector_inference_speed_seconds*1000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(frigate_cpu_usage_percent)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(frigate_mem_usage_percent)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Recording Storage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frigate_storage_used_bytes{storage=\"/media/frigate/recordings\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "frigate_storage_free_bytes{storage=\"/media/frigate/recordings\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Inference Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "frigate_detector_inference_speed_seconds",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Storage Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "frigate_storage_total_bytes", "legendFormat": "{{storage}}" }
   ]
  },
  {
   "title": "Detection FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    { "expr": "frigate_detection_fps", "legendFormat": "{{camera_name}}" },
    { "expr": "frigate_detection_total_fps", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Storage Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "frigate_storage_used_bytes", "legendFormat": "{{storage}}" }
   ]
  },
  {
   "title": "Total Detection Frames Processed over 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "tfp" } },
   "targets": [
    {
     "expr": "sum_over_time(frigate_detection_fps[24h])",
     "legendFormat": "{{camera_name}}"
    }
   ]
  },
  {
   "title": "Storage Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "frigate_storage_free_bytes", "legendFormat": "{{storage}}" }
   ]
  },
  {
   "title": "Camera FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    { "expr": "frigate_camera_fps", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "Number Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "count by(process) (frigate_cpu_usage_percent{process!~\"\"})",
     "legendFormat": "CPU - # {{process}} processes"
    },
    {
     "expr": "count by(process) (frigate_mem_usage_percent{process!~\"\"})",
     "legendFormat": "Mem - # {{process}} processes"
    },
    {
     "expr": "count(frigate_cpu_usage_percent{process!~\"\"}) + count(frigate_mem_usage_percent{process!~\"\"})",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Skipped FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    { "expr": "frigate_skipped_fps", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "Process FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    { "expr": "frigate_process_fps", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(frigate_cpu_usage_percent{type!~\"Camera|Detector\"})",
     "legendFormat": "Other Processes"
    },
    {
     "expr": "sum by(name, process) (frigate_cpu_usage_percent{type=~\"Camera|Detector\"})",
     "legendFormat": "{{name}} {{process}} {{pid}}"
    },
    { "expr": "sum(frigate_cpu_usage_percent)", "legendFormat": "TOTAL" }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"frigate-exporter-prometheus\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name, process) (frigate_mem_usage_percent{type=~\"Camera|Detector\"})",
     "legendFormat": "{{name}} {{process}} {{pid}}"
    },
    {
     "expr": "sum(frigate_mem_usage_percent{type!~\"Camera|Detector\"})",
     "legendFormat": "Other Processes"
    },
    { "expr": "sum(frigate_mem_usage_percent)", "legendFormat": "TOTAL" }
   ]
  },
  {
   "title": "GPU utilisation %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "frigate_gpu_usage_percent", "legendFormat": "{{gpu_name}}" }
   ]
  },
  {
   "title": "GPU memory usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "frigate_gpu_mem_usage_percent", "legendFormat": "{{gpu_name}}" }
   ]
  }
 ]
}