{
 "title": "Go Exporter Metrics (14061)",
 "description": "A quickstart to setup the Prometheus Go runtime exporter with preconfigured dashboards, alerting rules, and recording rules.",
 "tags": [
  "go",
  "golang",
  "prometheus",
  "self",
  "production"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": "label_values(go_info, job)" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(go_info{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "Go metric information can be found at: https://pkg.go.dev/runtime#MemStats"
   }
  },
  {
   "title": "Open FDs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{job=~\"$job\", instance=~\"$instance.*\"}",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Open FDs (derivative)",
   "type": "timeseries",
   "description": "Derivative shows rate of change - helpful to highlight movement in metrics which don't appear to change much.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "deriv(process_open_fds{job=~\"$job\", instance=~\"$instance.*\"}[$__rate_interval])",
     "legendFormat": "{{job}}{{job}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance.*\"}",
     "legendFormat": "{{job}} ({{instance}}) : resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=~\"$job\", instance=~\"$instance.*\"}",
     "legendFormat": "{{job}} ({{instance}}) : virtual"
    }
   ]
  },
  {
   "title": "Process Memory (derivative)",
   "type": "timeseries",
   "description": "Derivative shows rate of change - helpful to highlight movement in metrics which don't appear to change much.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : virtual"
    }
   ]
  },
  {
   "title": "Total Reserved Memory",
   "type": "timeseries",
   "description": "Average total bytes of memory reserved across all process instances of a job.\nsys_bytes is the total bytes of memory obtained from the OS. Sys measures the virtual address space reserved by the Go runtime for the heap, stacks, and other internal data structures. It's likely that not all of the virtual address space is backed by physical memory at any given moment, though in general it all was at some point.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(job)(go_memstats_sys_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Stack Memory Use",
   "type": "timeseries",
   "description": "Average stack memory usage across all instances of a job.\nStackSys is bytes of stack memory obtained from the OS. StackSys is StackInuse, plus any memory obtained directly from the OS for OS thread stacks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (job) (go_memstats_stack_inuse_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : stack inuse (avg)"
    },
    {
     "expr": "avg by (job) (go_memstats_stack_sys_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : stack sys (avg)"
    }
   ]
  },
  {
   "title": "Other Memory Reservations (Off Heap)",
   "type": "timeseries",
   "description": "Average memory reservations by the runtime, not for stack or heap, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (job,instance)(go_memstats_mspan_sys_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : mspan"
    },
    {
     "expr": "avg by (job,instance)(go_memstats_mcache_sys_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : mcache"
    },
    {
     "expr": "avg by (job,instance)(go_memstats_buck_hash_sys_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : buck hash"
    },
    {
     "expr": "avg by (job,instance)(go_memstats_gc_sys_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : gc"
    },
    {
     "expr": "avg by (job,instance)(go_memstats_mspan_inuse_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : mspan in use"
    },
    {
     "expr": "avg by (job,instance)(go_memstats_mcache_inuse_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : mcache in use"
    },
    {
     "expr": "avg by (job,instance)(go_memstats_other_sys_bytes{job=~\"$job\", instance=~\"$instance.*\"} - go_memstats_other_sys_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : other sys "
    },
    {
     "expr": "avg by (job,instance)(go_memstats_next_gc_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : next gc in use"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "description": "Average memory reserved, and actually in use, by the heap, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (job,instance)(go_memstats_heap_sys_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : heap reserved (avg)"
    },
    {
     "expr": "avg by (job,instance)(go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : heap in use (avg)"
    },
    {
     "expr": "avg by (job,instance)(go_memstats_heap_alloc_bytes{job=~\"$job\",instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : heap alloc (avg)"
    },
    {
     "expr": "avg by (job,instance)(go_memstats_heap_idle_bytes{job=~\"$job\",instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : heap idle (avg)"
    },
    {
     "expr": "avg by (job,instance)(go_memstats_heap_released_bytes{job=~\"$job\",instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : heap released (avg)"
    }
   ]
  },
  {
   "title": "Allocation Rate, Bytes",
   "type": "timeseries",
   "description": "Average allocation rate in bytes per second, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg by (job,instance)(rate(go_memstats_alloc_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$__rate_interval]))",
     "legendFormat": "{{job}} ({{instance}}) : bytes malloced/s (avg)"
    }
   ]
  },
  {
   "title": "Heap Object Allocation Rate",
   "type": "timeseries",
   "description": "Average rate of heap object allocation, across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total{job=~\"$job\", instance=~\"$instance.*\"}[$__rate_interval])",
     "legendFormat": "{{job}} ({{instance}}): obj mallocs/s (avg)"
    }
   ]
  },
  {
   "title": "Number of Live Objects",
   "type": "timeseries",
   "description": "Average number of live memory objects across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by(job,instance)(go_memstats_mallocs_total{job=~\"$job\", instance=~\"$instance.*\"} - go_memstats_frees_total{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}): object count (avg)"
    }
   ]
  },
  {
   "title": "Goroutines & Go Threads",
   "type": "timeseries",
   "description": "Average number of goroutines across instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (job,instance)(go_goroutines{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : goroutine count (avg)"
    },
    {
     "expr": "avg by (job,instance)(go_threads{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : go threads (avg)"
    }
   ]
  },
  {
   "title": "GC min & max duration",
   "type": "timeseries",
   "description": "Min and max of the pause duration of garbage collection cycles.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (job)(go_gc_duration_seconds{quantile=\"0\", job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : min gc time (avg)"
    },
    {
     "expr": "avg by (job)(go_gc_duration_seconds{quantile=\"1\", job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : max gc time (avg)"
    }
   ]
  },
  {
   "title": "Next GC, Bytes",
   "type": "timeseries",
   "description": "The number used bytes at which the runtime plans to perform the next GC, averaged across all instances of a job.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (job,instance)(go_memstats_next_gc_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : next gc bytes (avg)"
    }
   ]
  },
  {
   "title": "GC duration quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~\"$job\", instance=~\"$instance.*\"}",
     "legendFormat": "{{job}} ({{instance}}) : gc time"
    }
   ]
  },
  {
   "title": "GC Last Collection",
   "type": "table",
   "description": "Min and max of the pause duration of garbage collection cycles.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "now() - go_memstats_last_gc_time_seconds{job=~\"$job\", instance=~\"$instance.*\"}",
     "legendFormat": "{{job}} ({{instance}}) : Last GC Time"
    }
   ]
  },
  {
   "title": "Rate of a Pointer Dereferences",
   "type": "timeseries",
   "description": "go_memstats_lookups_total – counts how many pointer dereferences happened. This is a counter value so you can use rate() to lookups/s.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(go_memstats_lookups_total{job=~\"$job\", instance=~\"$instance.*\"}[1m]) >0",
     "legendFormat": "{{job}} ({{instance}}) : obj dereferences"
    }
   ]
  }
 ]
}