{
 "title": "Healthchecks.io (18998)",
 "tags": [
  "healthchecks.io",
  "prometheus",
  "production"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "name",
    "query": {
     "query": "label_values(hc_check_up{},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Healthchecks",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(hc_checks_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Healthchecks Down",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(hc_checks_down_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Healthcheck Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "hc_check_up{name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Healthchecks Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "$name",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "repeat": "name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hc_check_up{name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Healthchecks Running", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "$name",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 41 },
   "repeat": "name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hc_check_started{name=~\"$name\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}