{
 "title": "Klipper",
 "description": "3D printer monitoring",
 "tags": [
  "klipper",
  "3d-printer",
  "sv06",
  "prometheus",
  "exporter",
  "self",
  "production"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Printer",
    "query": {
     "query": "label_values(up{job=~\"klipper\"},instance)"
    }
   },
   { "name": "node", "label": "NodeExporter Node", "query": "192.168.0.82:9100" }
  ]
 },
 "panels": [
  { "title": "Current Print ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$current_layer * 100 / $total_layers",
     "type": "math"
    }
   ]
  },
  {
   "title": "Print Info",
   "type": "stat",
   "gridPos": { "h": 21, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "klipper_current_print_layer_height{instance=~\"$instance.*\"}",
     "legendFormat": "Layer Height"
    },
    {
     "expr": "klipper_current_print_first_layer_height{instance=~\"$instance.*\"}",
     "legendFormat": "1st Layer Height"
    },
    {
     "expr": "klipper_print_filament_used{instance=~\"$instance.*\"}",
     "legendFormat": "Filament Used"
    },
    {
     "expr": "klipper_toolhead_max_velocity{instance=~\"$instance.*\"}",
     "legendFormat": "Velocity - Max"
    },
    {
     "expr": "klipper_toolhead_square_corner_velocity{instance=~\"$instance.*\"}",
     "legendFormat": "Velocity - Square Corner"
    },
    {
     "expr": "klipper_extruder_pressure_advance{instance=~\"$instance.*\"}",
     "legendFormat": "Pressure Advance"
    },
    {
     "expr": "klipper_gcode_extrude_factor{instance=~\"$instance.*\"}",
     "legendFormat": "Extrusion Factor"
    },
    {
     "expr": "klipper_extruder_smooth_time{instance=~\"$instance.*\"}",
     "legendFormat": "Smooth Time"
    }
   ]
  },
  {
   "title": "Bed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_heater_bed_temperature{instance=~\"$instance.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "klipper_heater_bed_power{instance=~\"$instance.*\"}",
     "legendFormat": "power"
    },
    {
     "expr": "klipper_heater_bed_temperature{instance=~\"$instance.*\"}",
     "legendFormat": "temperature"
    },
    {
     "expr": "klipper_heater_bed_target{instance=~\"$instance.*\"}",
     "legendFormat": "target"
    }
   ]
  },
  {
   "title": "Extruder",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_extruder_temperature{instance=~\"$instance.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extruder",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "klipper_extruder_power{instance=~\"$instance.*\"}",
     "legendFormat": "power"
    },
    {
     "expr": "klipper_extruder_temperature{instance=~\"$instance.*\"}",
     "legendFormat": "temperature"
    },
    {
     "expr": "klipper_extruder_target{instance=~\"$instance.*\"}",
     "legendFormat": "target"
    },
    {
     "expr": "klipper_fan_speed{instance=~\"$instance.*\"}",
     "legendFormat": "fan speed"
    }
   ]
  },
  {
   "title": "Current Print Duration",
   "type": "stat",
   "gridPos": { "h": 13, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_print_total_duration{instance=~\"$instance.*\"}",
     "legendFormat": "Total Print Duration"
    },
    {
     "expr": "klipper_printing_time{instance=~\"$instance.*\"}",
     "legendFormat": "State = Printing"
    },
    {
     "expr": "klipper_print_print_duration{instance=~\"$instance.*\"}",
     "legendFormat": "Actively Printing"
    },
    {
     "expr": "klipper_print_file_progress{instance=~\"$instance.*\"}",
     "legendFormat": "Print File Completion"
    },
    {
     "expr": "klipper_print_gcode_progress{instance=~\"$instance.*\"}",
     "legendFormat": "G73 Progress"
    }
   ]
  },
  {
   "title": "Speed & Acceleration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mm/s" } },
   "targets": [
    {
     "expr": "klipper_gcode_speed{instance=~\"$instance.*\"}/60",
     "legendFormat": "Speed"
    },
    {
     "expr": "klipper_gcode_speed_factor{instance=~\"$instance.*\"}",
     "legendFormat": "Speed Factor"
    },
    {
     "expr": "klipper_toolhead_max_accel{instance=~\"$instance.*\"}",
     "legendFormat": "Acceleration - Max"
    },
    {
     "expr": "rate(klipper_gcode_speed{instance=~\"$instance.*\"}[$__rate_interval])",
     "legendFormat": "Acceleration - Calc"
    }
   ]
  },
  {
   "title": "Layers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 22 },
   "targets": [
    {
     "expression": "($object_height - $first_layer_height) / $layer_height + 1",
     "type": "math"
    },
    {
     "expression": "($position_z - $first_layer_height) / $layer_height + 1",
     "type": "math"
    }
   ]
  },
  {
   "title": "Extruded Length (E position)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "expr": "klipper_gcode_position_e{instance=~\"$instance.*\"}",
     "legendFormat": "Extruded Length (E Position)"
    },
    {
     "expr": "klipper_print_filament_used{instance=~\"$instance.*\"}",
     "legendFormat": "Filament Used"
    }
   ]
  },
  {
   "title": "Extruder Coordinates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "klipper_gcode_position_x{instance=~\"$instance.*\"}",
     "legendFormat": "X"
    },
    {
     "expr": "klipper_gcode_position_y{instance=~\"$instance.*\"}",
     "legendFormat": "Y"
    },
    {
     "expr": "klipper_gcode_position_z{instance=~\"$instance.*\"}",
     "legendFormat": "Z"
    }
   ]
  },
  {
   "title": "Filament Sensor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "targets": [
    {
     "expr": "klipper_filament_sensor_detected{instance=~\"$instance.*\"}",
     "legendFormat": "Filament Detected"
    },
    {
     "expr": "klipper_filament_sensor_enabled{instance=~\"$instance.*\"}",
     "legendFormat": "Sensor Enabled"
    }
   ]
  },
  {
   "title": "24V LED Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "expr": "klipper_output_pin_value{instance=~\"$instance.*\",pin=\"LED_TWENTYFOURV\"}",
     "legendFormat": "24V LED"
    }
   ]
  },
  { "title": "Klipper ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "type": "stat",
   "description": "Has other non-visible stats too which can be enabled in future.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_system_uptime{instance=~\"$instance.*\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Overall Print Stats",
   "type": "stat",
   "gridPos": { "h": 20, "w": 4, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_total_print_time{instance=~\"$instance.*\"}",
     "legendFormat": "Total Print Time"
    },
    {
     "expression": "$total_time_printing/$total_jobs",
     "type": "math"
    },
    {
     "expr": "klipper_longest_job{instance=~\"$instance.*\"}",
     "legendFormat": "Longest Job Duration"
    },
    {
     "expr": "klipper_longest_print{instance=~\"$instance.*\"}",
     "legendFormat": "Longest Job - Print Time"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_system_cpu{instance=~\"$instance.*\"}",
     "legendFormat": "CPU Usage - System"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "klipper_moonraker_cpu_usage{instance=~\"$instance.*\"}",
     "legendFormat": "CPU Usage - Moonraker"
    },
    {
     "expr": "klipper_system_cpu{instance=~\"$instance.*\"}",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "klipper_system_cpu_temp{instance=~\"$instance.*\"}",
     "legendFormat": "CPU Temperature"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_system_cpu_temp{instance=~\"$instance.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "description": "other non-visible metrics too",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_total_jobs{instance=~\"$instance.*\"}",
     "legendFormat": "Total Jobs"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "klipper_system_memory_used{instance=~\"$instance.*\"}",
     "legendFormat": "Memory Used"
    },
    {
     "expr": "klipper_system_memory_available{instance=~\"$instance.*\"}",
     "legendFormat": "Memory Available"
    },
    {
     "expr": "klipper_system_memory_total{instance=~\"$instance.*\"}",
     "legendFormat": "Memory Total"
    },
    { "expression": "1-$mem_available/$mem_total", "type": "math" },
    {
     "expr": "klipper_moonraker_memory_kb{instance=~\"$instance.*\"}",
     "legendFormat": "Memory Used - Moonraker"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "1-$mem_available/$mem_total", "type": "math" }
   ]
  },
  {
   "title": "Overall Print Stats",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "klipper_total_filament_used{instance=~\"$instance.*\"}",
     "legendFormat": "Total Filament Used"
    },
    { "expression": "$total_filament/$total_jobs", "type": "math" }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(klipper_network_rx_drop{instance=~\"$instance.*\"}[$__rate_interval]  !=0)",
     "legendFormat": " {{interface}} klipper_network_rx_drop"
    },
    {
     "expr": "increase(klipper_network_rx_errs{instance=~\"$instance.*\"}[$__rate_interval]  !=0)",
     "legendFormat": " {{interface}} klipper_network_rx_errs"
    },
    {
     "expr": "increase(klipper_network_tx_drop{instance=~\"$instance.*\"}[$__rate_interval]  !=0)",
     "legendFormat": "{{interface}} klipper_network_tx_drop"
    },
    {
     "expr": "increase(klipper_network_tx_errs{instance=~\"$instance.*\"}[$__rate_interval]  !=0)",
     "legendFormat": "{{interface}} klipper_network_tx_errs"
    },
    {
     "expr": "rate(klipper_network_rx_bytes{instance=~\"$instance.*\"}[$__rate_interval])",
     "legendFormat": "{{interface}} klipper_network_rx_bytes"
    },
    {
     "expr": "rate(klipper_network_tx_bytes{instance=~\"$instance.*\"}[$__rate_interval])",
     "legendFormat": "{{interface}} klipper_network_rx_bytes"
    }
   ]
  },
  {
   "title": "Node Exporter System Metrics ($node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$node\"} - node_boot_time_seconds{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\", mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\"}[$__rate_interval])))) * 100"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{instance=\"$node\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{instance=\"$node\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "Used Root FS",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_filesystem_avail_bytes{instance=\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]) * 100) / avg_over_time(node_filesystem_size_bytes{instance=\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Hardware temperature monitor",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 10, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{instance=\"$node\"}",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    }
   ]
  },
  {
   "title": "Host Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (host_system,id,name,pretty_name,version,version_codename,version_id) (node_os_info{instance=\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Load %",
   "type": "timeseries",
   "description": "Load shouldn't exceed number of threads.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(node_load1{instance=\"$node\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"$node\"}[$__rate_interval]))",
     "legendFormat": "Load - 1m"
    },
    {
     "expr": "avg_over_time(node_load5{instance=\"$node\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"$node\"}[$__rate_interval]))",
     "legendFormat": "Load - 5m"
    },
    {
     "expr": "avg_over_time(node_load15{instance=\"$node\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"$node\"}[$__rate_interval]))",
     "legendFormat": "Load - 15m"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"} - node_memory_MemFree_bytes{instance=\"$node\"} - (node_memory_Cached_bytes{instance=\"$node\"} + node_memory_Buffers_bytes{instance=\"$node\"} + node_memory_SReclaimable_bytes{instance=\"$node\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\"} + node_memory_Buffers_bytes{instance=\"$node\"} + node_memory_SReclaimable_bytes{instance=\"$node\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\"} - node_memory_SwapFree_bytes{instance=\"$node\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Disk Space Used (/dev devices) ",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$node\",device=~'/dev/.*'} * 100) / node_filesystem_size_bytes{instance=\"$node\",device=~'/dev/.*'})",
     "legendFormat": "{{device}} : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Basic network info per interface",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"$node\",device!~\"veth.*\"}[$__rate_interval])*8 !=0",
     "legendFormat": "In - {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\",device!~\"veth.*\"}[$__rate_interval])*8 !=0",
     "legendFormat": "Out - {{device}} "
    }
   ]
  }
 ]
}