{
 "title": "Minecraft",
 "tags": [
  "production",
  "prometheus",
  "minecraft",
  "cadvisor",
  "nodeexporter",
  "velocity-exporter",
  "fabric-exporter"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Minecraft Server",
    "query": {
     "query": "query_result(up{job=~\"$job\"})"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "query_result(minecraft_FE_minecraft_tps)"
    }
   },
   { "name": "host_system", "query": "minecraft" },
   { "name": "containers_old", "query": ".*" },
   { "name": "fsdevice", "query": ".*" },
   { "name": "interfaces", "query": ".*" },
   {
    "name": "node",
    "query": {
     "query": "{__name__=\"node_uname_info\",host_system=~\"$host_system\"}"
    }
   },
   {
    "name": "guest_ids",
    "query": {
     "query": "label_values(pve_guest_info{name=~\"$host_system\"},id)"
    }
   },
   { "name": "dimension", "label": "Dimension", "query": "overworld,the_nether,the_end" },
   {
    "name": "containers",
    "label": "Cadvisor Containers",
    "query": "All Containers On Host : .*, Pelican Containers : .*-.*-.*"
   }
  ]
 },
 "panels": [
  {
   "title": "Container Metrics (Cadvisor)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CONTAINER METRICS - Running Containers (cadvisor)",
     "type": "table",
     "description": "Excludes containers which have been stopped by Sablier",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 115 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "now() - max(container_start_time_seconds{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name,container_label_com_docker_compose_project_config_files,container_label_org_label_schema_group,image)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(container_memory_usage_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(container_memory_rss{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(container_memory_working_set_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(container_memory_swap{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(container_memory_migrate{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(container_memory_mapped_file{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(container_memory_cache{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(container_spec_memory_limit_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU - Percent (cadvisor)",
     "type": "timeseries",
     "description": "• container_cpu_usage_seconds_total: Measures the amount of CPU time used by the container - sum of container_cpu_user_seconds_total and container_cpu_system_seconds_total. If the CPU is fully utilized and unable to handle additional requests, it can lead to saturation.\n\n• node_cpu_seconds_total: Node Exporter measure of total seconds CPU has spent in each category - summing all categories to get total CPU seconds.\n\n\n[Node Exporter & Cadvisor]",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum by (host_system,name) (rate(container_cpu_usage_seconds_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}[$__rate_interval])) / scalar(count(node_cpu_seconds_total{host_system=~\"$host_system\",mode=\"user\"})) * 100",
       "legendFormat": "{{host_system}} - {{ name }}"
      },
      {
       "expr": "sum by (host_system) (rate(container_cpu_usage_seconds_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\"}[$__rate_interval])) / scalar(count(node_cpu_seconds_total{host_system=~\"$host_system\",mode=\"user\"})) * 100",
       "legendFormat": "{{host_system}} - ALL CONTAINERS"
      }
     ]
    },
    {
     "title": "CONTAINER METRICS - Network Traffic (cadvisor)",
     "type": "timeseries",
     "description": "Received and transmitted bytes rate - per container.\nMeasure the amount of network traffic transmitted and received by the container, respectively. When the network becomes saturated, the container may experience latency or dropped requests.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (host_system,name) (rate(container_network_receive_bytes_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
       "legendFormat": "IN: {{host_system}} - {{name}}"
      },
      {
       "expr": "sum by (host_system,name) (rate(container_network_transmit_bytes_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
       "legendFormat": "OUT: {{host_system}} - {{name}}"
      },
      {
       "expr": "sum by (host_system) (rate(container_network_receive_bytes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
       "legendFormat": "IN: {{host_system}} - ALL CONTAINERS"
      },
      {
       "expr": "sum by (host_system) (rate(container_network_transmit_bytes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",interface=~\"$interfaces\"}[$__rate_interval]))",
       "legendFormat": "OUT: {{host_system}} - ALL CONTAINERS"
      }
     ]
    },
    {
     "title": "CONTAINER METRICS - Memory - Working Set Percent Of Memory Limit Used (cadvisor)",
     "type": "timeseries",
     "description": "Working Set memory size divided by memory limit - Breaching 100% will likely trigger OOO event (although system may first try to evict memory to remain below limits).\n\nSee 'Memory Metrics Explained' row.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(container_memory_working_set_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name) / sum(container_spec_memory_limit_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name) ",
       "legendFormat": "{{host_system}} - {{ name }}"
      }
     ]
    },
    {
     "title": "CONTAINER METRICS - Memory - Usage (cadvisor)",
     "type": "timeseries",
     "description": "Size of all memory used regardless of when it was accessed (including both anonymous and page cache memory). Includes memory which can be evicted under memory pressure e.g. cached items.\n\nSee 'Memory Metrics Explained' row.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (host_system,name) (container_memory_usage_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"})",
       "legendFormat": "{{host_system}} - {{ name }}"
      },
      {
       "expr": "sum by (host_system) (container_memory_usage_bytes{host_system=~\"$host_system\",name=~\".+\",name!~\"\"})",
       "legendFormat": "{{host_system}} - ALL CONTAINERS"
      }
     ]
    },
    {
     "title": "CONTAINER METRICS - IO Bytes Per Container (cadvisor)",
     "type": "timeseries",
     "description": "Bytes per second.\n\nNote that the metrics are produced such that some of them have container names, and some don't. The ones without container names appear to cover the reads/writes as applied to the whole device. \n\nWe have created output to show:\n\n• <container_name> = metrics which include a container name are displayed according to dashboard Container filter.\n\nIt was too complex to show additional breakdown of IOps metrics in the same chart - see other panel for IOps charts showing:\n\n• ALL CONTAINERS = summation per device of all metrics with container names specified. \n\n• NO CONTAINERS = summation per device of all metrics without a container name specified. \n\n• ALL DEVICE = summation per device, regardless of whether it has a container name specified or not.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (host_system,name,device) (rate(container_fs_reads_bytes_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "READ : {{host_system}} - {{name}} ({{ device }})"
      },
      {
       "expr": "sum by (host_system,name,device) (rate(container_fs_writes_bytes_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "WRITE : {{host_system}} - {{name}} ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_reads_bytes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "READ : {{host_system}} - ALL CONTAINERS ({{ device }})"
      },
      {
       "expr": "sum by (host_system,device) (rate(container_fs_writes_bytes_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\",device=~\"$fsdevice\"}[$__rate_interval])) !=0",
       "legendFormat": "WRITE : {{host_system}} - ALL CONTAINERS ({{ device }})"
      }
     ]
    },
    {
     "title": "CONTAINER METRICS - Swap - Container Swap Usage (cadvisor)",
     "type": "timeseries",
     "description": "Number of bytes of swap usage\n\nSee 'Memory Metrics Explained' row.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 140 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (host_system,name) (container_memory_swap{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"})",
       "legendFormat": "{{host_system}} - {{ name }}"
      },
      {
       "expr": "sum by (host_system) (container_memory_swap{host_system=~\"$host_system\",name=~\".+\",name!~\"\"})",
       "legendFormat": "{{host_system}} - ALL CONTAINERS"
      }
     ]
    }
   ]
  },
  {
   "title": "Host Metrics (Node Exporter / Proxmox / Cadvisor)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Cores (Node Exporter)",
     "type": "stat",
     "description": "Total number of CPU cores",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(count(node_cpu_seconds_total{instance=\"$node\"}) by (cpu))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HOST CPU Use (Node Exporter)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together\n\n[Node Exporter]",
     "gridPos": { "h": 6, "w": 3, "x": 2, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by(host_system) (irate(node_cpu_seconds_total{host_system=~\"$host_system\", mode!=\"idle\"}[$__rate_interval])) / on(host_system) group_left sum by (host_system)((irate(node_cpu_seconds_total{host_system=~\"$host_system\"}[$__rate_interval])))) * 100",
       "legendFormat": "{{host_system}}"
      }
     ]
    },
    {
     "title": "Sys Load (5m avg)",
     "type": "gauge",
     "description": "Busy state of all CPU cores together (5 min average)",
     "gridPos": { "h": 6, "w": 3, "x": 5, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(node_load5{instance=\"$node\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{instance=\"$node\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Container CPU Use (cadvisor & Node Exporter)",
     "type": "gauge",
     "description": "[Node Exporter & Cadvisor]\n",
     "gridPos": { "h": 6, "w": 3, "x": 8, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum by(host_system) (irate(container_cpu_usage_seconds_total{name=~\".+\"}[$__rate_interval])) / on(host_system) group_left sum by (host_system)((irate(node_cpu_seconds_total{host_system=~\"$host_system\"}[$__rate_interval])))) * 100",
       "legendFormat": "{{host_system}}"
      }
     ]
    },
    {
     "title": "RAM Total (Node Exporter)",
     "type": "stat",
     "description": "Total RAM",
     "gridPos": { "h": 3, "w": 2, "x": 11, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "HOST RAM Used (Node Exporter)",
     "type": "gauge",
     "description": "[Node Exporter]\n\nSee 'Memory Metrics Explained' row below.",
     "gridPos": { "h": 6, "w": 3, "x": 13, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{host_system=~\"$host_system\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{host_system=~\"$host_system\"}[$__rate_interval]))",
       "legendFormat": "{{host_system}}"
      }
     ]
    },
    {
     "title": "Container RAM Use (cadvisor & Node Exporter)",
     "type": "gauge",
     "description": "[Node Exporter & Cadvisor]\n\nSee 'Memory Metrics Explained' row below.",
     "gridPos": { "h": 6, "w": 3, "x": 16, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(sum(container_memory_working_set_bytes{host_system=~\"$host_system\",name=~\".+\",name!~\"\"}) by(host_system)) / (sum(node_memory_MemTotal_bytes{host_system=~\"$host_system\"}) by(host_system)) * 100",
       "legendFormat": "{{host_system}}"
      }
     ]
    },
    {
     "title": "SWAP Used",
     "type": "gauge",
     "description": "Used Swap",
     "gridPos": { "h": 6, "w": 3, "x": 19, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((avg_over_time(node_memory_SwapTotal_bytes{instance=\"$node\"}[$__rate_interval]) - avg_over_time(node_memory_SwapFree_bytes{instance=\"$node\"}[$__rate_interval])) / (avg_over_time(node_memory_SwapTotal_bytes{instance=\"$node\"}[$__rate_interval]) )) * 100"
      }
     ]
    },
    {
     "title": "Disk Size (Node Exporter)",
     "type": "stat",
     "description": "Total RootFS",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"}"
      }
     ]
    },
    {
     "title": "SWAP Total (Node Exporter)",
     "type": "stat",
     "description": "Total SWAP",
     "gridPos": { "h": 3, "w": 2, "x": 11, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_memory_SwapTotal_bytes{instance=\"$node\"}"
      }
     ]
    },
    {
     "title": "Disk Used (Node Exporter)",
     "type": "stat",
     "description": "Total RootFS",
     "gridPos": { "h": 3, "w": 2, "x": 22, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{instance=\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"}-node_filesystem_free_bytes{instance=\"$node\",mountpoint=\"/\",fstype!=\"rootfs\"}"
      }
     ]
    },
    {
     "title": "Guest Info (Proxmox)",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 117 },
     "targets": [
      {
       "expr": "sum by(id, name, type, node) (pve_guest_info{id=~\"$guest_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_up{id=~\"$guest_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_cpu_usage_limit{id=~\"$guest_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_cpu_usage_ratio{id=~\"$guest_ids\"} and on (id) pve_up==1)"
      },
      {
       "expr": "sum by (id) (pve_cpu_usage_ratio{id=~\"$guest_ids\"} / pve_cpu_usage_limit and on (id) pve_up==1)"
      },
      {
       "expr": "sum by (id) (pve_memory_size_bytes{id=~\"$guest_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_memory_usage_bytes{template!=\"1\", id=~\"$guest_ids\"} and on (id) pve_up==1)"
      },
      {
       "expr": "sum by (id) (pve_memory_usage_bytes{template!=\"1\", id=~\"$guest_ids\"} / pve_memory_size_bytes and on (id) pve_up==1)"
      },
      {
       "expr": "sum by (id) (pve_disk_size_bytes{ id=~\"$guest_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_disk_usage_bytes{id=~\"$guest_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_disk_usage_bytes{id=~\"$guest_ids\"} / pve_disk_size_bytes )"
      },
      {
       "expr": "sum by (id) (pve_uptime_seconds{id=~\"$guest_ids\"}) !=0",
       "legendFormat": "Uptime"
      },
      {
       "expr": "sum by (id, node, storage) (pve_storage_info{id=~\"$guest_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_storage_shared{id=~\"$guest_ids\"})"
      }
     ]
    },
    {
     "title": "CPU Basic (Node Exporter)",
     "type": "timeseries",
     "description": "Basic CPU info",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\"}[$__rate_interval])))",
       "legendFormat": "Busy"
      },
      {
       "expr": "sum by(instance) (irate(node_cpu_seconds_total{instance=\"$node\", mode=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"$node\"}[$__rate_interval])))",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Guest CPU Use (%) (Proxmox)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "((pve_cpu_usage_ratio{id=~\"$guest_ids\"} / pve_cpu_usage_limit) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} [{{id}}]"
      }
     ]
    },
    {
     "title": "System Load  (Node Exporter)",
     "type": "timeseries",
     "description": "Load shouldn't exceed number of cores.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(node_load1{instance=\"$node\"}[$__rate_interval]) ",
       "legendFormat": "Load - 1m"
      },
      {
       "expr": "avg_over_time(node_load5{instance=\"$node\"}[$__rate_interval]) ",
       "legendFormat": "Load - 5m"
      },
      {
       "expr": "avg_over_time(node_load15{instance=\"$node\"}[$__rate_interval]) ",
       "legendFormat": "Load - 15m"
      }
     ]
    },
    {
     "title": "Guest CPU Load (Proxmox)",
     "type": "timeseries",
     "description": "pve_cpu_usage_ratio is a representation of the CPU load as detected by the Proxmox host. Its value is between 0 and the number of cores assigned to the guest (pve_cpu_usage_limit). \n\npve_cpu_usage_ratio is divided by the number of allocated cores to get CPU usage % (see separate chart). \nThis chart should stay below allocated core count. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "((pve_cpu_usage_ratio{id=~\"$guest_ids\"}) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} [{{id}}]"
      },
      {
       "expr": "max(\r\n    sum by (id,instance) (\r\n    ((pve_cpu_usage_limit{id=~\"$guest_ids\"}) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1\r\n  )\r\n)",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory Basic (Node Exporter)",
     "type": "timeseries",
     "description": "Basic memory usage",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "node_memory_MemTotal_bytes{instance=\"$node\"} - node_memory_MemFree_bytes{instance=\"$node\"} - (node_memory_Cached_bytes{instance=\"$node\"} + node_memory_Buffers_bytes{instance=\"$node\"} + node_memory_SReclaimable_bytes{instance=\"$node\"})",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "node_memory_Cached_bytes{instance=\"$node\"} + node_memory_Buffers_bytes{instance=\"$node\"} + node_memory_SReclaimable_bytes{instance=\"$node\"}",
       "legendFormat": "RAM Cache + Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{instance=\"$node\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\"} - node_memory_SwapFree_bytes{instance=\"$node\"})",
       "legendFormat": "SWAP Used"
      },
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\"} - node_memory_SwapFree_bytes{instance=\"$node\"}) / node_memory_SwapTotal_bytes{instance=\"$node\"}",
       "legendFormat": "SWAP Used %"
      },
      {
       "expr": "sum(1-(avg_over_time(node_memory_MemAvailable_bytes{instance=\"$node\"}[$__rate_interval]) / avg_over_time(node_memory_MemTotal_bytes{instance=\"$node\"}[$__rate_interval])))",
       "legendFormat": "Alert Calc - Avail Used %"
      },
      {
       "expr": "(node_memory_MemTotal_bytes{instance=\"$node\"} - node_memory_MemFree_bytes{instance=\"$node\"} - node_memory_Cached_bytes{instance=\"$node\"} - node_memory_Buffers_bytes{instance=\"$node\"} - node_memory_SReclaimable_bytes{instance=\"$node\"}) / node_memory_MemTotal_bytes{instance=\"$node\"}",
       "legendFormat": "Alert Calc - RAM Used %"
      }
     ]
    },
    {
     "title": "Guest Memory Use (%) (Proxmox)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(pve_memory_usage_bytes{id=~\"$guest_ids\"} / pve_memory_size_bytes * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} [{{id}}]"
      }
     ]
    },
    {
     "title": "Filesystem space available (Node Exporter)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_filesystem_avail_bytes{instance=\"$node\",device!~'rootfs',mountpoint!~\".*sshfs.*|.*nfs.*\"} !=0",
       "legendFormat": "{{device}} : {{mountpoint}}"
      }
     ]
    },
    {
     "title": "Guest Disk Usage (Proxmox)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pve_disk_usage_bytes{id=~\"$guest_ids\"} / pve_disk_size_bytes{id=~\"$guest_ids\"} * on (id, instance) group_left(name, type) pve_guest_info{type=\"lxc\"} !=0",
       "legendFormat": "{{name}} ({{type}})"
      }
     ]
    },
    {
     "title": "Network Traffic Basic (Node Exporter)",
     "type": "timeseries",
     "description": "Basic network info per interface",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_network_receive_bytes_total{instance=\"$node\",device!~\"veth.*\"}[$__rate_interval])*8 !=0",
       "legendFormat": "In - {{device}}"
      },
      {
       "expr": "irate(node_network_transmit_bytes_total{instance=\"$node\",device!~\"veth.*\"}[$__rate_interval])*8 !=0",
       "legendFormat": "Out - {{device}} "
      }
     ]
    },
    {
     "title": "Network Traffic (Proxmox)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 158 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(irate(pve_network_transmit_bytes{id=~\"$guest_ids\"}[$__rate_interval])* on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
       "legendFormat": "SENT -- {{name}} [{{id}}]"
      },
      {
       "expr": "(irate(pve_network_receive_bytes{id=~\"$guest_ids\"}[$__rate_interval]) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
       "legendFormat": "RECV -- {{name}} [{{id}}]"
      }
     ]
    }
   ]
  },
  { "title": "Fabric Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "HOST CPU Use (Node Exporter)",
   "type": "gauge",
   "description": "Busy state of all CPU cores together\n\n[Node Exporter]",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(host_system) (irate(node_cpu_seconds_total{host_system=~\"$host_system\", mode!=\"idle\"}[$__rate_interval])) / on(host_system) group_left sum by (host_system)((irate(node_cpu_seconds_total{host_system=~\"$host_system\"}[$__rate_interval])))) * 100",
     "legendFormat": "{{host_system}}"
    }
   ]
  },
  {
   "title": "CPU - Percent (cadvisor)",
   "type": "timeseries",
   "description": "• container_cpu_usage_seconds_total: Measures the amount of CPU time used by the container - sum of container_cpu_user_seconds_total and container_cpu_system_seconds_total. If the CPU is fully utilized and unable to handle additional requests, it can lead to saturation.\n\n• node_cpu_seconds_total: Node Exporter measure of total seconds CPU has spent in each category - summing all categories to get total CPU seconds.\n\n\n[Node Exporter & Cadvisor]",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (host_system,name) (rate(container_cpu_usage_seconds_total{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}[$__rate_interval])) / scalar(count(node_cpu_seconds_total{host_system=~\"$host_system\",mode=\"user\"})) * 100",
     "legendFormat": "{{host_system}} - {{ name }}"
    },
    {
     "expr": "sum by (host_system) (rate(container_cpu_usage_seconds_total{host_system=~\"$host_system\",name=~\".+\",name!~\"\"}[$__rate_interval])) / scalar(count(node_cpu_seconds_total{host_system=~\"$host_system\",mode=\"user\"})) * 100",
     "legendFormat": "{{host_system}} - ALL CONTAINERS"
    }
   ]
  },
  {
   "title": "CONTAINER METRICS - Memory - Working Set Percent Of Memory Limit Used (cadvisor)",
   "type": "timeseries",
   "description": "Working Set memory size divided by memory limit - Breaching 100% will likely trigger OOO event (although system may first try to evict memory to remain below limits).\n\nSee 'Memory Metrics Explained' row.",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name) / sum(container_spec_memory_limit_bytes{host_system=~\"$host_system\",name=~\"$containers\",name!~\"\"}) by (host_system,name) ",
     "legendFormat": "{{host_system}} - {{ name }}"
    }
   ]
  },
  {
   "title": "HOST RAM Used (Node Exporter)",
   "type": "gauge",
   "description": "[Node Exporter]\n\nSee 'Memory Metrics Explained' row below.",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{host_system=~\"$host_system\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{host_system=~\"$host_system\"}[$__rate_interval]))",
     "legendFormat": "{{host_system}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(minecraft_FE_process_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) by (instance) / sum(irate(node_cpu_seconds_total{host_system=~\"$host_system\"}[$__rate_interval])) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(minecraft_FE_process_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "stat",
   "description": "Using JVM metrics so not completely accurate but should be close.\nIn particular, 'minecraft_FE_jvm_memory_bytes_max' doesn't always report correct memory limit.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (instance) (minecraft_FE_jvm_memory_bytes_used{instance=~\"$instance\",job=~\"$job\"}) + sum by (instance) (minecraft_FE_jvm_buffer_pool_used_bytes{instance=~\"$instance\",job=~\"$job\"})) / sum by (instance) (minecraft_FE_jvm_memory_bytes_max{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Online Players",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_players_online{instance=~\"$instance\",job=~\"$job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current TPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_FE_minecraft_tps{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current MSPT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_FE_minecraft_mspt{type=\"mean\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Loaded Entities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-max by (instance) (minecraft_FE_process_start_time_seconds{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server Info ",
   "type": "table",
   "description": "Note that this will only show servers which have been active in period - if the server has not woken up then it will not be shown.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (instance) (minecraft_FE_minecraft_players_online{instance=~\".*\",job=~\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (instance) (time()-minecraft_FE_process_start_time_seconds{instance=~\".*\",job=~\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (minecraft_FE_minecraft_tps{instance=~\".*\",job=~\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (minecraft_FE_minecraft_mspt{type=\"mean\",instance=~\".*\",job=~\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (minecraft_FE_minecraft_entities{instance=~\".*\",job=~\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (minecraft_FE_minecraft_loaded_chunks{instance=~\".*\",job=~\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (irate(minecraft_FE_process_cpu_seconds_total{instance=~\".*\",job=~\"$job\"}[$__rate_interval])) / sum(irate(node_cpu_seconds_total{host_system=\"minecraft\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (minecraft_FE_jvm_memory_bytes_used{instance=~\".*\",job=~\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (minecraft_FE_jvm_memory_bytes_max{instance=~\".*\",job=~\"$job\"} - minecraft_FE_jvm_memory_bytes_used{instance=~\".*\",job=~\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "irate( sum by(instance) (minecraft_FE_process_cpu_seconds_total{instance=~\"$instance\", job=~\"$job\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load (Cores Used)",
   "type": "timeseries",
   "description": "This chart shows the number of CPU cores used by the process.\n• 'minecraft_FE_process_cpu_seconds_total' is a  cumulative counter of total CPU seconds consumed by the process. \n• The query gets the average CPU seconds consumed per second in the last X minutes - translates directly to CPU cores used - this value tells how many CPU cores are being utilized on average by the process over that interval. e.g. 0.5 means half a CPU core used.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "irate(minecraft_FE_process_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "description": "Uses Node Exporter's CPU total metric for the minecraft host system to calc % used per minecraft server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(minecraft_FE_process_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) / sum(irate(node_cpu_seconds_total{host_system=~\"$host_system\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ticks Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_FE_minecraft_tps{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MSPT",
   "type": "timeseries",
   "description": "Exclude values > 100 from max since MSPT gets very big when server is auto-paused",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_FE_minecraft_mspt{instance=~\"$instance\",job=~\"$job\",type=\"mean\"} !=0",
     "legendFormat": "Mean - {{instance}}"
    },
    {
     "expr": "minecraft_FE_minecraft_mspt{instance=~\"$instance\",job=~\"$job\",type=\"max\"} < 100",
     "legendFormat": "Max - {{instance}}"
    }
   ]
  },
  {
   "title": "Players online",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_players_online{instance=~\"$instance\",job=~\"$job\",world=~\"$dimension\"}) by (instance,world) !=0",
     "legendFormat": "{{instance}}-{{world}}"
    }
   ]
  },
  {
   "title": "Player flow",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(minecraft_FE_minecraft_players_online{instance=~\"$instance\",job=~\"$job\"} - minecraft_FE_minecraft_players_online{instance=~\"$instance\",job=~\"$job\"} offset 15s) by (instance,world))",
     "legendFormat": "{{instance}} - {{world}}"
    }
   ]
  },
  {
   "title": "Entities by world & dimension",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_entities{instance=~\"$instance\",job=~\"$job\",world=~\"$dimension\"}) by (instance,world) !=0",
     "legendFormat": "{{instance}}-{{world}}"
    }
   ]
  },
  {
   "title": "Loaded Chunks & New Chunks Generated",
   "type": "timeseries",
   "description": "Number of loaded chunks is on left-hand axis\n\nNumber of new chunks generated by the game is on the right-hand axis - new chunks are generated by the game if new parts of the world are visited.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_loaded_chunks{instance=~\"$instance\",job=~\"$job\"}) by (instance,world) !=0",
     "legendFormat": "Loaded: {{instance}} - {{world}}"
    },
    {
     "expr": "irate(minecraft_FE_minecraft_total_loaded_chunks{instance=~\"$instance\",job=~\"$job\"}[1m]) !=0",
     "legendFormat": "Generated: {{instance}} - {{world}}"
    }
   ]
  },
  {
   "title": "Top entities by type (Server: $instance | Dimension: $dimension)",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_entities{instance=~\"$instance\",job=~\"$job\",world=~\"$dimension\"})",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "sort_desc(sum(minecraft_FE_minecraft_entities{instance=~\"$instance\",job=~\"$job\",world=~\"$dimension\"} !=0) by (type))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(minecraft_FE_minecraft_entities{instance=~\"$instance\",job=~\"$job\",world=~\"$dimension\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "JVM Memory Pool Usage",
   "type": "timeseries",
   "description": "This is the closest metric we can get for RAM usage for each minecraft server. See Cadvisor metrics for more holistic memory stats.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (minecraft_FE_jvm_memory_bytes_used{instance=~\"$instance\",job=~\"$job\"}) + sum by (instance) (minecraft_FE_jvm_buffer_pool_used_bytes{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "{{instance}} - Used"
    },
    {
     "expr": "sum by (instance) (minecraft_FE_jvm_memory_bytes_max{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "{{instance}} - Limit"
    }
   ]
  },
  {
   "title": "JVM Memory Information",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "options": {
    "content": "# RAM Calculation\nFor calculating the JVM's actual RAM usage using Prometheus metrics, you should aggregate both heap and non-heap memory areas, summing across all memory pools and buffer pools if possible.\n\nPrometheus and JVM tracking may not see all native or OS overhead memory utilized by the JVM process (thread stacks, internal C/C++ structures, loaded libraries), so your total may underestimate true process RSS shown by ps or container stats\n\n### Why Not 1 simple metric?\n- `jvm_memory_bytes_used` is convenient for general JVM RAM tracking, as it splits JVM usage into two primary areas: heap and non-heap.\n- `jvm_memory_pool_bytes_used` is best for detailed, pool-by-pool breakdown, but if you sum all pools you effectively reproduce the total.\n- `jvm_buffer_pool_used_bytes` is essential for completeness if your app uses many direct/mapped buffers.\n\n\n### Recommended Approach For RAM Calculation\n\n- Start with `jvm_memory_bytes_used{area=\"heap\"}` and `jvm_memory_bytes_used{area=\"nonheap\"}`:\n  - These track used bytes for the full heap and non-heap segments, respectively.\n  - Summing both will cover the majority of the JVM’s managed memory footprints in RAM.\n\n- Optionally, sum all `jvm_memory_pool_bytes_used` values:\n  - This captures usage per memory pool (Eden Space, Survivor Space, Tenured Gen, Metaspace, Code Cache, etc.).\n  - The sum of all pools should closely match the total from `jvm_memory_bytes_used` for heap and non-heap, but may offer finer granularity if you want detailed per-pool visibility.\n\n- Include `jvm_buffer_pool_used_bytes` too:\n  - Direct ByteBuffers (native buffers) are significant for high-throughput applications (I/O, networking, large data processing).\n  - These are not included in heap/non-heap, yet they are mapped in process RAM.\n\n---\n\n# Memory Metrics\n\n### Metric Summary\n\n- `jvm_memory_bytes_used` provides a single aggregate JVM memory usage value.\n- `jvm_memory_pool_bytes_used` and `jvm_memory_pool_collection_used_bytes` offer per-pool statistics, with the latter showing the value right after GC.\n- `jvm_buffer_pool_used_bytes` specializes in buffer pool monitoring.\n\n### Metric Details\n\n- `jvm_memory_bytes_used`\n  - Description: Total bytes of JVM memory currently in use, aggregated across all JVM memory areas (heap, non-heap).\n  - Purpose: Provides a high-level view of overall memory actively used by the JVM at the time of measurement, including both heap and non-heap pools.\n\n</br>\n\n- `jvm_buffer_pool_used_bytes`\n  - Description: Bytes currently used by JVM buffer pools (such as direct and mapped byte buffers).\n  - Purpose: Specializes in tracking usage within the internal buffer pools, frequently for IO (NIO) operations.\n\n</br>\n\n- `jvm_memory_pool_collection_used_bytes`\n  - Description: Amount of memory in a pool immediately after the last garbage collection (GC).\n  - Purpose: Useful for monitoring the effectiveness of GC by showing how much memory remains used right after a collection cycle, for each memory pool (such as Eden, Survivor, Old Gen, Metaspace).\n\n</br>\n\n- `jvm_memory_pool_bytes_used`\n  - Description: Current bytes in use per individual memory pool (e.g., Eden, Old Gen, Metaspace, Code Cache).\n  - Purpose: Allows granular analysis of memory consumed in each specific memory pool, supporting deeper diagnostics.\n\n---\n\n# Cadvisor Host Metrics\n\n`container_memory_usage_bytes`\n* Size of all memory used regardless of when it was accessed (including both anonymous and page cache memory). Includes memory which can be evicted under memory pressure e.g. cached items.\n* Doesn’t show ‘exact’ value of memory (and swap) usage, it’s a fuzz value for efficient access. If you want to know more exact memory usage, you should use RSS+CACHE(+SWAP) value in memory.stat \n* (The value inside the memory.usage_in_bytes file)\n\n</br>\n\n`container_memory_working_set_bytes`\n* A heuristic for the minimum size of memory required for the app to work. It is an estimate of how much memory cannot be evicted. Equals container_memory_usage_bytes minus inactive memory (inactive_file: number of bytes of file-backed memory on inactive LRU list). \n* This metric is used to trigger Out Of Memory (OOM) actions if limits reached.\n* (Deduct inactive_file inside the memory.stat file from the  value inside the memory.usage_in_bytes file. If result is negative then use 0)"
   }
  },
  {
   "title": "JVM GC Duration",
   "type": "timeseries",
   "description": "Time spent in a given JVM garbage collector in seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate({__name__=~\"minecraft_FE_jvm_gc_collection_seconds_sum\",instance=~\"$instance\",job=~\"$job\"}[10m]) !=0",
     "legendFormat": "{{instance}}-{{gc}}"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "targets": [
    {
     "expr": "{__name__=~\"minecraft_FE_jvm_threads_(current|daemon|peak|deadlocked|deadlocked_monitor)\",instance=~\"$instance\",job=~\"$job\"} !=0",
     "legendFormat": "{{__name__}}-{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Threads State",
   "type": "timeseries",
   "description": "Current count of threads by state",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_jvm_threads_state{instance=~\"$instance\",job=~\"$job\"}) by (instance,state) !=0",
     "legendFormat": "{{instance}}-{{state}}"
    }
   ]
  },
  {
   "title": "Velocity Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "collapsed": true,
   "panels": [
    {
     "title": "Servers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "velocity_managed_servers", "legendFormat": "{{proxy_name}}" }
     ]
    },
    {
     "title": "Online Player List",
     "type": "table",
     "gridPos": { "h": 7, "w": 4, "x": 2, "y": 1 },
     "targets": [
      { "expr": "velocity_online_player > 0", "legendFormat": "{{label_name}}" }
     ]
    },
    {
     "title": "Player Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg by (name) (velocity_online_player_latency) !=0",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Ping Frequency",
     "type": "histogram",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "clamp_max(avg(velocity_online_player_latency > 0),1000)",
       "legendFormat": "average player ping"
      }
     ]
    },
    {
     "title": "Player Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(velocity_online_player)", "legendFormat": "Online Player" }
     ]
    },
    {
     "title": "Online Players",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (server) (velocity_online_player)",
       "legendFormat": "{{server}}"
      }
     ]
    },
    {
     "title": "Events per Minute",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(velocity_player_chats_total[1m]) !=0",
       "legendFormat": "chats"
      },
      {
       "expr": "increase(velocity_server_list_pings_total[1m]) !=0",
       "legendFormat": "server list pings"
      },
      {
       "expr": "increase(velocity_player_connects_total[1m]) !=0",
       "legendFormat": "connects"
      },
      {
       "expr": "increase(velocity_player_kicks_total[1m]) !=0",
       "legendFormat": "kicks"
      },
      {
       "expr": "increase(velocity_player_disconnects_total[1m]) !=0",
       "legendFormat": "disconnects"
      }
     ]
    },
    {
     "title": "JVM Memory Used By Velocity Proxy",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (type) (velocity_jvm_memory{type='used'})",
       "legendFormat": "{{server_name}} used"
      },
      {
       "expr": "sum by (type) (velocity_jvm_memory{type='free'})",
       "legendFormat": "{{server_name}} free"
      }
     ]
    },
    {
     "title": "JVM Threads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(velocity_jvm_threads_current) !=0",
       "legendFormat": "TOTAL"
      },
      {
       "expr": "sum by (state) (velocity_jvm_threads_state) !=0",
       "legendFormat": "{{state}}"
      }
     ]
    }
   ]
  }
 ]
}