{
 "title": "Ohm Windows Desktop (11587)",
 "tags": [
  "ohmgraphite",
  "windows",
  "prometheus",
  "production"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "system",
    "label": "System",
    "query": {
     "query": "label_values(up{job=\"ohmgraphite\"},host_system)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{job=\"ohmgraphite\", host_system=\"$system\"},instance)"
    }
   },
   {
    "name": "network",
    "query": {
     "query": "{__name__=~\"ohm_nic_.*\",instance=\"$instance\"}"
    }
   },
   {
    "name": "cpu",
    "query": {
     "query": "{__name__=~\"ohm_cpu_.*\",instance=\"$instance\"}"
    }
   },
   {
    "name": "gpu",
    "query": {
     "query": "{__name__=~\"ohm_gpu.*\",instance=\"$instance\"}"
    }
   },
   {
    "name": "hdd",
    "query": {
     "query": "{__name__=~\"ohm_hdd_.*\",instance=\"$instance\"}"
    }
   },
   {
    "name": "hdd_old",
    "query": {
     "query": "{__name__=~\"ohm_hdd_.*\",instance=\"$instance\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview - All Systems", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance,hardware) (ohm_cpu_load_percent{sensor=\"CPU Total\"}) * on(instance) group_left(instance,host_system) up{job=\"ohmgraphite\"}",
     "legendFormat": "{{host_system}} [{{hardware}}]"
    }
   ]
  },
  {
   "title": "GPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance,hardware) (ohm_gpunvidia_load_percent{sensor=\"GPU Core\"}) * on(instance) group_left(instance,host_system) up{job=\"ohmgraphite\"}",
     "legendFormat": "{{host_system}} [{{hardware}}]"
    },
    {
     "expr": "sum by (instance,hardware) (ohm_gpuati_load_percent{sensor=\"GPU Core\"}) * on(instance) group_left(instance,host_system) up{job=\"ohmgraphite\"}",
     "legendFormat": "{{host_system}} [{{hardware}}]"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "( sum by (host_system) (ohm_ram_bytes{sensor=\"Memory Used\"}) ) / \r\n( sum by (host_system) (ohm_ram_bytes{sensor=\"Memory Available\"}) + sum by (host_system) (ohm_ram_bytes{sensor=\"Memory Used\"}) )",
     "legendFormat": "{{host_system}}"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance,sensor,hardware) (ohm_gpunvidia_bytes) * on(instance) group_left(instance,host_system) up{job=\"ohmgraphite\"}",
     "legendFormat": "{{host_system}} [{{hardware}}] - {{sensor}}"
    },
    {
     "expr": "sum by (instance,sensor,hardware) (ohm_gpuati_bytes) * on(instance) group_left(instance,host_system) up{job=\"ohmgraphite\"}",
     "legendFormat": "{{host_system}} [{{hardware}}] - {{sensor}}"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (hw_instance,hardware,host_system) (ohm_nic_bytes_per_second{sensor=\"Download Speed\"}) !=0",
     "legendFormat": "DOWN : {{host_system}} -- {{hardware}}"
    },
    {
     "expr": "sum by (hw_instance,hardware,host_system) (ohm_nic_bytes_per_second{sensor=\"Upload Speed\"}) !=0",
     "legendFormat": "UP : {{host_system}} -- {{hardware}}"
    }
   ]
  },
  {
   "title": "Drives",
   "type": "table",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "max by (instance,hardware,hw_instance,host_system) (ohm_hdd_celsius)"
    },
    {
     "expr": "sum by (instance,hardware,hw_instance,host_system) (ohm_hdd_bytes{sensor=\"Data Read\"})"
    },
    {
     "expr": "sum by (instance,hardware,hw_instance,host_system) (ohm_hdd_bytes{sensor=\"Data Written\"})"
    },
    {
     "expr": "sum by (instance,hardware,hw_instance,host_system) (increase(ohm_hdd_bytes{sensor=\"Data Read\"}[$__range]))"
    },
    {
     "expr": "sum by (instance,hardware,hw_instance,host_system) (increase(ohm_hdd_bytes{sensor=\"Data Written\"}[$__range]))"
    },
    {
     "expr": "sum by (instance,hardware,hw_instance,host_system) (ohm_hdd_load_percent{sensor=\"Used Space\"})"
    },
    {
     "expr": "sum by (instance,hardware,hw_instance,host_system) (ohm_hdd_factor{sensor=\"Power Cycles\"})"
    },
    {
     "expr": "sum by (instance,hardware,hw_instance,host_system) (ohm_hdd_factor{sensor=\"Media Errors\"})"
    },
    {
     "expr": "sum by (instance,hardware,hw_instance,host_system) (ohm_hdd_factor{sensor=\"Error Info Log Entries\"})"
    },
    {
     "expr": "sum by (instance,hardware,hw_instance,host_system) (ohm_hdd_factor{sensor=\"Unsafe Shutdowns\"})"
    },
    {
     "expr": "sum by (instance,hardware,hw_instance,host_system) (ohm_hdd_level_percent{sensor=\"Available Spare\"})"
    },
    {
     "expr": "sum by (instance,hardware,hw_instance,host_system) (ohm_hdd_level_percent{sensor=\"Available Spare Threshold\"})"
    },
    {
     "expr": "sum by (instance,hardware,hw_instance,host_system) (ohm_hdd_level_percent{sensor=\"Percentage Used\"})"
    }
   ]
  },
  {
   "title": "Network Usage",
   "type": "table",
   "gridPos": { "h": 15, "w": 7, "x": 17, "y": 23 },
   "targets": [
    {
     "expr": "sum by (instance,hw_instance,hardware,host_system) (increase(ohm_nic_bytes{sensor=\"Data Downloaded\"}[$__range]))"
    },
    {
     "expr": "sum by (instance,hw_instance) (increase(ohm_nic_bytes{sensor=\"Data Uploaded\"}[$__range]))"
    },
    {
     "expr": "sum by (instance,hw_instance) (ohm_nic_bytes{sensor=\"Data Downloaded\"})"
    },
    {
     "expr": "sum by (instance,hw_instance) (ohm_nic_bytes{sensor=\"Data Uploaded\"})"
    },
    {
     "expr": "max by (instance,hw_instance) (ohm_nic_load_percent)"
    }
   ]
  },
  {
   "title": "Disk Activity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (host_system,hardware) (ohm_hdd_bytes_per_second{sensor=\"Read Rate\"})",
     "legendFormat": "READ -- [{{host_system}}] {{hardware}}"
    },
    {
     "expr": "sum by (host_system,hardware) (ohm_hdd_bytes_per_second{sensor=\"Write Rate\"})",
     "legendFormat": "WRITE -- [{{host_system}}] {{hardware}}"
    }
   ]
  },
  {
   "title": "Component Power Draw",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "max by(host_system) (ohm_cpu_watts{sensor=~\".*Package\"}) + max by(host_system) (ohm_gpuati_watts{sensor=~\".*Package\"}) + max by(host_system) (ohm_gpunvidia_watts{sensor=~\".*Package\"})",
     "legendFormat": "{{host_system}} - TOTAL"
    },
    {
     "expr": "sum by (host_system) (ohm_cpu_watts{sensor=~\".*Package\"}) ",
     "legendFormat": "{{host_system}} - cpu"
    },
    {
     "expr": "sum by (host_system) (ohm_gpunvidia_watts{sensor=\"GPU Package\"})",
     "legendFormat": "{{host_system}} - gpu nvidia"
    },
    {
     "expr": "sum by (host_system) (ohm_gpuati_watts{sensor=\"GPU Package\"})",
     "legendFormat": "{{host_system}} - gpu amd"
    }
   ]
  },
  {
   "title": "Overview for $system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ohm_cpu_load_percent{instance=\"$instance\",sensor=\"CPU Total\"}"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 2, "x": 2, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ohm_ram_load_percent{instance=\"$instance\",sensor=\"Memory\"}"
      }
     ]
    },
    {
     "title": "Max Disk Usage",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 2, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(ohm_hdd_load_percent{instance=\"$instance\",sensor=\"Total Activity\"})"
      }
     ]
    },
    {
     "title": "Max Disk Space",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 2, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(ohm_hdd_load_percent{instance=\"$instance\",sensor=\"Used Space\"})"
      }
     ]
    },
    {
     "title": "Disk Reads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ohm_hdd_bytes{instance=\"$instance\", sensor=\"Data Read\"}[$__range]))",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Disk Writes",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ohm_hdd_bytes{instance=\"$instance\", sensor=\"Data Written\"}[$__range]))",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Network Rate",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ohm_nic_bytes_per_second{instance=\"$instance\"})",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "table",
     "gridPos": { "h": 14, "w": 7, "x": 17, "y": 2 },
     "targets": [
      {
       "expr": "label_replace(label_replace(label_join({instance=\"$instance\",__name__=~\"ohm_.*_celsius\"}, \"Hardware\", \" \", \"hardware\", \"sensor\"), \"__SensorGroup\", \"$1$2\", \"sensor\", \"(.*)#[0-9]*(.*)\"), \"__SensorID\", \"$2\", \"sensor\", \"(.*#)([0-9]*)(.*)\")"
      }
     ]
    },
    {
     "title": "Downloads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ohm_nic_bytes{instance=\"$instance\",sensor=\"Data Downloaded\"}[$__range]))",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Uploads",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(ohm_nic_bytes{instance=\"$instance\",sensor=\"Data Uploaded\"}[$__range]))",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Disk Rate",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 14, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ohm_hdd_bytes_per_second{instance=\"$instance\"})",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "GPU Compute",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 2, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ohm_gpunvidia_load_percent{instance=\"$instance\",sensor=\"GPU Core\"}"
      }
     ]
    },
    {
     "title": "GPU Memory",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 2, "x": 2, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ohm_gpunvidia_bytes{instance=\"$instance\",sensor=\"GPU Memory Used\"} * 100 / ignoring(sensor) ohm_gpunvidia_bytes{instance=\"$instance\",sensor=\"GPU Memory Total\"}"
      }
     ]
    },
    {
     "title": "Network Usage",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 2, "x": 4, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(ohm_nic_load_percent{instance=\"$instance\"})"
      }
     ]
    },
    {
     "title": "Max Fan",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 2, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max({__name__=~\"ohm_.*_control_percent\",instance=\"$instance\"})"
      }
     ]
    },
    {
     "title": "Component Power Draw",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "ohm_cpu_watts{instance=\"$instance\", sensor=~\".*Package\"} + ignoring(hardware,hw_instance,sensor) ohm_gpunvidia_watts{instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Media Errors",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 14, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ohm_hdd_factor{instance=\"$instance\",sensor=\"Media Errors\"})",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU & RAM: $cpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "cpu",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Load",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(label_replace(ohm_cpu_load_percent{instance=\"$instance\", sensor!=\"CPU Total\"}, \"_sensor\", \"${1}0$2$3\", \"sensor\", \"(.*?)(\\\\d{1})([^\\\\d]+\\\\d|\\\\d{0}|[^\\\\d]+)\"), \"_sensor\", \"${1}$2$3\", \"sensor\", \"(.*?)(\\\\d{2})([^\\\\d]+\\\\d|\\\\d{0}|[^\\\\d]+)\"), \"_sensor\", \"${1}\", \"sensor\", \"([^\\\\d]*?)\")",
       "legendFormat": "{{_sensor}}"
      }
     ]
    },
    {
     "title": "RAM Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "( sum (ohm_ram_bytes{instance=~\"$instance\",sensor=\"Memory Used\"}) ) / \r\n( sum (ohm_ram_bytes{instance=~\"$instance\",sensor=\"Memory Available\"}) + sum  (ohm_ram_bytes{instance=~\"$instance\",sensor=\"Memory Used\"}) )",
       "legendFormat": "RAM"
      }
     ]
    },
    {
     "title": "CPU Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "repeat": "hardtemp",
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(label_replace(ohm_cpu_celsius{instance=\"$instance\"}, \"_sensor\", \"$3 ${1}0$2\", \"sensor\", \"(.*?)(\\\\d{1})([^\\\\d]+\\\\d|\\\\d{0}|[^\\\\d]+)\"), \"_sensor\", \"$3 ${1}$2\", \"sensor\", \"(.*?)(\\\\d{2})([^\\\\d]+\\\\d|\\\\d{0}|[^\\\\d]+)\"), \"_sensor\", \"${1}\", \"sensor\", \"([^\\\\d]*?)\")",
       "legendFormat": "{{_sensor}}"
      }
     ]
    },
    {
     "title": "CPU Wattage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "repeat": "power",
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "ohm_cpu_watts{instance=\"$instance\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "CPU Frequencies",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "repeat": "cpu",
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(label_replace(ohm_cpu_hertz{instance=\"$instance\"}, \"_sensor\", \"$3 ${1}0$2\", \"sensor\", \"(.*?)(\\\\d{1})([^\\\\d]+\\\\d|\\\\d{0}|[^\\\\d]+)\"), \"_sensor\", \"$3 ${1}$2\", \"sensor\", \"(.*?)(\\\\d{2})([^\\\\d]+\\\\d|\\\\d{0}|[^\\\\d]+)\"), \"_sensor\", \"${1}\", \"sensor\", \"([^\\\\d]*?)\")",
       "legendFormat": "{{_sensor}}"
      }
     ]
    },
    {
     "title": "CPU Volts",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "repeat": "volts",
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "label_replace(label_replace(label_replace(ohm_cpu_volts{instance=\"$instance\"}, \"_sensor\", \"$3 ${1}0$2\", \"sensor\", \"(.*?)(\\\\d{1})([^\\\\d]+\\\\d|\\\\d{0}|[^\\\\d]+)\"), \"_sensor\", \"$3 ${1}$2\", \"sensor\", \"(.*?)(\\\\d{2})([^\\\\d]+\\\\d|\\\\d{0}|[^\\\\d]+)\"), \"_sensor\", \"${1}\", \"sensor\", \"([^\\\\d]*?)\")",
       "legendFormat": "{{_sensor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU: $gpu",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "repeat": "gpu",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "GPU Load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ohm_gpunvidia_load_percent{instance=\"$instance\",hardware=~\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpuati_load_percent{instance=\"$instance\",hardware=~\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Wattage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
     "repeat": "power",
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "ohm_gpunvidia_watts{instance=\"$instance\",hardware=~\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpuati_watts{instance=\"$instance\",hardware=~\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 112 },
     "repeat": "hardtemp",
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "ohm_gpunvidia_celsius{instance=\"$instance\",hardware=~\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpuati_celsius{instance=\"$instance\",hardware=~\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Data Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "ohm_gpunvidia_bytes_per_second{instance=\"$instance\",hardware=~\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpuati_bytes_per_second{instance=\"$instance\",hardware=~\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "ohm_gpunvidia_bytes{instance=\"$instance\",hardware=~\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpuati_bytes{instance=\"$instance\",hardware=~\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Fan",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 121 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "expr": "ohm_gpunvidia_revolutions_per_minute{instance=\"$instance\",hardware=~\"$gpu\"}",
       "legendFormat": "Fan"
      },
      {
       "expr": "max(ohm_gpunvidia_revolutions_per_minute{instance=\"$instance\",hardware=~\"$gpu\"}) / ignoring(sensor) max(ohm_gpunvidia_control_percent{instance=\"$instance\",hardware=~\"$gpu\"}) * 90",
       "legendFormat": "High RPM (90%) - Nvidea"
      },
      {
       "expr": "ohm_gpuati_revolutions_per_minute{instance=\"$instance\",hardware=~\"$gpu\"}",
       "legendFormat": "Fan"
      },
      {
       "expr": "max(ohm_gpuati_revolutions_per_minute{instance=\"$instance\",hardware=~\"$gpu\"}) / ignoring(sensor) max(ohm_gpuati_control_percent{instance=\"$instance\",hardware=~\"$gpu\"}) * 90",
       "legendFormat": "High RPM (90%) - AMD"
      }
     ]
    },
    {
     "title": "Frequencies",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "hertz" } },
     "targets": [
      {
       "expr": "ohm_gpunvidia_hertz{instance=\"$instance\",hardware=~\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_gpuati_hertz{instance=\"$instance\",hardware=~\"$gpu\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Drives",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Drives",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "max by (hardware,hw_instance) (ohm_hdd_celsius{instance=\"$instance\"})"
      },
      {
       "expr": "ohm_hdd_bytes{instance=\"$instance\",sensor=\"Data Read\"}"
      },
      {
       "expr": "ohm_hdd_bytes{instance=\"$instance\",sensor=\"Data Written\"}"
      },
      {
       "expr": "sum by (hardware,hw_instance) (increase(ohm_hdd_bytes{instance=\"$instance\",sensor=\"Data Read\"}[$__range]))"
      },
      {
       "expr": "sum by (hardware,hw_instance) (increase(ohm_hdd_bytes{instance=\"$instance\",sensor=\"Data Written\"}[$__range]))"
      },
      {
       "expr": "ohm_hdd_load_percent{instance=\"$instance\",sensor=\"Used Space\"}"
      },
      {
       "expr": "ohm_hdd_factor{instance=\"$instance\",sensor=\"Power Cycles\"}"
      },
      {
       "expr": "ohm_hdd_factor{instance=\"$instance\",sensor=\"Media Errors\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Drive: $hdd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "repeat": "hdd",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$hdd Factors",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "ohm_hdd_factor{instance=\"$instance\",hw_instance=\"$hdd\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_hdd_bytes{instance=\"$instance\",hw_instance=\"$hdd\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "ohm_hdd_level_percent{instance=\"$instance\",hw_instance=\"$hdd\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "ohm_hdd_celsius{instance=\"$instance\",hw_instance=\"$hdd\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Disk Space Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ohm_hdd_load_percent{instance=\"$instance\",hw_instance=\"$hdd\",sensor=\"Used Space\"}",
       "legendFormat": "Used Space"
      }
     ]
    },
    {
     "title": "Disk Activity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "ohm_hdd_bytes_per_second{instance=\"$instance\",hw_instance=\"$hdd\",sensor=\"Read Rate\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "ohm_hdd_bytes_per_second{instance=\"$instance\",hw_instance=\"$hdd\",sensor=\"Write Rate\"}",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Disk Activity Load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ohm_hdd_load_percent{instance=\"$instance\",hw_instance=\"$hdd\",sensor=\"Total Activity\"}",
       "legendFormat": "Total Activity"
      },
      {
       "expr": "ohm_hdd_load_percent{instance=\"$instance\",hw_instance=\"$hdd\",sensor=\"Write Activity\"}",
       "legendFormat": "Write Activity"
      }
     ]
    }
   ]
  },
  {
   "title": "Motherboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Temperatures",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "ohm_superio_celsius{instance=\"$instance\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Fan",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "rotrpm" } },
     "targets": [
      {
       "expr": "ohm_superio_revolutions_per_minute{instance=\"$instance\"}",
       "legendFormat": "{{sensor}}"
      },
      {
       "expr": "(max(ohm_superio_revolutions_per_minute{instance=\"$instance\"}) / ignoring(sensor) (max(ohm_superio_control_percent{instance=\"$instance\"}) / 100)) * 0.9",
       "legendFormat": "High RPM"
      }
     ]
    },
    {
     "title": "Volts",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 186 },
     "repeat": "volts",
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "expr": "ohm_superio_volts{instance=\"$instance\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Network Usage",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum by (instance,hw_instance,hardware,host_system) (increase(ohm_nic_bytes{instance=\"$instance\",sensor=\"Data Downloaded\"}[$__range]))"
      },
      {
       "expr": "sum by (instance,hw_instance) (increase(ohm_nic_bytes{instance=\"$instance\",sensor=\"Data Uploaded\"}[$__range]))"
      },
      {
       "expr": "sum by (instance,hw_instance) (ohm_nic_bytes{instance=\"$instance\",sensor=\"Data Downloaded\"})"
      },
      {
       "expr": "sum by (instance,hw_instance) (ohm_nic_bytes{instance=\"$instance\",sensor=\"Data Uploaded\"})"
      },
      {
       "expr": "max by (instance,hw_instance) (ohm_nic_load_percent{instance=\"$instance\"})"
      }
     ]
    },
    {
     "title": "$network Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 60 },
     "repeat": "network",
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Download Speed\"}",
       "legendFormat": "Download"
      },
      {
       "expr": "ohm_nic_bytes_per_second{instance=\"$instance\",hardware=~\"$network\",sensor=\"Upload Speed\"}",
       "legendFormat": "Upload"
      }
     ]
    }
   ]
  }
 ]
}