{
 "title": "PI-Hole",
 "description": "This is a PI-Hole dashboard when using the https://github.com/eko/pihole-exporter Prometheus exporter",
 "tags": [
  "Prometheus",
  "pihole",
  "networking",
  "pihole exporter",
  "production"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "🍓PI-Hole",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_status", "legendFormat": "{{ legend }}" }
   ]
  },
  {
   "title": "Total Queries (rolling 24hr avg)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pihole_dns_queries_today" }
   ]
  },
  {
   "title": "Ads Blocked (rolling 24hr avg)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pihole_ads_blocked_today", "legendFormat": "Ads Blocked" },
    { "expr": "pihole_ads_percentage_today", "legendFormat": "%" }
   ]
  },
  {
   "title": "Domains being blocked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_domains_being_blocked" }
   ]
  },
  {
   "title": "Ads blocked (rolling 24hrs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pihole_ads_blocked_today", "legendFormat": "Count Ads Blocked" },
    { "expr": "pihole_ads_percentage_today", "legendFormat": "% Ads Blocked" }
   ]
  },
  {
   "title": "Unique clients (rolling 24hrs)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_unique_clients", "legendFormat": "{{ hostname }}" }
   ]
  },
  {
   "title": "Unique domains",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_unique_domains" }
   ]
  },
  {
   "title": "DNS queries all of types (rolling 24hrs)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pihole_dns_queries_all_types", "legendFormat": "Queries" }
   ]
  },
  {
   "title": "DNS Query types",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "pihole_querytypes", "legendFormat": "{{ type }}" }
   ]
  },
  {
   "title": "Queries cached/forwarded (rolling 24hrs)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pihole_queries_cached", "legendFormat": "Queries cached" },
    { "expr": "pihole_queries_forwarded", "legendFormat": "Queries forwarded" }
   ]
  },
  {
   "title": "Forward destinations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "pihole_forward_destinations", "legendFormat": "{{ destination }}" }
   ]
  },
  {
   "title": "Top queries by domain",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_top_queries", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "Top ads by domain",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_top_ads", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "Top Clients",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_top_sources", "legendFormat": "{{ source }}" }
   ]
  },
  {
   "title": "Top queries (rolling 24hrs)",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "topk(15, pihole_top_queries)", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "Top ads domains (rolling 24hrs)",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "topk(15, pihole_top_ads)", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "Top clients (rolling 24hrs)",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "topk(15, pihole_top_sources)", "legendFormat": "{{ source }}" }
   ]
  }
 ]
}