{
 "title": "Proxmox (PVE & PBS)",
 "description": "Proxmox Virtual Environment (10347) & Proxmox Backup Server (GitHub) Dashboards",
 "tags": [
  "proxmox",
  "prometheus",
  "production",
  "pbs",
  "proxmox-backup-server"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Queried PVE Instance",
    "query": {
     "query": "label_values(pve_node_info, instance)"
    }
   },
   {
    "name": "node_names",
    "label": "PVE Nodes",
    "query": {
     "query": "label_values(pve_node_info{instance=~\"$instance\"},name)"
    }
   },
   {
    "name": "node_ids",
    "label": "Node IDs",
    "query": {
     "query": "label_values(pve_node_info{instance=~\"$instance\", name=~\"$node_names\"},id)"
    }
   },
   {
    "name": "guest_names",
    "label": "PVE Guests",
    "query": {
     "query": "label_values(pve_guest_info{instance=~\"$instance\", node=~\"$node_names\"},name)"
    }
   },
   {
    "name": "guest_ids",
    "label": "PVE Guest IDs",
    "query": {
     "query": "label_values(pve_guest_info{instance=~\"$instance\", node=~\"$node_names\", name=~\"$guest_names\"},id)"
    }
   },
   {
    "name": "storage_names",
    "label": "PVE Storage",
    "query": {
     "query": "label_values(pve_storage_info{instance=~\"$instance\", node=~\"$node_names\"},storage)"
    }
   },
   {
    "name": "storage_ids",
    "label": "PVE Storage IDs",
    "query": {
     "query": "label_values(pve_storage_info{instance=~\"$instance\", node=~\"$node_names\", storage=~\"$storage_names\"},id)"
    }
   },
   {
    "name": "pbs_host_system",
    "label": "PBS Host",
    "query": {
     "query": "label_values(pbs_host_uptime,host_system)"
    }
   },
   {
    "name": "pbs_instance",
    "label": "PBS Instance",
    "query": {
     "query": "label_values(pbs_host_uptime,instance)"
    }
   },
   {
    "name": "pbs_datastore",
    "label": "PBS Datastore",
    "query": {
     "query": "label_values(pbs_size{host_system=~\"$pbs_host_system\"},datastore)"
    }
   },
   {
    "name": "pbs_guest",
    "label": "PBS Backup Guest",
    "query": {
     "query": "label_values(pbs_snapshot_vm_count{datastore=~\"$pbs_datastore\"},vm_name)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Cluster & Node Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Details",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(id, name, type, node) (pve_guest_info{instance=~\"$instance.*\",id=~\"$node_ids|$guest_ids|$storage_ids\"})"
    },
    {
     "expr": "sum by (id) (pve_up{instance=~\"$instance.*\",id=~\"$node_ids|$guest_ids|$storage_ids\"})"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_limit{instance=~\"$instance.*\",id=~\"$node_ids|$guest_ids|$storage_ids\"})"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_ratio{instance=~\"$instance.*\",id=~\"$node_ids|$guest_ids|$storage_ids\"} and on (id) pve_up==1)"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_ratio{instance=~\"$instance.*\",id=~\"$node_ids|$guest_ids|$storage_ids\"} / pve_cpu_usage_limit and on (id) pve_up==1)"
    },
    {
     "expr": "sum by (id) (pve_memory_size_bytes{instance=~\"$instance.*\",id=~\"$node_ids|$guest_ids|$storage_ids\"})"
    },
    {
     "expr": "sum by (id) (pve_memory_usage_bytes{instance=~\"$instance.*\",template!=\"1\", id=~\"$node_ids|$guest_ids|$storage_ids\"} and on (id) pve_up==1)"
    },
    {
     "expr": "sum by (id) (pve_memory_usage_bytes{instance=~\"$instance.*\",template!=\"1\", id=~\"$node_ids|$guest_ids|$storage_ids\"} / pve_memory_size_bytes and on (id) pve_up==1)"
    },
    {
     "expr": "sum by (id) (pve_disk_size_bytes{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
    },
    {
     "expr": "sum by (id) (pve_disk_usage_bytes{instance=~\"$instance.*\",id=~\"$node_ids|$guest_ids|$storage_ids\"})"
    },
    {
     "expr": "sum by (id) (pve_disk_usage_bytes{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"} / pve_disk_size_bytes )"
    },
    {
     "expr": "sum by (id) (pve_uptime_seconds{instance=~\"$instance.*\",id=~\"$node_ids|$guest_ids|$storage_ids\"}) !=0",
     "legendFormat": "Uptime"
    },
    {
     "expr": "sum by (id, node, storage) (pve_storage_info{instance=~\"$instance.*\",id=~\"$node_ids|$guest_ids|$storage_ids\"})"
    },
    {
     "expr": "sum by (id) (pve_storage_shared{instance=~\"$instance.*\",id=~\"$node_ids|$guest_ids|$storage_ids\"})"
    }
   ]
  },
  {
   "title": "NODE EXPORTER - Node Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (host_system, id, name, pretty_name, version, version_codename, version_id) (node_os_info{host_system=~\"$node_names\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (host_system) (\r\n    count by (host_system,cpu) (node_cpu_seconds_total{host_system=~\"$node_names\"}) )",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host_system) (\r\n    node_time_seconds{host_system=~\"$node_names\"} - \r\n    node_boot_time_seconds{host_system=~\"$node_names\"}\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (host_system) (node_load5{host_system=~\"$node_names\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (host_system) (irate(node_cpu_seconds_total{host_system=~\"$node_names\", mode!=\"idle\"}[5m])) / \r\non(host_system) group_left sum by (host_system)((irate(node_cpu_seconds_total{host_system=~\"$node_names\"}[5m]))))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (host_system) (node_memory_MemTotal_bytes{host_system=~\"$node_names\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host_system) (node_memory_MemTotal_bytes{host_system=~\"$node_names\"}) - \r\nsum by (host_system) (node_memory_MemAvailable_bytes{host_system=~\"$node_names\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - (sum by (host_system) (node_memory_MemAvailable_bytes{host_system=~\"$node_names\"}) / \r\n     sum by (host_system) (node_memory_MemTotal_bytes{host_system=~\"$node_names\"}) )",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (host_system) (node_memory_SwapTotal_bytes{host_system=~\"$node_names\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host_system) (node_memory_SwapTotal_bytes{host_system=~\"$node_names\"}) - \r\nsum by (host_system) (node_memory_SwapFree_bytes{host_system=~\"$node_names\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - (sum by (host_system) (node_memory_SwapFree_bytes{host_system=~\"$node_names\"}) / \r\n     sum by (host_system) (node_memory_SwapTotal_bytes{host_system=~\"$node_names\"}) )",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (host_system) (node_filesystem_size_bytes{host_system=~\"$node_names\",mountpoint=\"/\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host_system) (node_filesystem_size_bytes{host_system=~\"$node_names\",mountpoint=\"/\"}) - \r\nsum by (host_system) (node_filesystem_avail_bytes{host_system=~\"$node_names\",mountpoint=\"/\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - (sum by (host_system) (node_filesystem_avail_bytes{host_system=~\"$node_names\",mountpoint=\"/\"}) / \r\n     sum by (host_system) (node_filesystem_size_bytes{host_system=~\"$node_names\",mountpoint=\"/\"}) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pve_cluster_info{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Node Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 2, "y": 9 },
   "targets": [
    {
     "expr": "pve_up{instance=~\"$instance.*\",id=~\"node.*\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Node CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{instance=~\"$instance.*\",id=~\"node.*\"} and on(id,instance) pve_node_info and on(id, instance) pve_up == 1",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "pve_cpu_usage_limit{instance=~\"$instance.*\",id=~\"node.*\"} and on(id,instance) pve_node_info and on(id, instance) pve_up == 1",
     "legendFormat": "{{id}} - Limit"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_ratio{instance=~\"$instance.*\", id=~\"node.*\"} / pve_cpu_usage_limit and on (id, instance) pve_up==1)",
     "legendFormat": "{{id}} %"
    }
   ]
  },
  {
   "title": "Node Memory Use",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{instance=~\"$instance.*\",id=~\"node.*\"} and on(id) pve_node_info and on(id) pve_up == 1",
     "legendFormat": "{{id}} - Used"
    },
    {
     "expr": "pve_memory_size_bytes{instance=~\"$instance.*\",id=~\"node.*\"} and on(id) pve_node_info and on(id) pve_up == 1",
     "legendFormat": "{{id}} - Total"
    },
    {
     "expr": "sum by (id) (pve_memory_usage_bytes{instance=~\"$instance.*\",template!=\"1\", id=~\"node.*\"} / pve_memory_size_bytes and on (id) pve_up==1)",
     "legendFormat": "{{id}} %"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Sums all network send/receive metrics across guests - since a lot of traffic will be 'internal' to Proxmox (i.e. between guests) this does not represent total network input/output for Proxmox.",
   "gridPos": { "h": 9, "w": 21, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(rate(pve_network_receive_bytes{instance=~\"$instance.*\"}[$__rate_interval]) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} - Received"
    },
    {
     "expr": "sum by(instance) (\r\n  (rate(pve_network_receive_bytes{instance=~\"$instance.*\"}[$__rate_interval]) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1\r\n)",
     "legendFormat": "Received - TOTAL"
    },
    {
     "expr": "(rate(pve_network_transmit_bytes{instance=~\"$instance.*\"}[$__rate_interval]) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
     "legendFormat": "{{name}} - Sent"
    },
    {
     "expr": "sum by(instance) (\r\n  (rate(pve_network_transmit_bytes{instance=~\"$instance.*\"}[$__rate_interval]) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1\r\n)",
     "legendFormat": "Sent - TOTAL"
    }
   ]
  },
  {
   "title": "Total Data Tranferred In Range",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(\r\n  sum by (instance) (pve_network_receive_bytes)\r\n[$__range])",
     "legendFormat": "Received"
    },
    {
     "expr": "delta(\r\n  sum by (instance) (pve_network_transmit_bytes)\r\n[$__range])",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Overall Guest CPU Load",
   "type": "timeseries",
   "description": "Percentage used is the % of total node CPU, not the % of guest CPU used (see below for details of CPU use against guest's CPU allocation).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "((pve_cpu_usage_ratio{instance=~\"$instance.*\",id!~\"node.*\"}) * on(id, instance) group_left(name, type) pve_guest_info and on(id, instance) pve_up == 1)",
     "legendFormat": "{{name}} [{{id}}]"
    },
    {
     "expr": "sum by (instance) (\r\n  ((pve_cpu_usage_ratio{instance=~\"$instance.*\",id!~\"node.*\"}) * on(id, instance) group_left(name, type) pve_guest_info and on(id, instance) pve_up == 1)\r\n)",
     "legendFormat": "Guest CPU Use - TOTAL"
    },
    {
     "expr": "sum by (id,instance) (\r\n  pve_cpu_usage_limit{instance=~\"$instance.*\",id=~\"node.*\"} and on(id) pve_node_info and on(id, instance) pve_up == 1\r\n)",
     "legendFormat": "{{id}} Limit"
    }
   ]
  },
  {
   "title": "Overall Guest Memory Use",
   "type": "timeseries",
   "description": "Percentage used is the % of total node memory used, not % of guest memory used (see below for details of memory use against guest's memory allocation).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "((pve_memory_usage_bytes{instance=~\"$instance.*\",id!~\"node.*\"})  * on(id, instance) group_left(name, type)  pve_guest_info and on(id, instance) pve_up == 1)",
     "legendFormat": "{{name}} [{{id}}]"
    },
    {
     "expr": "sum by (instance) (\r\n  ((pve_memory_usage_bytes{instance=~\"$instance.*\",id!~\"node.*\"})  * on(id, instance) group_left(name, type)  pve_guest_info and on(id, instance) pve_up == 1)\r\n)",
     "legendFormat": "Guest Memory Use - TOTAL"
    },
    {
     "expr": "pve_memory_size_bytes{instance=~\"$instance.*\",id=~\"node.*\"} and on(id,instance) pve_node_info and on(id, instance) pve_up == 1",
     "legendFormat": "{{id}} Limit"
    }
   ]
  },
  {
   "title": "Overall Guest CPU Use (%)",
   "type": "timeseries",
   "description": "Percentage used is the % of total node CPU, not the % of guest CPU used (see below for details of CPU use against guest's CPU allocation).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((pve_cpu_usage_ratio{instance=~\"$instance.*\",id!~\"node.*\"}) * on(id, instance) group_left(name, type) pve_guest_info and on(id, instance) pve_up == 1) / \r\nsum(pve_cpu_usage_limit{instance=~\"$instance.*\",id=~\"node.*\"})",
     "legendFormat": "{{name}} [{{id}}]"
    },
    {
     "expr": "sum by (instance) (\r\n  ((pve_cpu_usage_ratio{instance=~\"$instance.*\",id!~\"node.*\"}) * on(id, instance) group_left(name, type) pve_guest_info and on(id, instance) pve_up == 1) / \r\nsum(pve_cpu_usage_limit{instance=~\"$instance.*\",id=~\"node.*\"})\r\n)",
     "legendFormat": "Guest CPU Use - TOTAL"
    }
   ]
  },
  {
   "title": "Overall Guest Memory Use (%)",
   "type": "timeseries",
   "description": "Percentage used is the % of total node memory used, not % of guest memory used (see below for details of memory use against guest's memory allocation).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((pve_memory_usage_bytes{instance=~\"$instance.*\",id!~\"node.*\"})  * on(id, instance) group_left(name, type)  pve_guest_info and on(id, instance) pve_up == 1) /\r\nsum(pve_memory_size_bytes{instance=~\"$instance.*\",id=~\"node.*\"})",
     "legendFormat": "{{name}} [{{id}}]"
    },
    {
     "expr": "sum by (instance) (\r\n  ((pve_memory_usage_bytes{instance=~\"$instance.*\",id!~\"node.*\"})  * on(id, instance) group_left(name, type)  pve_guest_info and on(id, instance) pve_up == 1) /\r\n  sum(pve_memory_size_bytes{instance=~\"$instance.*\",id=~\"node.*\"})\r\n)",
     "legendFormat": "Guest Memory Use - TOTAL"
    }
   ]
  },
  {
   "title": "Guests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Guest Info",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 92 },
     "targets": [
      {
       "expr": "sum by(id, name, type, node) (pve_guest_info{instance=~\"$instance.*\", id=~\"$guest_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_up{instance=~\"$instance.*\", id=~\"$guest_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_cpu_usage_limit{instance=~\"$instance.*\", id=~\"$guest_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_cpu_usage_ratio{instance=~\"$instance.*\", id=~\"$guest_ids\"} and on (id) pve_up==1)"
      },
      {
       "expr": "sum by (id) (pve_cpu_usage_ratio{instance=~\"$instance.*\", id=~\"$guest_ids\"} / pve_cpu_usage_limit and on (id) pve_up==1)"
      },
      {
       "expr": "sum by (id) (pve_memory_size_bytes{instance=~\"$instance.*\", id=~\"$guest_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_memory_usage_bytes{instance=~\"$instance.*\",template!=\"1\", id=~\"$guest_ids\"} and on (id) pve_up==1)"
      },
      {
       "expr": "sum by (id) (pve_memory_usage_bytes{instance=~\"$instance.*\",template!=\"1\", id=~\"$guest_ids\"} / pve_memory_size_bytes and on (id) pve_up==1)"
      },
      {
       "expr": "sum by (id) (pve_disk_size_bytes{instance=~\"$instance.*\", id=~\"$guest_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_disk_usage_bytes{instance=~\"$instance.*\", id=~\"$guest_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_disk_usage_bytes{instance=~\"$instance.*\", id=~\"$guest_ids\"} / pve_disk_size_bytes )"
      },
      {
       "expr": "sum by (id) (pve_uptime_seconds{instance=~\"$instance.*\", id=~\"$guest_ids\"}) !=0",
       "legendFormat": "Uptime"
      },
      {
       "expr": "sum by (id, node, storage) (pve_storage_info{instance=~\"$instance.*\", id=~\"$guest_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_storage_shared{instance=~\"$instance.*\", id=~\"$guest_ids\"})"
      }
     ]
    },
    {
     "title": "NODE EXPORTER - Guest Info",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 102 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (host_system, id, name, pretty_name, version, version_codename, version_id) (node_os_info{host_system=~\"$guest_names\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (host_system) (\r\n    count by (host_system,cpu) (node_cpu_seconds_total{host_system=~\"$guest_names\"}) )",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (host_system) (\r\n    node_time_seconds{host_system=~\"$guest_names\"} - \r\n    node_boot_time_seconds{host_system=~\"$guest_names\"}\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (host_system) (node_load5{host_system=~\"$guest_names\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum by (host_system) (irate(node_cpu_seconds_total{host_system=~\"$guest_names\", mode!=\"idle\"}[5m])) / \r\non(host_system) group_left sum by (host_system)((irate(node_cpu_seconds_total{host_system=~\"$guest_names\"}[5m]))))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (host_system) (node_memory_MemTotal_bytes{host_system=~\"$guest_names\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (host_system) (node_memory_MemTotal_bytes{host_system=~\"$guest_names\"}) - \r\nsum by (host_system) (node_memory_MemAvailable_bytes{host_system=~\"$guest_names\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "1 - (sum by (host_system) (node_memory_MemAvailable_bytes{host_system=~\"$guest_names\"}) / \r\n     sum by (host_system) (node_memory_MemTotal_bytes{host_system=~\"$guest_names\"}) )",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (host_system) (node_memory_SwapTotal_bytes{host_system=~\"$guest_names\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (host_system) (node_memory_SwapTotal_bytes{host_system=~\"$guest_names\"}) - \r\nsum by (host_system) (node_memory_SwapFree_bytes{host_system=~\"$guest_names\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "1 - (sum by (host_system) (node_memory_SwapFree_bytes{host_system=~\"$guest_names\"}) / \r\n     sum by (host_system) (node_memory_SwapTotal_bytes{host_system=~\"$guest_names\"}) )",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (host_system) (node_filesystem_size_bytes{host_system=~\"$guest_names\",mountpoint=\"/\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (host_system) (node_filesystem_size_bytes{host_system=~\"$guest_names\",mountpoint=\"/\"}) - \r\nsum by (host_system) (node_filesystem_avail_bytes{host_system=~\"$guest_names\",mountpoint=\"/\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "1 - (sum by (host_system) (node_filesystem_avail_bytes{host_system=~\"$guest_names\",mountpoint=\"/\"}) / \r\n     sum by (host_system) (node_filesystem_size_bytes{host_system=~\"$guest_names\",mountpoint=\"/\"}) )",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (host_system) (node_memory_MemTotal_bytes{host_system=~\"$guest_names\"}) - \r\nsum by (host_system) (node_memory_MemFree_bytes{host_system=~\"$guest_names\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "1 - (sum by (host_system) (node_memory_MemFree_bytes{host_system=~\"$guest_names\"}) / \r\n     sum by (host_system) (node_memory_MemTotal_bytes{host_system=~\"$guest_names\"}) )",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Guest CPU Use (%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "((pve_cpu_usage_ratio{instance=~\"$instance.*\",id=~\"$guest_ids\"} / pve_cpu_usage_limit) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} [{{id}}]"
      }
     ]
    },
    {
     "title": "NODE EXPORTER - CPU Busy %",
     "type": "timeseries",
     "description": "Basic CPU info",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(host_system) (irate(node_cpu_seconds_total{host_system=~\"$guest_names\", mode!=\"idle\"}[$__rate_interval])) / on(host_system) group_left sum by (host_system)((irate(node_cpu_seconds_total{host_system=~\"$guest_names\"}[$__rate_interval])))",
       "legendFormat": "{{host_system}} : Busy"
      }
     ]
    },
    {
     "title": "Guest CPU Load",
     "type": "timeseries",
     "description": "pve_cpu_usage_ratio is a representation of the CPU load as detected by the Proxmox host. Its value is between 0 and the number of cores assigned to the guest (pve_cpu_usage_limit). \n\npve_cpu_usage_ratio is divided by the number of allocated cores to get CPU usage % (see separate chart). \nThis chart should stay below allocated core count. ",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "((pve_cpu_usage_ratio{instance=~\"$instance.*\",id=~\"$guest_ids\"}) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} [{{id}}]"
      },
      {
       "expr": "max(\r\n    sum by (id,instance) (\r\n    ((pve_cpu_usage_limit{instance=~\"$instance.*\",id=~\"$guest_ids\"}) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1\r\n  )\r\n)",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "NODE EXPORTER - System Load",
     "type": "timeseries",
     "description": "Load shouldn't exceed number of cores.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg_over_time(node_load5{host_system=~\"$guest_names\"}[$__rate_interval]) ",
       "legendFormat": "{{host_system}} : Load - 5m"
      },
      {
       "expr": "max( count by (host_system) ( count by (host_system,cpu) (node_cpu_seconds_total{host_system=~\"$guest_names\"}) ) )",
       "legendFormat": "threshold"
      }
     ]
    },
    {
     "title": "Guest Memory Use (%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(pve_memory_usage_bytes{instance=~\"$instance.*\",id=~\"$guest_ids\"} / pve_memory_size_bytes * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
       "legendFormat": "{{name}} [{{id}}]"
      }
     ]
    },
    {
     "title": "NODE EXPORTER - Memory Use (%)",
     "type": "timeseries",
     "description": "Basic memory usage",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (node_memory_MemFree_bytes{host_system=~\"$guest_names\"} / node_memory_MemTotal_bytes{host_system=~\"$guest_names\"})",
       "legendFormat": "{{host_system}}"
      }
     ]
    },
    {
     "title": "Guest Memory Use",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "((pve_memory_usage_bytes{instance=~\"$instance.*\",id=~\"$guest_ids\"})  * on(id, instance) group_left(name, type)  pve_guest_info and on(id, instance) pve_up == 1)",
       "legendFormat": "{{name}} [{{id}}]"
      },
      {
       "expr": "max ( pve_memory_size_bytes{instance=~\"$instance.*\",id=~\"$guest_ids\"} )",
       "legendFormat": "threshold"
      }
     ]
    },
    {
     "title": "NODE EXPORTER - Memory Use",
     "type": "timeseries",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 139 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_MemTotal_bytes{host_system=~\"$guest_names\"} - node_memory_MemFree_bytes{host_system=~\"$guest_names\"}",
       "legendFormat": "{{host_system}}"
      },
      {
       "expr": "max(node_memory_MemTotal_bytes{host_system=~\"$guest_names\"})",
       "legendFormat": "threshold"
      }
     ]
    },
    {
     "title": "Guest Disk Usage (LXC Only)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pve_disk_usage_bytes{instance=~\"$instance.*\",id=~\"$guest_ids\"} / pve_disk_size_bytes{instance=~\"$instance.*\",id=~\"$guest_ids\"} * on (id, instance) group_left(name, type) pve_guest_info{type=\"lxc\"} !=0",
       "legendFormat": "{{name}} ({{type}})"
      }
     ]
    },
    {
     "title": "NODE EXPORTER - Disk Space Used (rootfs)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 149 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - ( node_filesystem_avail_bytes{host_system=~\"$guest_names\",mountpoint=~\"/\"} / node_filesystem_size_bytes{host_system=~\"$guest_names\",mountpoint=~\"/\"})",
       "legendFormat": "{{host_system}} -- {{device}}"
      }
     ]
    },
    {
     "title": "Disk Read / Write",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "( irate(pve_disk_write_bytes{instance=~\"$instance.*\",id=~\"$guest_ids\"}[$__rate_interval]) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1 ",
       "legendFormat": "WRITE -- {{name}} [{{id}}]"
      },
      {
       "expr": "( irate(pve_disk_read_bytes{instance=~\"$instance.*\",id=~\"$guest_ids\"}[$__rate_interval]) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1 ",
       "legendFormat": "READ -- {{name}} [{{id}}]"
      }
     ]
    },
    {
     "title": "NODE EXPORTER - Disk Read / Write",
     "type": "timeseries",
     "description": "Summed by system, can be broken down per disk ({{device}}) if preferred.",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (host_system) (irate(node_disk_written_bytes_total{host_system=~\"$guest_names\"}[$__rate_interval]))",
       "legendFormat": "WRITE -- {{host_system}}"
      },
      {
       "expr": "sum by (host_system) (irate(node_disk_read_bytes_total{host_system=~\"$guest_names\"}[$__rate_interval]))",
       "legendFormat": "READ -- {{host_system}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(irate(pve_network_transmit_bytes{instance=~\"$instance.*\",id=~\"$guest_ids\"}[$__rate_interval])* on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
       "legendFormat": "SENT -- {{name}} [{{id}}]"
      },
      {
       "expr": "(irate(pve_network_receive_bytes{instance=~\"$instance.*\",id=~\"$guest_ids\"}[$__rate_interval]) * on(id, instance) group_left(name, type) pve_guest_info) and on(id, instance) pve_up == 1",
       "legendFormat": "RECV -- {{name}} [{{id}}]"
      }
     ]
    },
    {
     "title": "NODE EXPORTER - Network Traffic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 169 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum by (host_system) (irate(node_network_receive_bytes_total{host_system=~\"$guest_names\"}[$__rate_interval]))",
       "legendFormat": "RECV -- {{host_system}}"
      },
      {
       "expr": "sum by (host_system) (irate(node_network_transmit_bytes_total{host_system=~\"$guest_names\"}[$__rate_interval]))",
       "legendFormat": "SENT -- {{host_system}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PVE Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "PVE Storage usage",
     "type": "gauge",
     "gridPos": { "h": 11, "w": 7, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "pve_disk_usage_bytes{instance=~\"$instance.*\", id=~\"$storage_ids\"} / pve_disk_size_bytes * on (id, instance) group_left(storage) pve_storage_info",
       "legendFormat": "{{storage}}"
      }
     ]
    },
    {
     "title": "PVE Storage Info",
     "type": "table",
     "gridPos": { "h": 11, "w": 17, "x": 7, "y": 51 },
     "targets": [
      {
       "expr": "sum by(id, name, type, node) (pve_guest_info{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_up{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_cpu_usage_limit{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_cpu_usage_ratio{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"} and on (id) pve_up==1)"
      },
      {
       "expr": "sum by (id) (pve_cpu_usage_ratio{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"} / pve_cpu_usage_limit and on (id) pve_up==1)"
      },
      {
       "expr": "sum by (id) (pve_memory_size_bytes{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_memory_usage_bytes{instance=~\"$instance.*\",template!=\"1\", id=~\"$node_ids|$guest_ids|$storage_ids\"} and on (id) pve_up==1)"
      },
      {
       "expr": "sum by (id) (pve_memory_usage_bytes{instance=~\"$instance.*\",template!=\"1\", id=~\"$node_ids|$guest_ids|$storage_ids\"} / pve_memory_size_bytes and on (id) pve_up==1)"
      },
      {
       "expr": "sum by (id) (pve_disk_size_bytes{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_disk_usage_bytes{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_disk_usage_bytes{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"} / pve_disk_size_bytes )"
      },
      {
       "expr": "sum by (id) (pve_uptime_seconds{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"}) !=0",
       "legendFormat": "Uptime"
      },
      {
       "expr": "sum by (id, node, storage) (pve_storage_info{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_storage_shared{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "PBS Backup Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Snapshot Detail per VM (select VM from dropdown)",
     "type": "table",
     "gridPos": { "h": 10, "w": 13, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(pbs_snapshot_vm_count{job=\"pbs\", host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (datastore,vm_id,vm_name,host_system)",
       "legendFormat": "snap-count"
      },
      {
       "expr": "sum(pbs_snapshot_vm_last_timestamp{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"} * 1000) by (datastore,vm_id,vm_name,host_system)",
       "legendFormat": "last-snapshot"
      },
      {
       "expr": "sum(pbs_snapshot_vm_last_verify{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (host_system,datastore,vm_id,vm_name)",
       "legendFormat": "verify-status"
      },
      {
       "expr": "sum(pbs_used{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (host_system,datastore,vm_id,vm_name) / sum(pbs_size{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (host_system,datastore,vm_id,vm_name)",
       "legendFormat": "datastore-perc"
      }
     ]
    },
    {
     "title": "Total Snapshots",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 13, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(pbs_snapshot_count{job=\"pbs\", host_system=~\"$pbs_host_system\"})"
      }
     ]
    },
    {
     "title": "Total Snapshots by VM / LXC",
     "type": "table",
     "description": "VM / LXC name taken from backup comment field",
     "gridPos": { "h": 18, "w": 5, "x": 19, "y": 1 },
     "targets": [
      {
       "expr": "sum(pbs_snapshot_vm_count{job=\"pbs\", host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\"}) by (vm_name)"
      }
     ]
    },
    {
     "title": "Total Snapshots by Datastore",
     "type": "table",
     "gridPos": { "h": 14, "w": 6, "x": 13, "y": 5 },
     "targets": [
      {
       "expr": "pbs_snapshot_count{job=\"pbs\", host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\"}"
      }
     ]
    },
    {
     "title": "Snapshot Detail per VM (nested tables)",
     "type": "table",
     "description": "VM / LXC name taken from backup comment field",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(pbs_snapshot_vm_count{job=\"pbs\", host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (datastore,vm_id,vm_name,host_system)"
      }
     ]
    },
    {
     "title": "PBS Uptime",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 9, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pbs_host_uptime{host_system=~\"$pbs_host_system\"}",
       "legendFormat": "{{host_system}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PVE Tables - All Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Details - Copy and Filter Using Transformations",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "sum by(id, name, type, node) (pve_guest_info{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_up{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_cpu_usage_limit{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_cpu_usage_ratio{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"} and on (id) pve_up==1)"
      },
      {
       "expr": "sum by (id) (pve_cpu_usage_ratio{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"} / pve_cpu_usage_limit and on (id) pve_up==1)"
      },
      {
       "expr": "sum by (id) (pve_memory_size_bytes{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_memory_usage_bytes{instance=~\"$instance.*\",template!=\"1\", id=~\"$node_ids|$guest_ids|$storage_ids\"} and on (id) pve_up==1)"
      },
      {
       "expr": "sum by (id) (pve_memory_usage_bytes{instance=~\"$instance.*\",template!=\"1\", id=~\"$node_ids|$guest_ids|$storage_ids\"} / pve_memory_size_bytes and on (id) pve_up==1)"
      },
      {
       "expr": "sum by (id) (pve_disk_size_bytes{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_disk_usage_bytes{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_disk_usage_bytes{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"} / pve_disk_size_bytes )"
      },
      {
       "expr": "sum by (id) (pve_uptime_seconds{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"}) !=0",
       "legendFormat": "Uptime"
      },
      {
       "expr": "sum by (id, node, storage) (pve_storage_info{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
      },
      {
       "expr": "sum by (id) (pve_storage_shared{instance=~\"$instance.*\", id=~\"$node_ids|$guest_ids|$storage_ids\"})"
      }
     ]
    },
    {
     "title": "Node Exporter Info",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (host_system, id, name, pretty_name, version, version_codename, version_id) (node_os_info{host_system=~\"$guest_names|$node_names|$storage_names\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "count by (host_system) (\r\n    count by (host_system,cpu) (node_cpu_seconds_total{host_system=~\"$guest_names|$node_names|$storage_names\"}) )",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (host_system) (\r\n    node_time_seconds{host_system=~\"$guest_names|$node_names|$storage_names\"} - \r\n    node_boot_time_seconds{host_system=~\"$guest_names|$node_names|$storage_names\"}\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (host_system) (node_load5{host_system=~\"$guest_names|$node_names|$storage_names\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "(sum by (host_system) (irate(node_cpu_seconds_total{host_system=~\"$guest_names|$node_names|$storage_names\", mode!=\"idle\"}[5m])) / \r\non(host_system) group_left sum by (host_system)((irate(node_cpu_seconds_total{host_system=~\"$guest_names|$node_names|$storage_names\"}[5m]))))",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (host_system) (node_memory_MemTotal_bytes{host_system=~\"$guest_names|$node_names|$storage_names\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (host_system) (node_memory_MemTotal_bytes{host_system=~\"$guest_names|$node_names|$storage_names\"}) - \r\nsum by (host_system) (node_memory_MemAvailable_bytes{host_system=~\"$guest_names|$node_names|$storage_names\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "1 - (sum by (host_system) (node_memory_MemAvailable_bytes{host_system=~\"$guest_names|$node_names|$storage_names\"}) / \r\n     sum by (host_system) (node_memory_MemTotal_bytes{host_system=~\"$guest_names|$node_names|$storage_names\"}) )",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (host_system) (node_memory_SwapTotal_bytes{host_system=~\"$guest_names|$node_names|$storage_names\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (host_system) (node_memory_SwapTotal_bytes{host_system=~\"$guest_names|$node_names|$storage_names\"}) - \r\nsum by (host_system) (node_memory_SwapFree_bytes{host_system=~\"$guest_names|$node_names|$storage_names\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "1 - (sum by (host_system) (node_memory_SwapFree_bytes{host_system=~\"$guest_names|$node_names|$storage_names\"}) / \r\n     sum by (host_system) (node_memory_SwapTotal_bytes{host_system=~\"$guest_names|$node_names|$storage_names\"}) )",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg by (host_system) (node_filesystem_size_bytes{host_system=~\"$guest_names|$node_names|$storage_names\",mountpoint=\"/\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (host_system) (node_filesystem_size_bytes{host_system=~\"$guest_names|$node_names|$storage_names\",mountpoint=\"/\"}) - \r\nsum by (host_system) (node_filesystem_avail_bytes{host_system=~\"$guest_names|$node_names|$storage_names\",mountpoint=\"/\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "1 - (sum by (host_system) (node_filesystem_avail_bytes{host_system=~\"$guest_names|$node_names|$storage_names\",mountpoint=\"/\"}) / \r\n     sum by (host_system) (node_filesystem_size_bytes{host_system=~\"$guest_names|$node_names|$storage_names\",mountpoint=\"/\"}) )",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}