{
 "title": "Traefik (12250)",
 "tags": [
  "traefik",
  "prometheus",
  "network",
  "production"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "entrypoint", "label": "Entrypoint", "query": { "query": "label_values(entrypoint)" } },
   { "name": "router", "label": "Router", "query": { "query": "label_values(router)" } },
   { "name": "service", "label": "Service", "query": { "query": "label_values(service)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests Per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total[$__rate_interval])) by (entrypoint) !=0",
     "legendFormat": " {{entrypoint}}"
    },
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total[$__rate_interval])) !=0",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Requests Per Router",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_router_requests_total[$__rate_interval])) by (router) !=0",
     "legendFormat": " {{router}}"
    },
    {
     "expr": "sum(increase(traefik_router_requests_total[$__rate_interval])) !=0",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Requests Per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total[$__rate_interval])) by (service) !=0",
     "legendFormat": " {{service}}"
    },
    {
     "expr": "sum(increase(traefik_service_requests_total[$__rate_interval])) !=0",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Certificate Expiry",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(cn, sans) (traefik_tls_certs_not_after)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Http Code (last 5m)",
   "type": "piechart",
   "description": "Mean Distribution",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total[5m])) by (method, code) !=0",
     "legendFormat": "{{method}}[{{code}}]"
    }
   ]
  },
  {
   "title": "Top Slow HTTP Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        traefik_service_request_duration_seconds_sum{protocol=\"http\"} / \n          traefik_service_request_duration_seconds_count{protocol=\"http\"},\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)\n\n",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Top Requests Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(10,\n    label_replace(\n        sum by (entrypoint,method,protocol) \n          (rate(traefik_entrypoint_requests_bytes_total[$__rate_interval])) > 0,\n        \"entrypoint\", \"$1\", \"entrypoint\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "Entrypoint: {{entrypoint}} -- {{protocol}} -- {{method}}"
    },
    {
     "expr": "topk(10,\n    label_replace(\n        sum by (router,method,protocol) \n          (rate(traefik_router_requests_bytes_total[$__rate_interval])) > 0,\n        \"router\", \"$1\", \"router\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "Router: {{router}} -- {{protocol}} -- {{method}}"
    },
    {
     "expr": "topk(10,\n    label_replace(\n        sum by (service,method,protocol) \n          (rate(traefik_service_requests_bytes_total[$__rate_interval])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "Service: {{service}} -- {{protocol}} -- {{method}}"
    }
   ]
  },
  {
   "title": "Top Responses Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(3,\n        sum by (entrypoint,method,protocol) \n          (rate(traefik_entrypoint_responses_bytes_total[$__rate_interval])) > 0\n)",
     "legendFormat": "Entrypoint: {{entrypoint}} -- {{protocol}} -- {{method}}"
    },
    {
     "expr": "topk(3,\n        sum by (router,method,protocol) \n          (rate(traefik_router_responses_bytes_total[$__rate_interval])) > 0\n)",
     "legendFormat": "Router: {{router}} -- {{protocol}} -- {{method}}"
    },
    {
     "expr": "topk(3,\n  sum by (service,method,protocol) \n    (rate(traefik_service_responses_bytes_total[$__rate_interval])) > 0\n)",
     "legendFormat": "Service: {{service}} -- {{protocol}} -- {{method}}"
    }
   ]
  },
  {
   "title": "Most Requested Services",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (service,code) \n          (rate(traefik_service_requests_total[5m])) > 0,\n        \"service\", \"$1\", \"service\", \"([^-]+-[^-]+).*\")\n)",
     "legendFormat": "[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "User Experience (Apdex Score)",
   "type": "timeseries",
   "description": "Ratio of Satisfactory vs Intolerable response timing. 1 is good.\n\nCalc uses 300ms as Satisfactory timing, 1200ms as tolerable, with anything longer being intolerable.\n\n(Tolerable must equal 4 x Satisfactory and prometheus metric bucket boundaries must align with this ratio between Satisfactory and Tolerable)\n\nhttps://medium.com/@tristan_96324/prometheus-apdex-alerting-d17a065e39d0",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 26 },
   "targets": [
    {
     "expr": "(sum(rate(traefik_service_request_duration_seconds_bucket{le=\"0.3\",code=\"200\"}[5m])) by (service) + \n sum(rate(traefik_service_request_duration_seconds_bucket{le=\"1.2\",code=\"200\"}[5m])) by (service)) / 2 / \n sum(rate(traefik_service_request_duration_seconds_count{code=\"200\"}[5m])) by (service)\n",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Entrypoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total[$__rate_interval])) by (entrypoint,protocol,method) !=0",
       "legendFormat": " {{entrypoint}} -- {{protocol}} -- {{method}}"
      },
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total[$__rate_interval])) !=0",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(traefik_entrypoint_open_connections) by (entrypoint,method,protocol) !=0",
       "legendFormat": "{{entrypoint}} -- {{protocol}} -- {{method}}"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "table",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(traefik_entrypoint_open_connections) by (entrypoint,method,protocol) !=0",
       "legendFormat": "{{entrypoint}} - {{method}} - {{protocol}}"
      }
     ]
    },
    {
     "title": "Requests (Status Code = 200)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total{code=\"200\"}[$__rate_interval])) by (entrypoint,protocol,method) !=0",
       "legendFormat": " {{entrypoint}} -- {{protocol}} -- {{method}}"
      },
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total{code=\"200\"}[$__rate_interval])) !=0",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Requests (Status Code != 200)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total{code!=\"200\"}[$__rate_interval])) by (entrypoint,protocol,method,code) !=0",
       "legendFormat": " {{code}} : {{entrypoint}}  -- {{protocol}} -- {{method}}"
      },
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total{code!=\"200\"}[$__rate_interval])) !=0",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 7, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total[$__rate_interval])) by (entrypoint,protocol,method) !=0",
       "legendFormat": "{{entrypoint}}  -- {{protocol}} -- {{method}}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(traefik_entrypoint_request_duration_seconds_sum) by (entrypoint,protocol,method) / sum(traefik_entrypoint_requests_total)",
       "legendFormat": " {{entrypoint}} -- {{protocol}} -- {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Routers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_router_requests_total[$__rate_interval])) by (router,protocol,method) !=0",
       "legendFormat": " {{router}} -- {{protocol}} -- {{method}}"
      },
      {
       "expr": "sum(increase(traefik_router_requests_total[$__rate_interval])) !=0",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(traefik_router_open_connections) by (router,method,protocol) !=0",
       "legendFormat": "{{router}} -- {{protocol}} -- {{method}}"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "table",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(traefik_router_open_connections) by (router,method,protocol) !=0",
       "legendFormat": "{{router}} - {{method}} - {{protocol}}"
      }
     ]
    },
    {
     "title": "Requests (Status Code = 200)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_router_requests_total{code=\"200\"}[$__rate_interval])) by (router,protocol,method) !=0",
       "legendFormat": " {{router}} -- {{protocol}} -- {{method}}"
      },
      {
       "expr": "sum(increase(traefik_router_requests_total{code=\"200\"}[$__rate_interval])) !=0",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Requests (Status Code != 200)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_router_requests_total{code!=\"200\"}[$__rate_interval])) by (router,protocol,method,code) !=0",
       "legendFormat": " {{code}} : {{router}} -- {{protocol}} -- {{method}}"
      },
      {
       "expr": "sum(increase(traefik_router_requests_total{code!=\"200\"}[$__rate_interval])) !=0",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 7, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(traefik_router_requests_total[$__rate_interval])) by (router,protocol,method) !=0",
       "legendFormat": "{{router}}  -- {{protocol}} -- {{method}}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(traefik_router_request_duration_seconds_sum) by (router,protocol,method) / sum(traefik_router_requests_total)",
       "legendFormat": " {{router}} -- {{protocol}} -- {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_total[$__rate_interval])) by (service,protocol,method) !=0",
       "legendFormat": " {{service}} -- {{protocol}} -- {{method}}"
      },
      {
       "expr": "sum(increase(traefik_service_requests_total[$__rate_interval])) !=0",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(traefik_service_open_connections) by (service,method,protocol) !=0",
       "legendFormat": "{{service}} -- {{protocol}} -- {{method}}"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "table",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(traefik_service_open_connections) by (service,method,protocol) !=0",
       "legendFormat": "{{service}} - {{method}} - {{protocol}}"
      }
     ]
    },
    {
     "title": "Requests (Status Code = 200)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_total{code=\"200\"}[$__rate_interval])) by (service,protocol,method) !=0",
       "legendFormat": " {{service}} -- {{protocol}} -- {{method}}"
      },
      {
       "expr": "sum(increase(traefik_service_requests_total{code=\"200\"}[$__rate_interval])) !=0",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Requests (Status Code != 200)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_total{code!=\"200\"}[$__rate_interval])) by (service,protocol,method,code) !=0",
       "legendFormat": " {{code}} : {{service}} -- {{protocol}} -- {{method}}"
      },
      {
       "expr": "sum(increase(traefik_service_requests_total{code!=\"200\"}[$__rate_interval])) !=0",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 7, "x": 12, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_total[$__rate_interval])) by (service,protocol,method,code) !=0",
       "legendFormat": "{{service}}  -- {{protocol}} -- {{method}}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(traefik_service_request_duration_seconds_sum) by (service,protocol,method) / sum(traefik_service_requests_total)",
       "legendFormat": " {{service}} -- {{protocol}} -- {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Entrypoint - $entrypoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "repeat": "entrypoint",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Open Connections",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(traefik_entrypoint_open_connections{entrypoint=\"$entrypoint\"}) !=0",
       "legendFormat": "Entrypoint"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 2, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(traefik_entrypoint_open_connections{entrypoint=\"$entrypoint\"}) by (entrypoint,method,protocol,code) !=0",
       "legendFormat": "{{protocol}} -- {{method}}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 7, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total{entrypoint=\"$entrypoint\"}[$__rate_interval])) by (entrypoint,protocol,method,code) !=0",
       "legendFormat": "{{protocol}} -- {{method}} -- {{code}}"
      },
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total{entrypoint=\"$entrypoint\"}[$__rate_interval])) !=0",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(traefik_entrypoint_request_duration_seconds_sum{entrypoint=\"$entrypoint\"}) by (entrypoint,protocol,method,code) / sum(traefik_entrypoint_requests_total)",
       "legendFormat": "{{protocol}} -- {{method}} -- {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Router - $router",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "repeat": "router",
   "collapsed": true,
   "panels": [
    {
     "title": "Open Connections",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(traefik_router_open_connections{router=\"$router\"}) !=0",
       "legendFormat": "Router"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 2, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(traefik_router_open_connections{router=\"$router\"}) by (router,method,protocol) !=0",
       "legendFormat": "{{protocol}} -- {{method}}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 7, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_router_requests_total{router=\"$router\"}[$__rate_interval])) by (router,protocol,method,code) !=0",
       "legendFormat": "{{protocol}} -- {{method}} -- {{code}}"
      },
      {
       "expr": "sum(increase(traefik_router_requests_total{router=\"$router\"}[$__rate_interval])) !=0",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 97 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(traefik_router_request_duration_seconds_sum{router=\"$router\"}) by (router,protocol,method,code) / sum(traefik_router_requests_total)",
       "legendFormat": "{{protocol}} -- {{method}} -- {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service - $service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "repeat": "service",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Open Connections",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(traefik_service_open_connections{service=\"$service\"}) !=0",
       "legendFormat": "Service"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 5, "x": 2, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(traefik_service_open_connections{service=\"$service\"}) by (service,method,protocol) !=0",
       "legendFormat": "{{protocol}} -- {{method}}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 7, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_total{service=\"$service\"}[$__rate_interval])) by (service,protocol,method,code) !=0",
       "legendFormat": "{{protocol}} -- {{method}} -- {{code}}"
      },
      {
       "expr": "sum(increase(traefik_service_requests_total{service=\"$service\"}[$__rate_interval])) !=0",
       "legendFormat": "TOTAL"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(traefik_service_request_duration_seconds_sum{service=\"$service\"}) by (service,protocol,method,code) / sum(traefik_service_requests_total)",
       "legendFormat": "{{protocol}} -- {{method}} -- {{code}}"
      }
     ]
    }
   ]
  }
 ]
}