{
 "title": "Ubiquity UniFi AP Dashboard [SNMP] (1486)",
 "description": "Ubiquiti Networks UniFi AP Dashboard",
 "tags": [
  "ubiquity",
  "unifi",
  "snmp",
  "prometheus",
  "network",
  "production"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host_old",
    "label": "UniFi AP:",
    "query": "SHOW TAG VALUES FROM \"snmp.UAP\" WITH KEY = \"agent_host\""
   },
   {
    "name": "radio_old",
    "label": "Radio",
    "query": "SHOW TAG VALUES FROM \"unifiVapTable\" WITH KEY = \"unifiVapRadio\" WHERE \"agent_host\" =~ /^$host$/"
   },
   {
    "name": "vap_old",
    "label": "vAP:",
    "query": "SHOW TAG VALUES FROM \"unifiVapTable\" WITH KEY = \"unifiVapName\" WHERE \"agent_host\" =~ /^$host$/"
   },
   {
    "name": "intf_old",
    "label": "Interface:",
    "query": "SHOW TAG VALUES FROM \"unifiIfTable\" WITH KEY = \"unifiIfName\" WHERE \"agent_host\" =~ /^$host$/"
   },
   {
    "name": "instance",
    "label": "AP",
    "query": {
     "query": "label_values(snmp_sysUpTime{module=\"unifi\"},instance)"
    }
   },
   {
    "name": "inft",
    "label": "Interface",
    "query": {
     "query": "label_values(snmp_unifiIfName{module=\"unifi\", instance=~\"$instance\"},unifiIfName)"
    }
   },
   {
    "name": "radio",
    "label": "Radio",
    "query": {
     "query": "label_values(snmp_unifiVapRadio{module=\"unifi\", instance=~\"$instance\"},unifiVapRadio)"
    }
   },
   {
    "name": "vap",
    "label": "VAP",
    "query": {
     "query": "label_values(snmp_unifiVapName{module=\"unifi\", instance=~\"$instance\"},unifiVapName)"
    }
   },
   {
    "name": "ssid",
    "label": "SSID",
    "query": {
     "query": "label_values(snmp_unifiVapEssId{module=\"unifi\", instance=~\"$instance\"},unifiVapEssId)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AP Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance,unifiApSystemModel) (snmp_unifiApSystemModel{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance,sysName) (snmp_sysName{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance,unifiApSystemVersion) (snmp_unifiApSystemVersion{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance,sysLocation) (snmp_sysLocation{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance,sysContact) (snmp_sysContact{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance,sysDescr) (snmp_sysDescr{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "* RSSI = Signal strength of connection to AP as measured by client.</br>\n* Signal Strength = Signal strength from client to AP as measured by AP.\n\n---\n\n* na = a/n/ac\n* ng = b/g/n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_sysUpTime{instance=~\"$instance\"}/100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Radios",
   "type": "table",
   "gridPos": { "h": 4, "w": 10, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "avg by (instance,unifiVapRadio,unifiVapExtChannel) (snmp_unifiVapExtChannel) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (instance,unifiVapRadio,unifiVapChannel) (snmp_unifiVapChannel)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (instance,unifiVapRadio,unifiVapTxPower) (snmp_unifiVapTxPower)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance,unifiVapRadio) (snmp_unifiVapRadio) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RF Channel Utilization",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(snmp_unifiRadioCuTotal{instance=~\"$instance\",unifiRadioRadio=~\"$radio\"})",
     "legendFormat": "{{instance}}: {{unifiRadioRadio}} ({{unifiRadioName}})"
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "snmp_laLoadInt{instance=~\"$instance\"}/100",
     "legendFormat": "{{instance}}: {{laNames}}"
    }
   ]
  },
  {
   "title": "Processor Load (1 Minute Average)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "snmp_hrProcessorLoad{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: {{hrDeviceIndex}}"
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "snmp_memBuffer{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: Buffer"
    },
    {
     "expr": "snmp_memCached{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: Cache"
    },
    {
     "expr": "snmp_memShared{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: Shared"
    },
    {
     "expr": "snmp_memTotalFree{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}: Free"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(avg by (instance) (snmp_memTotalReal) - avg by (instance) (snmp_memAvailReal) ) / avg by (instance) (snmp_memTotalReal) !=0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Stations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "snmp_unifiVapNumStations{instance=~\"$instance\",unifiVapRadio=~\"$radio\",unifiVapName=~\"$vap\",unifiVapEssId=~\"$ssid\"}",
     "legendFormat": "{{instance}}: {{unifiVapEssId}} ({{unifiVapRadio}}) ({{unifiVapName}})"
    }
   ]
  },
  {
   "title": "Other BSS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "snmp_unifiRadioOtherBss{instance=~\"$instance\",unifiRadioRadio=~\"$radio\"} !=0",
     "legendFormat": "{{instance}}: {{unifiRadioRadio}} ({{unifiRadioName}})"
    }
   ]
  },
  {
   "title": "CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Load ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "snmp_laLoadInt{instance=~\"$instance\"} / 100",
       "legendFormat": "{{instance}}: {{laNames}}"
      }
     ]
    },
    {
     "title": "CPU Load (1 Minute Average)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "snmp_hrProcessorLoad{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}: {{hrDeviceIndex}}"
      }
     ]
    },
    {
     "title": "Memory Distribution",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "expr": "snmp_memBuffer{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}: Buffer"
      },
      {
       "expr": "snmp_memCached{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}: Cache"
      },
      {
       "expr": "snmp_memShared{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}: Shared"
      },
      {
       "expr": "snmp_memTotalFree{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}: Free"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(avg by (instance) (snmp_memTotalReal) - avg by (instance) (snmp_memAvailReal) ) / avg by (instance) (snmp_memTotalReal) !=0",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Wifi",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "WiFi (802.11) Channel Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "snmp_unifiRadioCuSelfRx{instance=~\"$instance\",unifiRadioRadio=~\"$radio\"}",
       "legendFormat": "In - {{instance}}: {{unifiRadioRadio}} ({{unifiRadioName}})"
      },
      {
       "expr": "snmp_unifiRadioCuSelfTx{instance=~\"$instance\",unifiRadioRadio=~\"$radio\"}",
       "legendFormat": "Out - {{instance}}: {{unifiRadioRadio}} ({{unifiRadioName}})"
      },
      {
       "expr": "snmp_unifiRadioCuTotal{instance=~\"$instance\",unifiRadioRadio=~\"$radio\"}",
       "legendFormat": "Busy - {{instance}}: {{unifiRadioRadio}} ({{unifiRadioName}})"
      }
     ]
    },
    {
     "title": "WiFi (802.11) Traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(snmp_unifiVapRxBytes{instance=~\"$instance\", unifiVapRadio=~\"$radio\", unifiVapEssId=~\"$ssid\"}[$__rate_interval]) * 8",
       "legendFormat": "In - {{instance}}: {{unifiVapEssId}} ({{unifiVapRadio}}) ({{unifiVapName}})"
      },
      {
       "expr": "irate(snmp_unifiVapTxBytes{instance=~\"$instance\",unifiVapRadio=~\"$radio\",unifiVapEssId=~\"$ssid\"}[$__rate_interval]) * -8",
       "legendFormat": "Out - {{instance}}: {{unifiVapEssId}} ({{unifiVapRadio}}) ({{unifiVapName}})"
      }
     ]
    },
    {
     "title": "WiFi (802.11) Traffic Distribution",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(snmp_unifiVapRxPackets{instance=~\"$instance\", unifiVapRadio=~\"$radio\", unifiVapEssId=~\"$ssid\"}[$__rate_interval])",
       "legendFormat": "In - {{instance}}: {{unifiVapEssId}} ({{unifiVapRadio}}) ({{unifiVapName}})"
      },
      {
       "expr": "irate(snmp_unifiVapTxPackets{instance=~\"$instance\", unifiVapRadio=~\"$radio\", unifiVapEssId=~\"$ssid\"}[$__rate_interval])",
       "legendFormat": "Out - {{instance}}: {{unifiVapEssId}} ({{unifiVapRadio}}) ({{unifiVapName}})"
      }
     ]
    },
    {
     "title": "WiFi (802.11) Drops/Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(snmp_unifiVapRxDropped{instance=~\"$instance\", unifiVapRadio=~\"$radio\", unifiVapEssId=~\"$ssid\"}[$__rate_interval])",
       "legendFormat": "Dropped - In - {{instance}}: {{unifiVapEssId}} ({{unifiVapRadio}}) ({{unifiVapName}})"
      },
      {
       "expr": "irate(snmp_unifiVapTxDropped{instance=~\"$instance\", unifiVapRadio=~\"$radio\", unifiVapEssId=~\"$ssid\"}[$__rate_interval]) *-1",
       "legendFormat": "Dropped - Out - {{instance}}: {{unifiVapEssId}} ({{unifiVapRadio}}) ({{unifiVapName}})"
      },
      {
       "expr": "irate(snmp_unifiVapRxErrors{instance=~\"$instance\", unifiVapRadio=~\"$radio\", unifiVapEssId=~\"$ssid\"}[$__rate_interval])",
       "legendFormat": "Errors - In - {{instance}}: {{unifiVapEssId}} ({{unifiVapRadio}}) ({{unifiVapName}})"
      },
      {
       "expr": "irate(snmp_unifiVapTxErrors{instance=~\"$instance\", unifiVapRadio=~\"$radio\", unifiVapEssId=~\"$ssid\"}[$__rate_interval]) *-1",
       "legendFormat": "Errors - Out - {{instance}}: {{unifiVapEssId}} ({{unifiVapRadio}}) ({{unifiVapName}})"
      },
      {
       "expr": "irate(snmp_unifiVapRxCrypts{instance=~\"$instance\", unifiVapRadio=~\"$radio\", unifiVapEssId=~\"$ssid\"}[$__rate_interval])",
       "legendFormat": "Bad Crypts - In - {{instance}}: {{unifiVapEssId}} ({{unifiVapRadio}}) ({{unifiVapName}})"
      },
      {
       "expr": "irate(snmp_unifiVapRxFrags{instance=~\"$instance\", unifiVapRadio=~\"$radio\", unifiVapEssId=~\"$ssid\"}[$__rate_interval])",
       "legendFormat": "Bad Frags - In - {{instance}}: {{unifiVapEssId}} ({{unifiVapRadio}}) ({{unifiVapName}})"
      },
      {
       "expr": "irate(snmp_unifiVapTxRetries{instance=~\"$instance\", unifiVapRadio=~\"$radio\", unifiVapEssId=~\"$ssid\"}[$__rate_interval]) *-1",
       "legendFormat": "Retries - Out - {{instance}}: {{unifiVapEssId}} ({{unifiVapRadio}}) ({{unifiVapName}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Ethernet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ethernet (802.3) Traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(snmp_unifiIfRxBytes{instance=~\"$instance\",unifiIfName=~\"$inft\"}[$__rate_interval]) *8",
       "legendFormat": "In - {{instance}}: {{unifiIfName}}"
      },
      {
       "expr": "irate(snmp_unifiIfTxBytes{instance=~\"$instance\",unifiIfName=~\"$inft\"}[$__rate_interval]) *-8",
       "legendFormat": "Out - {{instance}}: {{unifiIfName}}"
      }
     ]
    },
    {
     "title": "Ethernet (802.3) Traffic Distribution",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(snmp_unifiIfRxPackets{instance=~\"$instance\",unifiIfName=~\"$inft\"}[$__rate_interval])",
       "legendFormat": "In - {{instance}}: {{unifiIfName}}"
      },
      {
       "expr": "irate(snmp_unifiIfRxPackets{instance=~\"$instance\",unifiIfName=~\"$inft\"}[$__rate_interval]) * -1",
       "legendFormat": "Out - {{instance}}: {{unifiIfName}}"
      },
      {
       "expr": "irate(snmp_unifiIfRxMulticast{instance=~\"$instance\",unifiIfName=~\"$inft\"}[$__rate_interval])",
       "legendFormat": "Multicast In - {{instance}}: {{unifiIfName}}"
      }
     ]
    },
    {
     "title": "Ethernet (802.3) Drops/Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(snmp_unifiIfRxDropped{instance=~\"$instance\", unifiIfName=~\"$inft\"}[$__rate_interval])",
       "legendFormat": "Drop - In - {{instance}}: {{unifiIfName}}"
      },
      {
       "expr": "irate(snmp_unifiIfTxDropped{instance=~\"$instance\", unifiIfName=~\"$inft\"}[$__rate_interval]) * -1",
       "legendFormat": "Drop - Out - {{instance}}: {{unifiIfName}}"
      },
      {
       "expr": "irate(snmp_unifiIfRxError{instance=~\"$instance\", unifiIfName=~\"$inft\"}[$__rate_interval])",
       "legendFormat": "Error - In - {{instance}}: {{unifiIfName}}"
      },
      {
       "expr": "irate(snmp_unifiIfTxError{instance=~\"$instance\", unifiIfName=~\"$inft\"}[$__rate_interval])",
       "legendFormat": "Error - Out - {{instance}}: {{unifiIfName}}"
      }
     ]
    },
    {
     "title": "All Interface Drops/Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "snmp_ifInDiscards{instance=~\"$instance\"} != 0",
       "legendFormat": "Drop - In - {{instance}}: {{ifDescr}}"
      },
      {
       "expr": "(snmp_ifOutDiscards{instance=~\"$instance\"} != 0)* -1",
       "legendFormat": "Drop - Out - {{instance}}: {{ifDescr}}"
      },
      {
       "expr": "snmp_ifInErrors{instance=~\"$instance\"} !=0",
       "legendFormat": "Errors - In - {{instance}}: {{ifDescr}}"
      },
      {
       "expr": "(snmp_ifOutErrors{instance=~\"$instance\"} !=0)* -1",
       "legendFormat": "Errors - Out - {{instance}}: {{ifDescr}}"
      },
      {
       "expr": "snmp_ifInUnknownProtos{instance=~\"$instance\"} !=0",
       "legendFormat": "Unknown - In - {{instance}}: {{ifDescr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ICMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "ICMP Summary",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(snmp_icmpStatsInMsgs{instance=~\"$instance\",icmpStatsIPVersion=\"1\"}[$__interval])",
       "legendFormat": "{{instance}} - IPv4:Msg:In"
      },
      {
       "expr": "irate(snmp_icmpStatsOutMsgs{instance=~\"$instance\",icmpStatsIPVersion=\"1\"}[$__interval])*-1",
       "legendFormat": "{{instance}} - IPv4:Msg:Out"
      },
      {
       "expr": "irate(snmp_icmpStatsInErrors{instance=~\"$instance\",icmpStatsIPVersion=\"1\"}[$__interval])",
       "legendFormat": "{{instance}} - IPv4:Error:In"
      },
      {
       "expr": "irate(snmp_icmpStatsOutErrors{instance=~\"$instance\",icmpStatsIPVersion=\"1\"}[$__interval]) *-1",
       "legendFormat": "{{instance}} - IPv4:Error:Out"
      },
      {
       "expr": "irate(snmp_icmpStatsInMsgs{instance=~\"$instance\",icmpStatsIPVersion=\"2\"}[$__interval])",
       "legendFormat": "{{instance}} - IPv6:Msg:In"
      },
      {
       "expr": "irate(snmp_icmpStatsOutMsgs{instance=~\"$instance\",icmpStatsIPVersion=\"2\"}[$__interval])*-1",
       "legendFormat": "{{instance}} - IPv6:Msg:Out"
      },
      {
       "expr": "irate(snmp_icmpStatsInErrors{instance=~\"$instance\",icmpStatsIPVersion=\"2\"}[$__interval])",
       "legendFormat": "{{instance}} - IPv6:Error:In"
      },
      {
       "expr": "irate(snmp_icmpStatsOutErrors{instance=~\"$instance\",icmpStatsIPVersion=\"2\"}[$__interval]) *-1",
       "legendFormat": "{{instance}} - IPv6:Error:Out"
      }
     ]
    },
    {
     "title": "ICMP Message Type",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "$tag_index:$col",
       "expr": "irate(snmp_icmpMsgStatsInPkts{instance=~\"$instance\",icmpMsgStatsIPVersion=\"1\"}[$__interval])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "index" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} - IPv4:{{icmpMsgStatsType}}:In",
       "measurement": "icmpMsgStatsTable",
       "select": [
        [
         { "params": [ "icmpMsgStatsInPkts" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "In" ], "type": "alias" }
        ],
        [
         { "params": [ "icmpMsgStatsOutPkts" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ " *-1" ], "type": "math" },
         { "params": [ "Out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "expr": "irate(snmp_icmpMsgStatsOutPkts{instance=~\"$instance\",icmpMsgStatsIPVersion=\"1\"}[$__interval])*-1",
       "legendFormat": "{{instance}} - IPv4:{{icmpMsgStatsType}}:Out"
      },
      {
       "expr": "irate(snmp_icmpMsgStatsInPkts{instance=~\"$instance\",icmpMsgStatsIPVersion=\"2\"}[$__interval])",
       "legendFormat": "{{instance}} - IPv6:{{icmpMsgStatsType}}:In"
      },
      {
       "expr": "irate(snmp_icmpMsgStatsOutPkts{instance=~\"$instance\",icmpMsgStatsIPVersion=\"2\"}[$__interval])*-1",
       "legendFormat": "{{instance}} - IPv6:{{icmpMsgStatsType}}:Out"
      }
     ]
    }
   ]
  },
  {
   "title": "SNMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "SNMP Messages (/min)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$col",
       "expr": "irate(snmp_snmpInPkts{instance=~\"$instance\"}[1m])",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{instance}} - Msgs:In",
       "measurement": "snmp",
       "select": [
        [
         { "params": [ "snmpInPkts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" },
         { "params": [ "Msgs:In" ], "type": "alias" }
        ],
        [
         { "params": [ "snmpOutPkts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" },
         { "params": [ " *-1" ], "type": "math" },
         { "params": [ "Msgs:Out" ], "type": "alias" }
        ],
        [
         { "params": [ "snmpInGetResponses" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" },
         { "params": [ "GetResp:In" ], "type": "alias" }
        ],
        [
         { "params": [ "snmpOutGetResponses" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" },
         { "params": [ " *-1" ], "type": "math" },
         { "params": [ "GetResp:Out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "expr": "irate(snmp_snmpOutPkts{instance=~\"$instance\"}[1m]) *-1",
       "legendFormat": "{{instance}} - Msgs:Out"
      },
      {
       "expr": "irate(snmp_snmpInGetResponses{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} - GetResp:In"
      },
      {
       "expr": "irate(snmp_snmpOutGetResponses{instance=~\"$instance\"}[1m]) * -1",
       "legendFormat": "{{instance}} - GetResp:Out"
      },
      {
       "expr": "irate(snmpInGetRequests{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} - GetReq:In"
      },
      {
       "expr": "irate(snmpOutGetRequests{instance=~\"$instance\"}[1m]) *-1",
       "legendFormat": "{{instance}} - GetReq:Out"
      },
      {
       "expr": "irate(snmpInGetNexts{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} - GetNext:In"
      },
      {
       "expr": "irate(snmpOutGetNexts{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} - GetNext:Out"
      }
     ]
    },
    {
     "title": "SNMP Objects Retrieved (/min)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "irate(snmp_snmpInTotalReqVars{instance=~\"$instance\"}[1m])",
       "legendFormat": "{{instance}} - Objects"
      }
     ]
    },
    {
     "title": "SNMP Exporter - Scrape Duration by Instance",
     "type": "timeseries",
     "description": "Sum of scrape durations for a specific instance.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (instance) (snmp_snmp_scrape_duration_seconds{instance=~\"$instance\"})",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "SNMP Exporter - Walk Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(snmp_snmp_scrape_walk_duration_seconds{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "SNMP Exporter - PDUs returned",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(snmp_snmp_scrape_pdus_returned{instance=~\"$instance\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}