{
 "title": "UniFi-Poller (GitHub)",
 "description": "UniFi Poller v2.0.1 Displays detailed information for wireless access points in a UniFi network using Prometheus. Official dashboards sourced from Unifi-poller GitHub repo (they are also available from Grafana's dashboard repo).",
 "tags": [
  "unifi",
  "uap",
  "unifi-poller",
  "prometheus",
  "network",
  "production"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Controller",
    "query": "label_values(unifipoller_device_info{type=\"uap\"},source)"
   },
   {
    "name": "Site",
    "query": "label_values(unifipoller_device_info{source=~\"$Controller\", type=\"uap\"},site_name)"
   },
   {
    "name": "AP",
    "label": "UniFi AP",
    "query": "label_values(unifipoller_device_info{site_name=~\"$Site\", type=~\"uap|udm\",model!=\"UDMPRO\"},name)"
   },
   { "name": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m,1h" },
   {
    "name": "Switch",
    "label": "Switch (Client Insights)",
    "query": {
     "query": "label_values(unifipoller_client_uptime_seconds{site_name=~\"$Site\"},sw_name)"
    }
   },
   {
    "name": "Wireless",
    "label": "Wireless (Client Insights)",
    "query": {
     "query": "label_values(unifipoller_client_uptime_seconds{site_name=~\"$Site\", ap_name=~\"$AP\", wired=\"false\"},name)"
    }
   },
   {
    "name": "Wired",
    "label": "Wired (Client Insights)",
    "query": {
     "query": "label_values(unifipoller_client_uptime_seconds{site_name=~\"$Site\", sw_name=~\"$Switch\", wired=\"true\"},name)"
    }
   },
   { "name": "Identifier", "label": "Identifier (Client Insights)", "query": "name, name\\,mac" },
   {
    "name": "Subsystem",
    "label": "Subsystem (Network Sites)",
    "query": {
     "query": "label_values(unifipoller_site_transmit_rate_bytes,subsystem)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network Sites (Github and/or 11311)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "Each site contains 5 subsystems: wan, lan, wlan, www, vpn. Each subsystem contains data specific to that system. \nAll subsystems except vpn have data rate. VPN has data transfer though.\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data Transfer",
   "type": "timeseries",
   "description": "Shows data transfer for each subsystem on the site. RX is on the negative axis.",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "unifipoller_site_transmit_rate_bytes{site_name=~\"$Site\",subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} Tx"
    },
    {
     "expr": "unifipoller_site_receive_rate_bytes{site_name=~\"$Site\",subsystem=~\"$Subsystem\"}",
     "legendFormat": "{{subsystem}} Rx"
    }
   ]
  },
  {
   "title": "UAP Insights (Github and/or 11314)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Information",
     "type": "text",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
     "options": {
      "content": "RSSI (Received Signal Strength Indicator) = Signal strength of connection to AP as measured by client.</br>\n<br/>\nSignal Strength = Signal strength from client to AP as measured by AP.<br/>\n<br/>\nBoth are usually measured in dBm (decibels per milliwatt). This is a logarithmic scale. \nThe closer to 0 the stronger the signal. A change of 3 dBm is approx. half the signal strength, change by 10 dBm is approx. 10x the strength.\n-30dBm is really good; -80dBm is pretty bad."
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Clients / Channel",
     "type": "piechart",
     "description": "Visualize wireless channel usage w/ wired client counts.",
     "gridPos": { "h": 11, "w": 6, "x": 4, "y": 10 },
     "format": "short",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (channel) (unifipoller_client_roam_count_total{site_name=~\"$Site\", ap_name=~\"$AP\"})\n",
       "legendFormat": "Ch {{channel}}"
      }
     ]
    },
    {
     "title": "Clients / AP Radio",
     "type": "piechart",
     "description": "Visualize how many clients are connected to which radios/APs.",
     "gridPos": { "h": 11, "w": 7, "x": 10, "y": 10 },
     "format": "short",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (radio_desc) (unifipoller_client_uptime_seconds{site_name=~\"$Site\", ap_name=~\"$AP\"})",
       "legendFormat": "{{radio_desc}}"
      }
     ]
    },
    {
     "title": "Client / MAC OUI",
     "type": "piechart",
     "description": "This shows an OUI breakdown from Unifi's perspective.",
     "gridPos": { "h": 11, "w": 7, "x": 17, "y": 10 },
     "format": "short",
     "valueName": "current",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (oui) (unifipoller_client_uptime_seconds{site_name=~\"$Site\", ap_name=~\"$AP\"})",
       "legendFormat": "e {{oui}}"
      }
     ]
    },
    {
     "title": "Users",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unifipoller_device_stations{site_name=~\"$Site\", name=~\"$AP\", station_type=\"user\"})"
      }
     ]
    },
    {
     "title": "Guests",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unifipoller_device_stations{site_name=~\"$Site\", name=~\"$AP\", station_type=\"guest\"})"
      }
     ]
    },
    {
     "title": "Access Point Details",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum by (ip,mac,model,name,serial,site_name,type,version) (unifipoller_device_info{site_name=~\"$Site\", name=~\"$AP\"})"
      },
      {
       "expr": "sum by (ip,mac,model,name,serial,site_name,type,version) (unifipoller_device_uptime_seconds{site_name=~\"$Site\", name=~\"$AP\"})"
      },
      {
       "expr": "sum by (ip,mac,model,name,serial,site_name,type,version) (unifipoller_device_bytes_total{site_name=~\"$Site\", name=~\"$AP\"})"
      }
     ]
    },
    {
     "title": "Networks / UAP",
     "type": "table",
     "description": "The counters in this table represent uptime totals and do not change with the time range selector. ",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_ccq_ratio{site_name=~\"$Site\", name=~\"$AP\"})"
      },
      {
       "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_average_client_signal{site_name=~\"$Site\", name=~\"$AP\"})"
      },
      {
       "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_receive_dropped_total{site_name=~\"$Site\", name=~\"$AP\"}) "
      },
      {
       "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_transmit_dropped_total{site_name=~\"$Site\", name=~\"$AP\"}) "
      },
      {
       "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_transmit_bytes_total{site_name=~\"$Site\", name=~\"$AP\"}) "
      },
      {
       "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_receive_bytes_total{site_name=~\"$Site\", name=~\"$AP\"}) "
      },
      {
       "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_receive_packets_total{site_name=~\"$Site\", name=~\"$AP\"}) "
      },
      {
       "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_transmit_packets_total{site_name=~\"$Site\", name=~\"$AP\"}) "
      }
     ]
    },
    {
     "title": "UAP CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "unifipoller_device_cpu_utilization_ratio{site_name=~\"$Site\",name=~\"$AP\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "UAP Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "unifipoller_device_memory_utilization_ratio{site_name=~\"$Site\",name=~\"$AP\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "UAP Load Average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "unifipoller_device_load_average_1{site_name=~\"$Site\",name=~\"$AP\"}",
       "legendFormat": "{{name}} load1"
      },
      {
       "expr": "unifipoller_device_load_average_15{site_name=~\"$Site\",name=~\"$AP\"}",
       "legendFormat": "{{name}} load15"
      }
     ]
    },
    {
     "title": "Clients / UAP",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (name,station_type) (unifipoller_device_stations{site_name=~\"$Site\",name=~\"$AP\"}) !=0",
       "legendFormat": "{{name}} users ({{station_type}})"
      }
     ]
    },
    {
     "title": "Wireless Traffic / Vendor",
     "type": "timeseries",
     "description": "Devices TX / RX bytes per second grouped by OUI. RX on negative axis.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum (unifipoller_client_receive_rate_bytes{site_name=~\"$Site\",ap_name=~\"$AP\"}) by (oui)",
       "legendFormat": "{{oui}} Rx"
      },
      {
       "expr": "sum (unifipoller_client_transmit_rate_bytes{site_name=~\"$Site\",ap_name=~\"$AP\"}) by (oui)",
       "legendFormat": "{{oui}} Tx"
      }
     ]
    },
    {
     "title": "Users & Guests / Radio Band",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (unifipoller_device_radio_stations{radio=\"ng\", site_name=~\"$Site\",name=~\"$AP\", station_type=\"guest\"}) by  (radio,name)",
       "legendFormat": "{{name}} Guests 2,4GHz"
      },
      {
       "expr": "sum (unifipoller_device_radio_stations{radio=\"ng\", site_name=~\"$Site\",name=~\"$AP\", station_type=\"user\"}) by (radio,name)",
       "legendFormat": "{{name}} Users  2.4GHz"
      },
      {
       "expr": "sum (unifipoller_device_radio_stations{radio=\"na\", site_name=~\"$Site\",name=~\"$AP\", station_type=\"user\"}) by (radio,name)",
       "legendFormat": "{{name}} Users 5GHz"
      },
      {
       "expr": "sum (unifipoller_device_radio_stations{radio=\"na\", site_name=~\"$Site\",name=~\"$AP\", station_type=\"guest\"}) by (radio,name)",
       "legendFormat": "{{name}} Guests 5GHz"
      }
     ]
    },
    {
     "title": "Average AP Client Signal",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "unifipoller_device_vap_average_client_signal{name=~\"$AP\"}",
       "legendFormat": "{{name}} {{vap_name}} {{radio}}"
      }
     ]
    },
    {
     "title": "Average AP Client RSSI",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      {
       "expr": "avg(unifipoller_client_rssi_db{ap_name=~\"$AP\"}) by (ap_name, radio_name)",
       "legendFormat": "{{ap_name}}  {{radio_name}}"
      }
     ]
    },
    {
     "title": "UAP Latency",
     "type": "timeseries",
     "description": "Visualize packet errors (several types)  per second in the 5GHz band.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum (unifipoller_device_vap_receive_latency_average_seconds{site_name=~\"$Site\",name=~\"$AP\"}) by (name) !=0",
       "legendFormat": "{{name}} Avg Latency Rx"
      },
      {
       "expr": "sum (unifipoller_device_vap_transmit_latency_average_seconds{site_name=~\"$Site\",name=~\"$AP\"}) by (name) !=0",
       "legendFormat": "{{name}} Avg Latency Tx"
      },
      {
       "expr": "sum (unifipoller_device_vap_receive_latency_maximum_seconds{site_name=~\"$Site\",name=~\"$AP\"}) by (name) !=0",
       "legendFormat": "{{name}} Max Latency Rx"
      },
      {
       "expr": "sum (unifipoller_device_vap_transmit_latency_maximum_seconds{site_name=~\"$Site\",name=~\"$AP\"}) by (name) !=0",
       "legendFormat": "{{name}} Max Latency Tx"
      }
     ]
    },
    {
     "title": "5 GHz Client Connection Quality",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "unifipoller_device_vap_ccq_ratio{site_name=~\"$Site\",name=~\"$AP\", radio=\"na\"}",
       "legendFormat": "{{name}} {{vap_name}}"
      }
     ]
    },
    {
     "title": "2.4 GHz Client Connection Quality",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "unifipoller_device_vap_ccq_ratio{site_name=~\"$Site\",name=~\"$AP\", radio=\"ng\"}",
       "legendFormat": "{{name}} {{vap_name}}"
      }
     ]
    },
    {
     "title": "5 GHz Channel Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "unifipoller_device_radio_channel_utilization_receive_ratio{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}",
       "legendFormat": "{{name}} Rx"
      },
      {
       "expr": "unifipoller_device_radio_channel_utilization_transmit_ratio{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}",
       "legendFormat": "{{name}} Tx"
      }
     ]
    },
    {
     "title": "2.4 GHz Channel Utilization",
     "type": "timeseries",
     "description": "Displays 2.4GHz usage.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "unifipoller_device_radio_channel_utilization_receive_ratio{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}",
       "legendFormat": "{{name}} {{radio}} Rx"
      },
      {
       "expr": "unifipoller_device_radio_channel_utilization_transmit_ratio{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}",
       "legendFormat": "{{name}} {{radio}} Tx"
      }
     ]
    },
    {
     "title": "5 GHz Traffic",
     "type": "timeseries",
     "description": "RX is on the negative Axis.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_bytes_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[5m])) by (name)",
       "legendFormat": "{{name}} Tx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_bytes_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[5m])) by (name)",
       "legendFormat": "{{name}}  Rx"
      }
     ]
    },
    {
     "title": "2.4 GHz Traffic",
     "type": "timeseries",
     "description": "RX is on the negative Axis.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_bytes_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[5m])) by (name)",
       "legendFormat": "{{name}} Tx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_bytes_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[5m])) by (name)",
       "legendFormat": "{{name}} Rx"
      }
     ]
    },
    {
     "title": "5 GHz Packets",
     "type": "timeseries",
     "description": "PPS on the na band. In is on the negative Axis.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_packets_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Out"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_packets_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} In"
      }
     ]
    },
    {
     "title": "2.4 GHz Packets",
     "type": "timeseries",
     "description": "PPS on the ng band calculated in 30 second buckets. In is on the negative Axis.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_packets_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Out"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_packets_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} In"
      }
     ]
    },
    {
     "title": "5 GHz Drops/Errors",
     "type": "timeseries",
     "description": "Visualize packet errors (several types)  per second in the 5GHz band.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_dropped_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name) !=0",
       "legendFormat": "{{name}} Drops Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_dropped_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name) !=0",
       "legendFormat": "{{name}} Drops Tx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_errors_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name) !=0",
       "legendFormat": "{{name}} Errors Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_errors_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name) !=0",
       "legendFormat": "{{name}} Errors Tx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_crypts_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Crypts Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_frags_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Frags Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_nwids_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Nwids Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_retries_total{radio=\"na\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Retries Tx"
      }
     ]
    },
    {
     "title": "2.4 GHz Drops/Errors",
     "type": "timeseries",
     "description": "In is on the negative axis.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_dropped_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name) !=0",
       "legendFormat": "{{name}} Drops Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_dropped_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name) !=0",
       "legendFormat": "{{name}} Drops Tx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_errors_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name) !=0",
       "legendFormat": "{{name}} Errors Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_errors_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name) !=0",
       "legendFormat": "{{name}} Errors Tx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_crypts_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Crypts Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_frags_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Frags Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_nwids_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Nwids Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_retries_total{radio=\"ng\",site_name=~\"$Site\",name=~\"$AP\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Retries Tx"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Insights (Github and/or 11315)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Wireless Devices",
   "type": "table",
   "description": "This table represents current (latest) data.\nBytes columns are lifetime totals.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unifipoller_client_receive_bytes_total{wired!=\"true\", site_name=~\"$Site\", name=~\"$Wireless\", wired=\"false\"})"
    },
    {
     "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unifipoller_client_transmit_bytes_total{wired!=\"true\",site_name=~\"$Site\", name=~\"$Wireless\", wired=\"false\"})"
    },
    {
     "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unifipoller_client_uptime_seconds{wired!=\"true\",site_name=~\"$Site\", name=~\"$Wireless\", wired=\"false\"})"
    }
   ]
  },
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 24 },
   "options": {
    "content": "RSSI (Received Signal Strength Indicator) = Signal strength of connection to AP as measured by client.</br>\n<br/>\nSignal Strength = Signal strength from client to AP as measured by AP.<br/>\n<br/>\nBoth are usually measured in dBm (decibels per milliwatt). This is a logarithmic scale. \nThe closer to 0 the stronger the signal. A change of 3 dBm is approx. half the signal strength, change by 10 dBm is approx. 10x the strength.\n-30dBm is really good; -80dBm is pretty bad."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Wired Devices",
   "type": "table",
   "description": "This table represents current (latest) data.\nBytes columns are lifetime totals.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "sum by (ap_name,ip,mac,name,network,oui,site_name,source,sw_port) (\n     unifipoller_client_uptime_seconds{wired=\"true\", site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\", wired=\"true\"})"
    },
    {
     "expr": "sum by (ap_name,ip,mac,name,network,oui,site_name,source,sw_port) (\n     unifipoller_client_receive_bytes_total{wired=\"true\", site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\", wired=\"true\"})"
    },
    {
     "expr": "sum by (ap_name,ip,mac,name,network,oui,site_name,source,sw_port) (\n     unifipoller_client_transmit_bytes_total{wired=\"true\", site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\", wired=\"true\"})"
    }
   ]
  },
  {
   "title": "Clients / Channel",
   "type": "piechart",
   "description": "Visualize wireless channel usage w/ wired client counts.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 32 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (hostname) (unifipoller_client_uptime_seconds{site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\",wired=\"true\"})",
     "legendFormat": "Wired"
    },
    {
     "expr": "count by (channel,radio_proto) (unifipoller_client_roam_count_total{site_name=~\"$Site\", name=~\"$Wireless\", ap_name=~\"$AP\",wired=\"false\"})",
     "legendFormat": "Channel {{channel}} ({{radio_proto}})"
    }
   ]
  },
  {
   "title": "Clients / AP Radio",
   "type": "piechart",
   "description": "Visualize how many clients are connected to which radios/APs.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 32 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (radio_proto) (unifipoller_client_roam_count_total{site_name=~\"$Site\", name=~\"$Wireless\", ap_name=~\"$AP\"})",
     "legendFormat": "{{radio_proto}}"
    }
   ]
  },
  {
   "title": "Client MAC OUI Breakdown",
   "type": "piechart",
   "description": "This shows an OUI breakdown from Unifi's perspective. e = wired, w = wireless",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 32 },
   "format": "short",
   "valueName": "current",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (oui) (unifipoller_client_uptime_seconds{site_name=~\"$Site\", name=~\"$Wireless\", ap_name=~\"$AP\",wired=\"false\"})",
     "legendFormat": " w {{oui}}"
    },
    {
     "expr": "count by (oui) (+unifipoller_client_uptime_seconds{site_name=~\"$Site\", name=~\"$Wired\", sw_name=~\"$Switch\",wired=\"true\"})",
     "legendFormat": "e  {{oui}}"
    }
   ]
  },
  {
   "title": "UAP Bandwidth / Wireless Devices",
   "type": "timeseries",
   "description": "Bandwidth usage per wireless devices as reported by the UAPs. Rx is on the negative axis. Does not include amazon devices.",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_transmit_bytes_total{name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\",wired=\"false\"}[$__interval])) !=0",
     "legendFormat": "{{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_receive_bytes_total{name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\",wired=\"false\"}[$__interval])) !=0",
     "legendFormat": "{{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Switch Bandwidth / Wired Devices",
   "type": "timeseries",
   "description": "Wired TX / RX bytes per second (calculated in 30 second buckets). Rx is on the negative axis. Does not include amazon and camera devices. Unaffected by the AP setting.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_transmit_bytes_total{name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\",wired=\"true\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_receive_bytes_total{name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\",wired=\"true\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Client Bandwidth: Amazon Devices",
   "type": "timeseries",
   "description": "Amazon Devices TX / RX bytes per second. Rx is on the negative axis. My home network has a ton of Amazon devices, so I broke them out separately. If you don't have Amazon devices, or they have different names, you can edit the query to use a different name. e = wired, w = wireless",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_transmit_bytes_total{oui=~\".*[aA]mazon.*\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\",wired=\"false\"}[$__interval])) !=0",
     "legendFormat": "w {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_receive_bytes_total{oui=~\".*[aA]mazon.*\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\",wired=\"false\"}[$__interval])) !=0",
     "legendFormat": "w {{name}} {{mac}} Rx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_transmit_bytes_total{oui=~\".*[aA]mazon.*\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\",wired=\"true\"}[$__interval])) !=0",
     "legendFormat": "e {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_receive_bytes_total{oui=~\".*[aA]mazon.*\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\",wired=\"true\"}[$__interval])) !=0",
     "legendFormat": "e {{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Client Bandwidth: Apple Devices",
   "type": "timeseries",
   "description": "Amazon Devices TX / RX bytes per second. Rx is on the negative axis. My home network has a ton of Amazon devices, so I broke them out separately. If you don't have Amazon devices, or they have different names, you can edit the query to use a different name. e = wired, w = wireless",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_transmit_bytes_total{oui=~\".*[aA]pple.*\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\",wired=\"false\"}[$__interval])) !=0",
     "legendFormat": "w {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_receive_bytes_total{oui=~\".*[aA]pple.*\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\",wired=\"false\"}[$__interval])) !=0",
     "legendFormat": "w {{name}} {{mac}} Rx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_transmit_bytes_total{oui=~\".*[aA]pple.*\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\",wired=\"true\"}[$__interval])) !=0",
     "legendFormat": "e {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_receive_bytes_total{oui=~\".*[aA]pple.*\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\",wired=\"true\"}[$__interval])) !=0",
     "legendFormat": "e {{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Client Bandwidth: ESPXX Devices",
   "type": "timeseries",
   "description": "Amazon Devices TX / RX bytes per second. Rx is on the negative axis. My home network has a ton of Amazon devices, so I broke them out separately. If you don't have Amazon devices, or they have different names, you can edit the query to use a different name. e = wired, w = wireless",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_transmit_bytes_total{oui=~\".*[eE]spre.*\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\",wired=\"false\"}[$__interval])) !=0",
     "legendFormat": "w {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_receive_bytes_total{oui=~\".*[eE]spre.*\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\",wired=\"false\"}[$__interval])) !=0",
     "legendFormat": "w {{name}} {{mac}} Rx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_transmit_bytes_total{oui=~\".*[eE]spre.*\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\",wired=\"true\"}[$__interval])) !=0",
     "legendFormat": "e {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_receive_bytes_total{oui=~\".*[eE]spre.*\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\",wired=\"true\"}[$__interval])) !=0",
     "legendFormat": "e {{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Client Bandwidth: Google Devices",
   "type": "timeseries",
   "description": "Amazon Devices TX / RX bytes per second. Rx is on the negative axis. My home network has a ton of Amazon devices, so I broke them out separately. If you don't have Amazon devices, or they have different names, you can edit the query to use a different name. e = wired, w = wireless",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by ($Identifier,oui) (rate(unifipoller_client_transmit_bytes_total{oui=~\".*[gG]oog.*\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\",wired=\"false\"}[$__interval])) !=0",
     "legendFormat": "w {{name}} {{mac}} Tx -- {{oui}}"
    },
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_receive_bytes_total{oui=~\".*[gG]oog.*\", name=~\"$Wireless\", site_name=~\"$Site\", ap_name=~\"$AP\",wired=\"false\"}[$__interval])) !=0",
     "legendFormat": "w {{name}} {{mac}} Rx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_transmit_bytes_total{oui=~\".*[gG]oog.*\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\",wired=\"true\"}[$__interval])) !=0",
     "legendFormat": "e {{name}} {{mac}} Tx"
    },
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_receive_bytes_total{oui=~\".*[gG]oog.*\", name=~\"$Wired\", site_name=~\"$Site\", sw_name=~\"$Switch\",wired=\"true\"}[$__interval])) !=0",
     "legendFormat": "e {{name}} {{mac}} Rx"
    }
   ]
  },
  {
   "title": "Received Signal Strength Indicator",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unifipoller_client_rssi_db{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"}) !=0",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Wireless Signal",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unifipoller_client_radio_signal_db{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"}) !=0",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "UAP Client Stats / Noise",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unifipoller_client_noise_db{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "TX Rate",
   "type": "timeseries",
   "description": "Client reported transmit rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unifipoller_client_radio_transmit_rate_bps{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Wifi Tx Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by ($Identifier) (rate(unifipoller_client_wifi_attempts_transmit_total{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"}[$__interval]))",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "RX Rate",
   "type": "timeseries",
   "description": "Client reported receive rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unifipoller_client_radio_receive_rate_bps{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Transmit Retries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (rate(unifipoller_client_transmit_retries_total{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"}[$__interval])) !=0",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Transmit Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unifipoller_client_radio_transmit_power_dbm{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Anomalies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unifipoller_client_anomalies{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"}) !=0",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Satisfaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unifipoller_client_satisfaction_ratio{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Roam Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unifipoller_client_roam_count_total{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"}) !=0",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  },
  {
   "title": "Client Connection Quality %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by ($Identifier) (unifipoller_client_ccq_ratio{ap_name=~\"$AP\", site_name=~\"$Site\", name=~\"$Wireless\"})",
     "legendFormat": "{{name}} {{mac}}"
    }
   ]
  }
 ]
}