{
 "title": "VictoriaMetrics (10229)",
 "description": "Overview for single node VictoriaMetrics v1.83.0 or higher",
 "tags": [
  "victoriametrics",
  "vmsingle",
  "prometheus",
  "self",
  "production"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(vm_app_version{version=~\"victoria-metrics-.*\"}, job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(vm_app_version{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Index size",
   "type": "stat",
   "description": "How many entries inverted index contains. This value is proportional to the number of unique timeseries in storage(cardinality).",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_rows{job=~\"$job\", instance=~\"$instance\", type=~\"indexdb.*\"})"
    }
   ]
  },
  {
   "title": "Total datapoints",
   "type": "stat",
   "description": "How many datapoints are in storage",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_rows{job=~\"$job\", instance=~\"$instance\", type!~\"indexdb.*\"})"
    }
   ]
  },
  {
   "title": "Ingestion rate",
   "type": "stat",
   "description": "Shows the datapoints ingestion rate.",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vm_rows_inserted_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Read requests",
   "type": "stat",
   "description": "Shows the rate of HTTP read requests.",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vm_http_requests_total{job=~\"$job\", instance=~\"$instance\", path!~\".*(/write|/metrics)\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Available CPU",
   "type": "stat",
   "description": "Total number of available CPUs for VM process",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_available_cpu_cores{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_app_uptime_seconds{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Active series",
   "type": "stat",
   "description": "Shows the number of active time series with new data points inserted during the last hour. High value may result in ingestion slowdown. \n\nSee more details here https://docs.victoriametrics.com/FAQ.html#what-is-an-active-time-series",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vm_cache_entries{job=~\"$job\", instance=~\"$instance\", type=\"storage/hour_metric_ids\"}"
    }
   ]
  },
  {
   "title": "Disk space usage",
   "type": "stat",
   "description": "Total amount of used disk space",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Bytes per point",
   "type": "stat",
   "description": "Average disk usage per datapoint.",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\"}) / sum(vm_rows{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Allowed memory",
   "type": "stat",
   "description": "Total size of allowed memory via flag `-memory.allowedPercent`",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_allowed_memory_bytes{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Available memory",
   "type": "stat",
   "description": "Total size of available memory for VM process",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_available_memory_bytes{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Samples Scraped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(job) (scrape_samples_scraped)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Scrape Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(scrape_duration_seconds) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Datapoints ingestion rate ($instance)",
     "type": "timeseries",
     "description": "How many datapoints are inserted into storage per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vm_rows_inserted_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (type) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests rate ($instance)",
     "type": "timeseries",
     "description": "* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vm_http_requests_total{job=~\"$job\", instance=~\"$instance\", path!~\"/favicon.ico\"}[$__rate_interval])) by (path) > 0",
       "legendFormat": "{{path}}"
      }
     ]
    },
    {
     "title": "Active time series ($instance)",
     "type": "timeseries",
     "description": "Shows the number of active time series with new data points inserted during the last hour. High value may result in ingestion slowdown. \n\nSee following link for details:",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vm_cache_entries{job=~\"$job\", instance=~\"$instance\", type=\"storage/hour_metric_ids\"}",
       "legendFormat": "Active time series"
      }
     ]
    },
    {
     "title": "Query duration 0.99 quantile ($instance)",
     "type": "timeseries",
     "description": "The less time it takes is better.\n* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(vm_request_duration_seconds{job=~\"$job\", instance=~\"$instance\", quantile=\"0.99\"}) by (path) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests error rate ($instance)",
     "type": "timeseries",
     "description": "* `*` - unsupported query path\n* `/write` - insert into VM\n* `/metrics` - query VM system metrics\n* `/query` - query instant values\n* `/query_range` - query over a range of time\n* `/series` - match a certain label set\n* `/label/{}/values` - query a list of label values (variables mostly)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vm_http_request_errors_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (path) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Logging rate",
     "type": "timeseries",
     "description": "Shows the rate of logging the messages by their level. Unexpected spike in rate is a good reason to check logs.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "sum(rate(vm_log_messages_total{job=~\"$job\", instance=~\"$instance\", level!=\"info\"}[$__rate_interval])) by (level, location) > 0",
       "legendFormat": "{{level}}: {{location}}"
      }
     ]
    },
    {
     "title": "Node Exporter Scrape Time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 18, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds",
       "legendFormat": "{{host_system}} - {{collector}}"
      }
     ]
    },
    {
     "title": "Node Exporter Scrape",
     "type": "table",
     "gridPos": { "h": 12, "w": 6, "x": 18, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg by(collector, host_system) (last_over_time(node_scrape_collector_success[$__interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance.*\"}",
     "legendFormat": "{{job}} ({{instance}}) : resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=~\"$job\", instance=~\"$instance.*\"}",
     "legendFormat": "{{job}} ({{instance}}) : virtual"
    }
   ]
  },
  {
   "title": "Process Memory (derivative)",
   "type": "timeseries",
   "description": "Derivative shows rate of change - helpful to highlight movement in metrics which don't appear to change much.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{job=~\"$job\", instance=~\"$instance.*\"})",
     "legendFormat": "{{job}} ({{instance}}) : virtual"
    }
   ]
  },
  {
   "title": "RSS memory % usage ($instance)",
   "type": "timeseries",
   "description": "Percentage of used memory (resident).\nThe application's performance will significantly degrade when memory usage is close to 100%.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n    max_over_time(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n    /\n    vm_available_memory_bytes{job=~\"$job\", instance=~\"$instance\"}\n) by(instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(go_memstats_sys_bytes{job=~\"$job\", instance=~\"$instance\"}) + sum(vm_cache_size_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "requested from system"
    },
    {
     "expr": "sum(go_memstats_heap_inuse_bytes{job=~\"$job\", instance=~\"$instance\"}) + sum(vm_cache_size_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "heap inuse"
    },
    {
     "expr": "sum(go_memstats_stack_inuse_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "sum(process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "resident"
    },
    {
     "expr": "sum(process_resident_memory_anon_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "resident anonymous"
    }
   ]
  },
  {
   "title": "RSS anonymous memory % usage ($instance)",
   "type": "timeseries",
   "description": "Share for memory allocated by the process itself. When memory usage reaches 100% it will be likely OOM-killed.\nSafe memory usage % considered to be below 80%",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n    max_over_time(process_resident_memory_anon_bytes{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n    /\n    vm_available_memory_bytes{job=~\"$job\", instance=~\"$instance\"}\n) by(instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU % usage ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n    rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n    /\n    vm_available_cpu_cores{job=~\"$job\", instance=~\"$instance\"}\n) by(instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open FDs ($instance)",
   "type": "timeseries",
   "description": "Shows the percentage of open file descriptors compared to the limit set in the OS.\nReaching the limit of open files can cause various issues and must be prevented.\n\nSee how to change limits here https://medium.com/@muhammadtriwibowo/set-permanently-ulimit-n-open-files-in-ubuntu-4d61064429a",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max_over_time(process_open_fds{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n/\nprocess_max_fds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "CPU cores used"
    },
    {
     "expr": "process_cpu_cores_available{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Goroutines ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines{job=~\"$job\", instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk writes/reads ($instance)",
   "type": "timeseries",
   "description": "Shows the number of bytes read/write from the storage layer.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(process_io_storage_read_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) >0",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(process_io_storage_written_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) >0",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Threads ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(process_num_threads{job=~\"$job\", instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk write/read calls ($instance)",
   "type": "timeseries",
   "description": "Shows the number of read/write syscalls such as read, pread, write, pwrite.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(process_io_read_syscalls_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "read calls"
    },
    {
     "expr": "sum(rate(process_io_write_syscalls_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "write calls"
    }
   ]
  },
  {
   "title": "TCP connections rate ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vm_tcplistener_accepts_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP connections ($instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(vm_tcplistener_conns{job=~\"$job\", instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network  usage ($instance)",
   "type": "timeseries",
   "description": "Network usage shows the bytes rate for data accepted by vmagent and pushed via remotewrite protocol.\nDiscrepancies are possible because of different protocols used for ingesting, scraping and writing data.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(vm_tcplistener_read_bytes_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job) * 8 \n+ sum(rate(vm_promscrape_conn_bytes_read_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job) * 8",
     "legendFormat": "in {{job}}"
    },
    {
     "expr": "sum(rate(vmagent_remotewrite_conn_bytes_written_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(job) * 8",
     "legendFormat": "out {{job}}"
    }
   ]
  },
  {
   "title": "Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top 5 jobs by unique samples",
   "type": "timeseries",
   "description": "Shows top 5 job by the number of new series registered by vmagent over the 5min range. These jobs generate the most of the churn rate.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk_max(5, sum(sum_over_time(scrape_series_added[5m])) by (job)) > 0",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Top 5 instances by unique samples",
   "type": "timeseries",
   "description": "Shows top 5 instances by the number of new series registered by vmagent over the 5min range. These instances generate the most of the churn rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum(sum_over_time(scrape_series_added[5m])) by (instance)) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Churn rate ($instance)",
   "type": "timeseries",
   "description": "Shows the rate and total number of new series created over last 24h.\n\nHigh churn rate tightly connected with database performance and may result in unexpected OOM's or slow queries. It is recommended to always keep an eye on this metric to avoid unexpected cardinality \"explosions\".\n\nThe higher churn rate is, the more resources required to handle it. Consider to keep the churn rate as low as possible.\n\nGood references to read:\n* https://www.robustperception.io/cardinality-is-key\n* https://www.robustperception.io/using-tsdb-analyze-to-investigate-churn-and-cardinality",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vm_new_timeseries_created_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "churn rate"
    },
    {
     "expr": "sum(increase(vm_new_timeseries_created_total{job=~\"$job\", instance=~\"$instance\"}[24h]))",
     "legendFormat": "new series over 24h"
    }
   ]
  },
  {
   "title": "Slow inserts ($instance)",
   "type": "timeseries",
   "description": "The percentage of slow inserts comparing to total insertion rate during the last 5 minutes. \n\nThe less value is better. If percentage remains high (>10%) during extended periods of time, then it is likely more RAM is needed for optimal handling of the current number of active time series. \n\nIn general, VictoriaMetrics requires ~1KB or RAM per active time series, so it should be easy calculating the required amounts of RAM for the current workload according to capacity planning docs. But the resulting number may be far from the real number because the required amounts of memory depends on many other factors such as the number of labels per time series and the length of label values. See also https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3976#issuecomment-1476883183",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(\n    rate(vm_slow_row_inserts_total{job=~\"$job\"}[$__rate_interval]) \n    / rate(vm_rows_added_to_storage_total{job=~\"$job\"}[$__rate_interval])\n)",
     "legendFormat": "slow inserts percentage"
    }
   ]
  },
  {
   "title": "Assisted merges ($instance)",
   "type": "timeseries",
   "description": "Merge assist happens when storage can't keep up with merging parts. This is usually a sign of overload for storage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(vm_assisted_merges_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(type) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow queries rate ($instance)",
   "type": "timeseries",
   "description": "Slow queries rate according to `search.logSlowQueryDuration` flag, which is `5s` by default.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(vm_slow_queries_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "slow queries rate"
    }
   ]
  },
  {
   "title": "Cache usage % by type ($instance)",
   "type": "timeseries",
   "description": "Shows the percentage of used cache size from the allowed size by type. \nValues close to 100% show the maximum potential utilization.\nValues close to 0% show that cache is underutilized.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "vm_cache_size_bytes{job=~\"$job\", instance=~\"$instance\"} / vm_cache_size_max_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cache size",
   "type": "timeseries",
   "description": "VictoriaMetrics stores various caches in RAM. Memory size for these caches may be limited with -`memory.allowedPercent` flag. Line `max allowed` shows max allowed memory size for cache.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(vm_cache_size_bytes{job=~\"$job\", instance=~\"$instance\"}) by(type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum(vm_allowed_memory_bytes{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "max allowed"
    }
   ]
  },
  {
   "title": "Non-default flags",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "sum(flag{is_set=\"true\", job=~\"$job\", instance=~\"$instance\"}) by(job, instance, name, value)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache miss ratio ($instance)",
   "type": "timeseries",
   "description": "Shows cache miss ratio. Lower is better.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    rate(vm_cache_misses_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n    /\n    rate(vm_cache_requests_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])\n) > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Labels limit exceeded ($instance)",
   "type": "timeseries",
   "description": "VictoriaMetrics limits the number of labels per each metric with `-maxLabelsPerTimeseries` command-line flag.\n\nThis prevents from ingesting metrics with too many labels. The value of `maxLabelsPerTimeseries` must be adjusted for your workload.\n\nWhen limit is exceeded (graph is > 0) - extra labels are dropped, which could result in unexpected identical time series.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(vm_metrics_with_dropped_labels_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "limit exceeded"
    }
   ]
  },
  {
   "title": "Cache hit ratio",
   "type": "timeseries",
   "description": "Cache hit ratio shows cache efficiency. The higher is hit rate the better.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (\n sum(rate(vm_cache_misses_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (type) /\n sum(rate(vm_cache_requests_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (type)\n)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Datapoints ingestion rate ($instance)",
     "type": "timeseries",
     "description": "How many datapoints are inserted into storage per second",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vm_rows_inserted_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (type) > 0",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Storage full ETA ($instance)",
     "type": "timeseries",
     "description": "Shows the time needed to reach the 100% of disk capacity based on the following params:\n* free disk space;\n* row ingestion rate;\n* dedup rate;\n* compression.\n\nUse this panel for capacity planning in order to estimate the time remaining for running out of the disk space.\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "vm_free_disk_space_bytes{job=~\"$job\", instance=~\"$instance\"} \n/ ignoring(path) (\n  (\n    rate(vm_rows_added_to_storage_total{job=~\"$job\", instance=~\"$instance\"}[1d]) \n    - ignoring(type) rate(vm_deduplicated_samples_total{job=~\"$job\", instance=~\"$instance\", type=\"merge\"}[1d])\n  ) * scalar(\n    sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\", type!~\"indexdb.*\"}) \n    / sum(vm_rows{job=~\"$job\", instance=~\"$instance\", type!~\"indexdb.*\"})\n    )\n  )",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk space usage - datapoints ($instance)",
     "type": "timeseries",
     "description": "Shows amount of on-disk space occupied by data points and the remaining disk space at `-storageDataPath`",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\", type!~\"indexdb.*\"})",
       "legendFormat": "Used (datapoints)"
      },
      {
       "expr": "sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\", type=~\"indexdb.*\"})",
       "legendFormat": "Used (index)"
      }
     ]
    },
    {
     "title": "Pending datapoints ($instance)",
     "type": "timeseries",
     "description": "How many datapoints are in RAM queue waiting to be written into storage. The number of pending data points should be in the range from 0 to `2*<ingestion_rate>`, since VictoriaMetrics pushes pending data to persistent storage every second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "vm_pending_rows{job=~\"$job\", instance=~\"$instance\", type=\"storage\"}",
       "legendFormat": "pending datapoints"
      },
      {
       "expr": "vm_pending_rows{job=~\"$job\", instance=~\"$instance\", type=\"indexdb\"}",
       "legendFormat": "pending index entries"
      }
     ]
    },
    {
     "title": "Datapoints ($instance)",
     "type": "timeseries",
     "description": "Shows how many datapoints are in the storage and what is average disk usage per datapoint.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(vm_rows{job=~\"$job\", instance=~\"$instance\", type!~\"indexdb.*\"})",
       "legendFormat": "total datapoints"
      },
      {
       "expr": "sum(vm_data_size_bytes{job=~\"$job\", instance=~\"$instance\"}) \n/ sum(vm_rows{job=~\"$job\", instance=~\"$instance\", type!~\"indexdb.*\"})",
       "legendFormat": "bytes-per-datapoint"
      }
     ]
    },
    {
     "title": "LSM parts ($instance)",
     "type": "timeseries",
     "description": "Data parts of LSM tree.\nHigh number of parts could be an evidence of slow merge performance - check the resource utilization.\n* `indexdb` - inverted index\n* `storage/small` - recently added parts of data ingested into storage(hot data)\n* `storage/big` -  small parts gradually merged into big parts (cold data)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(vm_parts{job=~\"$job\", instance=~\"$instance\"}) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Rows ignored for last 1h ($instance)",
     "type": "timeseries",
     "description": "Shows how many rows were ignored on insertion due to corrupted or out of retention timestamps.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(vm_rows_ignored_total{job=~\"$job\", instance=~\"$instance\"}[1h])) by (reason)",
       "legendFormat": "{{reason}}"
      }
     ]
    },
    {
     "title": "Active merges ($instance)",
     "type": "timeseries",
     "description": "The number of on-going merges in storage nodes.  It is expected to have high numbers for `storage/small` metric.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(vm_active_merges{job=~\"$job\", instance=~\"$instance\"}) by(type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Concurrent flushes on disk ($instance)",
     "type": "timeseries",
     "description": "Shows how many ongoing insertions (not API /write calls) on disk are taking place, where:\n* `max` - equal to number of CPUs;\n* `current` - current number of goroutines busy with inserting rows into underlying storage.\n\nEvery successful API /write call results into flush on disk. However, these two actions are separated and controlled via different concurrency limiters. The `max` on this panel can't be changed and always equal to number of CPUs. \n\nWhen `current` hits `max` constantly, it means storage is overloaded and requires more CPU.\n\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max_over_time(vm_concurrent_insert_capacity{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
       "legendFormat": "max"
      },
      {
       "expr": "sum(vm_concurrent_insert_current{job=~\"$job\", instance=~\"$instance\"})",
       "legendFormat": "current"
      }
     ]
    },
    {
     "title": "Merge speed ($instance)",
     "type": "timeseries",
     "description": "The number of rows merged per second by storage nodes.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(vm_rows_merged_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by(type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Series read per query ($instance)",
     "type": "timeseries",
     "description": "99th percentile of number of series read per query.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(vm_series_read_per_query_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (instance, vmrange))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Datapoints read per series ($instance)",
     "type": "timeseries",
     "description": "99th percentile of number of raw samples read per queried series.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(vm_rows_read_per_series_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (instance, vmrange))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Datapoints read per query ($instance)",
     "type": "timeseries",
     "description": "99th percentile of number of raw datapoints read per query.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(vm_rows_read_per_query_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (instance, vmrange))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Datapoints scanned per query ($instance)",
     "type": "timeseries",
     "description": "99th percentile of number of raw samples scanner per query.\n\nThis number can exceed number of RowsReadPerQuery if `step` query arg passed to [/api/v1/query_range](https://prometheus.io/docs/prometheus/latest/querying/api/#range-queries) is smaller than the lookbehind window set in square brackets of [rollup function](https://docs.victoriametrics.com/MetricsQL.html#rollup-functions). For example, if `increase(some_metric[1h])` is executed with the `step=5m`, then the same raw samples on a hour time range are scanned `1h/5m=12` times. See [this article](https://valyala.medium.com/how-to-optimize-promql-and-metricsql-queries-85a1b75bf986) for details.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(vm_rows_scanned_per_query_bucket{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])) by (instance, vmrange))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}