{
 "title": "Monitoring Art - Grafana utils (12975)",
 "description": "Demo dashboard for monitoring art using Grafana utils. https://github.com/yesoreyeram/grafana-utils for more details",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Servers", "query": "Servers()" },
   { "name": "AdhocFilter", "label": "Adhoc Filter" }
  ]
 },
 "panels": [
  {
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "LED(*       GRAFANA UTILS  *)", "type": "timeserie" },
    {
     "target": "LED(*   MAKE GRAFANA COOLEST *,-20)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Love",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "target": "Expression(Series B,multiply:0.1,cos,abs)",
     "type": "timeserie"
    },
    {
     "target": "Expression(Series A,multiply:0.1,sin,abs)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Cloud Monitoring",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "Pattern( ,0,0,0,0,0,3,0,0,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern( ,0,0,0,0,2.75,2.75,2.75,0,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern( ,0,0,0,2.50,2.50,2.50,2.50,2.50,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern( ,0,0,2.25,2.25,2.25,2.25,2.25,2.25,2.25,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern( ,0,0,0,0,0,1,0,0,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern( ,0,0,0,0,0,0.5,0,0,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern( ,0,0,0,0,0,0.25,0,0,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern( ,0,0,0,0,0,0.75,0,0,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern( ,0,0,0,0,0,1.25,0,0,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern( ,0,0,0,0,0,1.5,0,0,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern( ,0,0,0,0,0,1.75,0,0,0,0,0)",
     "type": "timeserie"
    },
    { "target": "Matrix(Moon,60,0,[5])", "type": "timeserie" },
    { "target": "Matrix(Star,10,0,[4.5])", "type": "timeserie" },
    { "target": "Matrix(Star,70,0,[4.1])", "type": "timeserie" },
    { "target": "Matrix(Star,80,0,[4.8])", "type": "timeserie" },
    { "target": "Matrix(Star,40,0,[5.8])", "type": "timeserie" },
    {
     "target": "Expression(Rainbow-V,divide:6,sin,abs,add:0.1,start-after:23,stop-after:37)",
     "type": "timeserie"
    },
    {
     "target": "Expression(Rainbow-I,divide:6,sin,abs,add:0.1,start-after:23,stop-after:37,add:0.05)",
     "type": "timeserie"
    },
    {
     "target": "Expression(Rainbow-B,divide:6,sin,abs,add:0.1,start-after:23,stop-after:37,add:0.10)",
     "type": "timeserie"
    },
    {
     "target": "Expression(Rainbow-G,divide:6,sin,abs,add:0.1,start-after:23,stop-after:37,add:0.15)",
     "type": "timeserie"
    },
    {
     "target": "Expression(Rainbow-Y,divide:6,sin,abs,add:0.1,start-after:23,stop-after:37,add:0.20)",
     "type": "timeserie"
    },
    {
     "target": "Expression(Rainbow-O,divide:6,sin,abs,add:0.1,start-after:23,stop-after:37,add:0.25)",
     "type": "timeserie"
    },
    {
     "target": "Expression(Rainbow-R,divide:6,sin,abs,add:0.1,start-after:23,stop-after:37,add:0.30)",
     "type": "timeserie"
    },
    {
     "target": "Expression(Hill,multiply:0.1,sin,abs)",
     "type": "timeserie"
    },
    {
     "target": "Matrix(Falls,50,0,[1,0.9][0.9,0.8][0.8,0.7][0.8,0.6,0.7][0.5]0.4,0.3][0.1,0][0][0][0])",
     "type": "timeserie"
    },
    {
     "target": "Matrix(roof,10,0.2,[0.3][0.5][0.7][0.5][0.3])",
     "type": "timeserie"
    },
    {
     "target": "Matrix(house,10,0.2,[0.3][0.3][0.3][0.3][0.3])",
     "type": "timeserie"
    },
    { "target": "Matrix(Door,12,0,[0.3][0.3])", "type": "timeserie" },
    {
     "target": "Matrix(Cloud1,40,0,[4][3.75,4.25][4])",
     "type": "timeserie"
    },
    {
     "target": "Matrix(Cloud2,20,1,[4][3.75,4.25][4])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Wave",
   "type": "graph",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 6 },
   "targets": [
    {
     "target": "Expression(hello1,multiply:0.1,sin,abs,min:0.75)",
     "type": "timeserie"
    },
    {
     "target": "Expression(hello3,multiply:0.1,cos,abs,min:0.65)",
     "type": "timeserie"
    },
    {
     "target": "Expression(hello2,multiply:0.1,cos,abs,max:0.75)",
     "type": "timeserie"
    },
    {
     "target": "Expression(hello,multiply:0.1,sin,abs,max:0.75)",
     "type": "timeserie"
    },
    {
     "target": "Expression(hello,multiply:0.1,sin,abs,sqrt)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Heartbeat",
   "type": "graph",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "target": "Pattern(HeartBeat,0,0,0,-3,-2,5,0,0)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Together",
   "type": "graph",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 10 },
   "targets": [
    { "target": "Expression(A,sin,stop-after:6)", "type": "timeserie" },
    {
     "target": "Expression(B,sin,start-after:5,stop-after:8)",
     "type": "timeserie"
    },
    {
     "target": "Expression(C,sin,start-after:7)",
     "type": "timeserie"
    },
    {
     "target": "Expression(A1,sin,add:-0.5,stop-after:6)",
     "type": "timeserie"
    },
    {
     "target": "Expression(B1,sin,add:-0.5,start-after:5,stop-after:8)",
     "type": "timeserie"
    },
    {
     "target": "Expression(C1,sin,add:-0.5,start-after:7)",
     "type": "timeserie"
    },
    {
     "target": "Expression(A2,sin,add:-1,stop-after:6)",
     "type": "timeserie"
    },
    {
     "target": "Expression(B2,sin,add:-1,start-after:5,stop-after:8)",
     "type": "timeserie"
    },
    {
     "target": "Expression(C2,sin,add:-1,start-after:7)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Demo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Timeseries with annotations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "cpu", "type": "timeserie" },
    { "target": "memory", "type": "timeserie" }
   ]
  },
  {
   "title": "Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 17, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "target": "RandomWalk(4, Server)", "type": "timeserie" }
   ]
  },
  {
   "title": "Table",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "target": "memory", "type": "table" },
    { "target": "cpu", "type": "table" }
   ]
  },
  {
   "title": "Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "target": "cpu", "type": "timeserie" },
    { "target": "memory", "type": "timeserie" }
   ]
  },
  {
   "title": "Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "target": "RandomWalk(5)", "type": "timeserie" }
   ]
  },
  {
   "title": "Series Demo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "RandomWalk()",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "RandomWalk()", "type": "timeserie" }
   ]
  },
  {
   "title": "RandomWalk(3)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "RandomWalk(3)", "type": "timeserie" }
   ]
  },
  {
   "title": "RandomWalk(5,Server)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "RandomWalk(5,Server)", "type": "timeserie" }
   ]
  },
  {
   "title": "FlatLine()",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "FlatLine()", "type": "timeserie" }
   ]
  },
  {
   "title": "FlatLine(16)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "FlatLine(16)", "type": "timeserie" }
   ]
  },
  {
   "title": "FlatLine(7,Rainbow)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "FlatLine(7,Rainbow)", "type": "timeserie" }
   ]
  },
  {
   "title": "Step()",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Step()", "type": "timeserie" }
   ]
  },
  {
   "title": "Step(50)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Step(50)", "type": "timeserie" }
   ]
  },
  {
   "title": "Step(50,Speed)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Step(50,Speed)", "type": "timeserie" }
   ]
  },
  {
   "title": "Step(0,Speed,10) & Step(1,,3)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "Step(0,Speed,10)", "type": "timeserie" },
    { "target": "Step(1,,3)", "type": "timeserie" }
   ]
  },
  {
   "title": "Buildings",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "Patterns([B,4,3,2,1,2,3][A,1,2,3,2])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Hello",
   "type": "graph",
   "gridPos": { "h": 5, "w": 15, "x": 9, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "Expression(hello1,multiply:0.1,sin,abs,min:0.75)",
     "type": "timeserie"
    },
    {
     "target": "Expression(hello3,multiply:0.1,cos,abs,min:0.65)",
     "type": "timeserie"
    },
    {
     "target": "Expression(hello2,multiply:0.1,cos,abs,max:0.75)",
     "type": "timeserie"
    },
    {
     "target": "Expression(hello,multiply:0.1,sin,abs,max:0.75)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Matrix",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 46 },
   "targets": [
    {
     "target": "Matrix(Foo,0,0,[6,7,1,2,3,4,5][1,2,0,4,5][1,2,,4,5])",
     "type": "timeserie"
    },
    {
     "target": "Matrix(Bar,3,0,[1,2,3,4,5][1,2,0,4,5][1,2,6,4,5])",
     "type": "timeserie"
    },
    {
     "target": "Matrix(Baz,6,0,[1,2,3,4,5][1,2,7,0,4,5][1,2,,4,5])",
     "type": "timeserie"
    },
    {
     "target": "Matrix(Bau,9,0,[1,2,3,4,5][1,2,0,4,5][1,2,,4,5])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Random Walk",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 4, "y": 46 },
   "targets": [
    { "target": "RandomWalk(5,Server)", "type": "timeserie" }
   ]
  },
  {
   "title": "Tower",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 46 },
   "targets": [
    {
     "target": "Pattern(A ,0,0,0,0,0,5,0,0,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern(B ,0,0,0,0,4,0,4,0,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern(C,0,0,0,3,0,0,0,3,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern(D,0,0,2,0,0,0,0,0,2,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern(E ,0,0,0,0,0,1,0,0,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern(F ,0,0,0,0,0,0.5,0,0,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern(G ,0,0,0,0,0,0.25,0,0,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern(H ,0,0,0,0,0,0.75,0,0,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern(I ,0,0,0,0,0,1.25,0,0,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern(J,0,0,0,0,0,1.5,0,0,0,0,0)",
     "type": "timeserie"
    },
    {
     "target": "Pattern(K ,0,0,0,0,0,1.75,0,0,0,0,0)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Alphabets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {}
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "target": "LED(*ABCDEFGHIJKLMNOPQRSTUVWXYZ*)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Logo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 7, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "Grafana Deno JSON Backend", "type": "timeserie" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "server1", "type": "timeserie" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 57 },
   "options": {
    "content": "![](https://camo.githubusercontent.com/68631b19ad7605c7f5f1f161f5dcc9452cc288f9/68747470733a2f2f64656e6f6c69622e6769746875622e696f2f686967682d7265732d64656e6f2d6c6f676f2f64656e6f5f68725f636972636c652e706e67)"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "server1", "type": "timeserie" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "server1", "type": "timeserie" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "server1", "type": "timeserie" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 9, "x": 7, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "target": "server1", "type": "timeserie" }
   ]
  },
  {
   "title": "WIki",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Help",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "options": {
    "content": "Running directly from url\n```\ndeno run --allow-net https://raw.githubusercontent.com/yesoreyeram/grafana-simple-deno-api-backend/master/index.ts --port 8080\n```\n\nRunning from local\n```\ngit clone https://github.com/yesoreyeram/grafana-simple-deno-api-backend.git\ncd grafana-simple-deno-api-backend\ndeno run --allow-net index.ts --port 8080\n```\n"
   }
  }
 ]
}