{
 "title": "Host",
 "description": "Metrics for the host machine [dockprom default dash]",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "{__name__=~\"node_.*\"}"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "{__name__=~\"node_.*\",host=~\"$host\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Uptime", "type": "stat", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "CPU Use - Host", "type": "gauge", "gridPos": { "h": 6, "w": 4, "x": 6, "y": 1 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "Server Temp", "type": "gauge", "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Used Memory",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes-(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes + + node_memory_SReclaimable_bytes)",
     "legendFormat": "RAM"
    },
    {
     "expr": "node_memory_SwapTotal_bytes-node_memory_SwapFree_bytes",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Boot Drive Storage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"}-node_filesystem_free_bytes{mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "processes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "processes_total_threads" }
   ]
  },
  { "title": "RAM Use - Host", "type": "gauge", "gridPos": { "h": 5, "w": 3, "x": 4, "y": 7 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "title": "Swap Use - Host", "type": "gauge", "gridPos": { "h": 5, "w": 2, "x": 7, "y": 7 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Boot Drive Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\"}-node_filesystem_free_bytes{mountpoint=\"/\"}) * 100 / node_filesystem_size_bytes{mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Data Drives Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes{mountpoint=~\"/mnt/data/.+\"} - node_filesystem_free_bytes{mountpoint=~\"/mnt/data/.+\"}) ) / sum(node_filesystem_size_bytes{mountpoint=~\"/mnt/data/.+\"}) * 100"
    }
   ]
  },
  {
   "title": "Data Storage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=~\"/mnt/data/.+\"}-node_filesystem_free_bytes{mountpoint=~\"/mnt/data/.+\"})"
    }
   ]
  },
  { "title": "Disk Usage", "type": "bargauge", "gridPos": { "h": 14, "w": 9, "x": 15, "y": 10 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "description": "Load values are out of 8 (number of cores/threads). Greater than 8 indicates that processes are waiting for CPU time",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "Load - 1m" },
    { "expr": "node_load5", "legendFormat": "Load - 5m" },
    { "expr": "node_load15", "legendFormat": "Load - 15m" }
   ]
  },
  { "title": "Network Traffic - Host", "type": "timeseries", "gridPos": { "h": 7, "w": 15, "x": 0, "y": 19 } },
  {
   "title": "Backups & Folders",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backups",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "targets": [
    { "expr": "node_snapraid", "legendFormat": "Snapraid" },
    {
     "expr": "node_duplicacy",
     "legendFormat": "{{storage}} [Duplicacy {{action}}]"
    },
    { "expr": "node_rsync_marlin", "legendFormat": "{{action}} [Rsync Marlin]" },
    { "expr": "node_rclone", "legendFormat": "{{remote}} [rclone {{action}}]" }
   ]
  },
  {
   "title": "Timeseries - NAS - Folder Sizes [Host]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 }
  },
  {
   "title": "Timeseries - Folder Sizes - Monitoring DBs & Plex [Docker Containers]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 }
  },
  {
   "title": "CPU & Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Timeseries - CPU Percent - Host [Host]",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 50 }
  },
  {
   "title": "Timeseries - RAM Use - Host [Host]",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 62 }
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_SwapFree_bytes", "legendFormat": "Free" }
   ]
  },
  {
   "title": "Swap I/O",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_vmstat_pswpin[$__rate_interval]) * 4096",
     "legendFormat": "Swap Moving Into Memory"
    },
    {
     "expr": "-rate(node_vmstat_pswpout[$__rate_interval]) * 4096",
     "legendFormat": "Memory Moving Into Swap"
    }
   ]
  },
  {
   "title": "Memory Active / Inactive",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Inactive_bytes",
     "legendFormat": "Inactive - Memory which has been less recently used.  It is more eligible to be reclaimed for other purposes"
    },
    {
     "expr": "node_memory_Active_bytes",
     "legendFormat": "Active - Memory that has been used more recently and usually not reclaimed unless absolutely necessary"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {}
   ]
  },
  { "title": "ISP Speedtest", "type": "timeseries", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 } },
  { "title": "Network Traffic - Host", "type": "timeseries", "gridPos": { "h": 10, "w": 17, "x": 0, "y": 94 } },
  {
   "title": "Network Traffic - Packets (per sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(host_net_packets_recv[$__rate_interval]) != 0",
     "legendFormat": "Received - {{interface}}"
    },
    {
     "expr": "rate(host_net_packets_sent[$__rate_interval]) * -1 != 0",
     "legendFormat": "Sent - {{interface}}"
    }
   ]
  },
  {
   "title": "Network Traffic - Dropped Packets (per sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(host_net_drop_in[$__rate_interval]) != 0",
     "legendFormat": "Received - {{interface}}"
    },
    {
     "expr": "rate(host_net_drop_out[$__rate_interval]) * -1 != 0",
     "legendFormat": "Sent - {{interface}}"
    }
   ]
  },
  {
   "title": "Network Volume",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "increase(host_net_bytes_recv[$__rate_interval]) != 0",
     "legendFormat": "Received - {{interface}}"
    },
    {
     "expr": "increase(host_net_bytes_sent[$__rate_interval]) * -1 != 0",
     "legendFormat": "Sent - {{interface}}"
    }
   ]
  },
  {
   "title": "Network Traffic - Error Packets (per sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(host_net_err_in[$__rate_interval]) != 0",
     "legendFormat": "Received - {{interface}}"
    },
    {
     "expr": "rate(host_net_err_out[$__rate_interval]) * -1 != 0",
     "legendFormat": "Sent - {{interface}}"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SMART Disk Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "max(smartmon_power_on_hours_raw_value) by (device_model,serial_number,disk)"
    },
    {
     "expr": "max(smartmon_load_cycle_count_raw_value) by (device_model,serial_number,disk)",
     "legendFormat": "Load Cycles"
    },
    {
     "expr": "max(smartmon_start_stop_count_raw_value) by (device_model,serial_number,disk)",
     "legendFormat": "Load Cycles"
    },
    {
     "expr": "avg(smartmon_temperature_celsius_raw_value) by (device_model,serial_number,disk)"
    },
    {
     "expr": "max(smartmon_device_smart_healthy) by (disk,device_model,serial_number)"
    },
    {
     "expr": "max(smartmon_reallocated_sector_ct_raw_value) by (disk,device_model,serial_number)"
    },
    {
     "expr": "max(smartmon_current_pending_sector_raw_value) by (disk,device_model,serial_number)"
    },
    {
     "expr": "max(smartmon_offline_uncorrectable_raw_value) by (disk,device_model,serial_number)"
    },
    {
     "expr": "(smartmon_total_lbas_written_raw_value * on(disk,device_model,serial_number) smartmon_device_sector_size_logical)"
    },
    {
     "expr": "max(smartmon_spin_up_time_raw_value) by (disk,device_model,serial_number)"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 126 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(disk_total{device=~\".*sd.*\"}) by (path)",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "max(disk_used{device=~\".*sd.*\"}) by (path)",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "max(disk_free{device=~\".*sd.*\"}) by (path)",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "max(disk_used_percent{device=~\".*sd.*\"}) by (path)",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "SMART Disk Temperature",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(smartmon_temperature_celsius_raw_value) by (device_model,serial_number,disk)",
     "legendFormat": "{{disk}} ({{device_model}})"
    }
   ]
  },
  {
   "title": "SMART Disk Health",
   "type": "timeseries",
   "description": "Values != 1 are bad. Displayed as graph to allow alerts to be generated.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 137 },
   "targets": [
    {
     "expr": "max by(disk, device_model, serial_number) (max_over_time(smartmon_device_smart_healthy[$__interval]))",
     "legendFormat": "{{disk}} ({{device_model}})"
    }
   ]
  },
  {
   "title": "SMART Raw Error Read Rate",
   "type": "timeseries",
   "description": "Error Read Value / Threshold\n(>1 indicates still healthy)",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(smartmon_raw_read_error_rate_value / smartmon_raw_read_error_rate_threshold) by (disk,device_model,serial_number)",
     "legendFormat": "{{disk}} ({{device_model}})"
    }
   ]
  },
  {
   "title": "SMART Critical Metrics",
   "type": "timeseries",
   "description": "Critical subset of SMART metrics which can indicate imminent drive failure.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "smartmon_reallocated_sector_ct_raw_value",
     "legendFormat": "005 Reallocated Sector Count - {{disk}}"
    },
    {
     "expr": "smartmon_spin_retry_count_raw_value",
     "legendFormat": "010 Spin Retry Count - {{disk}}"
    },
    {
     "expr": "smartmon_end_to_end_error_raw_value",
     "legendFormat": "184 End To End Errors - {{disk}}"
    },
    {
     "expr": "smartmon_reported_uncorrect_raw_value",
     "legendFormat": "187 Reported Uncorrectable Errors - {{disk}}"
    },
    {
     "expr": "smartmon_current_pending_sector_raw_value",
     "legendFormat": "197 Current Pending Sector - {{disk}}"
    },
    {
     "expr": "smartmon_offline_uncorrectable_raw_value",
     "legendFormat": "198 Offline Uncorrectable Sectors - {{disk}}"
    },
    {
     "expr": "smartmon_udma_crc_error_count_raw_value",
     "legendFormat": "199 UDMS CRC Error Count - {{disk}}"
    },
    {
     "expr": "smartmon_reallocated_event_count_raw_value",
     "legendFormat": "196 Reallocated Event Count - {{disk}}"
    }
   ]
  },
  {
   "title": "IOps",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total[$__rate_interval])",
     "legendFormat": "Read - {{ device }}"
    },
    {
     "expr": "-rate(node_disk_writes_completed_total[$__rate_interval])",
     "legendFormat": "Write - {{device}}"
    }
   ]
  },
  {
   "title": "I/O Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[$__rate_interval])",
     "legendFormat": "Read - {{ device }}"
    },
    {
     "expr": "-rate(node_disk_written_bytes_total[$__rate_interval])",
     "legendFormat": "Write - {{device}}"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total[$__rate_interval])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Disk Average Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total[$__rate_interval]) / rate(node_disk_reads_completed_total[$__rate_interval])",
     "legendFormat": "{{device}} - r_await"
    },
    {
     "expr": "-rate(node_disk_write_time_seconds_total[$__rate_interval]) / rate(node_disk_writes_completed_total[$__rate_interval])",
     "legendFormat": "{{device}} - w_await"
    }
   ]
  },
  {
   "title": "Misc - Temperature & Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 165 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Server Temp",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(avg(node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"})[5m])",
     "legendFormat": "CPU Package Avg (5m)"
    },
    {
     "expr": "avg_over_time(avg(node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"})[1m])",
     "legendFormat": "CPU Package Avg (1m)"
    }
   ]
  },
  {
   "title": "All Temperature Sensors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 176 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "node_hwmon_temp_celsius", "legendFormat": "{{ chip }} {{ sensor }} temp" },
    {
     "expr": "node_hwmon_temp_crit_celsius",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    },
    { "expr": "crush_temp_value" }
   ]
  },
  {
   "title": "Time Syncronized Drift",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 176 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds",
     "legendFormat": "Estimated error in seconds"
    },
    {
     "expr": "node_timex_offset_seconds",
     "legendFormat": "Time offset in between local system and reference clock"
    },
    { "expr": "node_timex_maxerror_seconds", "legendFormat": "Maximum error in seconds" }
   ]
  },
  {
   "title": "Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 185 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processes Status",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 186 },
   "yaxes": [
    { "format": "short", "label": "counter" }
   ],
   "targets": [
    {
     "expr": "node_procs_blocked",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    },
    { "expr": "node_procs_running", "legendFormat": "Processes in runnable state" }
   ]
  },
  {
   "title": "Process schedule stats Running / Waiting",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 186 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "rate(node_schedstat_running_seconds_total[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }} - seconds spent running a process"
    },
    {
     "expr": "rate(node_schedstat_waiting_seconds_total[$__rate_interval])",
     "legendFormat": "CPU {{ cpu }} - seconds spent by processing waiting for this CPU"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "last_over_time(processes_total_threads[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_intr_total[$__rate_interval])",
     "legendFormat": "interrupts"
    }
   ]
  }
 ]
}