{
 "title": "Minecraft - Old (contains ServerStats & UnifiedMetrics charts)",
 "description": "Using mc-router and ServerStats for metrics collection",
 "tags": [
  "host",
  "linux",
  "minecraft",
  "prometheus",
  "influxdb",
  "ServerStats",
  "mc-router",
  "vmagent",
  "fabricexporter",
  "unifiedmetrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "SS_server",
    "label": "Server (ServerStats)",
    "query": {
     "query": "label_values(minecraft_SS_cpu,instance)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "query_result(minecraft_FE_minecraft_entities)"
    }
   },
   {
    "name": "instance",
    "label": "Server",
    "query": {
     "query": "query_result(up{job=~\"$job\"})"
    }
   },
   {
    "name": "dimension",
    "label": "Dimension (applies to entity lists only)",
    "query": {
     "query": "label_values(minecraft_FE_minecraft_players_online,world)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Fabric Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(minecraft_FE_minecraft_tps{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(minecraft_FE_minecraft_mspt{type=\"mean\",instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_players_online{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_entities{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_loaded_chunks{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "count(minecraft_FE_minecraft_tps{instance=~\"$instance\",job=~\"$job\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-avg(minecraft_FE_process_start_time_seconds{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(minecraft_FE_process_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) / sum(irate(node_cpu_seconds_total{host_system=\"minecraft\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(minecraft_FE_process_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}[$__interval]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_jvm_memory_bytes_used{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_jvm_memory_bytes_max{instance=~\"$instance\",job=~\"$job\"} - minecraft_FE_jvm_memory_bytes_used{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Server Info ",
   "type": "table",
   "description": "Note that this will only show servers which have been active in period - if the server has not woken up then it will not be shown.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (instance) (minecraft_FE_minecraft_players_online{instance=~\".*\",job=~\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (instance) (time()-minecraft_FE_process_start_time_seconds{instance=~\".*\",job=~\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (minecraft_FE_minecraft_tps{instance=~\".*\",job=~\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (minecraft_FE_minecraft_mspt{type=\"mean\",instance=~\".*\",job=~\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (minecraft_FE_minecraft_entities{instance=~\".*\",job=~\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (minecraft_FE_minecraft_loaded_chunks{instance=~\".*\",job=~\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (irate(minecraft_FE_process_cpu_seconds_total{instance=~\".*\",job=~\"$job\"}[$__rate_interval])) / sum(irate(node_cpu_seconds_total{host_system=\"crush\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (minecraft_FE_jvm_memory_bytes_used{instance=~\".*\",job=~\"$job\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (minecraft_FE_jvm_memory_bytes_max{instance=~\".*\",job=~\"$job\"} - minecraft_FE_jvm_memory_bytes_used{instance=~\".*\",job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ticks Per Second",
   "type": "timeseries",
   "description": "Target is 20",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_FE_minecraft_tps{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Milliseconds Per Tick",
   "type": "timeseries",
   "description": "Below 50 is fine since that will still allow 20 TPS",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_FE_minecraft_mspt{type=\"mean\",instance=~\"$instance\",job=~\"$job\"} !=0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Players Online",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_players_online{instance=~\"$instance\",job=~\"$job\"}) by (instance,world) !=0",
     "legendFormat": "{{instance}} - {{world}}"
    }
   ]
  },
  {
   "title": "Player flow",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_players_online{instance=~\"$instance\",job=~\"$job\"} - minecraft_FE_minecraft_players_online{instance=~\"$instance\",job=~\"$job\"} offset 15s) by (instance,world) ",
     "legendFormat": "{{instance}} - {{world}}"
    }
   ]
  },
  {
   "title": "Loaded Chunks & New Chunks Generated",
   "type": "timeseries",
   "description": "Number of loaded chunks is on left-hand axis\n\nNumber of new chunks generated by the game is on the right-hand axis - new chunks are generated by the game if new parts of the world are visited.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_loaded_chunks{instance=~\"$instance\",job=~\"$job\"}) by (instance,world) !=0",
     "legendFormat": "Loaded: {{instance}} - {{world}}"
    },
    {
     "expr": "irate(minecraft_FE_minecraft_total_loaded_chunks{instance=~\"$instance\",job=~\"$job\"}[1m]) !=0",
     "legendFormat": "Generated: {{instance}} - {{world}}"
    }
   ]
  },
  {
   "title": "Entities by Type in Dimension ($dimension)",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_entities{instance=~\"$instance\",job=~\"$job\",world=~\"$dimension\"}) by (type)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "max(minecraft_FE_minecraft_entities{instance=~\"$instance\",job=~\"$job\",world=~\"$dimension\"})",
     "legendFormat": "BiggestValue"
    }
   ]
  },
  {
   "title": "Entities by world",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (instance,world) !=0",
     "legendFormat": "{{instance}} - {{world}}"
    }
   ]
  },
  {
   "title": "Entities by Spawn Group In Dimension ($dimension)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_entities{instance=~\"$instance\",job=~\"$job\",world=~\"$dimension\"}) by (group) !=0",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "MC Router",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Connections Active",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "mc_router_connections_active_value"
      }
     ]
    },
    {
     "title": "Transmitted Bytes / sec",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum_over_time(mc_router_transmitted_bytes_count[5m])/300",
       "legendFormat": "Packets"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
     "targets": [
      { "expr": "mc_router_connections_count", "legendFormat": "MC Router - {{host}}" }
     ]
    },
    {
     "title": "MC Router Errors",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
     "targets": [
      { "expr": "avg(mc_router_errors_count)", "legendFormat": "Errors" }
     ]
    }
   ]
  },
  {
   "title": "ServerStats (used in 1.18)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Loaded Chunks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "minecraft_SS_loaded_chunks_world{instance=~\"$SS_server\"} !=0",
       "legendFormat": "{{instance}} - {{world}}"
      },
      {
       "expr": "sum by (instance) (minecraft_SS_loaded_chunks_world{instance=~\"$SS_server\"}) !=0",
       "legendFormat": "{{instance}} - Total"
      }
     ]
    },
    {
     "title": "Loaded Chunks",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "minecraft_SS_loaded_chunks{instance=~\"$SS_server\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Entity Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "minecraft_SS_entity_count_world{instance=~\"$SS_server\"} !=0",
       "legendFormat": "{{instance}} - {{world}}"
      },
      {
       "expr": "sum by (instance) (minecraft_SS_entity_count_world{instance=~\"$SS_server\"}) !=0",
       "legendFormat": "{{instance}} Total"
      }
     ]
    },
    {
     "title": "Entity Count",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "minecraft_SS_entity_count{instance=~\"$SS_server\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Player Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "minecraft_SS_player_count{instance=~\"$SS_server\"} !=0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Player Count",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "minecraft_SS_player_count{instance=~\"$SS_server\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MSPT ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "minecraft_SS_mspt{instance=~\"$SS_server\"} !=0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "MSPT",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "minecraft_SS_mspt{instance=~\"$SS_server\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "TPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "TPS" } },
     "targets": [
      {
       "expr": "minecraft_SS_tps{instance=~\"$SS_server\"} !=0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "TPS",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "minecraft_SS_tps{instance=~\"$SS_server\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "minecraft_SS_cpu{instance=~\"$SS_server\"} !=0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "minecraft_SS_cpu{instance=~\"$SS_server\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(minecraft_SS_max_memory{instance=~\"$SS_server\"}-minecraft_SS_free_memory{instance=~\"$SS_server\"}) !=0",
       "legendFormat": "Used Mem - {{instance}}"
      },
      {
       "expr": "minecraft_SS_max_memory{instance=~\"$SS_server\"} !=0",
       "legendFormat": "Allocated Mem - {{instance}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "(minecraft_SS_max_memory{instance=~\"$SS_server\"}-minecraft_SS_free_memory{instance=~\"$SS_server\"}) !=0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "minecraft_SS_disk_space_world{instance=~\"$SS_server\"} !=0",
       "legendFormat": "{{instance}} - {{world}}"
      },
      {
       "expr": "sum by (instance) (minecraft_SS_disk_space_world{instance=~\"$SS_server\"}) !=0",
       "legendFormat": "{{instance}} Total"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum by (instance) (minecraft_SS_disk_space_world{instance=~\"$SS_server\"})",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 19, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "minecraft_SS_threads{instance=~\"$SS_server\"} !=0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 19, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "minecraft_SS_threads{instance=~\"$SS_server\"} !=0",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Packets Sent/Received",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (instance) (rate(minecraft_SS_packets_rx{instance=~\"$SS_server\"}[$__rate_interval])) !=0",
       "legendFormat": "{{instance}} - RX"
      },
      {
       "expr": "- sum by (instance) (rate(minecraft_SS_packets_tx{instance=~\"$SS_server\"}[$__rate_interval])) !=0",
       "legendFormat": "{{instance}} - TX"
      }
     ]
    }
   ]
  }
 ]
}