{
 "title": "Traefik",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "router", "label": "Router", "query": { "query": "label_values(router)" } },
   { "name": "service", "label": "Service", "query": { "query": "label_values(service)" } },
   { "name": "entrypoint", "label": "Entrypoint", "query": { "query": "label_values(entrypoint)" } }
  ]
 },
 "panels": [
  {
   "title": "Entrypoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Open Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections)",
     "legendFormat": "Entrypoint"
    },
    {
     "expr": "sum(traefik_service_open_connections)",
     "legendFormat": "Service"
    },
    {
     "expr": "sum(traefik_router_open_connections)",
     "legendFormat": "Router"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total[$__rate_interval])) by (entrypoint) ",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  },
  {
   "title": "Requests by Protocol",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total[$__rate_interval])) by (protocol) ",
     "legendFormat": "{{ protocol }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total[$__rate_interval])) by (entrypoint) !=0",
     "legendFormat": " {{entrypoint}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum) by (entrypoint) !=0 / sum(traefik_entrypoint_request_duration_seconds_count) by (entrypoint)",
     "legendFormat": " {{entrypoint}}"
    }
   ]
  },
  {
   "title": "Request Status code 200",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code=\"200\"}[$__rate_interval])) by (method,code) !=0",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request Status code 200",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code=\"200\"}[$__rate_interval])) by (entrypoint,method) !=0 ",
     "legendFormat": "{{entrypoint}} : {{method}}"
    }
   ]
  },
  {
   "title": "Request Status code != 200",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code!=\"200\"}[$__rate_interval])) by (entrypoint,code) !=0",
     "legendFormat": "{{entrypoint}} : {{code}}"
    }
   ]
  },
  {
   "title": "Request Status code != 200",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{code!=\"200\"}[$__rate_interval])) by (entrypoint,method,code) !=0 ",
     "legendFormat": "{{entrypoint}} : {{method}} : {{code}}"
    }
   ]
  },
  {
   "title": "Routers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Open Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(traefik_entrypoint_open_connections)",
       "legendFormat": "Entrypoint"
      },
      {
       "expr": "sum(traefik_service_open_connections)",
       "legendFormat": "Service"
      },
      {
       "expr": "sum(traefik_router_open_connections)",
       "legendFormat": "Router"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 19 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "expr": "sum(increase(traefik_router_requests_total[$__rate_interval])) by (router) ",
       "legendFormat": "{{ router }}"
      }
     ]
    },
    {
     "title": "Requests by Protocol",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 19 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "expr": "sum(increase(traefik_router_requests_total[$__rate_interval])) by (protocol) ",
       "legendFormat": "{{ protocol }}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(traefik_router_requests_total[$__rate_interval])) by (router) !=0",
       "legendFormat": " {{router}}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(traefik_router_request_duration_seconds_sum) by (router) !=0 / sum(traefik_router_request_duration_seconds_count) by (router)",
       "legendFormat": " {{router}}"
      }
     ]
    },
    {
     "title": "Request Status code 200",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_router_requests_total{code=\"200\"}[$__rate_interval])) by (method,code) !=0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Request Status code != 200",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_router_requests_total{code!=\"200\"}[$__rate_interval])) by (method,code) !=0",
       "legendFormat": "{{method}} : {{code}}"
      }
     ]
    },
    {
     "title": "Request Status code 200",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_router_requests_total{code=\"200\"}[$__rate_interval])) by (router,method) !=0 ",
       "legendFormat": "{{router}} : {{method}}"
      }
     ]
    },
    {
     "title": "Request Status code != 200",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_router_requests_total{code!=\"200\"}[$__rate_interval])) by (router,method,code) !=0 ",
       "legendFormat": "{{router}} : {{method}} : {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Open Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(traefik_entrypoint_open_connections)",
       "legendFormat": "Entrypoint"
      },
      {
       "expr": "sum(traefik_service_open_connections)",
       "legendFormat": "Service"
      },
      {
       "expr": "sum(traefik_router_open_connections)",
       "legendFormat": "Router"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 20 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_total[$__rate_interval])) by (service) ",
       "legendFormat": "{{ service }}"
      }
     ]
    },
    {
     "title": "Requests by Protocol",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 20 },
     "format": "short",
     "valueName": "total",
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_total[$__rate_interval])) by (protocol) ",
       "legendFormat": "{{ protocol }}"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_total[$__rate_interval])) by (service) !=0",
       "legendFormat": " {{service}}"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(traefik_service_request_duration_seconds_sum) by (service) !=0 / sum(traefik_service_request_duration_seconds_count) by (service)",
       "legendFormat": " {{service}}"
      }
     ]
    },
    {
     "title": "Request Status code 200",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total{code=\"200\"}[$__rate_interval])) by (method,code) !=0",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Request Status code != 200",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total{code!=\"200\"}[$__rate_interval])) by (method,code) !=0",
       "legendFormat": "{{method}} : {{code}}"
      }
     ]
    },
    {
     "title": "Request Status code 200",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total{code=\"200\"}[$__rate_interval])) by (service,method) !=0 ",
       "legendFormat": "{{service}} : {{method}}"
      }
     ]
    },
    {
     "title": "Request Status code != 200",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total{code!=\"200\"}[$__rate_interval])) by (service,method,code) !=0 ",
       "legendFormat": "{{service}} : {{method}} : {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Entrypoint - $entrypoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "entrypoint",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Average Response Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(traefik_entrypoint_request_duration_seconds_sum{entrypoint=\"$entrypoint\"}) by (entrypoint) !=0 / sum(traefik_entrypoint_request_duration_seconds_count) by (entrypoint)",
       "legendFormat": " {{entrypoint}}"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 2, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(traefik_entrypoint_open_connections{entrypoint=\"$entrypoint\"})",
       "legendFormat": "Entrypoint"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 91 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(traefik_entrypoint_requests_total{entrypoint=\"$entrypoint\"}[$__rate_interval])) by (entrypoint,code,method,protocol,service) !=0",
       "legendFormat": " {{protocol}} -> {{method}}:{{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service - $service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "repeat": "service",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Average Response Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(traefik_service_request_duration_seconds_sum{service=\"$service\"}) by (service) !=0 / sum(traefik_service_request_duration_seconds_count) by (service)",
       "legendFormat": " {{service}}"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "stat",
     "gridPos": { "h": 8, "w": 2, "x": 2, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(traefik_service_open_connections{service=\"$service\"})",
       "legendFormat": "Service"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 20, "x": 4, "y": 100 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_total{service=\"$service\"}[$__rate_interval])) by (code,method,protocol,service) !=0",
       "legendFormat": "{{service}} ({{method}}:{{code}}) [{{protocol}}]"
      }
     ]
    }
   ]
  }
 ]
}