{
 "title": "Ubiquity UniFi Access Point [SNMP & Unpoller]",
 "description": "Metrics from SNMP for Unifi AP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "SNMP - Host",
    "query": "SHOW TAG VALUES FROM \"snmp.UAP\" WITH KEY = \"agent_host\""
   },
   {
    "name": "radio",
    "label": "SNMP - Radio",
    "query": "SHOW TAG VALUES FROM \"unifiVapTable\" WITH KEY = \"unifiVapRadio\" WHERE \"agent_host\" =~ /^$host$/"
   },
   {
    "name": "vap",
    "label": "SNMP - vAP",
    "query": "SHOW TAG VALUES FROM \"unifiVapTable\" WITH KEY = \"unifiVapName\" WHERE \"agent_host\" =~ /^$host$/"
   },
   {
    "name": "intf",
    "label": "SNMP - Interface:",
    "query": "SHOW TAG VALUES FROM \"unifiIfTable\" WITH KEY = \"unifiIfName\" WHERE \"agent_host\" =~ /^$host$/"
   },
   { "name": "smooth", "label": "Smooth", "query": "30s,1m,2m,5m,10m,15m,30m" },
   {
    "name": "ap",
    "label": "Unifi-Poller - AP",
    "query": {
     "query": "label_values(unifipoller_device_info,name)"
    }
   },
   {
    "name": "site",
    "label": "Unifi-Poller - Site",
    "query": {
     "query": "label_values(unifipoller_device_info{type=\"uap\"},site_name)"
    }
   },
   {
    "name": "wireless",
    "label": "Unifi-Poller - Wireless",
    "query": {
     "query": "label_values(unifipoller_client_roam_count_total{wired=\"false\"},name)"
    }
   },
   { "name": "identifier", "label": "Unifi-Poller - Identifier", "query": "name, name\\,mac" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Information",
   "type": "text",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "options": {
    "content": "RSSI = Signal strength of connection to AP as measured by client.</br>\nSignal Strength = Signal strength from client to AP as measured by AP."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Unifi-Poller - UAP Insights (11314)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Switch Details",
     "type": "table",
     "description": "If you have access points and gateways they will also show up here because they have switch ports.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum by (ip,mac,model,name,serial,site_name,type,version,source) (unifipoller_device_info{name=~\"$ap\"})"
      },
      {
       "expr": "sum by (ip,mac,model,name,serial,site_name,type,version,source) (unifipoller_device_uptime_seconds{name=~\"$ap\"})"
      },
      {
       "expr": "sum by (ip,mac,model,name,serial,site_name,type,version,source) (unifipoller_device_bytes_total{name=~\"$ap\"})"
      }
     ]
    },
    {
     "title": "Overall Data Transfer",
     "type": "graph",
     "description": "Shows data transfer for each subsystem on the site. RX is on the negative axis.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "Bps", "label": "bytes / second" }
     ],
     "targets": [
      {
       "expr": "unifipoller_site_transmit_rate_bytes{site_name=~\"$site\"} !=0",
       "legendFormat": "{{subsystem}} Tx"
      },
      {
       "expr": "unifipoller_site_receive_rate_bytes{site_name=~\"$site\"} !=0",
       "legendFormat": "{{subsystem}} Rx"
      }
     ]
    },
    {
     "title": "Users",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unifipoller_device_stations{site_name=~\"$site\", name=~\"$ap\", station_type=\"user\"})"
      }
     ]
    },
    {
     "title": "Clients / Channel",
     "type": "piechart",
     "description": "Visualize wireless channel usage w/ wired client counts.",
     "gridPos": { "h": 9, "w": 6, "x": 2, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count by (channel) (unifipoller_client_roam_count_total{site_name=~\"$site\", ap_name=~\"$ap\"})\n",
       "legendFormat": "Ch {{channel}}"
      }
     ]
    },
    {
     "title": "Clients / UAP",
     "type": "graph",
     "gridPos": { "h": 9, "w": 16, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "unifipoller_device_stations{site_name=~\"$site\",name=~\"$ap\"}",
       "legendFormat": "{{name}} users"
      }
     ]
    },
    {
     "title": "Guests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(unifipoller_device_stations{site_name=~\"$site\", name=~\"$ap\", station_type=\"guest\"})"
      }
     ]
    },
    {
     "title": "Clients / AP Radio",
     "type": "grafana-piechart-panel",
     "description": "Visualize how many clients are connected to which radios/APs.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count by (radio_desc) (unifipoller_client_uptime_seconds{site_name=~\"$site\", ap_name=~\"$ap\"})",
       "legendFormat": "{{radio_desc}}"
      }
     ]
    },
    {
     "title": "Users & Guests / Radio Band",
     "type": "graph",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (unifipoller_device_radio_stations{radio=\"ng\", site_name=~\"$site\",name=~\"$ap\", station_type=\"guest\"}) by  (radio,name)",
       "legendFormat": "{{name}} Guests 2,4GHz"
      },
      {
       "expr": "sum (unifipoller_device_radio_stations{radio=\"ng\", site_name=~\"$site\",name=~\"$ap\", station_type=\"user\"}) by (radio,name)",
       "legendFormat": "{{name}} Users  2.4GHz"
      },
      {
       "expr": "sum (unifipoller_device_radio_stations{radio=\"na\", site_name=~\"$site\",name=~\"$ap\", station_type=\"user\"}) by (radio,name)",
       "legendFormat": "{{name}} Users 5GHz"
      },
      {
       "expr": "sum (unifipoller_device_radio_stations{radio=\"na\", site_name=~\"$site\",name=~\"$ap\", station_type=\"guest\"}) by (radio,name)",
       "legendFormat": "{{name}} Guests 5GHz"
      }
     ]
    },
    {
     "title": "Client / MAC OUI",
     "type": "grafana-piechart-panel",
     "description": "This shows an OUI breakdown from Unifi's perspective.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 33 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count by (oui) (unifipoller_client_uptime_seconds{site_name=~\"$site\", ap_name=~\"$ap\"})",
       "legendFormat": "{{oui}}"
      }
     ]
    },
    {
     "title": "Wireless Traffic / Vendor",
     "type": "graph",
     "description": "Devices TX / RX bytes per second grouped by OUI. RX on negative axis.",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 33 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum (unifipoller_client_receive_rate_bytes{site_name=~\"$site\",ap_name=~\"$ap\"}) by (oui)",
       "legendFormat": "{{oui}} Rx"
      },
      {
       "expr": "sum (unifipoller_client_transmit_rate_bytes{site_name=~\"$site\",ap_name=~\"$ap\"}) by (oui)",
       "legendFormat": "{{oui}} Tx"
      }
     ]
    },
    {
     "title": "UAP CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "percentunit", "label": "CPU Utilization" }
     ],
     "targets": [
      {
       "expr": "unifipoller_device_cpu_utilization_ratio{site_name=~\"$site\",name=~\"$ap\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Device Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 43 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "unifipoller_device_load_average_1{name=~\"$ap\"}",
       "legendFormat": "{{name}} load1"
      },
      {
       "expr": "unifipoller_device_load_average_15{name=~\"$ap\"}",
       "legendFormat": "{{name}} load15"
      }
     ]
    },
    {
     "title": "UAP Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 43 },
     "yaxes": [
      { "format": "percentunit", "label": "Memory Utilization" }
     ],
     "targets": [
      {
       "expr": "unifipoller_device_memory_utilization_ratio{site_name=~\"$site\",name=~\"$ap\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Networks / UAP",
     "type": "table",
     "description": "The counters in this table represent uptime totals and do not change with the time range selector. [CCQ=(100 - Error_Rate) * Current_TX_Rate / Highest_TX_Rate | Signa Strength - higher absolute number is better | Radio - usually 'na' = 5MHz and 'ng' = 2.4MHz]",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_ccq_ratio{site_name=~\"$site\", name=~\"$ap\"})"
      },
      {
       "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_average_client_signal{site_name=~\"$site\", name=~\"$ap\"})"
      },
      {
       "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_receive_dropped_total{site_name=~\"$site\", name=~\"$ap\"}) "
      },
      {
       "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_transmit_dropped_total{site_name=~\"$site\", name=~\"$ap\"}) "
      },
      {
       "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_transmit_bytes_total{site_name=~\"$site\", name=~\"$ap\"}) "
      },
      {
       "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_receive_bytes_total{site_name=~\"$site\", name=~\"$ap\"}) "
      },
      {
       "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_receive_packets_total{site_name=~\"$site\", name=~\"$ap\"}) "
      },
      {
       "expr": "sum by (bssid,essid,ap_name,name,radio,radio_name,vap_name,site_name,usage,source) (unifipoller_device_vap_transmit_packets_total{site_name=~\"$site\", name=~\"$ap\"}) "
      }
     ]
    },
    {
     "title": "Average AP Client RSSI",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "dBm", "label": "Average Client RSSI" }
     ],
     "targets": [
      {
       "expr": "avg(unifipoller_client_rssi_db{ap_name=~\"$ap\"}) by (ap_name, radio_name)",
       "legendFormat": "{{ap_name}}  {{radio_name}}"
      }
     ]
    },
    {
     "title": "Average AP Client Signal",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "dBm", "label": "Average Client Signal" }
     ],
     "targets": [
      {
       "expr": "unifipoller_device_vap_average_client_signal{name=~\"$ap\"}",
       "legendFormat": "{{name}} {{vap_name}} {{radio}}"
      }
     ]
    },
    {
     "title": "2.4 GHz Client Connection Quality",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "percentunit", "label": "Average CCQ % / VAP" }
     ],
     "targets": [
      {
       "expr": "unifipoller_device_vap_ccq_ratio{site_name=~\"$site\",name=~\"$ap\", radio=\"ng\"}",
       "legendFormat": "{{name}} {{vap_name}}"
      }
     ]
    },
    {
     "title": "5 GHz Client Connection Quality",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "percentunit", "label": "Average CCQ % / VAP" }
     ],
     "targets": [
      {
       "expr": "unifipoller_device_vap_ccq_ratio{site_name=~\"$site\",name=~\"$ap\", radio=\"na\"}",
       "legendFormat": "{{name}} {{vap_name}}"
      }
     ]
    },
    {
     "title": "2.4 GHz Channel Utilization",
     "type": "graph",
     "description": "Displays 2.4GHz usage.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "unifipoller_device_radio_channel_utilization_receive_ratio{radio=\"ng\",site_name=~\"$site\",name=~\"$ap\"}",
       "legendFormat": "{{name}} {{radio}} Rx"
      },
      {
       "expr": "unifipoller_device_radio_channel_utilization_transmit_ratio{radio=\"ng\",site_name=~\"$site\",name=~\"$ap\"}",
       "legendFormat": "{{name}} {{radio}} Tx"
      }
     ]
    },
    {
     "title": "5 GHz Channel Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "unifipoller_device_radio_channel_utilization_receive_ratio{radio=\"na\",site_name=~\"$site\",name=~\"$ap\"}",
       "legendFormat": "{{name}} Rx"
      },
      {
       "expr": "unifipoller_device_radio_channel_utilization_transmit_ratio{radio=\"na\",site_name=~\"$site\",name=~\"$ap\"}",
       "legendFormat": "{{name}} Tx"
      }
     ]
    },
    {
     "title": "2.4 GHz Traffic",
     "type": "graph",
     "description": "RX is on the negative Axis.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_bytes_total{radio=\"ng\",site_name=~\"$site\",name=~\"$ap\"}[5m])) by (name)",
       "legendFormat": "{{name}} Tx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_bytes_total{radio=\"ng\",site_name=~\"$site\",name=~\"$ap\"}[5m])) by (name)",
       "legendFormat": "{{name}} Rx"
      }
     ]
    },
    {
     "title": "5 GHz Traffic",
     "type": "graph",
     "description": "RX is on the negative Axis.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_bytes_total{radio=\"na\",site_name=~\"$site\",name=~\"$ap\"}[5m])) by (name)",
       "legendFormat": "{{name}} Tx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_bytes_total{radio=\"na\",site_name=~\"$site\",name=~\"$ap\"}[5m])) by (name)",
       "legendFormat": "{{name}}  Rx"
      }
     ]
    },
    {
     "title": "2.4 GHz Packets",
     "type": "graph",
     "description": "PPS on the ng band calculated in 30 second buckets. In is on the negative Axis.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "pps", "label": "PPS" }
     ],
     "targets": [
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_packets_total{radio=\"ng\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Out"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_packets_total{radio=\"ng\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} In"
      }
     ]
    },
    {
     "title": "5 GHz Packets",
     "type": "graph",
     "description": "PPS on the na band. In is on the negative Axis.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
     "yaxes": [
      { "format": "pps", "label": "PPS" }
     ],
     "targets": [
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_packets_total{radio=\"na\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Out"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_packets_total{radio=\"na\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} In"
      }
     ]
    },
    {
     "title": "2.4 GHz Drops/Errors",
     "type": "graph",
     "description": "In is on the negative axis.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_dropped_total{radio=\"ng\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Drops Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_dropped_total{radio=\"ng\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Drops Tx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_errors_total{radio=\"ng\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Errors Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_errors_total{radio=\"ng\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Errors Tx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_crypts_total{radio=\"ng\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Crypts Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_frags_total{radio=\"ng\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Frags Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_nwids_total{radio=\"ng\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Nwids Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_retries_total{radio=\"ng\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Retries Tx"
      }
     ]
    },
    {
     "title": "5 GHz Drops/Errors",
     "type": "graph",
     "description": "Visualize packet errors (several types)  per second in the 5GHz band.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 98 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_dropped_total{radio=\"na\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Drops Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_dropped_total{radio=\"na\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Drops Tx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_errors_total{radio=\"na\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Errors Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_errors_total{radio=\"na\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Errors Tx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_crypts_total{radio=\"na\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Crypts Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_frags_total{radio=\"na\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Frags Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_receive_nwids_total{radio=\"na\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Nwids Rx"
      },
      {
       "expr": "sum (rate(unifipoller_device_vap_transmit_retries_total{radio=\"na\",site_name=~\"$site\",name=~\"$ap\"}[$__interval])) by (name)",
       "legendFormat": "{{name}} Retries Tx"
      }
     ]
    }
   ]
  },
  {
   "title": "Unifi-Poller - Client Insights (11315)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Wireless Devices",
     "type": "table",
     "description": "This table represents current (latest) data.\nBytes columns are lifetime totals.",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unifipoller_client_receive_bytes_total{wired!=\"true\", site_name=~\"$site\", name=~\"$wireless\"})"
      },
      {
       "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unifipoller_client_transmit_bytes_total{wired!=\"true\",site_name=~\"$site\", name=~\"$wireless\"})"
      },
      {
       "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (\n unifipoller_client_uptime_seconds{wired!=\"true\",site_name=~\"$site\", name=~\"$wireless\"})"
      },
      {
       "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (unifipoller_client_rssi_db{wired!=\"true\",site_name=~\"$site\", name=~\"$wireless\"})"
      },
      {
       "expr": "sum by (channel,essid,ip,mac,name,network,oui,radio_desc,site_name,source) (unifipoller_client_radio_signal_db{wired!=\"true\",site_name=~\"$site\", name=~\"$wireless\"})"
      }
     ]
    },
    {
     "title": "Clients / Channel",
     "type": "grafana-piechart-panel",
     "description": "Visualize wireless channel usage w/ wired client counts.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 18 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count (unifipoller_client_roam_count_total{name=~\"$wireless\", ap_name=~\"$ap\"}) by (channel) ",
       "legendFormat": "Channel {{channel}}"
      }
     ]
    },
    {
     "title": "Clients / AP Radio",
     "type": "grafana-piechart-panel",
     "description": "Visualize how many clients are connected to which radios/APs.",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 18 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count by (radio_proto) (unifipoller_client_roam_count_total{site_name=~\"$site\", name=~\"$wireless\", ap_name=~\"$ap\"})",
       "legendFormat": "{{radio_proto}}"
      }
     ]
    },
    {
     "title": "Client MAC OUI Breakdown",
     "type": "grafana-piechart-panel",
     "description": "This shows an OUI breakdown from Unifi's perspective. e = wired, w = wireless",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 18 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "count by (oui) (unifipoller_client_uptime_seconds{site_name=~\"$site\", name=~\"$wireless\", ap_name=~\"$ap\"})",
       "legendFormat": "{{oui}}"
      }
     ]
    },
    {
     "title": "UAP Bandwidth / Wireless Devices",
     "type": "graph",
     "description": "Bandwidth usage per wireless devices as reported by the UAPs. Rx is on the negative axis. Does not include amazon devices.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "Bps", "label": "bytes / sec" }
     ],
     "targets": [
      {
       "expr": "sum by ($identifier) (rate(unifipoller_client_transmit_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$wireless\", site_name=~\"$site\", ap_name=~\"$ap\"}[$__rate_interval]))",
       "legendFormat": "{{name}} {{mac}} Tx"
      },
      {
       "expr": "sum by ($identifier) (rate(unifipoller_client_receive_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$wireless\", site_name=~\"$site\", ap_name=~\"$ap\"}[$__rate_interval]))",
       "legendFormat": "{{name}} {{mac}} Rx"
      }
     ]
    },
    {
     "title": "Data Transferred / Wireless Devices",
     "type": "graph",
     "description": "Bandwidth usage per wireless devices as reported by the UAPs. Rx is on the negative axis. Does not include amazon devices.",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "decbytes", "label": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum by ($identifier) (increase(unifipoller_client_transmit_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$wireless\", site_name=~\"$site\", ap_name=~\"$ap\"}[$__rate_interval]))",
       "legendFormat": "{{name}} {{mac}} Tx"
      },
      {
       "expr": "sum by ($identifier) (increase(unifipoller_client_receive_bytes_total{name!~\".*camera.*|.*cam(era)?$\", name=~\"$wireless\", site_name=~\"$site\", ap_name=~\"$ap\"}[$__rate_interval]))",
       "legendFormat": "{{name}} {{mac}} Rx"
      }
     ]
    },
    {
     "title": "Client Bandwidth / Echos & FireTVs",
     "type": "graph",
     "description": "Amazon Devices TX / RX bytes per second. Rx is on the negative axis. My home network has a ton of Amazon devices, so I broke them out separately. If you don't have Amazon devices, or they have different names, you can edit the query to use a different name. e = wired, w = wireless",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "Bps", "label": "bytes / sec" }
     ],
     "targets": [
      {
       "expr": "sum by ($identifier) (rate(unifipoller_client_transmit_bytes_total{oui=~\"^[aA]mazon.*\", name=~\"$wireless\", site_name=~\"$site\", ap_name=~\"$ap\"}[$__rate_interval]))",
       "legendFormat": "w {{name}} {{mac}} Tx"
      },
      {
       "expr": "sum by ($identifier) (rate(unifipoller_client_receive_bytes_total{oui=~\"^[aA]mazon.*\", name=~\"$wireless\", site_name=~\"$site\", ap_name=~\"$ap\"}[$__rate_interval]))",
       "legendFormat": "w {{name}} {{mac}} Rx"
      }
     ]
    },
    {
     "title": "Client Bandwidth: Cameras",
     "type": "graph",
     "description": "Cameras TX / RX bytes per second. Rx is on the negative axis. This graph shows any device with the word \"camera\" in its name and has nothing to do with UniFi Protect/video products. e = wired, w = wireless",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "Bps", "label": "bytes / sec" }
     ],
     "targets": [
      {
       "expr": "sum by ($identifier) (rate(unifipoller_client_transmit_bytes_total{ap_name=~\"$ap\", name=~\".*camera.*|.*cam$\", site_name=~\"$site\"}[$__rate_interval]))",
       "legendFormat": "w {{name}} {{mac}} Tx"
      },
      {
       "expr": "sum by ($identifier) (rate(unifipoller_client_receive_bytes_total{ap_name=~\"$ap\", name=~\".*camera.*|.*cam$\", site_name=~\"$site\"}[$__rate_interval]))",
       "legendFormat": "w {{name}} {{mac}} Rx"
      }
     ]
    },
    {
     "title": "Received Signal Strength Indicator",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "dB", "label": "RSSI Quality" }
     ],
     "targets": [
      {
       "expr": "sum by ($identifier) (unifipoller_client_rssi_db{ap_name=~\"$ap\", site_name=~\"$site\", name=~\"$wireless\"})",
       "legendFormat": "{{name}} {{mac}}"
      }
     ]
    },
    {
     "title": "Wireless Signal",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "dBm", "label": "Signal Power" }
     ],
     "targets": [
      {
       "expr": "sum by ($identifier) (unifipoller_client_radio_signal_db{ap_name=~\"$ap\", site_name=~\"$site\", name=~\"$wireless\"})",
       "legendFormat": "{{name}} {{mac}}"
      }
     ]
    },
    {
     "title": "UAP Client Stats / Noise",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "yaxes": [
      { "format": "dB", "label": "Noise" }
     ],
     "targets": [
      {
       "expr": "sum by ($identifier) (unifipoller_client_noise_db{ap_name=~\"$ap\", site_name=~\"$site\", name=~\"$wireless\"})",
       "legendFormat": "{{name}} {{mac}}"
      }
     ]
    },
    {
     "title": "TX Rate",
     "type": "graph",
     "description": "Client reported transmit rate.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum by ($identifier) (unifipoller_client_radio_transmit_rate_bps{ap_name=~\"$ap\", site_name=~\"$site\", name=~\"$wireless\"})",
       "legendFormat": "{{name}} {{mac}}"
      }
     ]
    },
    {
     "title": "Client Wifi Tx Attempts",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
     "yaxes": [
      { "format": "short", "label": "Attempts / Second" }
     ],
     "targets": [
      {
       "expr": "avg by ($identifier) (rate(unifipoller_client_wifi_attempts_transmit_total{ap_name=~\"$ap\", site_name=~\"$site\", name=~\"$wireless\"}[$__interval]))",
       "legendFormat": "{{name}} {{mac}}"
      }
     ]
    },
    {
     "title": "RX Rate",
     "type": "graph",
     "description": "Client reported receive rate.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
     "yaxes": [
      { "format": "bps" }
     ],
     "targets": [
      {
       "expr": "sum by ($identifier) (unifipoller_client_radio_receive_rate_bps{ap_name=~\"$ap\", site_name=~\"$site\", name=~\"$wireless\"})",
       "legendFormat": "{{name}} {{mac}}"
      }
     ]
    },
    {
     "title": "Client Transmit Retries",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
     "yaxes": [
      { "format": "short", "label": "Tx Retries / Second" }
     ],
     "targets": [
      {
       "expr": "sum by ($identifier) (rate(unifipoller_client_transmit_retries_total{ap_name=~\"$ap\", site_name=~\"$site\", name=~\"$wireless\"}[$__interval]))",
       "legendFormat": "{{name}} {{mac}}"
      }
     ]
    },
    {
     "title": "Client Transmit Power",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
     "yaxes": [
      { "format": "dBm", "label": "Transmit Power dBm" }
     ],
     "targets": [
      {
       "expr": "sum by ($identifier) (unifipoller_client_radio_transmit_power_dbm{ap_name=~\"$ap\", site_name=~\"$site\", name=~\"$wireless\"})",
       "legendFormat": "{{name}} {{mac}}"
      }
     ]
    },
    {
     "title": "Client Anomalies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
     "yaxes": [
      { "format": "short", "label": "Anomalies" }
     ],
     "targets": [
      {
       "expr": "sum by ($identifier) (unifipoller_client_anomalies{ap_name=~\"$ap\", site_name=~\"$site\", name=~\"$wireless\"})",
       "legendFormat": "{{name}} {{mac}}"
      }
     ]
    },
    {
     "title": "Client Satisfaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
     "yaxes": [
      { "format": "percentunit", "label": "Client Satisfaction" }
     ],
     "targets": [
      {
       "expr": "sum by ($identifier) (unifipoller_client_satisfaction_ratio{ap_name=~\"$ap\", site_name=~\"$site\", name=~\"$wireless\"})",
       "legendFormat": "{{name}} {{mac}}"
      }
     ]
    },
    {
     "title": "Roam Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
     "yaxes": [
      { "format": "short", "label": "Roam Count" }
     ],
     "targets": [
      {
       "expr": "sum by ($identifier) (unifipoller_client_roam_count_total{ap_name=~\"$ap\", site_name=~\"$site\", name=~\"$wireless\"})",
       "legendFormat": "{{name}} {{mac}}"
      }
     ]
    },
    {
     "title": "Client Connection Quality %",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
     "yaxes": [
      { "format": "percentunit", "label": "CCQ" }
     ],
     "targets": [
      {
       "expr": "sum by ($identifier) (unifipoller_client_ccq_ratio{ap_name=~\"$ap\", site_name=~\"$site\", name=~\"$wireless\"})",
       "legendFormat": "{{name}} {{mac}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SNMP Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "$host",
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "sysName" ], "type": "tag" }
       ],
       "measurement": "snmp.UAP",
       "select": [
        [
         { "params": [ "unifiApSystemModel" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Model" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiApSystemVersion" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Version" ], "type": "alias" }
        ],
        [
         { "params": [ "sysDescr" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Description" ], "type": "alias" }
        ],
        [
         { "params": [ "sysContact" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Contact" ], "type": "alias" }
        ],
        [
         { "params": [ "sysLocation" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Location" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "snmp.UAP",
       "select": [
        [
         { "params": [ "sysUpTime" ], "type": "field" },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "na Radio Channel",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "unifiVapTable",
       "select": [
        [
         { "params": [ "unifiVapChannel" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "na" }
       ]
      }
     ]
    },
    {
     "title": "na Radio  Tx Power",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 9, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "unifiVapTable",
       "select": [
        [
         { "params": [ "unifiVapTxPower" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "na" }
       ]
      }
     ]
    },
    {
     "title": "ng Radio Channel",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "unifiVapTable",
       "select": [
        [
         { "params": [ "unifiVapChannel" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "unifiVapRadio", "operator": "=", "value": "ng" }
       ]
      }
     ]
    },
    {
     "title": "ng Radio Tx Power",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "unifiVapTable",
       "select": [
        [
         { "params": [ "unifiVapTxPower" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "unifiVapName", "operator": "=", "value": "ath1" }
       ]
      }
     ]
    },
    {
     "title": "Stations",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$tag_unifiVapName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "unifiVapName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unifiVapTable",
       "select": [
        [
         { "params": [ "unifiVapNumStations" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "unifiVapName", "operator": "=~", "value": "/^$vap$/" },
        { "condition": "AND", "key": "unifiVapRadio", "operator": "=~", "value": "/^$radio$/" }
       ]
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snmp.UAP",
       "select": [
        [
         { "params": [ "memBuffer" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Buffer" ], "type": "alias" }
        ],
        [
         { "params": [ "memCached" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Cache" ], "type": "alias" }
        ],
        [
         { "params": [ "memTotalFree" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "Free" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    },
    {
     "title": "Other BSS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_unifiRadioName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "unifiRadioName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unifiRadioTable",
       "select": [
        [
         { "params": [ "unifiRadioOtherBss" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "unifiRadioRadio", "operator": "=~", "value": "/^$radio$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SNMP Wifi Utilisation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "802.11 (Wifi) Channel Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 230 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_unifiRadioName:$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "unifiRadioName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unifiRadioTable",
       "select": [
        [
         { "params": [ "unifiRadioCuSelfRx" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 10" ], "type": "math" },
         { "params": [ "Rx" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiRadioCuSelfTx" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 10" ], "type": "math" },
         { "params": [ "Tx" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiRadioCuTotal" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 10" ], "type": "math" },
         { "params": [ "Busy" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "unifiRadioRadio", "operator": "=~", "value": "/^$radio$/" }
       ]
      }
     ]
    },
    {
     "title": "802.11 (Wifi) Traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 237 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "$tag_unifiVapName:$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "unifiVapName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unifiVapTable",
       "select": [
        [
         { "params": [ "unifiVapRxBytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "In" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiVapTxBytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "*-8" ], "type": "math" },
         { "params": [ "Out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "unifiVapName", "operator": "=~", "value": "/^$vap$/" },
        { "condition": "AND", "key": "unifiVapRadio", "operator": "=~", "value": "/^$radio$/" }
       ]
      }
     ]
    },
    {
     "title": "802.11 (Wifi) Traffic Distribution",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 244 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "$tag_unifiVapName:$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "unifiVapName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unifiVapTable",
       "select": [
        [
         { "params": [ "unifiVapRxPackets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "In" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiVapTxPackets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "*-1" ], "type": "math" },
         { "params": [ "Out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "unifiVapName", "operator": "=~", "value": "/^$vap$/" },
        { "condition": "AND", "key": "unifiVapRadio", "operator": "=~", "value": "/^$radio$/" }
       ]
      }
     ]
    },
    {
     "title": "802.11 (Wifi) Drops/Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 251 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "$tag_unifiVapName:$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "unifiVapName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unifiVapTable",
       "select": [
        [
         { "params": [ "unifiVapRxDropped" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "Drop:In" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiVapTxDropped" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "*-1" ], "type": "math" },
         { "params": [ "Drop:Out" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiVapRxErrors" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "Error:In" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiVapTxErrors" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "*-1" ], "type": "math" },
         { "params": [ "Error:Out" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiVapRxCrypts" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "BadCrypt:In" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiVapRxFrags" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "BadFrag:In" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiVapTxRetries" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "derivative" },
         { "params": [ "*-1" ], "type": "math" },
         { "params": [ "ExsRetry:Out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "unifiVapName", "operator": "=~", "value": "/^$vap$/" },
        { "condition": "AND", "key": "unifiVapRadio", "operator": "=~", "value": "/^$radio$/" }
       ]
      }
     ]
    },
    {
     "title": "All Interface Drops/Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 258 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "alias": "$tag_ifDescr:$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "ifDescr" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ifTable",
       "query": "SELECT non_negative_derivative(last(\"ifInDiscards\"), 1s) AS \"Drop:In\", non_negative_derivative(last(\"ifOutDiscards\"), 1s) AS \"Drop:Out\", non_negative_derivative(last(\"ifInErrors\"), 1s) AS \"Error:In\", non_negative_derivative(last(\"ifOutErrors\"), 1s) AS \"Error:Out\", non_negative_derivative(last(\"ifInUnknownProtos\"), 1s) AS \"Unkwn:In\" FROM \"ifTable\" WHERE \"agent_host\" =~ /^$host$/ AND \"ifOperStatus\" = 1 AND $timeFilter GROUP BY time($__interval), \"ifDescr\" fill(null)",
       "select": [
        [
         { "params": [ "ifInDiscards" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Drop:In" ], "type": "alias" }
        ],
        [
         { "params": [ "ifOutDiscards" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Drop:Out" ], "type": "alias" }
        ],
        [
         { "params": [ "ifInErrors" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Error:In" ], "type": "alias" }
        ],
        [
         { "params": [ "ifOutErrors" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Error:Out" ], "type": "alias" }
        ],
        [
         { "params": [ "ifInUnknownProtos" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Unkwn:In" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "ifOperStatus", "operator": "=", "value": "1" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SNMP Ethernet Utilisation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "802.3 (Wired) Traffic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 266 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "alias": "$tag_unifiIfName:$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "unifiIfName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unifiIfTable",
       "select": [
        [
         { "params": [ "unifiIfRxBytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*8" ], "type": "math" },
         { "params": [ "In" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiIfTxBytes" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*-8" ], "type": "math" },
         { "params": [ "Out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "unifiIfName", "operator": "=~", "value": "/^$intf$/" }
       ]
      }
     ]
    },
    {
     "title": "802.3 (Wired) Traffic Distribution",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 273 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "$tag_unifiIfName:$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "unifiIfName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unifiIfTable",
       "select": [
        [
         { "params": [ "unifiIfRxPackets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Ucast:In" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiIfTxPackets" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*-1" ], "type": "math" },
         { "params": [ "Ucast:Out" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiIfRxMulticast" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Mcast:In" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "unifiIfName", "operator": "=~", "value": "/^$intf$/" }
       ]
      }
     ]
    },
    {
     "title": "802.3 (Wired) Drops/Errors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 280 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "alias": "$tag_unifiIfName:$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "unifiIfName" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "unifiIfTable",
       "select": [
        [
         { "params": [ "unifiIfRxDropped" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Drop:In" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiIfTxDropped" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*-1" ], "type": "math" },
         { "params": [ "Drop:Out" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiIfRxError" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "Error:In" ], "type": "alias" }
        ],
        [
         { "params": [ "unifiIfTxError" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "1s" ], "type": "non_negative_derivative" },
         { "params": [ "*-1" ], "type": "math" },
         { "params": [ "Error:Out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "unifiIfName", "operator": "=~", "value": "/^$intf$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "SNMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SNMP Messages (/min)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snmp.UAP",
       "select": [
        [
         { "params": [ "snmpInPkts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" },
         { "params": [ "Msgs:In" ], "type": "alias" }
        ],
        [
         { "params": [ "snmpOutPkts" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" },
         { "params": [ "*-1" ], "type": "math" },
         { "params": [ "Msgs:Out" ], "type": "alias" }
        ],
        [
         { "params": [ "snmpInGetResponses" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" },
         { "params": [ "GetResp:In" ], "type": "alias" }
        ],
        [
         { "params": [ "snmpOutGetResponses" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" },
         { "params": [ "*-1" ], "type": "math" },
         { "params": [ "GetResp:Out" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
       ]
      },
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_derivative(mean(\"allReqIn\"), 1m) AS \"GetReq:In\", non_negative_derivative(mean(\"allReqOut\"), 1m) AS \"GetReq:Out\" FROM ( SELECT \"snmpInGetRequests\"+\"snmpInGetNexts\" AS \"allReqIn\", \"snmpOutGetRequests\"+\"snmpOutGetNexts\" AS \"allReqOut\" FROM \"snmp.UAP\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter) WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "SNMP Objects Retrieved (/min)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$col",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "snmp.UAP",
       "select": [
        [
         { "params": [ "snmpInTotalReqVars" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1m" ], "type": "non_negative_derivative" },
         { "params": [ "Objects" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}