{
 "title": "Crowdsec - Details per Machine",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "machine", "label": "machine", "query": { "query": "label_values(up, machine)" } },
   {
    "name": "datasource_type",
    "query": {
     "query": "label_values(cs_parsing_time_seconds_bucket{machine=\"$machine\"}, type)"
    }
   },
   {
    "name": "source",
    "query": {
     "query": "label_values(cs_parsing_time_seconds_bucket{machine=\"$machine\", type=\"$datasource_type\"}, source)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Process Mem Usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{machine=\"$machine\"}"
      }
     ]
    },
    {
     "title": "Process CPU Usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{machine=\"$machine\"}[$__interval])*100"
      }
     ]
    },
    {
     "title": "Up Since",
     "type": "stat",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(process_start_time_seconds{machine=\"$machine\"})*1000"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Alerts Count",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(cs_alerts)" }
     ]
    },
    {
     "title": "Alerts per Scenario",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "cs_alerts{machine=\"$machine\"}",
       "legendFormat": "{{reason}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Parsing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Acquisition",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_filesource_hits_total{machine=\"$machine\"}[$__interval])) by (source)",
       "legendFormat": "{{source}}"
      },
      {
       "expr": "sum(increase(cs_journalctlsource_hits_total{machine=\"$machine\"}[$__interval])) by (source)",
       "legendFormat": "{{source}}"
      },
      {
       "expr": "sum(increase(cs_cloudwatch_stream_hits_total{machine=\"$machine\"}[$__interval])) by (group, stream)",
       "legendFormat": "{{group}} - {{stream}}"
      },
      {
       "expr": "sum(increase(cs_syslogsource_hits_total{machine=\"$machine\"}[$__interval])) by (source)"
      }
     ]
    },
    {
     "title": "Parsed lines",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_parser_hits_ok_total{machine=\"$machine\"}[$__interval])) by (source)",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Unparsed lines",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_parser_hits_ko_total{machine=\"$machine\"}[$__interval])) by (source)",
       "legendFormat": "{{source}}"
      }
     ]
    },
    {
     "title": "Parsing time",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cs_parsing_time_seconds_bucket{machine=\"$machine\", type=\"$datasource_type\", source=\"$source\"}",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Bucket Timeline",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(cs_buckets{machine=\"$machine\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buckets creation",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_bucket_created_total{machine=\"$machine\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buckets overflow",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_bucket_overflowed_total{machine=\"$machine\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Buckets underflow",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(cs_bucket_underflowed_total{machine=\"$machine\"}[$__interval])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Bucket pour time",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 37 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "cs_bucket_pour_seconds_bucket{machine=\"$machine\", type=\"$datasource_type\", source=\"$source\"}",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}