{
 "title": "Frigate (18226)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Frigate Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "frigate_service_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inference Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frigate_detector_inference_speed_seconds*1000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(frigate_cpu_usage_percent)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(frigate_mem_usage_percent)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Recording Storage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "frigate_storage_used_bytes{storage=\"/media/frigate/recordings\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "frigate_storage_free_bytes{storage=\"/media/frigate/recordings\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Inference Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "frigate_detector_inference_speed_seconds",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Storage Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "frigate_storage_total_bytes", "legendFormat": "{{storage}}" }
   ]
  },
  {
   "title": "Detection FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    { "expr": "frigate_detection_fps", "legendFormat": "{{camera_name}}" },
    { "expr": "frigate_detection_total_fps", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Storage Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "frigate_storage_used_bytes", "legendFormat": "{{storage}}" }
   ]
  },
  {
   "title": "Total Detection Frames Processed over 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "tfp" } },
   "targets": [
    {
     "expr": "sum_over_time(frigate_detection_fps[24h])",
     "legendFormat": "{{camera_name}}"
    }
   ]
  },
  {
   "title": "Storage Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "frigate_storage_free_bytes", "legendFormat": "{{storage}}" }
   ]
  },
  {
   "title": "Camera FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    { "expr": "frigate_camera_fps", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "GPU utilisation %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "frigate_gpu_usage_percent", "legendFormat": "{{gpu_name}}" }
   ]
  },
  {
   "title": "Skipped FPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "fps" } },
   "targets": [
    { "expr": "frigate_skipped_fps", "legendFormat": "{{camera_name}}" }
   ]
  },
  {
   "title": "GPU memory usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "frigate_gpu_mem_usage_percent", "legendFormat": "{{gpu_name}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(frigate_cpu_usage_percent{type!~\"Camera|Detector\"})",
     "legendFormat": "Other Processes"
    },
    {
     "expr": "sum by(name, process) (frigate_cpu_usage_percent{type=~\"Camera|Detector\"})",
     "legendFormat": "{{name}} {{process}} {{pid}}"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=~\"frigate.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name, process) (frigate_mem_usage_percent{type=~\"Camera|Detector\"})",
     "legendFormat": "{{name}} {{process}} {{pid}}"
    },
    {
     "expr": "sum(frigate_mem_usage_percent{type!~\"Camera|Detector\"})",
     "legendFormat": "Other Processes"
    }
   ]
  },
  {
   "title": "Number Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "count(frigate_cpu_usage_percent)",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(frigate_mem_usage_percent)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "sum(frigate_cpu_usage_percent)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "sum(frigate_mem_usage_percent)", "legendFormat": "Total" }
   ]
  }
 ]
}