{
 "title": "Home Automation",
 "tags": [
  "energy",
  "influxdb",
  "octopus",
  "octograph",
  "home assistant",
  "home automation",
  "production"
 ],
 "time": { "from": "now-8d", "to": "now-1d" },
 "templating": {
  "list": [
   { "name": "entity", "label": "Entity", "query": { "query": "label_values(entity)" } },
   { "name": "domain", "label": "Domain", "query": { "query": "label_values(domain)" } },
   {
    "name": "ha_entities",
    "label": "Home Assistant Entities",
    "query": {
     "query": "label_values(ha_entity_available{entity!~\"device.*|automation.*\",entity=~\".*humidity.*|.*temperature.*|climate.*|.*power.*|.*energy.*|.*consumption.*\"}, entity)"
    }
   },
   {
    "name": "ha_test_entities",
    "label": "Home Assistant Entities (Test Instance)",
    "query": {
     "query": "label_values(ha_test_entity_available{entity!~\"device.*|automation.*\",entity=~\".*humidity.*|.*temperature.*|climate.*|.*power.*|.*energy.*|.*consumption.*\"}, entity)"
    }
   },
   { "name": "gas_cal_value", "label": "(Gas) Calorific Value ", "query": "39.6" },
   { "name": "gas_vol_correction", "label": "(Gas) Volumetric Correction", "query": "1.02264" },
   {
    "name": "interval_octo",
    "label": "Octopus Interval",
    "query": "30m,1h,2h,3h,4h,6h,12h,1d,2d,7d,14d,30d"
   },
   {
    "name": "interval_shelly",
    "label": "Shelly Interval",
    "query": "30m,1h,2h,3h,4h,6h,12h,1d,2d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "'Master' Charts - for copying & customising",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  { "gridPos": { "h": 9, "w": 22, "x": 0, "y": 1 } },
  { "gridPos": { "h": 4, "w": 12, "x": 0, "y": 10 } },
  {
   "title": "Home Assistant",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Climate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 20, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "ha_climate_current_temperature_celsius{friendly_name=\"Living Room\"}",
       "legendFormat": "{{friendly_name}} Temperature"
      },
      {
       "expr": "ha_climate_target_temperature_celsius{friendly_name=\"Living Room\"}",
       "legendFormat": "{{friendly_name}} Temperature - Target"
      },
      {
       "expr": "ha_sensor_humidity_percent{friendly_name=\"Living Room Humidity\"}\n",
       "legendFormat": "{{friendly_name}}"
      },
      {
       "expr": "ha_sensor_humidity_percent{friendly_name=\"OpenWeatherMap Humidity\"}",
       "legendFormat": "{{friendly_name}}"
      },
      {
       "expr": "ha_sensor_temperature_celsius{entity=\"sensor.openweathermap_temperature\"}",
       "legendFormat": "{{friendly_name}}"
      }
     ]
    },
    {
     "title": "Battery Levels",
     "type": "gauge",
     "gridPos": { "h": 22, "w": 4, "x": 20, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{__name__=~\"ha.*battery.*\"}",
       "legendFormat": "{{friendly_name}}"
      }
     ]
    },
    {
     "title": "Temperatures",
     "type": "stat",
     "gridPos": { "h": 11, "w": 20, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{__name__=~\"ha.*temperature.*\"}",
       "legendFormat": "{{friendly_name}}"
      },
      {
       "expr": "{__name__=~\"ha.*unit_celsius.*\"}",
       "legendFormat": "{{friendly_name}}"
      }
     ]
    },
    {
     "title": "Humidity",
     "type": "stat",
     "gridPos": { "h": 11, "w": 20, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "{__name__=~\"ha.*humidity.*\"}",
       "legendFormat": "{{friendly_name}}"
      }
     ]
    },
    {
     "title": "Temperature & Humidity (Entity Filter)",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "ha_climate_current_temperature_celsius !=0",
       "legendFormat": "Temp - Nest ({{entity}})"
      },
      {
       "expr": "ha_sensor_temperature_celsius{entity=\"sensor.openweathermap_temperature\"} !=0",
       "legendFormat": "Temp - Outside: OpenWeatherMap ({{entity}})"
      },
      {
       "expr": "{__name__=~\"ha.*temperature.*\", entity=~\"$ha_entities\"}",
       "legendFormat": "Temp - {{friendly_name}} ({{entity}})"
      },
      {
       "expr": "{__name__=~\"ha.*humidity.*\", entity=~\"$ha_entities\"}",
       "legendFormat": "Humidity - {{friendly_name}} ({{entity}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Power Costs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Octopus Energy - Consumption (per $interval_octo)",
   "type": "timeseries",
   "description": "Source: Octograph (& Octopus API via curl into NodeExporter for pricing)",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum_over_time(electricity_consumption[$interval_octo:30m]) offset -30m",
     "legendFormat": "Electricity Consumption - kWh (Octograph)"
    },
    {
     "expr": "sum_over_time(gas_consumption[$interval_octo:30m]) offset -30m * $gas_cal_value * $gas_vol_correction / 3.6",
     "legendFormat": "Gas Consumption - kWh"
    }
   ]
  },
  {
   "title": "Electricity & Gas Pricing",
   "type": "stat",
   "description": "Source: Octopus API via curl -> NodeExporter",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(node_octopus_energy_standingcharge_electricity_pence[$__interval]) / 100",
     "legendFormat": "Electricity - Standing Charge (per day)"
    },
    {
     "expr": "avg_over_time(node_octopus_energy_unitrate_electricity_pence[$__interval]) / 100",
     "legendFormat": "Electricity - Unit Rate (per kWh)"
    },
    {
     "expr": "avg_over_time(node_octopus_energy_standingcharge_gas_pence[$__interval]) / 100",
     "legendFormat": "Gas - Standing Charge (per day)"
    },
    {
     "expr": "avg_over_time(node_octopus_energy_unitrate_gas_pence[$__interval]) / 100",
     "legendFormat": "Gas - Unit Rate (per kWh)"
    }
   ]
  },
  {
   "title": "Energy Supply - Gas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Gas Calculations",
     "type": "text",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 5 },
     "options": {
      "content": "<table style=\"border-collapse: collapse; width: 100%;\" border=\"1\">\n<tbody>\n<tr>\n<td style=\"width: 3.66975%; text-align: left;\" colspan=\"2\"><strong>Consumption in kWh</strong></td>\n</tr>\n<tr>\n<td style=\"width: 3.66975%; text-align: center;\">&nbsp;</td>\n<td style=\"width: 96.3303%;\">Meter Reading <em>(in m&sup3;)</em></td>\n</tr>\n<tr>\n<td style=\"width: 3.66975%; text-align: center;\">x</td>\n<td style=\"width: 96.3303%;\">Volumetric Correction<em> (pressure/temp)</em></td>\n</tr>\n<tr>\n<td style=\"width: 3.66975%; text-align: center;\">x</td>\n<td style=\"width: 96.3303%;\">Calorific Value <em>(energy in each m&sup3;)</em></td>\n</tr>\n<tr>\n<td style=\"width: 3.66975%; text-align: center;\">&divide;</td>\n<td style=\"width: 96.3303%;\">3.6 <em>(convert from joules)</em></td>\n</tr>\n</tbody>\n</table>"
     }
    },
    {
     "title": "Octopus Energy - Consumption & Cost (per day)",
     "type": "stat",
     "description": "Source: Octograph (& Octopus API via curl into NodeExporter for pricing)",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "present_over_time(node_octopus_energy_standingcharge_gas_pence[1d:30m])",
       "legendFormat": "Days"
      },
      {
       "expr": "avg_over_time(node_octopus_energy_standingcharge_electricity_pence[1d:12h] / 100) offset -3d",
       "legendFormat": "Electric - Standing Charge Cost"
      },
      {
       "expr": "sum_over_time(electricity_consumption[1d:30m]) offset -2d",
       "legendFormat": "Electricity Consumption - kWh"
      },
      {
       "expr": "avg_over_time(node_octopus_energy_unitrate_electricity_pence[1d:12h] / 100) offset -3d",
       "legendFormat": "Electric - Per kWh (Unit Charge)"
      },
      {
       "expr": "avg_over_time(node_octopus_energy_standingcharge_gas_pence[1d:12h] / 100) offset -3d",
       "legendFormat": "Gas - Standing Charge Cost"
      },
      {
       "expr": "sum_over_time(gas_consumption[1d:30m]) offset -2d",
       "legendFormat": "Gas Consumption - m³"
      },
      {
       "expr": "sum_over_time(gas_consumption[1d:30m]) offset -2d * $gas_cal_value * $gas_vol_correction / 3.6",
       "legendFormat": "Gas Consumption - kWh"
      },
      {
       "expr": "avg_over_time(node_octopus_energy_unitrate_gas_pence[1d:12h] / 100) offset -3d",
       "legendFormat": "Gas - Per kWh (Unit Charge)"
      }
     ]
    },
    {
     "title": "Gas Cost - Standing Charge",
     "type": "stat",
     "gridPos": { "h": 4, "w": 2, "x": 18, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "present_over_time(node_octopus_energy_standingcharge_gas_pence[$__interval])",
       "legendFormat": "Days"
      },
      {
       "expr": "node_octopus_energy_standingcharge_gas_pence / 100",
       "legendFormat": "Standing Charge"
      }
     ]
    },
    {
     "title": "Gas UNIT Usage Cost in Interval",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "gas",
       "query": "SELECT sum(\"cost\")/100 FROM \"gas\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "cost" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ]
      },
      { "expr": "gas_unit_charge / 100", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Gas effective unit cost (/ m^3)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "electricity",
       "query": "SELECT sum(\"total_cost\")  / sum(\"consumption\") / 100 FROM \"electricity\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "total_cost" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Gas cost (total)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "electricity",
       "query": "SELECT sum(\"total_cost\")/100 FROM \"gas\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "total_cost" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Gas Used",
     "type": "barchart",
     "description": "Source: Consumption=Octopus; Cost=Octopus\nOctopus reports every 24hrs so we can only start with previous day's readings to compare.",
     "gridPos": { "h": 13, "w": 9, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum_over_time(gas_consumption[$__interval:30m])",
       "legendFormat": "Gas - m³"
      },
      {}
     ]
    },
    {
     "title": "Gas used",
     "type": "stat",
     "description": "Source: Octograph\n(based on per day calcs)",
     "gridPos": { "h": 4, "w": 2, "x": 22, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "alias": "Influx - m³",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "gas",
       "query": "SELECT sum(\"consumption\") FROM \"gas\" WHERE $timeFilter GROUP BY time(1d,-1h) fill(linear)",
       "select": [
        [
         { "params": [ "consumption" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ]
      },
      {
       "expr": "sum_over_time(gas_consumption[1d:30m]) offset -2d",
       "legendFormat": "m³"
      },
      {
       "expr": "sum_over_time(gas_consumption[1d:30m]) offset -2d * $gas_cal_value * $gas_vol_correction / 3.6",
       "legendFormat": "kWh"
      }
     ]
    },
    {
     "title": "Gas used",
     "type": "stat",
     "description": "Source: Octograph\n(based on per day calcs)",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "m3" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "sum_over_time(gas_consumption[1d:30m]) offset -2d",
       "legendFormat": "m³"
      },
      {
       "expr": "sum_over_time(gas_consumption[1d:30m]) offset -2d * $gas_cal_value * $gas_vol_correction / 3.6",
       "legendFormat": "kWh"
      },
      {
       "expr": "avg_over_time(node_octopus_energy_unitrate_gas_pence[1d:12h] / 100) !=0",
       "legendFormat": "Avg Cost"
      }
     ]
    }
   ]
  },
  {
   "title": "Energy Supply - Electricity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Cumulative Power (over Full Time Range)",
   "type": "timeseries",
   "description": "Source: ShellyEM",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Cumulative Sum",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "shellyem",
     "select": [
      [
       { "params": [ "0_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power Now",
   "type": "gauge",
   "description": "Source: ShellyEM",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "shellyem_0_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Instantaneous Power (last 24h)",
   "type": "timeseries",
   "description": "Source: ShellyEM",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "shellyem_0_power", "legendFormat": "Power (Shelly EM)" }
   ]
  },
  {
   "title": "ShellyEM: Total Power for Interval",
   "type": "stat",
   "description": "Source: ShellyEM",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "ShellyEM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "shellyem",
     "select": [
      [
       { "params": [ "0_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "ShellyEM: Cost for Unit Usage in Interval (Est)",
   "type": "stat",
   "description": "Source: ShellyEM\nExcluding Standing Charge of 21.17p/day",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "ShellyEM Use",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "shellyem",
     "select": [
      [
       { "params": [ "0_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "description": "Source: ShellyEM",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "shellyem",
     "select": [
      [
       { "params": [ "0_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Octopus: Total Power for Interval",
   "type": "stat",
   "description": "Source: Octopus",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Octopus",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Octopus: UNIT Usage Cost in Interval",
   "type": "stat",
   "description": "Source: Octopus\nExcluding Standing Charge of 21.17p/day",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Octopus Cost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instantaneous Power (Full Time Range)",
   "type": "timeseries",
   "description": "Source: ShellyEM",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "shellyem_0_power", "legendFormat": "Power (ShellyEM)" }
   ]
  },
  {
   "title": "Octopus: Total Cost in Interval",
   "type": "stat",
   "description": "Source: Octopus\nIncluding Standing Charge of 21.17p/day",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Octopus Cost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "total_cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Octopus: Effective Unit Cost",
   "type": "stat",
   "description": "Source: Octopus",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Octopus Cost",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT (sum(\"total_cost\") / sum(\"consumption\"))/100 FROM \"electricity\" WHERE $timeFilter ",
     "select": [
      [
       { "params": [ "total_cost" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hourly Average",
   "type": "stat",
   "description": "Source: ShellyEM",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "shellyem",
     "select": [
      [
       { "params": [ "0_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Daily Average",
   "type": "stat",
   "description": "Source: ShellyEM",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "shellyem",
     "select": [
      [
       { "params": [ "0_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Energy Used & Cost",
   "type": "timeseries",
   "description": "Source: Consumption=ShellyEM; Cost=Octopus\nOctopus reports every 24hrs so we can only start with previous day's readings to compare.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "alias": "Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "shellyem",
     "select": [
      [
       { "params": [ "0_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "Price",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "query": "SELECT last(\"total_cost\") FROM \"electricity\" WHERE $timeFilter GROUP BY time(30m) fill(null)",
     "select": [
      [
       { "params": [ "total_cost" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instantaneous Current (last 24h)",
   "type": "timeseries",
   "description": "Source: ShellyEM",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "shellyem",
     "select": [
      [
       { "params": [ "0_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 240" ], "type": "math" }
      ]
     ]
    },
    { "expr": "shellyem_0_power / 240", "legendFormat": "Current (ShellyEM)" }
   ]
  },
  {
   "title": "Electricity Consumption - ShellyEM vs Octopus Consumption",
   "type": "timeseries",
   "description": "Source: Octopus & ShellyEM\nOctopus reports every 24hrs so we can only start with previous day's readings to compare. Octopus reading lag 1hr behind ShellyEM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "ShellyEM",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "shellyem",
     "select": [
      [
       { "params": [ "0_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Octopus",
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electricity",
     "select": [
      [
       { "params": [ "consumption" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Instantaneous Current (Full Time Range)",
   "type": "timeseries",
   "description": "Source: ShellyEM",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "shellyem_0_power / 240", "legendFormat": "Current (ShellyEM)" }
   ]
  },
  {
   "title": "Electricity Consumption - ShellyEM vs Octopus Consumption",
   "type": "timeseries",
   "description": "Source: Octopus & ShellyEM\nOctopus reports every 24hrs so we can only start with previous day's readings to compare. Octopus reading lag 1hr behind ShellyEM",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "increase(interpolate(shellyem_0_total)[$__interval]) offset -30m",
     "legendFormat": "Shelly"
    },
    {
     "expr": "sum_over_time(electricity_consumption[$__interval:30m] offset -30m) *1000",
     "legendFormat": "Octopus"
    }
   ]
  },
  {
   "title": "Energy By Hour (last 24h)",
   "type": "timeseries",
   "description": "Source: ShellyEM",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "ShellyEM",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "shellyem",
     "query": "SELECT difference(last(\"0_total\")) FROM \"shellyem\" WHERE $timeFilter GROUP BY time(1h) fill(linear)",
     "select": [
      [
       { "params": [ "0_total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "expr": "increase(shellyem_0_total[$__rate_interval])",
     "legendFormat": "Energy (ShellyEM)"
    }
   ]
  },
  {
   "title": "Energy By Hour (Full Time Range)",
   "type": "timeseries",
   "description": "Source: ShellyEM",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "increase(shellyem_0_total[$__rate_interval])",
     "legendFormat": "Energy (ShellyEM)"
    }
   ]
  },
  {
   "title": "Energy By Day (Full Time Range)",
   "type": "timeseries",
   "description": "Source: ShellyEM",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "increase(shellyem_0_total[$__interval])",
     "legendFormat": "Energy (ShellyEM)"
    }
   ]
  },
  { "title": "Misc Energy Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Home Assistant Power Metrics (Entity Filter)",
   "type": "timeseries",
   "description": "(may not be 100% accurate - not clear if all MQTT messages parsed by HA)",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "ha_sensor_power_w{entity=~\"$ha_entities\"} !=0",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "ha_test_sensor_power_w{entity=~\"$ha_test_entities\"} !=0",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Home Assistant 'Energy' Entities (Entity Filter) - Per Hour (Full Time Range)",
   "type": "timeseries",
   "description": "(may not be 100% accurate - not clear if all MQTT messages parsed by HA)",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "increase(ha_sensor_energy_kwh{entity=~\"$ha_entities\"}[$__rate_interval]) != 0",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Shelly (1PM #04) Power Monitor",
   "type": "timeseries",
   "description": "Metrics from MQTT -> VMAgent via Node Red flow\n\nEnergy metric is in Watt Minutes - divide by 60 to get Wh.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "targets": [
    { "expr": "shelly1PM04_power", "legendFormat": "Power" },
    {
     "expr": "avg_over_time(shelly1PM04_power[1h])",
     "legendFormat": "Power Avg Over Time"
    },
    {
     "expr": "sum_over_time(increase(shelly1PM04_energy)[$__interval]) / 60",
     "legendFormat": "energy"
    },
    {
     "expr": "sum_over_time(shelly1PM04_power[$__interval])/(count_over_time(shelly1PM04_power[1m])*60)",
     "legendFormat": "Wh (1 hour)"
    }
   ]
  },
  { "title": "Lay-Z-Spa Hot Tub", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Spa Functions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "targets": [
    { "expr": "layzspa_heater", "legendFormat": "Heater" },
    { "expr": "layzspa_heating + 2", "legendFormat": "Active Heating" },
    { "expr": "layzspa_filter + 4", "legendFormat": "Pump" },
    { "expr": "layzspa_air + 6", "legendFormat": "Bubbles" }
   ]
  },
  {
   "title": "Spa KWH",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    { "expr": "remove_resets(layzspa_kwh)", "legendFormat": "kWh" },
    {
     "expr": "remove_resets(layzspa_cost) / 100",
     "legendFormat": "Cost (est)"
    }
   ]
  },
  {
   "title": "Spa Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "layzspa_temp", "legendFormat": "Actual Temp" },
    { "expr": "layzspa_target", "legendFormat": "Target Temp" },
    {
     "expr": "ha_sensor_temperature_celsius{entity=\"sensor.openweathermap_temperature\"}",
     "legendFormat": "Air Temp"
    },
    {
     "expr": "ha_input_number_state_celsius{entity=\"input_number.layzspa_min_temp\"}",
     "legendFormat": "Min Temp (Home Assistant)"
    }
   ]
  }
 ]
}