{
 "title": "Media (Plex - Sonarr - Radarr - Transmission)",
 "description": "Metrics from PMS, Sonarr and Radarr (based on Varken official v1.5)",
 "tags": [
  "varken",
  "plex",
  "tautulli",
  "sonarr",
  "radarr",
  "production",
  "influxdb",
  "transmission",
  "prometheus",
  "deluge",
  "torrent"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tautulliurl",
    "label": "Tautulli URL",
    "query": "https://tautulli.mc-guinness.co.uk"
   },
   {
    "name": "sonarrurl",
    "label": "Sonarr URL",
    "query": "https://sonarr.mc-guinness.co.uk"
   },
   {
    "name": "radarrurl",
    "label": "Radarr URL",
    "query": "https://radarr.mc-guinness.co.uk"
   },
   {
    "name": "torrentstransmission",
    "label": "Torrents - Transmission",
    "query": {
     "query": "label_values(transmission_torrent_status,name)"
    }
   },
   {
    "name": "torrentsdeluge",
    "label": "Torrents - Deluge",
    "query": {
     "query": "label_values(deluge_torrent_done_total,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Plex",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Current Streams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "stream_count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Current Total BW",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total_bandwidth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "Movies" },
      { "condition": "OR", "key": "section_name", "operator": "=", "value": "Movies - 4K" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "Movies - 3D" }
     ]
    }
   ]
  },
  {
   "title": "TV Episodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "TV Shows" }
     ]
    }
   ]
  },
  {
   "title": "Videos - Unsorted DLs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "Video - Scratchpad Downloads" }
     ]
    }
   ]
  },
  { "gridPos": { "h": 6, "w": 4, "x": 15, "y": 1 } },
  { "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 } },
  {
   "title": "Videos - Misc",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "Videos - Misc" }
     ]
    }
   ]
  },
  {
   "title": "Online users",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Current LAN BW",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "lan_bandwidth" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Recently Added Movies [in last 7d]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "Movies" }
     ]
    }
   ]
  },
  {
   "title": "Recently Added TV [in last 7d]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "episodes" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "TV Shows" }
     ]
    }
   ]
  },
  {
   "title": "Direct Play Streams",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "direct_play_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Movies - 4K",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "Movies - 4K" }
     ]
    }
   ]
  },
  {
   "title": "TV Seasons",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "seasons" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "TV Shows" }
     ]
    }
   ]
  },
  { "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 } },
  {
   "title": "Direct Stream",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "direct_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Current WAN BW",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "wan_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Movies - 3D",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "Movies - 3D" }
     ]
    }
   ]
  },
  {
   "title": "TV Shows",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "TV Shows" }
     ]
    }
   ]
  },
  {
   "title": "Transocde Streams",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "transcode_streams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "current_stream_stats" }
     ]
    }
   ]
  },
  {
   "title": "Users & Stream Types [in last 30d] (Tautulli)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_friendly_name - $tag_video_decision",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "video_decision" ], "type": "tag" },
      { "params": [ "friendly_name" ], "type": "tag" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Users & Device Types [in last 30d] (Tautulli)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_friendly_name - $tag_device_type",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "device_type" ], "type": "tag" },
      { "params": [ "friendly_name" ], "type": "tag" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Stream Count [in last 365d] (Tautulli)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_friendly_name",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "friendly_name" ], "type": "tag" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ],
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Server Popularity [in last 1d] (Tautulli)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "alias": ".",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "host": { "filter": "" },
     "item": { "filter": "" },
     "measurement": "Tautulli",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Location (Tautulli)",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_region_code",
     "groupBy": [
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "longitude" ], "type": "tag" },
      { "params": [ "full_location" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Users Online (Tautulli)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "title" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" },
      { "params": [ "video_decision" ], "type": "tag" },
      { "params": [ "quality_profile" ], "type": "tag" },
      { "params": [ "platform" ], "type": "tag" },
      { "params": [ "product_version" ], "type": "tag" },
      { "params": [ "location" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "query": "SELECT distinct(\"hash\") FROM \"Tautulli\" WHERE (\"type\" = 'Session') AND $timeFilter GROUP BY \"friendly_name\",  \"title\", \"quality\", \"video_decision\", \"quality_profile\", \"platform\", \"product_version\", \"location\", \"player_state\"",
     "select": [
      [
       { "params": [ "session_key" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Sonarr & Radarr",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "TV Shows in Queue (Sonarr)",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "protocol_id" ], "type": "tag" },
        { "params": [ "sxe" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "Sonarr",
       "select": [
        [
         { "params": [ "hash" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Queue" }
       ]
      }
     ]
    },
    {
     "title": "Missing Available Movies (Radarr)",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "Radarr",
       "select": [
        [
         { "params": [ "hash" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "Missing_Available", "operator": "=", "value": "0" }
       ]
      }
     ]
    },
    {
     "title": "TV Shows on Today (Sonarr)",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 43 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "downloaded" ], "type": "tag" },
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "sxe" ], "type": "tag" }
       ],
       "measurement": "Sonarr",
       "select": [
        [
         { "params": [ "hash" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Future" }
       ]
      }
     ]
    },
    {
     "title": "Movies in Queue (Radarr)",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "protocol_id" ], "type": "tag" },
        { "params": [ "quality" ], "type": "tag" },
        { "params": [ "protocol" ], "type": "tag" }
       ],
       "measurement": "Radarr",
       "select": [
        [
         { "params": [ "hash" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Queue" }
       ]
      }
     ]
    },
    {
     "title": "Missing TV Shows [Last 7 Days] (Sonarr)",
     "type": "table",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" },
        { "params": [ "sxe" ], "type": "tag" },
        { "params": [ "server" ], "type": "tag" }
       ],
       "measurement": "Sonarr",
       "select": [
        [
         { "params": [ "hash" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "Missing" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Deluge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Torrents",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "deluge_torrents{state=\"total\"}"
      }
     ]
    },
    {
     "title": "Active",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 2, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "deluge_torrents{state=\"active\"}"
      }
     ]
    },
    {
     "title": "Seeding",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 5, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "deluge_torrents{state=\"seeding\"}"
      }
     ]
    },
    {
     "title": "Paused",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "deluge_torrents{state=\"paused\"}"
      }
     ]
    },
    {
     "title": "Total download",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 11, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "deluge_libtorrent_net_recv_payload_bytes_total"
      }
     ]
    },
    {
     "title": "Total upload",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 15, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "deluge_libtorrent_net_sent_payload_bytes_total"
      }
     ]
    },
    {
     "title": "Total Ratio",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 19, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "deluge_libtorrent_net_sent_payload_bytes_total/deluge_libtorrent_net_recv_payload_bytes_total"
      }
     ]
    },
    {
     "title": "Connected Peers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "deluge_libtorrent_peer_num_peers_connected"
      }
     ]
    },
    {
     "title": "Error",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 2, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "deluge_torrents{state=\"error\"}"
      }
     ]
    },
    {
     "title": "Downloading",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 5, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "deluge_torrents{state=\"downloading\"}"
      }
     ]
    },
    {
     "title": "Queued",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "deluge_torrents{state=\"queued\"}"
      }
     ]
    },
    {
     "title": "DHT Peers",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "deluge_libtorrent_dht_dht_peers"
      }
     ]
    },
    {
     "title": "Bandwidth (filtered)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(deluge_torrent_done_total{name=~\"$torrentsdeluge\"}[$__rate_interval]) !=0",
       "legendFormat": "DL - {{name}}"
      },
      {
       "expr": "rate(deluge_torrent_uploaded_total{name=~\"$torrentsdeluge\"}[$__rate_interval]) !=0",
       "legendFormat": "UL - {{name}}"
      }
     ]
    },
    {
     "title": "Download % (filtered)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "deluge_torrent_done_total{state=\"downloading\",name=~\"$torrentsdeluge\"} / deluge_torrent_size_total{state=\"downloading\",name=~\"$torrentsdeluge\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Peers & Seeds (filtered)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "deluge_torrent_total_peers{state=\"downloading\",name=~\"$torrentsdeluge\"} !=0",
       "legendFormat": "Peers Total - {{name}}"
      },
      {
       "expr": "deluge_torrent_num_peers{state=\"downloading\",name=~\"$torrentsdeluge\"} !=0",
       "legendFormat": "Peers Connected - {{name}}"
      },
      {
       "expr": "deluge_torrent_num_seeds{state=\"downloading\",name=~\"$torrentsdeluge\"} !=0",
       "legendFormat": "Seeds Connected - {{name}}"
      },
      {
       "expr": "deluge_torrent_total_seeds{state=\"downloading\",name=~\"$torrentsdeluge\"} !=0",
       "legendFormat": "Seeds Total - {{name}}"
      }
     ]
    },
    {
     "title": "Disk Read/Write Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(deluge_libtorrent_disk_disk_read_time_total[$__rate_interval])",
       "legendFormat": "Read"
      },
      {
       "expr": "rate(deluge_libtorrent_disk_disk_write_time_total[$__rate_interval])",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "deluge_libtorrent_peer_num_peers_connected",
       "legendFormat": "peers_connected"
      },
      {
       "expr": "deluge_libtorrent_utp_num_utp_connected",
       "legendFormat": "utp_connected"
      }
     ]
    },
    {
     "title": "DHT (peerless) Bandwidth Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "irate(deluge_libtorrent_dht_dht_bytes_in_total[$__rate_interval])",
       "legendFormat": "Download"
      },
      {
       "expr": "irate(deluge_libtorrent_dht_dht_bytes_out_total[$__rate_interval])",
       "legendFormat": "Upload"
      }
     ]
    },
    {
     "title": "DHT",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "deluge_libtorrent_dht_dht_nodes",
       "legendFormat": "DHT Nodes"
      },
      {
       "expr": "deluge_libtorrent_dht_dht_peers",
       "legendFormat": "DHT Peers"
      }
     ]
    },
    {
     "title": "Torrents By Label",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "deluge_torrents_by_label{label=\"\"} !=0",
       "legendFormat": "No Label"
      },
      {
       "expr": "deluge_torrents_by_label{label!=\"\"} !=0",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "Peer Exchange",
     "type": "timeseries",
     "description": "Peer exchange allows a group of users (or peers) that are collaborating to share a given file to do so more swiftly and efficiently. PEX allows peers in a swarm to exchange information about the swarm directly without asking (polling) a tracker computer or a DHT. By doing so, PEX leverages the knowledge of peers that a user is connected to by asking them for the addresses of peers that they are connected to. This is faster and more efficient than relying solely on one tracker and reduces the processing load on the tracker. It also keep swarms together when the tracker is down.\nhttps://www.wikiwand.com/en/Peer_exchange",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(deluge_libtorrent_ses_num_incoming_pex_total[$__rate_interval])",
       "legendFormat": "In"
      },
      {
       "expr": "rate(deluge_libtorrent_ses_num_outgoing_pex_total[$__rate_interval])",
       "legendFormat": "Out"
      }
     ]
    }
   ]
  },
  {
   "title": "Transmission",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of torrents",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(transmission_torrent_done)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Current Speed - Download",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "transmission_session_stats_download_speed_bytes"
      }
     ]
    },
    {
     "title": "Current Speed - Upload",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "transmission_session_stats_upload_speed_bytes"
      }
     ]
    },
    {
     "title": "Seeds Actively Downloading",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(transmission_torrent_downloads_total)"
      }
     ]
    },
    {
     "title": "Downloaded - Current Session",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "transmission_session_stats_downloaded_bytes{type=\"current\"}"
      }
     ]
    },
    {
     "title": "Uploaded - Current Session",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "transmission_session_stats_uploaded_bytes{type=\"current\"}"
      }
     ]
    },
    {
     "title": "Available Space",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "transmission_free_space" }
     ]
    },
    {
     "title": "Downloaded - Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "transmission_session_stats_downloaded_bytes{type=\"cumulative\"}"
      }
     ]
    },
    {
     "title": "Uploaded - Total",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "transmission_session_stats_uploaded_bytes{type=\"cumulative\"}"
      }
     ]
    },
    {
     "title": "Ratio - Current",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "transmission_session_stats_uploaded_bytes{type=\"current\"}/transmission_session_stats_downloaded_bytes{type=\"current\"}"
      }
     ]
    },
    {
     "title": "Ratio - Cumulative",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "transmission_session_stats_uploaded_bytes{type=\"cumulative\"}/transmission_session_stats_downloaded_bytes{type=\"cumulative\"}"
      }
     ]
    },
    {
     "title": "Completed Torrents - Awaiting Clearance",
     "type": "stat",
     "gridPos": { "h": 2, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(transmission_torrent_finished)"
      }
     ]
    },
    {
     "title": "Download Speed (filtered)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "transmission_torrent_download_bytes{name=~\"$torrentstransmission\"}",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "% Completion (filtered)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "transmission_torrent_done{name=~\"$torrentstransmission\"}",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  }
 ]
}