{
 "title": "Minecraft",
 "description": "Using mc-router and ServerStats for metrics collection",
 "tags": [
  "production",
  "host",
  "linux",
  "minecraft",
  "prometheus",
  "influxdb",
  "ServerStats",
  "mc-router"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(minecraft_players_online,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Router",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections Active",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "mc_router_connections_active_value"
    }
   ]
  },
  {
   "title": "Transmitted Bytes / sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum_over_time(mc_router_transmitted_bytes_count[5m])/300"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    { "expr": "mc_router_connections_count", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Router Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "avg(mc_router_errors_count)" }
   ]
  },
  {
   "title": "ServerStats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "minecraft_SS_loaded_chunks_world !=0",
     "legendFormat": "{{instance}} - {{world}}"
    },
    {
     "expr": "sum by (instance) (minecraft_SS_loaded_chunks_world) !=0",
     "legendFormat": "{{instance}} Total"
    }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "minecraft_SS_loaded_chunks", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Entity Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "minecraft_SS_entity_count_world !=0",
     "legendFormat": "{{instance}} - {{world}}"
    },
    {
     "expr": "sum by (instance) (minecraft_SS_entity_count_world) !=0",
     "legendFormat": "{{instance}} Total"
    }
   ]
  },
  {
   "title": "Entity Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "minecraft_SS_entity_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Player Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "minecraft_SS_player_count !=0", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Player Count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "minecraft_SS_player_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "MSPT ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "minecraft_SS_mspt !=0", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "MSPT",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "minecraft_SS_mspt", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "targets": [
    { "expr": "minecraft_SS_tps !=0", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "TPS",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "minecraft_SS_tps", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 50 },
   "targets": [
    { "expr": "minecraft_SS_cpu !=0", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "minecraft_SS_cpu", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(minecraft_SS_max_memory-minecraft_SS_free_memory) !=0",
     "legendFormat": "Used Mem - {{instance}}"
    },
    { "expr": "minecraft_SS_max_memory !=0", "legendFormat": "Allocated Mem - {{instance}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(minecraft_SS_max_memory-minecraft_SS_free_memory) !=0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "minecraft_SS_disk_space_world !=0",
     "legendFormat": "{{instance}} - {{world}}"
    },
    {
     "expr": "sum by (instance) (minecraft_SS_disk_space_world) !=0",
     "legendFormat": "{{instance}} Total"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (minecraft_SS_disk_space_world)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "minecraft_SS_threads !=0", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "minecraft_SS_threads !=0", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Packets Sent/Received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(minecraft_SS_packets_rx[$__rate_interval])) !=0",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "- sum by (instance) (rate(minecraft_SS_packets_tx[$__rate_interval])) !=0",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}