{
 "title": "Minecraft - UnifiedMetrics 0.3.x (14756) - Variables Fixed",
 "description": "Fully-featured metrics collection agent for Minecraft servers.",
 "tags": [
  "minecraft",
  "prometheus"
 ],
 "time": { "from": "2023-12-21T17:05:10.000Z", "to": "2023-12-21T18:05:10.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "label_values(minecraft_UM_minecraft_players_count,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(minecraft_UM_minecraft_players_count{job=~\"$job\"},instance)"
    }
   },
   {
    "name": "world",
    "query": {
     "query": "label_values(minecraft_UM_minecraft_world_entities_count{job=~\"$job\", instance=~\"$instance\"},world)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Servers" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(minecraft_UM_minecraft_players_count{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-avg(minecraft_UM_process_start_time_seconds{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_UM_minecraft_players_count{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_UM_minecraft_world_entities_count{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_UM_minecraft_world_loaded_chunks{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(minecraft_UM_minecraft_world_loaded_chunks{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(minecraft_UM_minecraft_tick_duration_seconds_count{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(minecraft_UM_minecraft_tick_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(minecraft_UM_process_cpu_load_ratio{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(minecraft_UM_process_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}[$__interval]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_UM_jvm_memory_bytes_used{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_UM_jvm_memory_bytes_max{instance=~\"$instance\",job=~\"$job\"} - minecraft_UM_jvm_memory_bytes_used{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(minecraft_UM_minecraft_tick_duration_seconds_count{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "tps: {{instance}}"
    }
   ]
  },
  {
   "title": "MSPT",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(minecraft_UM_minecraft_tick_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "mspt: 0.5 quantile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(minecraft_UM_minecraft_tick_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "mspt: 0.75 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(minecraft_UM_minecraft_tick_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "mspt: 0.95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(minecraft_UM_minecraft_tick_duration_seconds_bucket{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])) by (le))",
     "legendFormat": "mspt: 0.99 quantile"
    }
   ]
  },
  {
   "title": "Players",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_UM_minecraft_players_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "players: {{instance}}"
    }
   ]
  },
  {
   "title": "Player flow",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_UM_minecraft_players_count{instance=~\"$instance\",job=~\"$job\"} - minecraft_UM_minecraft_players_count{instance=~\"$instance\",job=~\"$job\"} offset $__interval",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "World [$world]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "world",
   "targets": [
    {}
   ]
  },
  {
   "title": "Chunks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_UM_minecraft_world_loaded_chunks{instance=~\"$instance\",job=~\"$job\",world=\"$world\"}",
     "legendFormat": "chunks: {{instance}}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_UM_minecraft_world_entities_count{instance=~\"$instance\",job=~\"$job\",world=\"$world\"}",
     "legendFormat": "entities: {{instance}}"
    },
    {
     "expr": "minecraft_UM_minecraft_world_players_count{instance=~\"$instance\",job=~\"$job\",world=\"$world\"}",
     "legendFormat": "players: {{instance}}"
    }
   ]
  },
  {
   "title": "JVM: Computation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "minecraft_UM_process_cpu_load_ratio{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "cpu: {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(minecraft_UM_process_cpu_seconds_total{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "cpu_seconds: {{instance}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minecraft_UM_jvm_threads_current_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "threads: {{instance}}"
    }
   ]
  },
  {
   "title": "Daemons",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minecraft_UM_jvm_threads_daemon_count{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "daemons: {{instance}}"
    }
   ]
  },
  {
   "title": "Threads started",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "minecraft_UM_jvm_threads_started_total{instance=~\"$instance\",job=~\"$job\"} - minecraft_UM_jvm_threads_started_total{instance=~\"$instance\",job=~\"$job\"} offset $__interval",
     "legendFormat": "threads_started: {{instance}}"
    }
   ]
  },
  {
   "title": "JVM: Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "minecraft_UM_jvm_memory_bytes_used{instance=~\"$instance\",job=~\"$job\",area=\"heap\"}",
     "legendFormat": "heap: {{instance}}"
    }
   ]
  },
  {
   "title": "Nonheap Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "minecraft_UM_jvm_memory_bytes_used{instance=~\"$instance\",job=~\"$job\",area=\"nonheap\"}",
     "legendFormat": "nonheap: {{instance}}"
    }
   ]
  },
  {
   "title": "GC Duration (Mean)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(gc) (minecraft_UM_jvm_gc_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\"} - minecraft_UM_jvm_gc_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\"} offset $__interval)",
     "legendFormat": "gc_duration: {{gc}}"
    }
   ]
  },
  {
   "title": "GC Freed (Total)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(gc) (minecraft_UM_jvm_gc_freed_bytes_sum{instance=~\"$instance\",job=~\"$job\"} - minecraft_UM_jvm_gc_freed_bytes_sum{instance=~\"$instance\",job=~\"$job\"} offset $__interval)",
     "legendFormat": "gc_freed: {{gc}}"
    }
   ]
  }
 ]
}