{
 "title": "Minecraft - Fabric Exporter (14492)",
 "tags": [
  "minecraft",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{job=~\"$job\"})"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "query_result(minecraft_entities)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Online Players",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 1, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_players_online{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Current MSPT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_mspt{type=\"mean\",instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Current TPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_tps{instance=~\"$instance\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Loaded Entities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Players online",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(minecraft_players_online{instance=~\"$instance\",job=~\"$job\"}) by (world)",
     "legendFormat": "Players in {{world}}"
    }
   ]
  },
  {
   "title": "Ticks Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minecraft_tps{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Loaded chunks per 10 minutes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(minecraft_total_loaded_chunks{instance=~\"$instance\",job=~\"$job\"}[10m])",
     "legendFormat": "Loaded chunks in {{world}}"
    }
   ]
  },
  {
   "title": "Milliseconds Per Tick",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minecraft_mspt{type=\"mean\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "MSPT"
    }
   ]
  },
  {
   "title": "Loaded chunks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(minecraft_loaded_chunks{instance=~\"$instance\",job=~\"$job\"}) by (world)",
     "legendFormat": "Loaded chunks in {{world}}"
    }
   ]
  },
  {
   "title": "Top entities by type",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Entities by spawn group",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (group)",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Entities by world",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (world)",
     "legendFormat": "Entities in {{world}}"
    }
   ]
  }
 ]
}