{
 "title": "Minecraft - UnifiedMetrics 0.3.x (14756)",
 "description": "Fully-featured metrics collection agent for Minecraft servers.",
 "tags": [
  "minecraft",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "query": {
     "query": "query_result(minecraft_players_count)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{job=~\"^$job$\"})"
    }
   },
   {
    "name": "interval",
    "query": "15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "world",
    "query": {
     "query": "query_result(minecraft_world_entities_count{instance=~\"$instance\",job=~\"$job\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Servers" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(minecraft_players_count{job=~\"^$job$\",instance=~\"^$instance$\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-avg(process_start_time_seconds{instance=~\"^$instance$\",job=~\"^$job$\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_players_count{instance=~\"^$instance$\",job=~\"^$job$\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_world_entities_count{instance=~\"^$instance$\",job=~\"^$job$\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_world_loaded_chunks{instance=~\"^$instance$\",job=~\"^$job$\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(minecraft_world_loaded_chunks{instance=~\"^$instance$\",job=~\"^$job$\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(minecraft_tick_duration_seconds_count{instance=~\"^$instance$\",job=~\"^$job$\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(minecraft_tick_duration_seconds_bucket{instance=~\"^$instance$\",job=~\"^$job$\"}[$__rate_interval])) by (le))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(process_cpu_load_ratio{instance=~\"^$instance$\",job=~\"^$job$\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{instance=~\"^$instance$\",job=~\"^$job$\"}[$__interval]))"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{instance=~\"^$instance$\",job=~\"^$job$\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{instance=~\"^$instance$\",job=~\"^$job$\"} - jvm_memory_bytes_used{instance=~\"^$instance$\",job=~\"^$job$\"})"
    }
   ]
  },
  {
   "title": "Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(minecraft_tick_duration_seconds_count{instance=~\"^$instance$\",job=~\"^$job$\"}[$__interval])",
     "legendFormat": "tps: {{job}}"
    }
   ]
  },
  {
   "title": "MSPT",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(minecraft_tick_duration_seconds_bucket{instance=~\"^$instance$\",job=~\"^$job$\"}[$__interval])) by (le))",
     "legendFormat": "mspt: 0.5 quantile"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(minecraft_tick_duration_seconds_bucket{instance=~\"^$instance$\",job=~\"^$job$\"}[$__interval])) by (le))",
     "legendFormat": "mspt: 0.75 quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(minecraft_tick_duration_seconds_bucket{instance=~\"^$instance$\",job=~\"^$job$\"}[$__interval])) by (le))",
     "legendFormat": "mspt: 0.95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(minecraft_tick_duration_seconds_bucket{instance=~\"^$instance$\",job=~\"^$job$\"}[$__interval])) by (le))",
     "legendFormat": "mspt: 0.99 quantile"
    }
   ]
  },
  {
   "title": "Players",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_players_count{instance=~\"^$instance$\",job=~\"^$job$\"}",
     "legendFormat": "players: {{job}}"
    }
   ]
  },
  {
   "title": "Player flow",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_players_count{instance=~\"^$instance$\",job=~\"^$job$\"} - minecraft_players_count{instance=~\"^$instance$\",job=~\"^$job$\"} offset $__interval",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "World [$world]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "world",
   "targets": [
    {}
   ]
  },
  {
   "title": "Chunks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_world_loaded_chunks{instance=~\"^$instance$\",job=~\"^$job$\",world=\"$world\"}",
     "legendFormat": "chunks: {{job}}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_world_entities_count{instance=~\"^$instance$\",job=~\"^$job$\",world=\"$world\"}",
     "legendFormat": "entities: {{job}}"
    },
    {
     "expr": "minecraft_world_players_count{instance=~\"^$instance$\",job=~\"^$job$\",world=\"$world\"}",
     "legendFormat": "players: {{job}}"
    }
   ]
  },
  {
   "title": "JVM: Computation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_load_ratio{instance=~\"^$instance$\",job=~\"^$job$\"}",
     "legendFormat": "cpu: {{job}}"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=~\"^$instance$\",job=~\"^$job$\"}[$__rate_interval])",
     "legendFormat": "cpu_seconds: {{job}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_current_count{instance=~\"^$instance$\",job=~\"^$job$\"}",
     "legendFormat": "threads: {{job}}"
    }
   ]
  },
  {
   "title": "Daemons",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_daemon_count{instance=~\"^$instance$\",job=~\"^$job$\"}",
     "legendFormat": "daemons: {{job}}"
    }
   ]
  },
  {
   "title": "Threads started",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_started_total{instance=~\"^$instance$\",job=~\"^$job$\"} - jvm_threads_started_total{instance=~\"^$instance$\",job=~\"^$job$\"} offset $__interval",
     "legendFormat": "threads_started: {{job}}"
    }
   ]
  },
  {
   "title": "JVM: Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"^$instance$\",job=~\"^$job$\",area=\"heap\"}",
     "legendFormat": "heap: {{job}}"
    }
   ]
  },
  {
   "title": "Nonheap Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=~\"^$instance$\",job=~\"^$job$\",area=\"nonheap\"}",
     "legendFormat": "nonheap: {{job}}"
    }
   ]
  },
  {
   "title": "GC Duration (Mean)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(gc) (jvm_gc_duration_seconds_sum{instance=~\"^$instance$\",job=~\"^$job$\"} - jvm_gc_duration_seconds_sum{instance=~\"^$instance$\",job=~\"^$job$\"} offset $__interval)",
     "legendFormat": "gc_duration: {{gc}}"
    }
   ]
  },
  {
   "title": "GC Freed (Total)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(gc) (jvm_gc_freed_bytes_sum{instance=~\"^$instance$\",job=~\"^$job$\"} - jvm_gc_freed_bytes_sum{instance=~\"^$instance$\",job=~\"^$job$\"} offset $__interval)",
     "legendFormat": "gc_freed: {{gc}}"
    }
   ]
  }
 ]
}