{
 "title": "Minecraft - Fabric Exporter (14492) - Fixed Variables",
 "tags": [
  "minecraft",
  "prometheus"
 ],
 "time": { "from": "2023-12-21T17:00:00.000Z", "to": "2023-12-21T18:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "job",
    "query": {
     "query": "query_result(minecraft_FE_minecraft_entities)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{job=~\"$job\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Online Players",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 1, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_players_online{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Current MSPT",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_FE_minecraft_mspt{type=\"mean\",instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current TPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minecraft_FE_minecraft_tps{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Loaded Entities",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_entities{instance=~\"$instance\",job=~\"$job\"})"
    }
   ]
  },
  {
   "title": "Players online",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_players_online{instance=~\"$instance\",job=~\"$job\"}) by (instance,world) !=0",
     "legendFormat": "Players in {{instance}} - {{world}}"
    }
   ]
  },
  {
   "title": "Ticks Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_FE_minecraft_tps{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Loaded chunks per 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(minecraft_FE_minecraft_total_loaded_chunks{instance=~\"$instance\",job=~\"$job\"}[5m]) !=0",
     "legendFormat": "{{instance}} - {{world}}"
    }
   ]
  },
  {
   "title": "Milliseconds Per Tick",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_FE_minecraft_mspt{type=\"mean\",instance=~\"$instance\",job=~\"$job\"} !=0",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Loaded chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_loaded_chunks{instance=~\"$instance\",job=~\"$job\"}) by (instance,world) !=0",
     "legendFormat": "{{instance}} - {{world}}"
    }
   ]
  },
  {
   "title": "Top entities by type",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Entities by spawn group",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (group) !=0",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Entities by world",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_FE_minecraft_entities{instance=~\"$instance\",job=~\"$job\"}) by (instance,world) !=0",
     "legendFormat": "{{instance}} - {{world}}"
    }
   ]
  }
 ]
}