{
 "title": "Proxmox Backup Server (GitHub)",
 "tags": [ "proxmox" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "pbs_host_system",
    "label": "PBS Host",
    "query": {
     "query": "label_values(pbs_host_uptime,host_system)"
    }
   },
   {
    "name": "pbs_instance",
    "label": "PBS Instance",
    "query": {
     "query": "label_values(pbs_host_uptime,instance)"
    }
   },
   {
    "name": "pbs_datastore",
    "label": "PBS Datastore",
    "query": {
     "query": "label_values(pbs_size{host_system=~\"$pbs_host_system\"},datastore)"
    }
   },
   {
    "name": "pbs_guest",
    "label": "PBS Backup Guest",
    "query": {
     "query": "label_values(pbs_snapshot_vm_count{datastore=~\"$pbs_datastore\"},vm_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbs_host_uptime{host_system=~\"$pbs_host_system\"}",
     "legendFormat": "{{host_system}}"
    }
   ]
  },
  {
   "title": "Snapshot overview",
   "type": "table",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(pbs_snapshot_vm_last_timestamp{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"} * 1000) by (host_system,datastore,vm_id,vm_name)"
    },
    {
     "expr": "sum(pbs_snapshot_vm_last_verify{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (host_system,datastore,vm_id,vm_name)"
    },
    {
     "expr": "sum(pbs_size{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (host_system,datastore,vm_id,vm_name)"
    },
    {
     "expr": "sum(pbs_available{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (host_system,datastore,vm_id,vm_name)"
    },
    {
     "expr": "sum(pbs_used{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (host_system,datastore,vm_id,vm_name)"
    },
    {
     "expr": "sum(pbs_used{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (host_system,datastore,vm_id,vm_name) / sum(pbs_size{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (host_system,datastore,vm_id,vm_name)"
    },
    {
     "expr": "sum(pbs_snapshot_count{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (host_system,datastore,vm_id,vm_name)"
    },
    {
     "expr": "sum(pbs_snapshot_vm_count{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (host_system,datastore,vm_id,vm_name)"
    },
    {
     "expr": "sum(pbs_host_cpu_usage{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (host_system)"
    }
   ]
  },
  {
   "title": "Total Snapshots",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pbs_snapshot_count{job=\"pbs\", host_system=~\"$pbs_host_system\"})"
    }
   ]
  },
  { "title": "Snapshots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Snapshots by VM",
   "type": "table",
   "gridPos": { "h": 15, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(pbs_snapshot_vm_count{job=\"pbs\", host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\"}) by (vm_name)"
    }
   ]
  },
  {
   "title": "Total Snapshots by Namespace",
   "type": "table",
   "gridPos": { "h": 15, "w": 4, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "pbs_snapshot_count{job=\"pbs\", host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\"}"
    }
   ]
  },
  {
   "title": "Snapshot count by VM",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(pbs_snapshot_vm_count{job=\"pbs\", host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (datastore,vm_id,vm_name,host_system)",
     "legendFormat": "snap-count"
    },
    {
     "expr": "sum(pbs_snapshot_vm_last_timestamp{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"} * 1000) by (datastore,vm_id,vm_name,host_system)",
     "legendFormat": "last-snapshot"
    },
    {
     "expr": "sum(pbs_snapshot_vm_last_verify{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (host_system,datastore,vm_id,vm_name)",
     "legendFormat": "verify-status"
    },
    {
     "expr": "sum(pbs_used{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (host_system,datastore,vm_id,vm_name) / sum(pbs_size{host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (host_system,datastore,vm_id,vm_name)",
     "legendFormat": "datastore-perc"
    }
   ]
  },
  {
   "title": "Snapshot count by VM",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "sum(pbs_snapshot_vm_count{job=\"pbs\", host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\", vm_name=~\"$pbs_guest\"}) by (datastore,vm_id,vm_name,host_system)"
    }
   ]
  },
  { "title": "Datastore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Datastore Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pbs_available{job=\"pbs\", host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pbs_size{job=\"pbs\", host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\"}"
    },
    {
     "expr": "pbs_used{job=\"pbs\", host_system=~\"$pbs_host_system\", datastore=~\"$pbs_datastore\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pbs_host_cpu_usage{job=\"pbs\",host_system=~\"$pbs_host_system\"}",
       "legendFormat": "usage"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "pbs_host_load1{job=\"pbs\",host_system=~\"$pbs_host_system\"}",
       "legendFormat": "1m load average"
      },
      {
       "expr": "pbs_host_load5{job=\"pbs\",host_system=~\"$pbs_host_system\"}",
       "legendFormat": "5m load average"
      },
      {
       "expr": "pbs_host_load15{job=\"pbs\",host_system=~\"$pbs_host_system\"}",
       "legendFormat": "15m load average"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "pbs_host_memory_used{job=\"pbs\", host_system=~\"$pbs_host_system\"}",
       "legendFormat": "{{host_system}} - memory used"
      },
      {
       "expr": "pbs_host_memory_free{job=\"pbs\", host_system=~\"$pbs_host_system\"}",
       "legendFormat": "{{host_system}} - memory free"
      },
      {
       "expr": "sum(pbs_host_memory_used{job=\"pbs\", host_system=~\"$pbs_host_system\"}) by (host_system) / (sum(pbs_host_memory_total{job=\"pbs\", host_system=~\"$pbs_host_system\"}) by (host_system))",
       "legendFormat": "{{host_system}} - memory used %"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pbs_host_memory_used{job=\"pbs\", host_system=~\"$pbs_host_system\"} / pbs_host_memory_total{job=\"pbs\", host_system=~\"$pbs_host_system\"} * 100",
       "legendFormat": "{{host_system}}"
      }
     ]
    },
    {
     "title": "Swap Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(pbs_host_swap_used{job=~\"pbs\", host_system=~\"$pbs_host_system\"}) by (host_system)",
       "legendFormat": "{{host_system}} - swap used"
      },
      {
       "expr": "sum(pbs_host_swap_free{job=~\"pbs\", host_system=~\"$pbs_host_system\"}) by (host_system)",
       "legendFormat": "{{host_system}} - swap free"
      },
      {
       "expr": "sum(pbs_host_swap_used{job=~\"pbs\", host_system=~\"$pbs_host_system\"}) by (host_system) / sum(pbs_host_swap_total{job=~\"pbs\", host_system=~\"$pbs_host_system\"}) by (host_system)",
       "legendFormat": "{{host_system}} - swap used %"
      }
     ]
    },
    {
     "title": "Swap Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pbs_host_swap_used{job=~\"pbs\", host_system=~\"$pbs_host_system\"} / pbs_host_swap_total{job=~\"pbs\", host_system=~\"$pbs_host_system\"} * 100",
       "legendFormat": "{{host_system}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk I/O Delay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "pbs_host_io_wait{host_system=~\"$pbs_host_system\"}",
       "legendFormat": "{{host_system}}"
      }
     ]
    },
    {
     "title": "Root Disk Space Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 11, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(pbs_host_disk_used{job=\"pbs\", host_system=~\"$pbs_host_system\"}) by (host_system)",
       "legendFormat": "{{host_system}} - used"
      },
      {
       "expr": "sum(pbs_host_disk_available{job=\"pbs\", host_system=~\"$pbs_host_system\"}) by (host_system)",
       "legendFormat": "{{host_system}} - free"
      },
      {
       "expr": "pbs_host_disk_used{job=~\"pbs\", host_system=~\"$pbs_host_system\"} / pbs_host_disk_total{job=~\"pbs\",host_system=~\"$pbs_host_system\"}",
       "legendFormat": "{{host_system}} - used %"
      }
     ]
    },
    {
     "title": "Root Disk Space Usage",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "pbs_host_disk_used{job=~\"pbs\", host_system=~\"$pbs_host_system\"} / pbs_host_disk_total{job=~\"pbs\",host_system=~\"$pbs_host_system\"} * 100",
       "legendFormat": "{{host_system}}"
      }
     ]
    }
   ]
  }
 ]
}