{
 "title": "Telegraf - conversion of 928 for VM (11051)",
 "description": "Prometheus/victoriametrics dashboards for telegraf metrics",
 "tags": [
  "telegraf",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "inter", "label": "Sampling", "query": "10s,30s,1m,2m,5m,10m,30m,1h" },
   { "name": "server", "label": "Server", "query": "label_values(host)" },
   { "name": "mountpoint", "label": "Mountpoint", "query": "label_values(path)" },
   { "name": "cpu", "label": "CPU", "query": "label_values(cpu)" },
   { "name": "disk", "label": "Disk", "query": "label_values(name)" },
   { "name": "netif", "label": "Network interface", "query": "label_values(interface)" }
  ]
 },
 "panels": [
  {
   "title": "Quick overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{host =~ \"^$server$\"}",
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "LA medium",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load5{host =~ \"^$server$\"}",
     "measurement": "system",
     "select": [
      [
       { "params": [ "load5" ], "type": "field" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "Zombies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processes_zombies{host =~ \"^$server$\"}",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "zombies" ], "type": "field" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processes_total{host =~ \"^$server$\"}",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "processes_total_threads{host =~ \"^$server$\"}",
     "measurement": "processes",
     "select": [
      [
       { "params": [ "total_threads" ], "type": "field" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-cpu_usage_idle{host =~ \"^$server$\",cpu = \"cpu-total\"}",
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" }
      ]
     ],
     "tags": "{host =~ \"^$server$\",cpu = \"cpu-total\"}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mem_used_percent{host =~ \"^$server$\"}",
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "swap_used_percent{host =~ \"^$server$\"}",
     "measurement": "swap",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "RootFS used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_used_percent{host =~ \"^$server$\",path = \"/\"}",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": "{host =~ \"^$server$\",path = \"/\"}"
    }
   ]
  },
  {
   "title": "IOWait",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_iowait{host =~ \"^$server$\",cpu = \"cpu-total\"}",
     "measurement": "cpu",
     "query": "SELECT non_negative_derivative(mean(\"usage_iowait\"), 1s) FROM \"cpu\" WHERE \"host\" =~ /^$server$/ AND \"cpu\" = 'cpu-total' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" }
      ]
     ],
     "tags": "{host =~ \"^$server$\",cpu = \"cpu-total\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "user",
     "expr": "median(cpu_usage_user{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: user",
     "measurement": "cpu",
     "query": "select mean(usage_user) as user from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "system",
     "expr": "median(cpu_usage_system{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: system",
     "measurement": "cpu",
     "query": "select mean(usage_system) as system from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "softirq",
     "expr": "median(cpu_usage_softirq{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: softirq",
     "measurement": "cpu",
     "query": "select mean(usage_softirq) as softirq from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_softirq" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "steal",
     "expr": "median(cpu_usage_steal{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: steal",
     "measurement": "cpu",
     "query": "select mean(usage_steal) as steal from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_steal" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "nice",
     "expr": "median(cpu_usage_nice{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: nice",
     "measurement": "cpu",
     "query": "select mean(usage_nice) as nice from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_nice" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "irq",
     "expr": "median(cpu_usage_irq{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: irq",
     "measurement": "cpu",
     "query": "select mean(usage_irq) as irq from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_irq" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "iowait",
     "expr": "median(cpu_usage_iowait{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: iowait",
     "measurement": "cpu",
     "query": "select mean(usage_iowait) as iowait from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "guest",
     "expr": "median(cpu_usage_guest{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: guest",
     "measurement": "cpu",
     "query": "select mean(usage_guest) as guest from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "guest_nice",
     "expr": "median(cpu_usage_guest_nice{host =~ \"$server$\",cpu = 'cpu-total'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: guest_nice",
     "measurement": "cpu",
     "query": "select mean(usage_guest_nice) as guest_nice from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = 'cpu-total' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_guest_nice" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = 'cpu-total'}"
    }
   ]
  },
  {
   "title": "Load averages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "short",
     "expr": "median(system_load1{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: short",
     "measurement": "system",
     "query": "select mean(load1) as short from \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "params": [ "load1" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "medium",
     "expr": "median(system_load5{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: medium",
     "measurement": "system",
     "query": "select mean(load5) as medium from \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "params": [ "load5" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "long",
     "expr": "median(system_load15{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: long",
     "measurement": "system",
     "query": "select mean(load15) as long from \"system\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), * ORDER BY asc",
     "select": [
      [
       { "params": [ "load15" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "running",
     "expr": "median(processes_running{host =~ \"$server$\"}) by (host)",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: running",
     "measurement": "processes",
     "query": "select mean(running) as running from \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "running" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "blocked",
     "expr": "median(processes_blocked{host =~ \"$server$\"}) by (host)",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: blocked",
     "measurement": "processes",
     "query": "select mean(blocked) as blocked from \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "blocked" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "sleeping",
     "expr": "median(processes_sleeping{host =~ \"$server$\"}) by (host)",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: sleeping",
     "measurement": "processes",
     "query": "select mean(sleeping) as sleeping from \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "sleeping" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "stopped",
     "expr": "median(processes_stopped{host =~ \"$server$\"}) by (host)",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: stopped",
     "measurement": "processes",
     "query": "select mean(stopped) as stopped from \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "stopped" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "zombies",
     "expr": "median(processes_zombies{host =~ \"$server$\"}) by (host)",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: zombies",
     "measurement": "processes",
     "query": "select mean(zombies) as zombies from \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "zombies" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "paging",
     "expr": "median(processes_paging{host =~ \"$server$\"}) by (host)",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: paging",
     "measurement": "processes",
     "query": "select mean(paging) as paging from \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "paging" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "unknown",
     "expr": "median(processes_unknown{host =~ \"$server$\"}) by (host)",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: unknown",
     "measurement": "processes",
     "query": "select mean(unknown) as unknown from \"processes\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "unknown" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "total",
     "expr": "median(mem_total{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: total",
     "measurement": "mem",
     "query": "select mean(total) as total from \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "total" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "used",
     "expr": "median(mem_used{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: used",
     "measurement": "mem",
     "query": "select mean(used) as used from \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "used" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "cached",
     "expr": "median(mem_cached{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: cached",
     "measurement": "mem",
     "query": "select mean(cached) as cached from \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "cached" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "free",
     "expr": "median(mem_free{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: free",
     "measurement": "mem",
     "query": "select mean(free) as free from \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "free" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "buffered",
     "expr": "median(mem_buffered{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: buffered",
     "measurement": "mem",
     "query": "select mean(buffered) as buffered from \"mem\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "buffered" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Context switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "expr": "abs(ideriv(median(kernel_context_switches{host =~ \"$server$\"}) by (host)))",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: context_switches",
     "measurement": "kernel",
     "query": "SELECT non_negative_derivative(mean(context_switches),1s)as \"context switches\"  FROM \"kernel\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "context_switches" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "forks",
     "expr": "abs(ideriv(median(kernel_processes_forked{host =~ \"^$server$\"}) by (host)))",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: forks",
     "measurement": "kernel",
     "query": "SELECT non_negative_derivative(mean(processes_forked),1s) as forks FROM \"kernel\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
     "select": [
      [
       { "params": [ "processes_forked" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "File descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "max",
     "expr": "median(linux_sysctl_fs_file-max{host =~ \"^$server$\"}) by (host)",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: max",
     "measurement": "linux_sysctl_fs",
     "query": "SELECT mean(\"file-max\") as max FROM \"linux_sysctl_fs\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
     "select": [
      [
       { "params": [ "file-max" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "opened",
     "expr": "median(linux_sysctl_fs_file-nr{host =~ \"^$server$\"}) by (host)",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: opened",
     "measurement": "linux_sysctl_fs",
     "query": "SELECT mean(\"file-nr\") as opened FROM \"linux_sysctl_fs\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval), host fill(null)",
     "select": [
      [
       { "params": [ "file-nr" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_irq",
     "expr": "abs(idelta(median(interrupts_total{host =~ \"^$server$\"}) by (irq,host)))",
     "groupBy": " by (irq,host)",
     "legendFormat": "{{host}}: {{irq}}",
     "measurement": "interrupts",
     "select": [
      [
       { "params": [ "total" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "Per-cpu usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU usage for $cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 51 },
   "repeat": "cpu",
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $cpu $col",
     "col": "user",
     "expr": "median(cpu_usage_user{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: $cpu user",
     "measurement": "cpu",
     "query": "select mean(usage_user) as user from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}"
    },
    {
     "alias": "$tag_host: $cpu $col",
     "col": "system",
     "expr": "median(cpu_usage_system{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: $cpu system",
     "measurement": "cpu",
     "query": "select mean(usage_system) as system from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}"
    },
    {
     "alias": "$tag_host: $cpu $col",
     "col": "softirq",
     "expr": "median(cpu_usage_softirq{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: $cpu softirq",
     "measurement": "cpu",
     "query": "select mean(usage_softirq) as softirq from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_softirq" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}"
    },
    {
     "alias": "$tag_host: $cpu $col",
     "col": "steal",
     "expr": "median(cpu_usage_steal{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: $cpu steal",
     "measurement": "cpu",
     "query": "select mean(usage_steal) as steal from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_steal" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}"
    },
    {
     "alias": "$tag_host: $cpu $col",
     "col": "nice",
     "expr": "median(cpu_usage_nice{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: $cpu nice",
     "measurement": "cpu",
     "query": "select mean(usage_nice) as nice from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_nice" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}"
    },
    {
     "alias": "$tag_host: $cpu $col",
     "col": "irq",
     "expr": "median(cpu_usage_irq{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: $cpu irq",
     "measurement": "cpu",
     "query": "select mean(usage_irq) as irq from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_irq" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}"
    },
    {
     "alias": "$tag_host: $cpu $col",
     "col": "iowait",
     "expr": "median(cpu_usage_iowait{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: $cpu iowait",
     "measurement": "cpu",
     "query": "select mean(usage_iowait) as iowait from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}"
    },
    {
     "alias": "$tag_host: $cpu $col",
     "col": "guest",
     "expr": "median(cpu_usage_guest{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: $cpu guest",
     "measurement": "cpu",
     "query": "select mean(usage_guest) as guest from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_guest" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}"
    },
    {
     "alias": "$tag_host: $cpu $col",
     "col": "guest_nice",
     "expr": "median(cpu_usage_guest_nice{host =~ \"$server$\",cpu = '$cpu'}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: $cpu guest_nice",
     "measurement": "cpu",
     "query": "select mean(usage_guest_nice) as guest_nice from \"cpu\" WHERE \"host\" =~ /$server$/ and cpu = '$cpu' AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "usage_guest_nice" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",cpu = '$cpu'}"
    }
   ]
  },
  {
   "title": "Conntrack",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Netfilter conntrack usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$server: current",
     "expr": "median(conntrack_ip_conntrack_count{host =~ \"^$server$\"})",
     "legendFormat": "$server: current",
     "measurement": "conntrack",
     "select": [
      [
       { "params": [ "ip_conntrack_count" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "$server: maximum",
     "expr": "median(conntrack_ip_conntrack_max{host =~ \"^$server$\"})",
     "legendFormat": "$server: maximum",
     "measurement": "conntrack",
     "select": [
      [
       { "params": [ "ip_conntrack_max" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "Network stack (TCP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {}
   ]
  },
  {
   "title": "TCP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "CLOSED",
     "expr": "median(netstat_tcp_close{host =~ \"$server$\"}) by (host)",
     "function": "derivative",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: CLOSED",
     "measurement": "netstat",
     "query": "select mean(tcp_close) as CLOSED from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "tcp_close" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "CLOSE_WAIT",
     "expr": "median(netstat_tcp_close_wait{host =~ \"$server$\"}) by (host)",
     "function": "derivative",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: CLOSE_WAIT",
     "measurement": "netstat",
     "query": "select mean(tcp_close_wait) as CLOSE_WAIT from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "tcp_close_wait" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "CLOSING",
     "expr": "median(netstat_tcp_closing{host =~ \"$server$\"}) by (host)",
     "function": "derivative",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: CLOSING",
     "measurement": "netstat",
     "query": "select mean(tcp_closing) as CLOSING from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "tcp_closing" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "ESTABLISHED",
     "expr": "median(netstat_tcp_established{host =~ \"$server$\"}) by (host)",
     "function": "derivative",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: ESTABLISHED",
     "measurement": "netstat",
     "query": "select mean(tcp_established) as ESTABLISHED from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "tcp_established" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "FIN_WAIT1",
     "expr": "median(netstat_tcp_fin_wait1{host =~ \"$server$\"}) by (host)",
     "function": "derivative",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: FIN_WAIT1",
     "measurement": "netstat",
     "query": "select mean(tcp_fin_wait1) as FIN_WAIT1 from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "tcp_fin_wait1" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "FIN_WAIT2",
     "expr": "median(netstat_tcp_fin_wait2{host =~ \"$server$\"}) by (host)",
     "function": "derivative",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: FIN_WAIT2",
     "measurement": "netstat",
     "query": "select mean(tcp_fin_wait2) as FIN_WAIT2 from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "tcp_fin_wait2" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "LAST_ACK",
     "expr": "median(netstat_tcp_last_ack{host =~ \"$server$\"}) by (host)",
     "function": "derivative",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: LAST_ACK",
     "measurement": "netstat",
     "query": "select mean(tcp_last_ack) as LAST_ACK from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "tcp_last_ack" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "SYN_RECV",
     "expr": "median(netstat_tcp_syn_recv{host =~ \"$server$\"}) by (host)",
     "function": "derivative",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: SYN_RECV",
     "measurement": "netstat",
     "query": "select mean(tcp_syn_recv) as SYN_RECV from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "tcp_syn_recv" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "SYN_SENT",
     "expr": "median(netstat_tcp_syn_sent{host =~ \"$server$\"}) by (host)",
     "function": "derivative",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: SYN_SENT",
     "measurement": "netstat",
     "query": "select mean(tcp_syn_sent) as SYN_SENT from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "tcp_syn_sent" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "TIME_WAIT",
     "expr": "median(netstat_tcp_time_wait{host =~ \"$server$\"}) by (host)",
     "function": "derivative",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: TIME_WAIT",
     "measurement": "netstat",
     "query": "select mean(tcp_time_wait) as TIME_WAIT from \"netstat\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "tcp_time_wait" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "TCP aborts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "on close",
     "expr": "abs(idelta(median(nstat_TcpExtTCPAbortOnClose{host =~ \"^$server$\"})))",
     "legendFormat": "on close",
     "measurement": "nstat",
     "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "TcpExtTCPAbortOnClose" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "on data",
     "expr": "abs(idelta(median(nstat_TcpExtTCPAbortOnData{host =~ \"^$server$\"})))",
     "legendFormat": "on data",
     "measurement": "nstat",
     "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "TcpExtTCPAbortOnData" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "timeout",
     "expr": "abs(idelta(median(nstat_TcpExtTCPAbortOnTimeout{host =~ \"^$server$\"})))",
     "legendFormat": "timeout",
     "measurement": "nstat",
     "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "TcpExtTCPAbortOnTimeout" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "failed",
     "expr": "abs(idelta(median(nstat_TcpExtTCPAbortFailed{host =~ \"^$server$\"})))",
     "legendFormat": "failed",
     "measurement": "nstat",
     "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "TcpExtTCPAbortFailed" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "linger",
     "expr": "abs(idelta(median(nstat_TcpExtTCPAbortOnLinger{host =~ \"^$server$\"})))",
     "legendFormat": "linger",
     "measurement": "nstat",
     "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "TcpExtTCPAbortOnLinger" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "memory",
     "expr": "abs(idelta(median(nstat_TcpExtTCPAbortOnMemory{host =~ \"^$server$\"})))",
     "legendFormat": "memory",
     "measurement": "nstat",
     "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "TcpExtTCPAbortOnMemory" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "TCP handshake issues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "estabresets",
     "expr": "abs(ideriv(median(net_tcp_estabresets{host =~ \"^$server$\"})))",
     "legendFormat": "estabresets",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(tcp_estabresets), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "tcp_estabresets" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "outrsts",
     "expr": "abs(ideriv(median(net_tcp_outrsts{host =~ \"^$server$\"})))",
     "legendFormat": "outrsts",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(tcp_outrsts), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "tcp_outrsts" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "activeopens",
     "expr": "abs(ideriv(median(net_tcp_activeopens{host =~ \"^$server$\"})))",
     "legendFormat": "activeopens",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(tcp_activeopens), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "tcp_activeopens" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "passiveopens",
     "expr": "abs(ideriv(median(net_tcp_passiveopens{host =~ \"^$server$\"})))",
     "legendFormat": "passiveopens",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(tcp_passiveopens), 1s) FROM \"net\" WHERE \"host\" =~ /^$server$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "tcp_passiveopens" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "TCP SYN cookies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "failed",
     "expr": "abs(ideriv(median(nstat_TcpExtSyncookiesFailed{host =~ \"^$server$\"})))",
     "legendFormat": "failed",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "TcpExtSyncookiesFailed" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "received",
     "expr": "abs(ideriv(median(nstat_TcpExtSyncookiesRecv{host =~ \"^$server$\"})))",
     "legendFormat": "received",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "TcpExtSyncookiesRecv" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "sent",
     "expr": "abs(ideriv(median(nstat_TcpExtSyncookiesSent{host =~ \"^$server$\"})))",
     "legendFormat": "sent",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "TcpExtSyncookiesSent" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "ICMP packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 102 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "in echos",
     "expr": "abs(ideriv(median(nstat_IcmpInEchos{host =~ \"^$server$\"})))",
     "legendFormat": "in echos",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IcmpInEchos" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "out echos",
     "expr": "abs(ideriv(median(nstat_IcmpOutEchos{host =~ \"^$server$\"})))",
     "legendFormat": "out echos",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IcmpOutEchos" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "in echo responses",
     "expr": "abs(ideriv(median(nstat_IcmpInEchoReps{host =~ \"^$server$\"})))",
     "legendFormat": "in echo responses",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IcmpInEchoReps" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "out echo responses",
     "expr": "abs(ideriv(median(nstat_IcmpOutEchoReps{host =~ \"^$server$\"})))",
     "legendFormat": "out echo responses",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IcmpOutEchoReps" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "ICMP errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 102 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "in errors",
     "expr": "abs(ideriv(median(nstat_IcmpInErrors{host =~ \"^$server$\"})))",
     "legendFormat": "in errors",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IcmpInErrors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "out errors",
     "expr": "abs(ideriv(median(nstat_IcmpOutErrors{host =~ \"^$server$\"})))",
     "legendFormat": "out errors",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IcmpOutErrors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "checksum errors",
     "expr": "abs(ideriv(median(nstat_IcmpInCsumErrors{host =~ \"^$server$\"})))",
     "legendFormat": "checksum errors",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IcmpInCsumErrors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "IPv4 errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "in discards",
     "expr": "abs(ideriv(median(nstat_IpInDiscards{host =~ \"^$server$\"})))",
     "legendFormat": "in discards",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IpInDiscards" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "out discards",
     "expr": "abs(ideriv(median(nstat_IpOutDiscards{host =~ \"^$server$\"})))",
     "legendFormat": "out discards",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IpOutDiscards" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "in hdr errors",
     "expr": "abs(ideriv(median(nstat_IpInHdrErrors{host =~ \"^$server$\"})))",
     "legendFormat": "in hdr errors",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IpInHdrErrors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "in addr errors",
     "expr": "abs(ideriv(median(nstat_IpInAddrErrors{host =~ \"^$server$\"})))",
     "legendFormat": "in addr errors",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IpInAddrErrors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "out no routes",
     "expr": "abs(ideriv(median(nstat_IpOutNoRoutes{host =~ \"^$server$\"})))",
     "legendFormat": "out no routes",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IpOutNoRoutes" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "in unknown protocol",
     "expr": "abs(ideriv(median(nstat_IpInUnknownProtos{host =~ \"^$server$\"})))",
     "legendFormat": "in unknown protocol",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "IpInUnknownProtos" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "IPv6 errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "in discards",
     "expr": "abs(ideriv(median(nstat_Ip6InDiscards{host =~ \"^$server$\"})))",
     "legendFormat": "in discards",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "Ip6InDiscards" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "out discards",
     "expr": "abs(ideriv(median(nstat_Ip6OutDiscards{host =~ \"^$server$\"})))",
     "legendFormat": "out discards",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "Ip6OutDiscards" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "in hdr errors",
     "expr": "abs(ideriv(median(nstat_Ip6InHdrErrors{host =~ \"^$server$\"})))",
     "legendFormat": "in hdr errors",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "Ip6InHdrErrors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "in addr errors",
     "expr": "abs(ideriv(median(nstat_Ip6InAddrErrors{host =~ \"^$server$\"})))",
     "legendFormat": "in addr errors",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "Ip6InAddrErrors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "out no routes",
     "expr": "abs(ideriv(median(nstat_Ip6OutNoRoutes{host =~ \"^$server$\"})))",
     "legendFormat": "out no routes",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "Ip6OutNoRoutes" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "in unknown protocol",
     "expr": "abs(ideriv(median(nstat_Ip6InUnknownProtos{host =~ \"^$server$\"})))",
     "legendFormat": "in unknown protocol",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "Ip6InUnknownProtos" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "Network stack (UDP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "targets": [
    {}
   ]
  },
  {
   "title": "UDP datagrams",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "in datagrams",
     "expr": "abs(ideriv(median(net_udp_indatagrams{host =~ \"$server\"}) by (host)))",
     "function": "derivative",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: in datagrams",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(udp_indatagrams), 1s) as \"in datagrams\" FROM \"net\" WHERE host =~ /$server/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "udp_indatagrams" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "out datagrams",
     "expr": "abs(ideriv(median(net_udp_outdatagrams{host =~ \"$server\"}) by (host)))",
     "function": "derivative",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: out datagrams",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(udp_outdatagrams), 1s) as \"out datagrams\" FROM \"net\" WHERE host =~ /$server/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "udp_outdatagrams" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server\"}"
    }
   ]
  },
  {
   "title": "UDP buffer errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Send buffer errors",
     "expr": "abs(ideriv(median(nstat_UdpSndbufErrors{host =~ \"^$server$\"})))",
     "legendFormat": "Send buffer errors",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpSndbufErrors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "Receive buffer errors",
     "expr": "abs(ideriv(median(nstat_UdpRcvbufErrors{host =~ \"^$server$\"})))",
     "legendFormat": "Receive buffer errors",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpRcvbufErrors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "UDP errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "checksum errors",
     "expr": "abs(ideriv(median(nstat_UdpInCsumErrors{host =~ \"^$server$\"})))",
     "legendFormat": "checksum errors",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpInCsumErrors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "in errors",
     "expr": "abs(ideriv(median(nstat_UdpInErrors{host =~ \"^$server$\"})))",
     "legendFormat": "in errors",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpInErrors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "no ports",
     "expr": "abs(ideriv(median(nstat_UdpNoPorts{host =~ \"^$server$\"})))",
     "legendFormat": "no ports",
     "measurement": "nstat",
     "select": [
      [
       { "params": [ "UdpNoPorts" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "Network interface stats for $netif",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 },
   "repeat": "netif",
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_interface: $col",
     "col": "in",
     "expr": "abs(ideriv(median(net_bytes_recv{host =~ \"$server\",interface =~ \"$netif\"}) by (host,interface)))*8",
     "function": "derivative",
     "groupBy": " by (host,interface)",
     "legendFormat": "{{host}}: {{interface}}: in",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(bytes_recv),1s)*8 as \"in\"  FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server\",interface =~ \"$netif\"}"
    },
    {
     "alias": "$tag_host: $tag_interface: $col",
     "col": "out",
     "expr": "abs(ideriv(median(net_bytes_sent{host =~ \"$server\",interface =~ \"$netif\"}) by (host,interface)))*8",
     "function": "derivative",
     "groupBy": " by (host,interface)",
     "legendFormat": "{{host}}: {{interface}}: out",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(bytes_sent),1s)*8 as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server\",interface =~ \"$netif\"}"
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_interface: $col",
     "col": "in",
     "expr": "abs(ideriv(median(net_packets_recv{host =~ \"$server\",interface =~ \"$netif\"}) by (host,interface)))",
     "function": "derivative",
     "groupBy": " by (host,interface)",
     "legendFormat": "{{host}}: {{interface}}: in",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(packets_recv), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "packets_recv" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server\",interface =~ \"$netif\"}"
    },
    {
     "alias": "$tag_host: $tag_interface: $col",
     "col": "out",
     "expr": "abs(ideriv(median(net_packets_sent{host =~ \"$server\",interface =~ \"$netif\"}) by (host,interface)))",
     "function": "derivative",
     "groupBy": " by (host,interface)",
     "legendFormat": "{{host}}: {{interface}}: out",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(packets_sent), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), * fill(none)",
     "select": [
      [
       { "params": [ "packets_sent" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server\",interface =~ \"$netif\"}"
    }
   ]
  },
  {
   "title": "Network drops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "pps", "label": "Drops per second" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_interface: $col",
     "col": "in",
     "expr": "abs(ideriv(median(net_drop_in{host =~ \"$server\",interface =~ \"$netif\"}) by (host,interface)))",
     "function": "derivative",
     "groupBy": " by (host,interface)",
     "legendFormat": "{{host}}: {{interface}}: in",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(drop_in), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
     "select": [
      [
       { "params": [ "drop_in" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server\",interface =~ \"$netif\"}"
    },
    {
     "alias": "$tag_host: $tag_interface: $col",
     "col": "out",
     "expr": "abs(ideriv(median(net_drop_out{host =~ \"$server\",interface =~ \"$netif\"}) by (host,interface)))",
     "function": "derivative",
     "groupBy": " by (host,interface)",
     "legendFormat": "{{host}}: {{interface}}: out",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(drop_out), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
     "select": [
      [
       { "params": [ "drop_out" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server\",interface =~ \"$netif\"}"
    }
   ]
  },
  {
   "title": "Network errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "short", "label": "Errors per second" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_interface: $col",
     "col": "in",
     "expr": "abs(ideriv(median(net_err_in{host =~ \"$server\",interface =~ \"$netif\"}) by (host,interface)))",
     "function": "derivative",
     "groupBy": " by (host,interface)",
     "legendFormat": "{{host}}: {{interface}}: in",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(err_in), 1s) as \"in\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
     "select": [
      [
       { "params": [ "err_in" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server\",interface =~ \"$netif\"}"
    },
    {
     "alias": "$tag_host: $tag_interface: $col",
     "col": "out",
     "expr": "abs(ideriv(median(net_err_out{host =~ \"$server\",interface =~ \"$netif\"}) by (host,interface)))",
     "function": "derivative",
     "groupBy": " by (host,interface)",
     "legendFormat": "{{host}}: {{interface}}: out",
     "measurement": "net",
     "query": "SELECT non_negative_derivative(mean(err_out), 1s) as \"out\" FROM \"net\" WHERE host =~ /$server/ AND interface =~ /$netif/ AND $timeFilter GROUP BY time($interval), host,interface fill(none)",
     "select": [
      [
       { "params": [ "err_out" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server\",interface =~ \"$netif\"}"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 401 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Swap I/O bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 402 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "in",
     "expr": "abs(idelta(median(swap_in{host =~ \"$server$\"}) by (host)))",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: in",
     "measurement": "swap",
     "query": "select non_negative_derivative(mean(in)) as in from \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "in" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "out",
     "expr": "abs(idelta(median(swap_out{host =~ \"$server$\"}) by (host)))",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: out",
     "measurement": "swap",
     "query": "select non_negative_derivative(mean(out)) as out from \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "out" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Swap usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 402 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $col",
     "col": "used",
     "expr": "median(swap_used{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: used",
     "measurement": "swap",
     "query": "select mean(used) as used from \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "used" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    },
    {
     "alias": "$tag_host: $col",
     "col": "total",
     "expr": "median(swap_total{host =~ \"$server$\"}) by (host)",
     "function": "mean",
     "groupBy": " by (host)",
     "legendFormat": "{{host}}: total",
     "measurement": "swap",
     "query": "select mean(total) as total from \"swap\" WHERE host =~ /$server$/ AND $timeFilter GROUP BY time($interval), host ORDER BY asc",
     "select": [
      [
       { "params": [ "total" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\"}"
    }
   ]
  },
  {
   "title": "Disk IOPS for /dev/$disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 409 },
   "repeat": "disk",
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk I/O requests for /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 410 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "col": "read",
     "expr": "abs(ideriv(median(diskio_reads{host =~ \"$server$\",name =~ \"$disk$\"}) by (host,name)))",
     "function": "mean",
     "groupBy": " by (host,name)",
     "legendFormat": "{{host}}: {{name}}: read",
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(reads),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "reads" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",name =~ \"$disk$\"}"
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "col": "write",
     "expr": "abs(ideriv(median(diskio_writes{host =~ \"$server$\",name =~ \"$disk$\"}) by (host,name)))",
     "function": "mean",
     "groupBy": " by (host,name)",
     "legendFormat": "{{host}}: {{name}}: write",
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(writes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "writes" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",name =~ \"$disk$\"}"
    }
   ]
  },
  {
   "title": "Disk I/O bytes for /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 410 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "col": "read",
     "expr": "abs(ideriv(median(diskio_read_bytes{host =~ \"$server$\",name =~ \"$disk$\"}) by (host,name)))",
     "function": "mean",
     "groupBy": " by (host,name)",
     "legendFormat": "{{host}}: {{name}}: read",
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(read_bytes),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",name =~ \"$disk$\"}"
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "col": "write",
     "expr": "abs(ideriv(median(diskio_write_bytes{host =~ \"$server$\",name =~ \"$disk$\"}) by (host,name)))",
     "function": "mean",
     "groupBy": " by (host,name)",
     "legendFormat": "{{host}}: {{name}}: write",
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(write_bytes),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "write_bytes" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",name =~ \"$disk$\"}"
    }
   ]
  },
  {
   "title": "Disk I/O time for /dev/$disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 410 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host: $tag_name: $col",
     "col": "read",
     "expr": "abs(ideriv(median(diskio_read_time{host =~ \"$server$\",name =~ \"$disk$\"}) by (host,name)))",
     "function": "mean",
     "groupBy": " by (host,name)",
     "legendFormat": "{{host}}: {{name}}: read",
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(read_time),1s) as \"read\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/  AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "read_time" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",name =~ \"$disk$\"}"
    },
    {
     "alias": "$tag_host: $tag_name: $col",
     "col": "write",
     "expr": "abs(ideriv(median(diskio_write_time{host =~ \"$server$\",name =~ \"$disk$\"}) by (host,name)))",
     "function": "mean",
     "groupBy": " by (host,name)",
     "legendFormat": "{{host}}: {{name}}: write",
     "measurement": "diskio",
     "query": "SELECT non_negative_derivative(mean(write_time),1s) as \"write\" FROM \"diskio\" WHERE \"host\" =~ /$server$/ AND \"name\" =~ /$disk$/ AND $timeFilter GROUP BY time($interval), *",
     "select": [
      [
       { "params": [ "write_time" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",name =~ \"$disk$\"}"
    }
   ]
  },
  {
   "title": "Disk space usage for $mountpoint",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 465 },
   "repeat": "mountpoint",
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk usage for $mountpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 466 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host: mountpoint $tag_path - $col",
     "col": "total",
     "expr": "median(disk_total{host =~ \"$server$\",path =~ \"^$mountpoint$\"}) by (host,path)",
     "function": "mean",
     "groupBy": " by (host,path)",
     "legendFormat": "{{host}}: mountpoint {{path}} - total",
     "measurement": "disk",
     "query": "select mean(total) AS total from \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" =~ /^$mountpoint$/AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "total" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",path =~ \"^$mountpoint$\"}"
    },
    {
     "alias": "$tag_host: mountpoint $tag_path - $col",
     "col": "used",
     "expr": "median(disk_used{host =~ \"$server$\",path =~ \"^$mountpoint$\"}) by (host,path)",
     "function": "mean",
     "groupBy": " by (host,path)",
     "legendFormat": "{{host}}: mountpoint {{path}} - used",
     "measurement": "disk",
     "query": "select mean(used) as used from \"disk\" WHERE \"host\" =~ /$server$/ AND \"path\" =~ /^$mountpoint$/AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "used" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",path =~ \"^$mountpoint$\"}"
    }
   ]
  },
  {
   "title": "Disk inodes for $mountpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 466 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host: mountpoint $tag_path - $col",
     "col": "used",
     "expr": "median(disk_inodes_used{host =~ \"$server$\",path =~ \"^$mountpoint$\"}) by (host,path)",
     "function": "mean",
     "groupBy": " by (host,path)",
     "legendFormat": "{{host}}: mountpoint {{path}} - used",
     "measurement": "disk",
     "query": "SELECT mean(inodes_used) as \"used\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "inodes_used" ], "type": "mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",path =~ \"^$mountpoint$\"}"
    },
    {
     "alias": "$tag_host: mountpoint $tag_path - $col",
     "col": "total",
     "expr": "median(disk_inodes_free{host =~ \"$server$\",path =~ \"^$mountpoint$\"}) + median(disk_inodes_used{host =~ \"$server$\",path =~ \"^$mountpoint$\"}) by (host,path)",
     "function": "mean",
     "groupBy": " by (host,path)",
     "legendFormat": "{{host}}: mountpoint {{path}} - total",
     "measurement": "disk",
     "query": "SELECT mean(inodes_free) + mean(inodes_used) as \"total\" FROM \"disk\" WHERE \"host\" =~ /$server$/  AND \"path\" =~ /^$mountpoint$/ AND $timeFilter GROUP BY time($interval), \"host\", \"path\"",
     "select": [
      [
       { "params": [ "inodes_used" ], "type": "mean(inodes_free) + mean" }
      ]
     ],
     "tags": "{host =~ \"$server$\",path =~ \"^$mountpoint$\"}"
    }
   ]
  },
  {
   "title": "Metrics velocity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1217 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Delivery time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1218 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Delivery time",
     "expr": "abs(idelta(median(internal_write_write_time_ns{host =~ \"^$server$\"})))",
     "legendFormat": "Delivery time",
     "measurement": "internal_write",
     "select": [
      [
       { "params": [ "write_time_ns" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "Gather time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1218 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "alias": "Gather time",
     "expr": "abs(idelta(median(internal_gather_gather_time_ns{host =~ \"^$server$\"})))",
     "legendFormat": "Gather time",
     "measurement": "internal_gather",
     "select": [
      [
       { "params": [ "gather_time_ns" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "Written metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1218 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Metrics written",
     "expr": "abs(idelta(median(internal_agent_metrics_written{host =~ \"^$server$\"})))",
     "legendFormat": "Metrics written",
     "measurement": "internal_agent",
     "select": [
      [
       { "params": [ "metrics_written" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1218 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Gather errors",
     "expr": "abs(idelta(median(internal_agent_gather_errors{host =~ \"^$server$\"})))",
     "legendFormat": "Gather errors",
     "measurement": "internal_agent",
     "select": [
      [
       { "params": [ "gather_errors" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    },
    {
     "alias": "Dropped metrics",
     "expr": "abs(idelta(median(internal_agent_metrics_dropped{host =~ \"^$server$\"})))",
     "legendFormat": "Dropped metrics",
     "measurement": "internal_agent",
     "select": [
      [
       { "params": [ "metrics_dropped" ], "type": "non_negative_derivative(mean" }
      ]
     ],
     "tags": "{host =~ \"^$server$\"}"
    }
   ]
  }
 ]
}