{
 "title": "Ubiquity EdgeRouter [SNMP] (1756)",
 "description": "UBNT EdgeRouter Templated Dashboard",
 "tags": [
  "ubiquity",
  "edgerouter",
  "snmp",
  "influxdb",
  "network"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "dataSource", "query": "influxdb" },
   {
    "name": "host",
    "label": "Router:",
    "query": "SHOW TAG VALUES FROM \"snmp.EdgeOS\" WITH KEY = \"agent_host\""
   },
   {
    "name": "intf",
    "label": "Interface:",
    "query": "SHOW TAG VALUES FROM \"ifTable\" WITH KEY = \"ifName\" WHERE \"agent_host\" =~ /^$host$/"
   }
  ]
 },
 "panels": [
  {
   "title": "$host",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "sysName" ], "type": "tag" }
     ],
     "measurement": "snmp.EdgeOS",
     "select": [
      [
       { "params": [ "sysDescr" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Description" ], "type": "alias" }
      ],
      [
       { "params": [ "sysContact" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Contact" ], "type": "alias" }
      ],
      [
       { "params": [ "sysLocation" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Location" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "snmp.EdgeOS",
     "select": [
      [
       { "params": [ "sysUpTime" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "snmp.EdgeOS",
     "select": [
      [
       { "params": [ "hrSystemNumUsers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "snmp.EdgeOS",
     "query": "SELECT last(\"hrSystemProcesses\") FROM \"snmp.EdgeOS\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "hrSystemProcesses" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_laNames Minute",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "laNames" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "laTable",
     "select": [
      [
       { "params": [ "laLoadInt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Interrupts / Ctx-Switches (/sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.EdgeOS",
     "select": [
      [
       { "params": [ "ssRawContexts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Context Switches" ], "type": "alias" }
      ],
      [
       { "params": [ "ssRawInterrupts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Interrupts" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Block I/O (/sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.EdgeOS",
     "select": [
      [
       { "params": [ "ssIORawSent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "BlocksOut" ], "type": "alias" }
      ],
      [
       { "params": [ "ssIORawReceived" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "BlocksIn" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.EdgeOS",
     "query": "SELECT difference(\"ssCpuRawUser\") / (difference(\"ssCpuRawUser\") + difference(\"ssCpuRawNice\") + difference(\"ssCpuRawSystem\") + difference(\"ssCpuRawIdle\") + difference(\"ssCpuRawWait\") + difference(\"ssCpuRawKernel\") + difference(\"ssCpuRawInterrupt\") + difference(\"ssCpuRawSoftIRQ\")) AS \"User\" FROM \"snmp.EdgeOS\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "ssCpuRawIdle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "Idle" ], "type": "alias" }
      ],
      [
       { "params": [ "ssCpuRawInterrupt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "Interrupt" ], "type": "alias" }
      ],
      [
       { "params": [ "ssCpuRawKernel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "Kernel" ], "type": "alias" }
      ],
      [
       { "params": [ "ssCpuRawNice" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "Nice" ], "type": "alias" }
      ],
      [
       { "params": [ "ssCpuRawSystem" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "System" ], "type": "alias" }
      ],
      [
       { "params": [ "ssCpuRawUser" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "User" ], "type": "alias" }
      ],
      [
       { "params": [ "ssCpuRawWait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "I/O Wait" ], "type": "alias" }
      ],
      [
       { "params": [ "ssCpuRawSoftIRQ" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "Soft IRQ" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"ssCpuRawNice\")  / (difference(\"ssCpuRawUser\") + difference(\"ssCpuRawNice\") + difference(\"ssCpuRawSystem\") + difference(\"ssCpuRawIdle\") + difference(\"ssCpuRawWait\") + difference(\"ssCpuRawKernel\") + difference(\"ssCpuRawInterrupt\") + difference(\"ssCpuRawSoftIRQ\")) AS \"Nice\" FROM \"snmp.EdgeOS\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"ssCpuRawSystem\")  / (difference(\"ssCpuRawUser\") + difference(\"ssCpuRawNice\") + difference(\"ssCpuRawSystem\") + difference(\"ssCpuRawIdle\") + difference(\"ssCpuRawWait\") + difference(\"ssCpuRawKernel\") + difference(\"ssCpuRawInterrupt\") + difference(\"ssCpuRawSoftIRQ\")) AS \"System\" FROM \"snmp.EdgeOS\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"ssCpuRawIdle\")  / (difference(\"ssCpuRawUser\") + difference(\"ssCpuRawNice\") + difference(\"ssCpuRawSystem\") + difference(\"ssCpuRawIdle\") + difference(\"ssCpuRawWait\") + difference(\"ssCpuRawKernel\") + difference(\"ssCpuRawInterrupt\") + difference(\"ssCpuRawSoftIRQ\")) AS \"Idle\" FROM \"snmp.EdgeOS\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"ssCpuRawWait\")  / (difference(\"ssCpuRawUser\") + difference(\"ssCpuRawNice\") + difference(\"ssCpuRawSystem\") + difference(\"ssCpuRawIdle\") + difference(\"ssCpuRawWait\") + difference(\"ssCpuRawKernel\") + difference(\"ssCpuRawInterrupt\") + difference(\"ssCpuRawSoftIRQ\")) AS \"I/O Wait\" FROM \"snmp.EdgeOS\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"ssCpuRawKernel\")  / (difference(\"ssCpuRawUser\") + difference(\"ssCpuRawNice\") + difference(\"ssCpuRawSystem\") + difference(\"ssCpuRawIdle\") + difference(\"ssCpuRawWait\") + difference(\"ssCpuRawKernel\") + difference(\"ssCpuRawInterrupt\") + difference(\"ssCpuRawSoftIRQ\")) AS \"Kernel\" FROM \"snmp.EdgeOS\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"ssCpuRawInterrupt\")  / (difference(\"ssCpuRawUser\") + difference(\"ssCpuRawNice\") + difference(\"ssCpuRawSystem\") + difference(\"ssCpuRawIdle\") + difference(\"ssCpuRawWait\") + difference(\"ssCpuRawKernel\") + difference(\"ssCpuRawInterrupt\") + difference(\"ssCpuRawSoftIRQ\")) AS \"Interrupt\" FROM \"snmp.EdgeOS\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"ssCpuRawSoftIRQ\")  / (difference(\"ssCpuRawUser\") + difference(\"ssCpuRawNice\") + difference(\"ssCpuRawSystem\") + difference(\"ssCpuRawIdle\") + difference(\"ssCpuRawWait\") + difference(\"ssCpuRawKernel\") + difference(\"ssCpuRawInterrupt\") + difference(\"ssCpuRawSoftIRQ\")) AS \"Soft IRQ\" FROM \"snmp.EdgeOS\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Processor Load (1 Minute Average)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_index",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "index" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hrProcessorTable",
     "select": [
      [
       { "params": [ "hrProcessorLoad" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.EdgeOS",
     "select": [
      [
       { "params": [ "memBuffer" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Buffer" ], "type": "alias" }
      ],
      [
       { "params": [ "memCached" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Cache" ], "type": "alias" }
      ],
      [
       { "params": [ "memShared" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Shared" ], "type": "alias" }
      ],
      [
       { "params": [ "memTotalFree" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Free" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.EdgeOS",
     "select": [
      [
       { "params": [ "memAvailReal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Real" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_hrStorageDescr",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hrStorageTable",
     "query": "SELECT (last(\"hrStorageUsed\")/last(\"hrStorageSize\"))  FROM \"hrStorageTable\"  WHERE \"agent_host\" =~ /^$host$/ AND \"hrStorageType\" = '.1.3.6.1.2.1.25.2.1.2' AND $timeFilter GROUP BY time($interval), \"hrStorageDescr\" fill(null)",
     "select": [
      [
       { "params": [ "hrStorageUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifXTable",
     "select": [
      [
       { "params": [ "ifHCInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$intf$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Traffic Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifXTable",
     "select": [
      [
       { "params": [ "ifHCInBroadcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Bcast:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutBroadcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Bcast:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCInMulticastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Mcast:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutMulticastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Mcast:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCInUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Ucast:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifHCOutUcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Ucast:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$intf$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Drops/Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_ifName:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ifTable",
     "select": [
      [
       { "params": [ "ifInDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drop:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOutDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drop:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ifInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOutErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ifInUnknownProtos" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Unkwn:In" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "ifName", "operator": "=~", "value": "/^$intf$/" }
     ]
    }
   ]
  },
  {
   "title": "IP Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "IPv4:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipSystemStatsTable",
     "select": [
      [
       { "params": [ "ipSystemStatsHCInBcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Bcast:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsHCOutBcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Bcast:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsHCInMcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Mcast:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsHCOutMcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Mcast:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsHCInReceives" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Total:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsHCOutTransmits" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Total:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "IPv6:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipSystemStatsTable",
     "select": [
      [
       { "params": [ "ipSystemStatsHCInBcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Bcast:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsHCOutBcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Bcast:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsHCInMcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Mcast:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsHCOutMcastPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Mcast:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsHCInReceives" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Total:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsHCOutTransmits" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Total:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "IP Forwards",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "IPv4:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipSystemStatsTable",
     "select": [
      [
       { "params": [ "ipSystemStatsHCInForwDatagrams" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "ipSystemStatsHCOutForwDatagrams"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "IPv6:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipSystemStatsTable",
     "select": [
      [
       { "params": [ "ipSystemStatsHCInForwDatagrams" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "ipSystemStatsHCOutForwDatagrams"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "IP Fragmentation (/sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "IPv4:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipSystemStatsTable",
     "select": [
      [
       { "params": [ "ipSystemStatsReasmReqds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "ReasmReqd:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsReasmOKs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "ReasmOK:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsReasmFails" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "ReasmFail:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsOutFragReqds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "FragReqd:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsOutFragCreates" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Fragments:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsOutFragOKs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "FragOK:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsOutFragFails" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "FragFail:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "IPv6:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipSystemStatsTable",
     "select": [
      [
       { "params": [ "ipSystemStatsReasmReqds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "ReasmReqd:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsReasmOKs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "ReasmOK:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsReasmFails" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "ReasmFail:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsOutFragReqds" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "FragReqd:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsOutFragCreates" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Fragments:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsOutFragOKs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "FragOK:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsOutFragFails" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "FragFail:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "IP Forwarding Drops/Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "IPv4:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipSystemStatsTable",
     "select": [
      [
       { "params": [ "ipSystemStatsInAddrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "AddrError:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsInHdrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "HdrError:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsInNoRoutes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "NoRoute:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsInTruncatedPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Truncated:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsInDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drop:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsOutDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drop:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "IPv6:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipSystemStatsTable",
     "select": [
      [
       { "params": [ "ipSystemStatsInAddrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "AddrError:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsInHdrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "HdrError:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsInNoRoutes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "NoRoute:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsInTruncatedPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Truncated:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsInDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drop:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsOutDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Drop:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "IP Non-Forward Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "IPv4:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipSystemStatsTable",
     "select": [
      [
       { "params": [ "ipSystemStatsHCInDelivers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsHCOutRequests" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "IPv6:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipSystemStatsTable",
     "select": [
      [
       { "params": [ "ipSystemStatsHCInDelivers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsHCOutRequests" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "IP Non-Forward Drops/Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "IPv4:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipSystemStatsTable",
     "select": [
      [
       { "params": [ "ipSystemStatsInUnknownProtos" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "UnkProto:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsOutNoRoutes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "NoRoute:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "IPv6:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipSystemStatsTable",
     "select": [
      [
       { "params": [ "ipSystemStatsInUnknownProtos" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "UnkProto:In" ], "type": "alias" }
      ],
      [
       { "params": [ "ipSystemStatsOutNoRoutes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "NoRoute:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "TCP State Transitions (/sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.EdgeOS",
     "select": [
      [
       { "params": [ "tcpActiveOpens" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "ActiveOpen" ], "type": "alias" }
      ],
      [
       { "params": [ "tcpPassiveOpens" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "PassiveOpen" ], "type": "alias" }
      ],
      [
       { "params": [ "tcpAttemptFails" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Fail" ], "type": "alias" }
      ],
      [
       { "params": [ "tcpEstabResets" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Reset" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "TCP Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.EdgeOS",
     "select": [
      [
       { "params": [ "tcpCurrEstab" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Connections" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "TCP Traffic, Non-Forward  (seg/sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.EdgeOS",
     "select": [
      [
       { "params": [ "tcpInSegs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "tcpOutSegs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Out" ], "type": "alias" }
      ],
      [
       { "params": [ "tcpRetransSegs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Retrans:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "tcpInErrs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:In" ], "type": "alias" }
      ],
      [
       { "params": [ "tcpOutRsts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Reset:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "UDP Traffic, Non-Forward (dgram/sec)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.EdgeOS",
     "select": [
      [
       { "params": [ "udpInDatagrams" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "udpOutDatagrams" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Out" ], "type": "alias" }
      ],
      [
       { "params": [ "udpInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error" ], "type": "alias" }
      ],
      [
       { "params": [ "udpNoPorts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "NoPort" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "ICMP Summary",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "IPv4:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "icmpStatsTable",
     "select": [
      [
       { "params": [ "icmpStatsInMsgs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Msg:In" ], "type": "alias" }
      ],
      [
       { "params": [ "icmpStatsOutMsgs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Msg:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "icmpStatsInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:In" ], "type": "alias" }
      ],
      [
       { "params": [ "icmpStatsOutErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "IPv6:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "icmpStatsTable",
     "select": [
      [
       { "params": [ "icmpStatsInMsgs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Msg:In" ], "type": "alias" }
      ],
      [
       { "params": [ "icmpStatsOutMsgs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Msg:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "icmpStatsInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:In" ], "type": "alias" }
      ],
      [
       { "params": [ "icmpStatsOutErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Error:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "index", "operator": "=", "value": "2" }
     ]
    }
   ]
  },
  {
   "title": "ICMP Message Type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "alias": "$tag_index:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "index" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "icmpMsgStatsTable",
     "select": [
      [
       { "params": [ "icmpMsgStatsInPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "In" ], "type": "alias" }
      ],
      [
       { "params": [ "icmpMsgStatsOutPkts" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "$tag_diskIODevice:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "diskIODevice" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskIOTable",
     "select": [
      [
       { "params": [ "diskIOReads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "diskIOWrites" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "$tag_diskIODevice:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "diskIODevice" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskIOTable",
     "select": [
      [
       { "params": [ "diskIONReadX" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "diskIONWrittenX" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_diskIODevice:$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "diskIODevice" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskIOTable",
     "select": [
      [
       { "params": [ "diskIOLA1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1-Min" ], "type": "alias" }
      ],
      [
       { "params": [ "diskIOLA5" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5-Min" ], "type": "alias" }
      ],
      [
       { "params": [ "diskIOLA15" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15-Min" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 139 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$tag_hrStorageDescr",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "hrStorageDescr" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hrStorageTable",
     "query": "SELECT (last(\"hrStorageUsed\")/last(\"hrStorageSize\"))  FROM \"hrStorageTable\"  WHERE \"agent_host\" =~ /^$host$/ AND \"hrStorageType\" = '.1.3.6.1.2.1.25.2.1.4' AND $timeFilter GROUP BY time($interval), \"hrStorageDescr\" fill(null)",
     "select": [
      [
       { "params": [ "hrStorageUsed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "hrStorageSize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "hrStorageType", "operator": "=", "value": ".1.3.6.1.2.1.25.2.1.4" }
     ]
    }
   ]
  },
  {
   "title": "Routing/Forwarding",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.EdgeOS",
     "select": [
      [
       { "params": [ "ipRoutingDiscards" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "Routes Discarded" ], "type": "alias" }
      ],
      [
       { "params": [ "inetCidrRouteNumber" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Route Entries" ], "type": "alias" }
      ],
      [
       { "params": [ "ipForwardNumber" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Forward Entries" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "SNMP Messages (/min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.EdgeOS",
     "select": [
      [
       { "params": [ "snmpInPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Msgs:In" ], "type": "alias" }
      ],
      [
       { "params": [ "snmpOutPkts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Msgs:Out" ], "type": "alias" }
      ],
      [
       { "params": [ "snmpInGetResponses" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "GetResp:In" ], "type": "alias" }
      ],
      [
       { "params": [ "snmpOutGetResponses" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "GetResp:Out" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT non_negative_derivative(mean(\"allReqIn\"), 1m) AS \"GetReq:In\", non_negative_derivative(mean(\"allReqOut\"), 1m) AS \"GetReq:Out\" FROM ( SELECT \"snmpInGetRequests\"+\"snmpInGetNexts\" AS \"allReqIn\", \"snmpOutGetRequests\"+\"snmpOutGetNexts\" AS \"allReqOut\" FROM \"snmp.EdgeOS\" WHERE \"agent_host\" =~ /^$host$/ AND $timeFilter) WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SNMP Objects Retrieved (/min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp.EdgeOS",
     "select": [
      [
       { "params": [ "snmpInTotalReqVars" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" },
       { "params": [ "Objects" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "agent_host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}