{
 "title": "At A Glance #1",
 "description": "Key server health metrics on one screen.",
 "tags": [ "summary" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Linux Hosts",
    "query": {
     "query": "label_values(node_uname_info,host_system)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "{__name__=\"node_uname_info\",host_system=~\"$host\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{instance=\"$node\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{instance=\"$node\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "NAS - Folder Sizes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "repeat": "host_system",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "directory_size_bytes{host_system=~\"$host\"}",
     "legendFormat": "{{host_system}}-{{directory}}"
    }
   ]
  },
  {
   "title": "Folder Size Changes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(directory, host_system) (delta(directory_size_bytes{host_system=~\"$host\"}[24h])) / (min(directory_size_bytes{host_system=~\"$host\"}) by (host_system,directory))",
     "legendFormat": "{{host_system}}-{{directory}}"
    }
   ]
  },
  {
   "title": "Disk Space Used (/dev devices) ",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{host_system=~\"$host\",device=~'/dev/.*'} * 100) / node_filesystem_size_bytes{host_system=~\"$host\",device=~'/dev/.*'})",
     "legendFormat": "{{host_system}} - {{device}} : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "System Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"nodeexporter|ohmgraphite\"}",
     "legendFormat": "{{host_system}}"
    }
   ]
  },
  {
   "title": "ISP Speedtest",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "avg(speedtest_download_bandwidth_bps)*8",
     "legendFormat": "Download"
    },
    {
     "expr": "avg(speedtest_upload_bandwidth_bps) * 8",
     "legendFormat": "Upload"
    },
    { "expr": "avg(speedtest_ping_jitter_ms)", "legendFormat": "Ping Jitter" },
    { "expr": "avg(speedtest_ping_latency_ms)", "legendFormat": "Ping Latency" }
   ]
  },
  {
   "title": "Backups",
   "type": "state-timeline",
   "gridPos": { "h": 16, "w": 10, "x": 14, "y": 30 },
   "targets": [
    { "expr": "(backups_rsync_marlin) > 0", "legendFormat": "Marlin Rsync - {{storage}}" },
    {
     "expr": "backups_snapraid{storage!=\"ALL\"}  > 0",
     "legendFormat": "Snapraid - {{storage}}"
    },
    { "expr": "backups_duplicacy > 0", "legendFormat": "Duplicacy - {{storage}}" },
    { "expr": "backups_rsync_usb_backup > 0", "legendFormat": "USB - {{storage}}" }
   ]
  },
  {
   "title": "Disk Space Used (/dev devices) ",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{host_system=~\"$host\",device=~'/dev/.*'} * 100) / node_filesystem_size_bytes{host_system=~\"$host\",device=~'/dev/.*'})",
     "legendFormat": "{{host_system}} - {{device}} : {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Disk Usage - Root Partitions",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_avail_bytes{mountpoint=\"/\"}) / node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "{{host_system}} - %"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "table",
   "gridPos": { "h": 17, "w": 7, "x": 7, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (host_system,mountpoint,device) (node_filesystem_size_bytes{host_system=~\"$host\",mountpoint!~\"(/run|/var).*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host_system,mountpoint,device) (node_filesystem_size_bytes{host_system=~\"$host\",mountpoint!~\"(/run|/var).*\"}) - \r\nsum by (host_system,mountpoint,device) (node_filesystem_avail_bytes{host_system=~\"$host\",mountpoint!~\"(/run|/var).*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - (sum by (host_system,mountpoint,device) (node_filesystem_avail_bytes{host_system=~\"$host\",mountpoint!~\"(/run|/var).*\"}) / \r\n     sum by (host_system,mountpoint,device) (node_filesystem_size_bytes{host_system=~\"$host\",mountpoint!~\"(/run|/var).*\"}) )",
     "legendFormat": "__auto"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 61 }, "options": { "content": "# Node Exporter - $host" } },
  {
   "title": "NODE EXPORTER - Node Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (host_system, id, instance, name, pretty_name, version, version_codename, version_id) (node_os_info{host_system=~\"$host\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count by (host_system) (\r\n    count by (host_system,cpu) (node_cpu_seconds_total{host_system=~\"$host\"}) )",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host_system) (\r\n    node_time_seconds{host_system=~\"$host\"} - \r\n    node_boot_time_seconds{host_system=~\"$host\"}\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (host_system) (node_load5{host_system=~\"$host\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum by (host_system) (irate(node_cpu_seconds_total{host_system=~\"$host\", mode!=\"idle\"}[5m])) / \r\non(host_system) group_left sum by (host_system)((irate(node_cpu_seconds_total{host_system=~\"$host\"}[5m]))))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (host_system) (node_memory_MemTotal_bytes{host_system=~\"$host\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host_system) (node_memory_MemTotal_bytes{host_system=~\"$host\"}) - \r\nsum by (host_system) (node_memory_MemAvailable_bytes{host_system=~\"$host\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - (sum by (host_system) (node_memory_MemAvailable_bytes{host_system=~\"$host\"}) / \r\n     sum by (host_system) (node_memory_MemTotal_bytes{host_system=~\"$host\"}) )",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (host_system) (node_memory_SwapTotal_bytes{host_system=~\"$host\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host_system) (node_memory_SwapTotal_bytes{host_system=~\"$host\"}) - \r\nsum by (host_system) (node_memory_SwapFree_bytes{host_system=~\"$host\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - (sum by (host_system) (node_memory_SwapFree_bytes{host_system=~\"$host\"}) / \r\n     sum by (host_system) (node_memory_SwapTotal_bytes{host_system=~\"$host\"}) )",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (host_system) (node_filesystem_size_bytes{host_system=~\"$host\",mountpoint=\"/\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host_system) (node_filesystem_size_bytes{host_system=~\"$host\",mountpoint=\"/\"}) - \r\nsum by (host_system) (node_filesystem_avail_bytes{host_system=~\"$host\",mountpoint=\"/\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - (sum by (host_system) (node_filesystem_avail_bytes{host_system=~\"$host\",mountpoint=\"/\"}) / \r\n     sum by (host_system) (node_filesystem_size_bytes{host_system=~\"$host\",mountpoint=\"/\"}) )",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (host_system) (node_filesystem_size_bytes{host_system=~\"$host\",mountpoint=~\"(/storage|/mnt/proxdata).*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (host_system) (node_filesystem_size_bytes{host_system=~\"$host\",mountpoint=~\"(/storage|/mnt/proxdata).*\"}) - \r\nsum by (host_system) (node_filesystem_avail_bytes{host_system=~\"$host\",mountpoint=~\"(/storage|/mnt/proxdata).*\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "1 - (sum by (host_system) (node_filesystem_avail_bytes{host_system=~\"$host\",mountpoint=~\"(/storage|/mnt/proxdata).*\"}) / \r\n     sum by (host_system) (node_filesystem_size_bytes{host_system=~\"$host\",mountpoint=~\"(/storage|/mnt/proxdata).*\"}) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Metrics - $host",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 68 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(host_system) (irate(node_cpu_seconds_total{host_system=\"$host\", mode!=\"idle\"}[$__rate_interval])) / on(host_system) group_left sum by (host_system)((irate(node_cpu_seconds_total{host_system=\"$host\"}[$__rate_interval])))) * 100",
     "legendFormat": "CPU Busy ({{host_system}})"
    },
    {
     "expr": "avg_over_time(node_load1{host_system=~\"$host\"}[$__rate_interval]) * 100 / on(host_system) group_left sum by (host_system)(irate(node_cpu_seconds_total{host_system=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "Load 1m ({{host_system}})"
    },
    {
     "expr": "avg_over_time(node_load5{host_system=~\"$host\"}[$__rate_interval]) * 100 / on(host_system) group_left sum by (host_system)(irate(node_cpu_seconds_total{host_system=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "Load 5m ({{host_system}})"
    },
    {
     "expr": "avg_over_time(node_load15{host_system=~\"$host\"}[$__rate_interval]) * 100 / on(host_system) group_left sum by (host_system)(irate(node_cpu_seconds_total{host_system=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "Load 15m ({{host_system}})"
    },
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{host_system=\"$host\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{host_system=\"$host\"}[$__rate_interval]))",
     "legendFormat": "RAM ({{host_system}})"
    },
    {
     "expr": "((avg_over_time(node_memory_SwapTotal_bytes{host_system=\"$host\"}[$__rate_interval]) - avg_over_time(node_memory_SwapFree_bytes{host_system=\"$host\"}[$__rate_interval])) / (avg_over_time(node_memory_SwapTotal_bytes{host_system=\"$host\"}[$__rate_interval]) )) * 100",
     "legendFormat": "Swap ({{host_system}})"
    },
    {
     "expr": "100 - ((avg_over_time(node_filesystem_avail_bytes{host_system=\"$host\",mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]) * 100) / avg_over_time(node_filesystem_size_bytes{host_system=\"$host\",mountpoint=\"/\",fstype!=\"rootfs\"}[$__rate_interval]))",
     "legendFormat": "Root FS ({{host_system}})"
    },
    {
     "expr": "100 - ((avg_over_time(node_filesystem_avail_bytes{host_system=\"$host\",mountpoint=~\"(/storage|/mnt/proxdata).*\"}[$__rate_interval]) * 100) / avg_over_time(node_filesystem_size_bytes{host_system=\"$host\",mountpoint=~\"(/storage|/mnt/proxdata).*\"}[$__rate_interval]))\r\n",
     "legendFormat": "Storage ({{host_system}})"
    }
   ]
  },
  {
   "title": "System Load %",
   "type": "timeseries",
   "description": "Load shouldn't exceed number of threads.",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 68 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg_over_time(node_load5{host_system=~\"$host\"}[$__rate_interval]) * 100 / on(instance) group_left sum by (instance)(irate(node_cpu_seconds_total{host_system=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "{{host_system}} - Load - 5m"
    },
    {
     "expr": "(sum by(host_system) (irate(node_cpu_seconds_total{host_system=~\"$host\", mode!=\"idle\"}[$__rate_interval])) / on(host_system) group_left sum by (host_system)((irate(node_cpu_seconds_total{host_system=~\"$host\"}[$__rate_interval])))) * 100",
     "legendFormat": "{{host_system}} - CPU"
    }
   ]
  }
 ]
}