{
 "title": "Cloudflare Tunnels (17457)",
 "description": "Display Statistics for your Cloudflare Tunnels (cloudflared)",
 "tags": [
  "cloudflared",
  "Cloudflare Tunnels"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 18, "x": 3, "y": 0 },
   "options": {
    "content": "# Add metrics for DNS queries and for tunnelled services\r\n\r\nhttps://developers.cloudflare.com/cloudflare-one/tutorials/grafana/"
   }
  },
  {
   "title": "Metric List",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/monitor-tunnels/metrics/"
   }
  },
  {
   "title": "Cloudflare Edge Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_ha_connections",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Concurrent Requests",
   "type": "timeseries",
   "description": "Concurrent requests proxied through each tunnel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "cloudflared_tunnel_concurrent_requests_per_tunnel",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response By Code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum by(status_code) (increase(cloudflared_tunnel_response_by_code[$__rate_interval]))",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "sum by(instance) (increase(cloudflared_tunnel_total_requests[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Config Updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes(cloudflared_orchestration_config_version[$__interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "targets": [
    {
     "expr": "increase(cloudflared_tunnel_request_errors[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}