{
 "title": "Home Automation",
 "time": { "from": "now-60d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval_consumption",
    "label": "Consumption Sum Interval",
    "query": "30m,1h,2h,3h,4h,6h,12h,1d,2d,7d,14d,30d"
   },
   { "name": "gas_cal_value", "label": "(Gas) Calorific Value ", "query": "39.6" },
   { "name": "gas_vol_correction", "label": "(Gas) Volumetric Correction", "query": "1.02264" },
   {
    "name": "ha_entities",
    "label": "Home Assistant Entities",
    "query": {
     "query": "label_values(ha_entity_available{entity=~\".*_power.*|.*_energy.*|.*_temp.*|.*_humidity.*|.*brightness.*|.*_current.*|.*_occupancy.*|proximity..*|.*_battery.*\"},entity)"
    }
   },
   {
    "name": "ha_camera_area",
    "label": "HA Camera Area",
    "query": {
     "query": "label_values(ha_binary_sensor_state{entity=~\".*_occupancy\"},friendly_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Shelly Energy Monitor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "shelly1PM04_power", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Energy - All Metrics (for reference)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Energy Metrics - NEED TO UPDATE ONCE DATASET ESTABLISHED",
     "type": "timeseries",
     "description": "Octograph Gas Consumption may be slightly off if calorific value/volumetric correction is not 100% accurate.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "avg_over_time(avg(ha_sensor_monetary_gbp{entity=~\"sensor.octopus_energy_gas_.*_current_standing_charge\"})[1d])",
       "legendFormat": "Gas - Charge - Standing [HA]"
      },
      {
       "expr": "avg_over_time(avg(ha_sensor_monetary_gbp_per_kwh{entity=~\"sensor.octopus_energy_gas_.*_current_rate\"})[1d])",
       "legendFormat": "Gas - Charge - Unit (per kWh) [HA]"
      },
      {
       "expr": "ha_sensor_energy_kwh{entity=~\"sensor.octopus_energy_gas_.*_previous_accumulative_consumption_kwh\"} offset -24h",
       "legendFormat": "Gas - Consumption - Daily (kWh) [HA]"
      },
      {
       "expr": "avg_over_time(ha_sensor_monetary_gbp_per_kwh{entity=~\"sensor.octopus_energy_gas_.*_current_rate\"}[1d]) *\r\nsum(ha_sensor_energy_kwh{entity=~\"sensor.octopus_energy_gas_.*_previous_accumulative_consumption_kwh\"} offset -24h)",
       "legendFormat": "Gas - Consumption Cost - Daily [Consumption=HA; Unit Charge=HA]"
      },
      {
       "expr": "sum_over_time(gas_consumption[$interval_consumption:30m]) * $gas_cal_value * $gas_vol_correction / 3.6",
       "legendFormat": "Gas - Consumption (kWh) [Octograph] (from volumetric/calorific values)"
      },
      {
       "expr": "avg_over_time(octopus_energy_unitrate_gas_pence[$interval_consumption:30m] / 100) *\r\nsum(sum_over_time(gas_consumption[$interval_consumption:30m]) * $gas_cal_value * $gas_vol_correction / 3.6)",
       "legendFormat": "Gas - Consumption Cost [Consumption=Octograph; Unit Charge=API]"
      },
      {
       "expr": "avg_over_time(octopus_energy_standingcharge_gas_pence[1d:12h] / 100)",
       "legendFormat": "Gas - Charge - Standing [API->VMIMPORT]"
      },
      {
       "expr": "avg_over_time(octopus_energy_unitrate_gas_pence[1d:12h] / 100)",
       "legendFormat": "Gas - Charge - Unit (per kWh) [API->VMIMPORT]"
      }
     ]
    },
    {
     "title": "TESTING - All Energy Metrics - NEED TO UPDATE ONCE DATASET ESTABLISHED",
     "type": "timeseries",
     "description": "Octograph Gas Consumption may be slightly off if calorific value/volumetric correction is not 100% accurate.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "ha_sensor_energy_kwh{entity=~\"sensor.octopus_energy_electricity_.*_previous_accumulative_consumption\"} offset -24h",
       "legendFormat": "Electricity - Consumption - Daily (kWh) [HA]"
      },
      {
       "expr": "sum_over_time(electricity_consumption[$interval_consumption:30m])",
       "legendFormat": "Electricity - Consumption (kWh) [Octograph]"
      },
      {
       "expr": "increase(shellyem_0_total[$__rate_interval]) / 1000 ",
       "legendFormat": "Electricity - Consumption (kWh) [ShellyEM MQTT->VMA]"
      }
     ]
    },
    {
     "title": "All Energy Metrics - NEED TO UPDATE ONCE DATASET ESTABLISHED",
     "type": "stat",
     "description": "Octograph Gas Consumption may be slightly off if calorific value/volumetric correction is not 100% accurate.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "expr": "present_over_time(octopus_energy_standingcharge_electricity_pence[1d:30m])",
       "legendFormat": "Days"
      },
      {
       "expr": "avg_over_time(ha_sensor_monetary_gbp{entity=~\"sensor.octopus_energy_electricity_.*_current_standing_charge\"}[1d])",
       "legendFormat": "Electricity - Standing Charge [HA]"
      },
      {
       "expr": "avg_over_time(ha_sensor_monetary_gbp{entity=~\"sensor.octopus_energy_gas_.*_current_standing_charge\"}[1d])",
       "legendFormat": "Gas - Standing Charge [HA]"
      },
      {
       "expr": "ha_sensor_energy_kwh{entity=~\"sensor.octopus_energy_electricity_.*_previous_accumulative_consumption\"} offset -24h",
       "legendFormat": "Electricity - Consumption (kWh) [HA]"
      },
      {
       "expr": "sum_over_time(electricity_consumption[$interval_consumption:30m])",
       "legendFormat": "Electricity - Consumption (kWh) [Octograph]"
      },
      {
       "expr": "increase(shellyem_0_total[$__rate_interval])/1000",
       "legendFormat": "Electricity - ShellyEM Electricity Consumption (kWh) [MQTT->VMA]"
      },
      {
       "expr": "increase(interpolate(shellyem_0_total)[$__rate_interval])/1000",
       "legendFormat": "Electricity - ShellyEM Electricity Consumption (kWh) [MQTT->VMA] INTERPOLATED"
      },
      {
       "expr": "avg_over_time(octopus_energy_standingcharge_electricity_pence[1d:12h] / 100)",
       "legendFormat": "Electricity - Standing Charge [API->VMIMPORT]"
      },
      {
       "expr": "avg_over_time(octopus_energy_standingcharge_gas_pence[1d:12h] / 100)",
       "legendFormat": "Gas - Standing Charge [API->VMIMPORT]"
      }
     ]
    }
   ]
  },
  {
   "title": "Electricity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power Now [ShellyEM]",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "shellyem_0_power", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Energy By Day (Full Time Range) [ShellyEM]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "expr": "increase(shellyem_0_total[$__rate_interval])/1000",
       "legendFormat": "Electricity - ShellyEM Electricity Consumption (kWh) [MQTT->VMA]"
      }
     ]
    },
    {
     "title": "Consumption Over Time Range [ShellyEM]",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(shellyem_0_total[$__interval]))",
       "legendFormat": "ShellyEM"
      }
     ]
    },
    {
     "title": "Total Unit Cost (Full Time Range) {ShellyEM]",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(shellyem_0_total[$__interval]))",
       "legendFormat": "ShellyEM"
      },
      {
       "expr": "avg_over_time(octopus_energy_unitrate_electricity_pence[1d:12h] / 100)",
       "legendFormat": "Electricity - Unit Cost (per kWh) [API->VMIMPORT]"
      }
     ]
    },
    {
     "title": "Electricity Consumption - Octograph vs ShellyEM",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "expr": "sum_over_time(electricity_consumption[$interval_consumption:30m])",
       "legendFormat": "Electricity - Consumption (kWh) [Octograph]"
      },
      {
       "expr": "increase(interpolate(shellyem_0_total)[$__rate_interval])/1000",
       "legendFormat": "Electricity - ShellyEM Electricity Consumption (kWh) [MQTT->VMA] INTERPOLATED"
      },
      {
       "expr": "increase(shellyem_0_total[$__rate_interval])/1000",
       "legendFormat": "Electricity - ShellyEM Electricity Consumption (kWh) [MQTT->VMA]"
      }
     ]
    },
    {
     "title": "Consumption Over Time Range [Octograph]",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time(electricity_consumption[$__interval:30m])",
       "legendFormat": "Octograph"
      }
     ]
    },
    {
     "title": "Total Unit Cost (Full Time Range) {ShellyEM]",
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 3, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum_over_time(electricity_consumption[$interval_consumption:30m])",
       "legendFormat": "Octograph"
      },
      {
       "expr": "avg_over_time(octopus_energy_unitrate_electricity_pence[$__interval]) / 100",
       "legendFormat": "Electricity - Unit Cost (per kWh) [API->VMIMPORT]"
      },
      { "expr": "electricity_consumption", "legendFormat": "Octograph2" }
     ]
    },
    {
     "title": "Instantaneous Power (last 24h) [ShellyEM]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      { "expr": "shellyem_0_power", "legendFormat": "Power (ShellyEM)" }
     ]
    },
    {
     "title": "Energy By Hour (last 24h) [ShellyEM]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "expr": "increase(shellyem_0_total[$__rate_interval])/1000",
       "legendFormat": "Electricity - ShellyEM Electricity Consumption (kWh) [MQTT->VMA]"
      }
     ]
    },
    {
     "title": "Instantaneous Current (last 24h) [ShellyEM]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "shellyem_0_power / shellyem_0_voltage",
       "legendFormat": "Current (ShellyEM)"
      }
     ]
    },
    {
     "title": "Energy By Hour (Full Time Range) [ShellyEM]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "expr": "increase(shellyem_0_total[$__rate_interval])/1000",
       "legendFormat": "Electricity - ShellyEM Electricity Consumption (kWh) [MQTT->VMA]"
      }
     ]
    },
    {
     "title": "Energy By Day (Full Time Range) [ShellyEM]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "expr": "increase(shellyem_0_total[$__rate_interval])/1000",
       "legendFormat": "Electricity - ShellyEM Electricity Consumption (kWh) [MQTT->VMA]"
      }
     ]
    },
    {
     "title": "Energy Used & Cost - UPDATE WHEN WEHAVE DATASET",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 }
    },
    {
     "title": "Instantaneous Power (Full Time Range) [ShellyEM]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      { "expr": "shellyem_0_power", "legendFormat": "Power (ShellyEM)" }
     ]
    },
    {
     "title": "Instantaneous Current (Full Time Range) [ShellyEM]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "expr": "shellyem_0_power / shellyem_0_voltage",
       "legendFormat": "Current (ShellyEM)"
      }
     ]
    }
   ]
  },
  {
   "title": "Gas",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "text",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
     "options": {
      "content": "# Create gas versions of electricity metrics\n\nAns see old Grafana visualisations"
     }
    },
    {
     "title": "Gas Calculations",
     "type": "text",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 40 },
     "options": {
      "content": "<table style=\"border-collapse: collapse; width: 100%;\" border=\"1\">\n<tbody>\n<tr>\n<td style=\"width: 3.66975%; text-align: left;\" colspan=\"2\"><strong>Consumption in kWh</strong></td>\n</tr>\n<tr>\n<td style=\"width: 3.66975%; text-align: center;\">&nbsp;</td>\n<td style=\"width: 96.3303%;\">Meter Reading <em>(in m&sup3;)</em></td>\n</tr>\n<tr>\n<td style=\"width: 3.66975%; text-align: center;\">x</td>\n<td style=\"width: 96.3303%;\">Volumetric Correction<em> (pressure/temp)</em></td>\n</tr>\n<tr>\n<td style=\"width: 3.66975%; text-align: center;\">x</td>\n<td style=\"width: 96.3303%;\">Calorific Value <em>(energy in each m&sup3;)</em></td>\n</tr>\n<tr>\n<td style=\"width: 3.66975%; text-align: center;\">&divide;</td>\n<td style=\"width: 96.3303%;\">3.6 <em>(convert from joules)</em></td>\n</tr>\n</tbody>\n</table>"
     }
    }
   ]
  },
  {
   "title": "Home Assistant - Interesting Entities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Camera Detections - Filtered",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
     "targets": [
      {
       "expr": "ha_binary_sensor_state{entity=~\".*_occupancy\", friendly_name=~\"$ha_camera_area.*\"}",
       "legendFormat": "{{friendly_name}}"
      }
     ]
    },
    {
     "title": "HA Humidity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "ha_sensor_humidity_percent{entity=~\"$ha_entities\"}",
       "legendFormat": "{{friendly_name}}"
      }
     ]
    },
    {
     "title": "HA Batteries",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ha_sensor_battery_percent{entity=~\"$ha_entities\"}",
       "legendFormat": "{{friendly_name}}"
      }
     ]
    },
    {
     "title": "HA Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "ha_sensor_temperature_celsius{entity=~\"$ha_entities\"}",
       "legendFormat": "{{friendly_name}}"
      }
     ]
    },
    {
     "title": "Home Assistant Power Metrics (Entity Filter)",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "ha_sensor_power_w {entity=~\"$ha_entities\"} !=0",
       "legendFormat": "{{friendly_name}}"
      }
     ]
    },
    {
     "title": "Home Assistant 'Energy' Entities (Entity Filter) - Per Hour (Full Time Range)",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "targets": [
      {
       "expr": "increase(ha_sensor_energy_kwh{entity=~\"$ha_entities\"}[$__rate_interval]) != 0",
       "legendFormat": "{{friendly_name}}"
      }
     ]
    },
    {
     "title": "Shelly (1PM #04) Power Monitor",
     "type": "timeseries",
     "description": "Metrics from MQTT -> VMAgent via Node Red flow\n\nEnergy metric is in Watt Minutes - divide by 60 to get Wh.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 160 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      { "expr": "shelly1PM04_power", "legendFormat": "Power" },
      {
       "expr": "sum_over_time(increase(shelly1PM04_energy)[$interval_consumption])/60",
       "legendFormat": "Consumption (interval filter)"
      },
      {
       "expr": "sum_over_time(increase(shelly1PM04_energy)[1h])/60",
       "legendFormat": "Consumption (1h)"
      }
     ]
    }
   ]
  },
  {
   "title": "Lay-Z-Spa",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spa Functions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      { "expr": "layzspa_heater", "legendFormat": "Heater" },
      { "expr": "layzspa_heating + 2", "legendFormat": "Active Heating" },
      { "expr": "layzspa_filter + 4", "legendFormat": "Pump" },
      { "expr": "layzspa_air + 6", "legendFormat": "Bubbles" }
     ]
    },
    {
     "title": "Spa KWH & Cost",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "kwatth" } },
     "targets": [
      {
       "expr": "avg_over_time(octopus_energy_unitrate_electricity_pence[1d:12h] / 100)",
       "legendFormat": "Unit Cost"
      },
      {
       "expr": "sum(increase(layzspa_kwh[$__rate_interval]))",
       "legendFormat": "kWh"
      }
     ]
    },
    {
     "title": "Spa Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      { "expr": "layzspa_temp", "legendFormat": "Actual Temp" },
      { "expr": "layzspa_target", "legendFormat": "Target Temp" },
      {
       "expr": "ha_sensor_temperature_celsius{entity=\"sensor.openweathermap_temperature\"}",
       "legendFormat": "Air Temp"
      },
      {
       "expr": "ha_input_number_state_celsius{entity=\"input_number.layzspa_min_temp\"}",
       "legendFormat": "Min Temp (Home Assistant)"
      }
     ]
    }
   ]
  }
 ]
}