{
 "title": "Tdarr (20388)",
 "tags": [
  "tdarr",
  "media"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "instance", "query": { "query": "label_values(tdarr_instance)" } },
   {
    "name": "library",
    "query": {
     "query": "label_values(tdarr_library_files_total{tdarr_instance=\"$instance\"},library_name)"
    }
   },
   {
    "name": "tdarr_node",
    "query": {
     "query": "label_values(tdarr_node_heap_used_mb,node_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "All Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Transcodes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tdarr_transcodes_total{tdarr_instance=\"$instance\"}",
       "legendFormat": "{{library_name}}"
      }
     ]
    },
    {
     "title": "Total Transcode Errors (Current Value)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tdarr_library_transcodes{tdarr_instance=\"$instance\", library_id=\"all_libraries\", status=\"error\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total Transcodes by Library",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 7, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Transcodes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(tdarr_library_transcodes_total{tdarr_instance=\"$instance\", library_id!=\"all_libraries\"}) by (library_name)",
       "legendFormat": "{{library_name}}"
      }
     ]
    },
    {
     "title": "Total Transcodes by Status",
     "type": "piechart",
     "gridPos": { "h": 12, "w": 5, "x": 13, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(tdarr_library_transcodes{tdarr_instance=\"$instance\", library_id=\"all_libraries\"}) by (status)",
       "legendFormat": "{{library_name}}"
      }
     ]
    },
    {
     "title": "Total Health Checks by Library",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Health Checks" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(tdarr_library_health_checks_total{tdarr_instance=\"$instance\", library_id!=\"all_libraries\"}) by (library_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "(+/-) Total Size Difference in GB by Tdarr Transcodes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tdarr_size_diff_gb{tdarr_instance=\"$instance\"}",
       "legendFormat": "{{library_name}}"
      }
     ]
    },
    {
     "title": "Total Health Checks",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tdarr_health_checks_total{tdarr_instance=\"$instance\"}",
       "legendFormat": "{{library_name}}"
      }
     ]
    },
    {
     "title": "Total Health Check Errors (Current Value)",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 9 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tdarr_library_health_checks{tdarr_instance=\"$instance\", library_id=\"all_libraries\", status=\"error\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total Media Count",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 13 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tdarr_files_total{tdarr_instance=\"$instance\"}",
       "legendFormat": "{{library_name}}"
      }
     ]
    },
    {
     "title": "Total Video Codec Count by Type",
     "type": "piechart",
     "gridPos": { "h": 14, "w": 6, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(tdarr_library_video_codecs{tdarr_instance=\"$instance\", library_id=\"all_libraries\"}) by (codec))",
       "legendFormat": "{{library_name}}"
      }
     ]
    },
    {
     "title": "Total Video Resolutions by Type",
     "type": "piechart",
     "gridPos": { "h": 14, "w": 6, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(tdarr_library_video_resolutions{tdarr_instance=\"$instance\", library_id=\"all_libraries\"}) by (resolution))",
       "legendFormat": "{{resolution}}"
      }
     ]
    },
    {
     "title": "Total Video Containers by Type",
     "type": "piechart",
     "gridPos": { "h": 14, "w": 6, "x": 18, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(tdarr_library_video_containers{tdarr_instance=\"$instance\", library_id=\"all_libraries\"}) by (container_type))",
       "legendFormat": "{{library_name}}"
      },
      { "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Media Count by Library",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Files" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (tdarr_library_files_total{tdarr_instance=\"$instance\", library_id != \"all_libraries\"}) by (library_name)",
       "legendFormat": "{{library_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total Transcodes (in period)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "tdarr_transcodes_total{tdarr_instance=\"$instance\"}",
     "legendFormat": "{{library_name}}"
    }
   ]
  },
  {
   "title": "Total Transcode Errors (in period)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "sum(tdarr_library_transcodes{tdarr_instance=\"$instance\", library_id!=\"all_libraries\", status=\"error\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total Transcodes by Library (in period)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Transcodes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(tdarr_library_transcodes_total{tdarr_instance=\"$instance\", library_id!=\"all_libraries\"}) by (library_name)",
     "legendFormat": "{{library_name}}"
    }
   ]
  },
  {
   "title": "Total Health Checks by Library (in period)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Health Checks" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum(tdarr_library_health_checks_total{tdarr_instance=\"$instance\", library_id!=\"all_libraries\"}) by (library_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Media Count Changes (in period)",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "Files" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum (tdarr_library_files_total{tdarr_instance=\"$instance\", library_id != \"all_libraries\"}) by (library_name)",
     "legendFormat": "{{library_name}}"
    }
   ]
  },
  {
   "title": "(+/-) Total Size Difference in GB by Tdarr Transcodes (in period)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "tdarr_size_diff_gb{tdarr_instance=\"$instance\"}",
     "legendFormat": "{{library_name}}"
    }
   ]
  },
  {
   "title": "Media Count Change (in period)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "sum (tdarr_library_files_total{tdarr_instance=\"$instance\", library_id != \"all_libraries\"})",
     "legendFormat": "{{library_name}}"
    }
   ]
  },
  {
   "title": "Tdarr Score (at end of period)",
   "type": "stat",
   "description": "Score based on how many media files (compared to total media files) were successfully transcoded by Tdarr",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tdarr_score_pct{tdarr_instance=\"$instance\"}",
     "legendFormat": "{{library_name}}"
    }
   ]
  },
  {
   "title": "Health Check Score (at end of period)",
   "type": "stat",
   "description": "Score based on how many media files (compared to total media files) were successfully health checked by Tdarr",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tdarr_health_check_score_pct{tdarr_instance=\"$instance\"}",
     "legendFormat": "{{library_name}}"
    }
   ]
  },
  {
   "title": "Total Health Checks by Status",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tdarr_library_health_checks{tdarr_instance=\"$instance\", library_id=\"all_libraries\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total Health Checks (in period)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "tdarr_health_checks_total{tdarr_instance=\"$instance\"}",
     "legendFormat": "{{library_name}}"
    }
   ]
  },
  {
   "title": "Total Health Check Errors (in period)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "diff" ] } },
   "targets": [
    {
     "expr": "increase(tdarr_library_health_checks{tdarr_instance=\"$instance\", library_id=\"all_libraries\", status=\"error\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Average Num of Streams",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tdarr_avg_num_streams{tdarr_instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Stats Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tdarr_stream_stats_duration{tdarr_instance=\"$instance\"}) by (stat_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num of Frames",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Frames" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tdarr_stream_stats_num_frames{tdarr_instance=\"$instance\"}) by (stat_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bit Rates",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tdarr_stream_stats_bit_rate{tdarr_instance=\"$instance\"}) by (stat_type)",
     "legendFormat": "{{stat_type}}"
    }
   ]
  },
  {
   "title": "Total Audio Codec Count by Type",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(tdarr_library_audio_codecs{tdarr_instance=\"$instance\", library_id=\"all_libraries\"}) by (codec))",
     "legendFormat": "{{library_name}}"
    }
   ]
  },
  {
   "title": "Total Audio Containers by Type",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(tdarr_library_audio_containers{tdarr_instance=\"$instance\", library_id=\"all_libraries\"}) by (container_type))",
     "legendFormat": "{{library_name}}"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host CPU Used %",
     "type": "timeseries",
     "description": "CPU used percentage for host that Tdarr node runs on",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "tdarr_node_host_cpu_percent{tdarr_instance=\"$instance\", node_name=\"$tdarr_node\"}",
       "legendFormat": "{{node_name}} - host cpu percentage"
      }
     ]
    },
    {
     "title": "Host Memory (GB)",
     "type": "timeseries",
     "description": "Memory usage for host that Tdarr node runs on",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "tdarr_node_host_mem_used_gb{tdarr_instance=\"$instance\", node_name=\"$tdarr_node\"}",
       "legendFormat": "{{node_name}} - heap used mb"
      },
      {
       "expr": "tdarr_node_host_mem_total_gb{tdarr_instance=\"$instance\", node_name=\"$tdarr_node\"}",
       "legendFormat": "{{node_name }} - heap total mb"
      }
     ]
    },
    {
     "title": "Tdarr Node Heap (MB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "tdarr_node_heap_used_mb{tdarr_instance=\"$instance\", node_name=\"$tdarr_node\"}",
       "legendFormat": "{{node_name}} - heap used mb"
      },
      {
       "expr": "tdarr_node_heap_total_mb{tdarr_instance=\"$instance\", node_name=\"$tdarr_node\"}",
       "legendFormat": "{{node_name }} - heap total mb"
      }
     ]
    },
    {
     "title": "Node Info",
     "type": "table",
     "description": "\"-\" gpu transcpding type = \"auto\"",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 104 },
     "targets": [
      {
       "expr": "tdarr_node_info{tdarr_instance=\"$instance\", node_name=\"$tdarr_node\"}"
      }
     ]
    },
    {
     "title": "Current Node Queues",
     "type": "table",
     "description": "If Node is GPU worker that has \"CPU Tasks\" enabled, \"CPU/GPU\" tasks will be the same",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 104 },
     "targets": [
      {
       "expr": "tdarr_node_info{tdarr_instance=\"$instance\", node_name=\"$tdarr_node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Flow Workers",
     "type": "table",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 112 },
     "targets": [
      {
       "expr": "tdarr_node_worker_flow_info{tdarr_instance=\"$instance\", node_name=\"$tdarr_node\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Health Check Workers",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 122 },
     "targets": [
      {
       "expr": "tdarr_node_worker_info{tdarr_instance=\"$instance\", node_name=\"$tdarr_node\", worker_type=~\"healthcheck.*\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Classic Plugin Workers",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 122 },
     "targets": [
      {
       "expr": "tdarr_node_worker_info{tdarr_instance=\"$instance\", node_name=\"$tdarr_node\", worker_type!~\"healthcheck.*\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "By Library: $library",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Media Count",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tdarr_library_files_total{tdarr_instance=\"$instance\", library_name=\"$library\"}",
       "legendFormat": "{{library_name}}"
      }
     ]
    },
    {
     "title": "Total Transcodes",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 2, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tdarr_library_transcodes_total{tdarr_instance=\"$instance\", library_name=\"$library\"}",
       "legendFormat": "{{library_name}}"
      }
     ]
    },
    {
     "title": "Total Health Checks",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 4, "y": 33 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tdarr_library_health_checks_total{tdarr_instance=\"$instance\", library_name=\"$library\"}",
       "legendFormat": "{{library_name}}"
      }
     ]
    },
    {
     "title": "Transcodes by Status",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 5, "x": 6, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(tdarr_library_transcodes{tdarr_instance=\"$instance\", library_name = \"$library\"}) by (status)",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total Video Codec Count by Type",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 4, "x": 11, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(tdarr_library_video_codecs{tdarr_instance=\"$instance\",library_name=\"$library\"}) by (codec))",
       "legendFormat": "{{library_name}}"
      }
     ]
    },
    {
     "title": "Total Video Resolutions by Type",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 5, "x": 15, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(tdarr_library_video_resolutions{tdarr_instance=\"$instance\",library_name=\"$library\"}) by (resolution))",
       "legendFormat": "{{resolution}}"
      }
     ]
    },
    {
     "title": "Total Video Containers by Type",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 4, "x": 20, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum(tdarr_library_video_containers{tdarr_instance=\"$instance\",library_name=\"$library\"}) by (container_type))",
       "legendFormat": "{{library_name}}"
      }
     ]
    },
    {
     "title": "(+/-) Total Size Difference in GB by Tdarr Transcodes",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tdarr_library_size_diff_gb{tdarr_instance=\"$instance\", library_name=\"$library\"}",
       "legendFormat": "{{library_name}}"
      }
     ]
    },
    {
     "title": "Total Transcode Errors (Current Value)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 2, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tdarr_library_transcodes{tdarr_instance=\"$instance\", library_name=\"$library\", status=\"error\"}",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Total Health Check Errors (Current Value)",
     "type": "stat",
     "gridPos": { "h": 5, "w": 2, "x": 4, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "tdarr_library_health_checks{tdarr_instance=\"$instance\", library_name=\"$library\", status=\"error\"}",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  }
 ]
}