{
 "title": "VictoriaMetrics API Imports",
 "description": "Metrics pushed directly to VictoriaMetrics via API commands.",
 "tags": [
  "customimports",
  "victoriametrics",
  "smart",
  "lmsensors",
  "speedtest",
  "directory-sizes",
  "backup"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host_system",
    "label": "Host System",
    "query": {
     "query": "label_values({__name__=~\"node_.*\"},host_system)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Network Stats - $host_system - DISABLED)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Octopus Energy Pricing (Monitoring LXC)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Octopus Energy Pricing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "currencyGBP" } },
     "targets": [
      {
       "expr": "octopus_energy_standingcharge_electricity_pence / 100",
       "legendFormat": "{{category}} - {{source}}"
      },
      {
       "expr": "octopus_energy_standingcharge_gas_pence / 100",
       "legendFormat": "{{category}} - {{source}}"
      },
      {
       "expr": "octopus_energy_unitrate_electricity_pence / 100",
       "legendFormat": "{{category}} - {{source}}"
      },
      {
       "expr": "octopus_energy_unitrate_gas_pence / 100",
       "legendFormat": "{{category}} - {{source}}"
      },
      {
       "expr": "octopus_energy_unitrate_day_electricity_pence / 100",
       "legendFormat": "{{category}} - {{source}}"
      },
      {
       "expr": "octopus_energy_unitrate_night_electricity_pence / 100",
       "legendFormat": "{{category}} - {{source}}"
      }
     ]
    }
   ]
  },
  {
   "title": "ISP Speedtest (Proxmox Host)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "ISP Speedtest",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "expr": "avg(speedtest_download_bandwidth_bps)*8",
       "legendFormat": "Download"
      },
      {
       "expr": "avg(speedtest_upload_bandwidth_bps) * 8",
       "legendFormat": "Upload"
      },
      { "expr": "avg(speedtest_ping_jitter_ms)", "legendFormat": "Ping Jitter" },
      { "expr": "avg(speedtest_ping_latency_ms)", "legendFormat": "Ping Latency" }
     ]
    },
    {
     "title": "Test Results",
     "type": "table",
     "gridPos": { "h": 11, "w": 18, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "avg by (host_system, intf_internalip, intf_externalip, intf_name, intf_vpn, isp,server_id,server_location ,server_ip ,server_name,server_country) (speedtest_download_bandwidth_bps)"
      },
      {
       "expr": "avg(speedtest_upload_bandwidth_bps)"
      },
      { "expr": "avg(speedtest_ping_latency_ms)", "legendFormat": "Latency" },
      { "expr": "avg(speedtest_ping_jitter_ms)", "legendFormat": "Latency" },
      {
       "expr": "avg(speedtest_download_bandwidth_bytes)",
       "legendFormat": "__auto"
      },
      {
       "expr": "avg(speedtest_upload_bandwidth_bytes)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Download",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(max_over_time(speedtest_download_bandwidth_bps[1w:5m]))",
       "legendFormat": "Best"
      },
      {
       "expr": "min(min_over_time(speedtest_download_bandwidth_bps[1w:5m]))",
       "legendFormat": "Worst"
      },
      {
       "expr": "avg(avg_over_time(speedtest_download_bandwidth_bps[1w:5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(min_over_time(speedtest_ping_latency_ms[1w:5m]))",
       "legendFormat": "Latency - Best"
      },
      {
       "expr": "max(max_over_time(speedtest_ping_latency_ms[1w:5m]))",
       "legendFormat": "Latency - Worst"
      },
      {
       "expr": "avg(avg_over_time(speedtest_ping_latency_ms[1w:5m]))",
       "legendFormat": "Latency - Avg"
      }
     ]
    },
    {
     "title": "Upload",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(max_over_time(speedtest_upload_bandwidth_bps[1w:5m]))",
       "legendFormat": "Best"
      },
      {
       "expr": "min(min_over_time(speedtest_upload_bandwidth_bps[1w:5m]))",
       "legendFormat": "Worst"
      },
      {
       "expr": "avg(avg_over_time(speedtest_upload_bandwidth_bps[1w:5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Jitter",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min(min_over_time(speedtest_ping_jitter_ms[1w:5m]))",
       "legendFormat": "Best"
      },
      {
       "expr": "max(max_over_time(speedtest_ping_jitter_ms[1w:5m]))",
       "legendFormat": "Worst"
      },
      {
       "expr": "avg(avg_over_time(speedtest_ping_jitter_ms[1w:5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Transferred Data",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(speedtest_download_bandwidth_bytes)",
       "legendFormat": "Download"
      },
      {
       "expr": "sum(speedtest_upload_bandwidth_bytes)",
       "legendFormat": "Upload"
      }
     ]
    }
   ]
  },
  {
   "title": "Backups (Inside Backup Scripts)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backups",
     "type": "state-timeline",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 4 },
     "targets": [
      { "expr": "(backups_rsync_marlin) > 0", "legendFormat": "Marlin Rsync - {{storage}}" },
      {
       "expr": "backups_snapraid{storage!=\"ALL\"}  > 0",
       "legendFormat": "Snapraid - {{storage}}"
      },
      { "expr": "backups_duplicacy > 0", "legendFormat": "Duplicacy - {{storage}}" },
      { "expr": "backups_rsync_usb_backup > 0", "legendFormat": "USB - {{storage}}" }
     ]
    }
   ]
  },
  { "title": "SMART Monitor - $host_system", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "SMART Disk Overview",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max(smartmon_device_info{host_system=~\"$host_system\"}) by(disk, type, host_system, device_model, model_family, serial_number,rpm,capacity_bytes) "
    },
    {
     "expr": "max(smartmon_power_on_hours_raw_value{host_system=~\"$host_system\",type=~\"sat\"}) by(disk, type, host_system) "
    },
    {
     "expr": "max(smartmon_load_cycle_count_raw_value{host_system=~\"$host_system\",type=~\"sat\"}) by (disk, type, host_system)",
     "legendFormat": "Load Cycles"
    },
    {
     "expr": "max(smartmon_start_stop_count_raw_value{host_system=~\"$host_system\",type=~\"sat\"}) by (disk, type, host_system)",
     "legendFormat": "Load Cycles"
    },
    {
     "expr": "avg(smartmon_temperature_celsius_raw_value{host_system=~\"$host_system\"}) by (disk, type, host_system)"
    },
    {
     "expr": "max(smartmon_device_smart_healthy{host_system=~\"$host_system\",type!~\"scsi\"}) by (disk, type, host_system)"
    },
    {
     "expr": "max(smartmon_reallocated_sector_ct_raw_value{host_system=~\"$host_system\",type=~\"sat\"}) by (disk, type, host_system)"
    },
    {
     "expr": "max(smartmon_current_pending_sector_raw_value{host_system=~\"$host_system\",type=~\"sat\"}) by (disk, type, host_system)"
    },
    {
     "expr": "max(smartmon_offline_uncorrectable_raw_value{host_system=~\"$host_system\",type=~\"sat\"}) by (disk, type, host_system)"
    },
    {
     "expr": "(max(smartmon_total_lbas_written_raw_value{host_system=~\"$host_system\"}) by (disk, type, host_system)) * (max(smartmon_device_sector_size_logical{host_system=~\"$host_system\"}) by (disk, type, host_system) )",
     "legendFormat": "__auto"
    },
    {
     "expr": "(max(smartmon_total_lbas_read_raw_value{host_system=~\"$host_system\"}) by (disk, type, host_system)) * (max(smartmon_device_sector_size_logical{host_system=~\"$host_system\"}) by (disk, type, host_system) )",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(smartmon_spin_up_time_raw_value{host_system=~\"$host_system\",type=~\"sat\"}) by (disk, type, host_system)"
    },
    {
     "expr": "max(smartmon_ssd_percentage_used{host_system=~\"$host_system\",type=~\"sat\"}) by (disk, type, host_system)"
    },
    {
     "expr": "max(smartmon_unsafe_shutdowns_count_raw_value{host_system=~\"$host_system\",type=~\"sat\"}) by (disk, type, host_system)"
    },
    {
     "expr": "max(smartmon_integrity_errors_count_raw_value{host_system=~\"$host_system\",type=~\"sat\"}) by (disk, type, host_system)"
    }
   ]
  },
  {
   "title": "Directory Sizes - $host_system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "NAS - Folder Sizes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
     "repeat": "host_system",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "directory_size_bytes{host_system=~\"$host_system\"}",
       "legendFormat": "{{host_system}}-{{directory}}"
      }
     ]
    },
    {
     "title": "Folder Size Changes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by(directory, host_system) (delta(directory_size_bytes{host_system=~\"$host_system\"}[24h])) / (min(directory_size_bytes{host_system=~\"$host_system\"}) by (host_system,directory))",
       "legendFormat": "{{host_system}}-{{directory}}"
      }
     ]
    }
   ]
  },
  {
   "title": "lmsensors - $host_system",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "LM Sensors Imports",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "lmsensors{host_system=~\"$host_system\"}",
       "legendFormat": "{{host_system}} - {{device}} - {{sensor}}"
      }
     ]
    }
   ]
  },
  { "title": "Docker Info - $host_system", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Docker Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "docker_custom_events", "legendFormat": "{{action}} - {{name}}" }
   ]
  },
  {
   "title": "Docker Image Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "docker_custom_image_count", "legendFormat": "{{host_system}}" }
   ]
  }
 ]
}